/**
 * A static C string representing the contents of UANativeBridge.js.
 *
 * @note This array is autogenerated with a pre-build script.
 */
extern unsigned char UANativeBridge_js[];

/**
 * The length of the UANativeBridge_js array, in bytes.
 */
extern unsigned int UANativeBridge_js_len;
