{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSArrayValueTransformer"]]},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSArrayValueTransformer\/allowsReverseTransformation()"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowsReverseTransformation","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"platforms":["Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"AirshipCore"}],"externalID":"c:@M@AirshipCore@objc(cs)NSArrayValueTransformer(cm)allowsReverseTransformation","title":"allowsReverseTransformation()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowsReverseTransformation"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"roleHeading":"Type Method","role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"allowsReverseTransformation"}]},"variants":[{"paths":["\/documentation\/airshipcore\/nsarrayvaluetransformer\/allowsreversetransformation()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airshipcore\/nsarrayvaluetransformer\/allowsreversetransformation()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSArrayValueTransformer/allowsReverseTransformation()":{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSArrayValueTransformer\/allowsReverseTransformation()","title":"allowsReverseTransformation()","abstract":[],"role":"symbol","url":"\/documentation\/airshipcore\/nsarrayvaluetransformer\/allowsreversetransformation()","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowsReverseTransformation","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"allowsReverseTransformation","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSArrayValueTransformer":{"kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSArrayValueTransformer","type":"topic","url":"\/documentation\/airshipcore\/nsarrayvaluetransformer","abstract":[],"title":"NSArrayValueTransformer","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSArrayValueTransformer","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"NSArrayValueTransformer","kind":"identifier"}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"role":"collection","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","abstract":[],"url":"\/documentation\/airshipcore","title":"AirshipCore","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"allowsReverseTransformation","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"allowsReverseTransformation"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["Mac Catalyst"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"allowsReverseTransformation"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"allowsReverseTransformation","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSArrayValueTransformer~1allowsReverseTransformation()\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"allowsReverseTransformation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSArrayValueTransformer~1allowsReverseTransformation()\/fragments"},{"value":"NSArrayValueTransformer","op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSArrayValueTransformer\/title"},{"value":[{"text":"NSArrayValueTransformer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSArrayValueTransformer\/fragments"},{"value":[{"text":"NSArrayValueTransformer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSArrayValueTransformer\/navigatorTitle"}]}]}