{"metadata":{"externalID":"c:@M@AirshipCore@objc(cs)NSArrayValueTransformer(im)init","title":"init","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"modules":[{"name":"AirshipCore"}],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method"},"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSArrayValueTransformer\/init","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSArrayValueTransformer"]]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/airshipcore\/nsarrayvaluetransformer\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSArrayValueTransformer/init":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"title":"init","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSArrayValueTransformer\/init","navigatorTitle":[{"kind":"identifier","text":"init"}],"kind":"symbol","role":"symbol","url":"\/documentation\/airshipcore\/nsarrayvaluetransformer\/init","abstract":[],"type":"topic"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","url":"\/documentation\/airshipcore","title":"AirshipCore","kind":"symbol","role":"collection"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSArrayValueTransformer":{"navigatorTitle":[{"text":"NSArrayValueTransformer","kind":"identifier"}],"title":"NSArrayValueTransformer","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSArrayValueTransformer","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSArrayValueTransformer","abstract":[],"url":"\/documentation\/airshipcore\/nsarrayvaluetransformer"}},"variantOverrides":[{"patch":[{"value":"NSArrayValueTransformer","op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSArrayValueTransformer\/title"},{"value":[{"text":"NSArrayValueTransformer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSArrayValueTransformer\/fragments"},{"value":[{"text":"NSArrayValueTransformer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSArrayValueTransformer\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}