{"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher\/matcherWhereValueIsPresent(_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/jsonvaluematcher\/matcherwherevalueispresent(_:)"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"matcherWhereValueIsPresent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"present"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher","kind":"typeIdentifier","preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONValueMatcher","text":"JSONValueMatcher"}],"platforms":["Mac Catalyst"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"present","content":[{"inlineContent":[{"type":"text","text":"If "},{"code":"true","type":"codeVoice"},{"type":"text","text":", the value must exist (not be null). If "},{"code":"false","type":"codeVoice"},{"type":"text","text":", it must not."}],"type":"paragraph"}]}]},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"type":"codeVoice","code":"JSONValueMatcher"},{"type":"text","text":" for the specified condition."}]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"matcherWhereValueIsPresent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"JSONValueMatcher","preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONValueMatcher"}],"modules":[{"name":"AirshipCore"}],"symbolKind":"method","title":"matcherWhereValueIsPresent(_:)","externalID":"s:11AirshipCore16JSONValueMatcherC26matcherWhereValueIsPresentyACSbFZ","roleHeading":"Type Method","role":"symbol"},"sections":[],"abstract":[{"type":"text","text":"Creates a matcher that checks for the presence or absence of a value."}],"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONValueMatcher":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSONValueMatcher"}],"role":"symbol","kind":"symbol","title":"JSONValueMatcher","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher","url":"\/documentation\/airshipcore\/jsonvaluematcher","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"JSONValueMatcher"},{"type":"text","text":" is used to match a JSON value against a set of constraints."}],"navigatorTitle":[{"kind":"identifier","text":"JSONValueMatcher"}],"type":"topic"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"type":"topic","title":"AirshipCore","role":"collection","url":"\/documentation\/airshipcore","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","kind":"symbol"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONValueMatcher/matcherWhereValueIsPresent(_:)":{"url":"\/documentation\/airshipcore\/jsonvaluematcher\/matcherwherevalueispresent(_:)","type":"topic","abstract":[{"text":"Creates a matcher that checks for the presence or absence of a value.","type":"text"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher\/matcherWhereValueIsPresent(_:)","title":"matcherWhereValueIsPresent(_:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"matcherWhereValueIsPresent","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"text":"JSONValueMatcher","kind":"typeIdentifier","preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONValueMatcher"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueMatcher\/title","value":"JSONValueMatcher","op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueMatcher\/fragments","value":[{"kind":"identifier","text":"JSONValueMatcher"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueMatcher\/navigatorTitle","value":[{"text":"JSONValueMatcher","kind":"identifier"}],"op":"replace"}]}]}