plugin 'cocoapods-pod-linkage'

platform :ios, '16.0'
use_frameworks! :linkage => :static

target 'AirshipCocoaPodsTest' do
  pod 'Airship'
  pod 'Adjust', '4.38.4'
  pod 'ComScore', '6.11.0'
  pod 'Firebase', '10.22.0'
  pod 'Firebase/Core', '10.22.0'
  pod 'Firebase/InAppMessaging', '10.22.0'
  pod 'Firebase/RemoteConfig', '10.22.0'
  pod 'FirebaseDynamicLinks', '10.22.0'
  pod 'FirebaseCrashlytics', '10.22.0'
  pod 'Realm', '10.36.0'
  pod 'libwebp', '1.5.0'
  pod 'mParticle-Apple-SDK', '8.18.0'
  pod 'GoogleUtilities', '7.13.3'
  pod 'GoogleAds-IMA-iOS-SDK', '3.20.0'
  pod 'Google-Mobile-Ads-SDK', '10.11.0'
  pod 'AmazonPublisherServicesSDK', '4.9.3'
  pod 'FirebaseSharedSwift', '10.29.0'
  pod 'Flutter', '1.0.0'
  pod 'Armchair', '0.3.7'
  pod 'ASN1Swift', '1.2.7'
  pod 'CocoaLumberjack', '3.8.0'
  pod 'CriteoMRAID', '1.0.1'
  pod 'CriteoPublisherSdk', '6.0.0'
  pod 'FileMD5Hash', '2.0.0'
  pod 'FirebaseAnalytics/AdIdSupport', '10.22.0'
  pod 'FirebaseCoreExtension', '10.29.0'
  pod 'FirebaseSessions', '10.29.0'
  pod 'GoogleAppMeasurement', '10.22.0'
  pod 'GoogleDataTransport', '9.4.1'
  pod 'GoogleUserMessagingPlatform', '3.0.0'
  pod 'lottie-ios', '4.5.2'
  pod 'LRAtsSDK', '2.3.0'
  pod 'LRAtsSDKMediationAdapter', '2.4.0'
  pod 'nanopb', '2.30910.0'
  pod 'PrebidMobile', '2.2.0'
  pod 'PromisesObjC', '2.4.0'
  pod 'PromisesSwift', '2.4.0'
  pod 'SDWebImage', '5.11.1'
  pod 'Shimmer', '1.0.2'
  pod 'TaboolaSDK', '4.0.7'
  pod 'SVProgressHUD', '2.1.2'
  pod 'SwiftLint', '0.32.0'
  pod 'JSONModel', '1.8.0'
  pod 'nanopb', '2.30910.0'
  pod 'TPInAppReceipt', '3.0.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end

