{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nativeBridgeDelegate"},{"kind":"text","text":": ("},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:11AirshipCore20NativeBridgeDelegateP","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridgeDelegate","text":"NativeBridgeDelegate"},{"kind":"text","text":")?"}],"platforms":["Mac Catalyst"]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nativeBridgeDelegate"},{"kind":"text","text":": ("},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NativeBridgeDelegate","preciseIdentifier":"s:11AirshipCore20NativeBridgeDelegateP"},{"kind":"text","text":")?"}],"modules":[{"name":"AirshipCore"}],"externalID":"s:11AirshipCore12NativeBridgeC06nativeD8DelegateAA0cdF0_pSgvp","roleHeading":"Instance Property","role":"symbol","title":"nativeBridgeDelegate","symbolKind":"property"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge"]]},"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge\/nativeBridgeDelegate","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/airshipcore\/nativebridge\/nativebridgedelegate"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Delegate to support additional native bridge features such as "},{"type":"codeVoice","code":"close"},{"type":"text","text":"."}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NativeBridge":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NativeBridge"}],"kind":"symbol","role":"symbol","title":"NativeBridge","url":"\/documentation\/airshipcore\/nativebridge","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NativeBridge"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge","abstract":[{"text":"The native bridge will automatically load the Airship JavaScript environment into whitlelisted sites. The native","type":"text"},{"text":" ","type":"text"},{"text":"bridge must be assigned as the navigation delegate on a ","type":"text"},{"type":"codeVoice","code":"WKWebView"},{"text":" in order to function.","type":"text"}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NativeBridgeDelegate":{"role":"symbol","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridgeDelegate","url":"\/documentation\/airshipcore\/nativebridgedelegate","type":"topic","title":"NativeBridgeDelegate","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NativeBridgeDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"NativeBridgeDelegate"}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NativeBridge/nativeBridgeDelegate":{"abstract":[{"text":"Delegate to support additional native bridge features such as ","type":"text"},{"code":"close","type":"codeVoice"},{"text":".","type":"text"}],"url":"\/documentation\/airshipcore\/nativebridge\/nativebridgedelegate","type":"topic","role":"symbol","kind":"symbol","title":"nativeBridgeDelegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nativeBridgeDelegate","kind":"identifier"},{"text":": (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:11AirshipCore20NativeBridgeDelegateP","text":"NativeBridgeDelegate","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge\/nativeBridgeDelegate"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"kind":"symbol","role":"collection","title":"AirshipCore","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","url":"\/documentation\/airshipcore","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge\/title","value":"NativeBridge","op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge\/fragments","value":[{"kind":"identifier","text":"NativeBridge"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge\/navigatorTitle","value":[{"kind":"identifier","text":"NativeBridge"}],"op":"replace"}]}]}