{"kind":"symbol","abstract":[{"text":"Decide whether to allow or cancel a navigation. :nodoc:","type":"text"}],"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge\/webView(_:decidePolicyFor:decisionHandler:)-94du1","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge"]]},"variants":[{"paths":["\/documentation\/airshipcore\/nativebridge\/webview(_:decidepolicyfor:decisionhandler:)-94du1"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airshipcore\/nativebridge\/webview(_:decidepolicyfor:decisionhandler:)-94du1"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"webView(_:decidePolicyFor:decisionHandler:)","navigatorTitle":[{"text":"webView:decidePolicyForNavigationAction:decisionHandler:","kind":"identifier"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"decidePolicyFor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"WKNavigationAction","preciseIdentifier":"c:objc(cs)WKNavigationAction","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"decisionHandler","kind":"externalParam"},{"text":": @","kind":"text"},{"text":"MainActor","kind":"typeIdentifier","preciseIdentifier":"s:ScM"},{"text":" (","kind":"text"},{"text":"WKNavigationActionPolicy","kind":"typeIdentifier","preciseIdentifier":"c:@E@WKNavigationActionPolicy"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"symbolKind":"method","role":"symbol","modules":[{"name":"AirshipCore"}],"externalID":"c:@M@AirshipCore@objc(cs)NativeBridge(im)webView:decidePolicyForNavigationAction:decisionHandler:"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"webView","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"WKWebView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView"},{"text":", ","kind":"text"},{"text":"decidePolicyFor","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"navigationAction","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"WKNavigationAction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKNavigationAction"},{"text":", ","kind":"text"},{"text":"decisionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" @","kind":"text"},{"text":"MainActor","kind":"typeIdentifier","preciseIdentifier":"s:ScM"},{"text":" (","kind":"text"},{"text":"WKNavigationActionPolicy","kind":"typeIdentifier","preciseIdentifier":"c:@E@WKNavigationActionPolicy"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"platforms":["Mac Catalyst"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"If a uairship:\/\/ URL, process it ourselves"}],"type":"paragraph"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NativeBridge/webView(_:decidePolicyFor:decisionHandler:)-94du1":{"navigatorTitle":[{"text":"webView:decidePolicyForNavigationAction:decisionHandler:","kind":"identifier"}],"abstract":[{"type":"text","text":"Decide whether to allow or cancel a navigation. :nodoc:"}],"kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webView","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"decidePolicyFor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKNavigationAction","text":"WKNavigationAction","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"decisionHandler","kind":"externalParam"},{"text":": @","kind":"text"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"typeIdentifier"},{"text":" (","kind":"text"},{"preciseIdentifier":"c:@E@WKNavigationActionPolicy","text":"WKNavigationActionPolicy","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge\/webView(_:decidePolicyFor:decisionHandler:)-94du1","url":"\/documentation\/airshipcore\/nativebridge\/webview(_:decidepolicyfor:decisionhandler:)-94du1","title":"webView(_:decidePolicyFor:decisionHandler:)"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","url":"\/documentation\/airshipcore","abstract":[],"kind":"symbol","role":"collection","title":"AirshipCore"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NativeBridge":{"role":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge","abstract":[{"text":"The native bridge will automatically load the Airship JavaScript environment into whitlelisted sites. The native","type":"text"},{"text":" ","type":"text"},{"text":"bridge must be assigned as the navigation delegate on a ","type":"text"},{"code":"WKWebView","type":"codeVoice"},{"text":" in order to function.","type":"text"}],"title":"NativeBridge","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NativeBridge","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"NativeBridge","kind":"identifier"}],"url":"\/documentation\/airshipcore\/nativebridge"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"webView:decidePolicyForNavigationAction:decisionHandler:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:decidePolicyForNavigationAction:decisionHandler:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"webView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"webView"},{"kind":"text","text":" "},{"kind":"identifier","text":"decidePolicyForNavigationAction:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKNavigationAction","text":"WKNavigationAction"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"navigationAction"},{"kind":"text","text":" "},{"kind":"identifier","text":"decisionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^)("},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@WKNavigationActionPolicy","text":"WKNavigationActionPolicy"},{"kind":"text","text":" "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"decisionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["Mac Catalyst"]}]}},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge~1webView(_:decidePolicyFor:decisionHandler:)-94du1\/title","op":"replace","value":"webView:decidePolicyForNavigationAction:decisionHandler:"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge~1webView(_:decidePolicyFor:decisionHandler:)-94du1\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"webView:decidePolicyForNavigationAction:decisionHandler:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge\/title","op":"replace","value":"NativeBridge"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge\/fragments","op":"replace","value":[{"kind":"identifier","text":"NativeBridge"}]},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"NativeBridge"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}