{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueTransformer\/allowsReverseTransformation()"},"sections":[],"metadata":{"modules":[{"name":"AirshipCore"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowsReverseTransformation"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"allowsReverseTransformation"}],"roleHeading":"Type Method","symbolKind":"method","externalID":"c:@M@AirshipCore@objc(cs)JSONValueTransformer(cm)allowsReverseTransformation","title":"allowsReverseTransformation()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowsReverseTransformation","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/jsonvaluetransformer\/allowsreversetransformation()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airshipcore\/jsonvaluetransformer\/allowsreversetransformation()"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueTransformer"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONValueTransformer/allowsReverseTransformation()":{"abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueTransformer\/allowsReverseTransformation()","navigatorTitle":[{"text":"allowsReverseTransformation","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowsReverseTransformation","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/airshipcore\/jsonvaluetransformer\/allowsreversetransformation()","title":"allowsReverseTransformation()"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"title":"AirshipCore","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/airshipcore"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONValueTransformer":{"navigatorTitle":[{"text":"JSONValueTransformer","kind":"identifier"}],"type":"topic","title":"JSONValueTransformer","url":"\/documentation\/airshipcore\/jsonvaluetransformer","abstract":[{"text":"NOTE: For internal use only. :nodoc:","type":"text"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueTransformer","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"JSONValueTransformer","kind":"identifier"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"allowsReverseTransformation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"allowsReverseTransformation","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"allowsReverseTransformation"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["Mac Catalyst"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"allowsReverseTransformation","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueTransformer~1allowsReverseTransformation()\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"allowsReverseTransformation"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueTransformer~1allowsReverseTransformation()\/fragments"},{"op":"replace","value":"JSONValueTransformer","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueTransformer\/title"},{"op":"replace","value":[{"text":"JSONValueTransformer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueTransformer\/fragments"},{"op":"replace","value":[{"text":"JSONValueTransformer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueTransformer\/navigatorTitle"}]}]}