{"metadata":{"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","title":"transformedValue(_:)","modules":[{"name":"AirshipCore"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transformedValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?","kind":"text"}],"externalID":"c:@M@AirshipCore@objc(cs)JSONValueTransformer(im)transformedValue:","navigatorTitle":[{"text":"transformedValue:","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueTransformer\/transformedValue(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueTransformer"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transformedValue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"value"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}]}]}],"variants":[{"paths":["\/documentation\/airshipcore\/jsonvaluetransformer\/transformedvalue(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airshipcore\/jsonvaluetransformer\/transformedvalue(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONValueTransformer":{"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JSONValueTransformer","kind":"identifier"}],"navigatorTitle":[{"text":"JSONValueTransformer","kind":"identifier"}],"title":"JSONValueTransformer","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueTransformer","abstract":[{"type":"text","text":"NOTE: For internal use only. :nodoc:"}],"kind":"symbol","url":"\/documentation\/airshipcore\/jsonvaluetransformer"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"kind":"symbol","role":"collection","title":"AirshipCore","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","url":"\/documentation\/airshipcore","abstract":[]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONValueTransformer/transformedValue(_:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transformedValue"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueTransformer\/transformedValue(_:)","title":"transformedValue(_:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"transformedValue:"}],"role":"symbol","abstract":[],"url":"\/documentation\/airshipcore\/jsonvaluetransformer\/transformedvalue(_:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"transformedValue:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"transformedValue:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"transformedValue:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"value"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst"]}]}},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueTransformer\/title","op":"replace","value":"JSONValueTransformer"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueTransformer\/fragments","op":"replace","value":[{"kind":"identifier","text":"JSONValueTransformer"}]},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueTransformer\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"JSONValueTransformer"}]},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueTransformer~1transformedValue(_:)\/title","op":"replace","value":"transformedValue:"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueTransformer~1transformedValue(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"transformedValue:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}