{"kind":"symbol","metadata":{"externalID":"s:35AirshipNotificationServiceExtension17ChallengeResolverC7resolveySo016NSURLSessionAuthE11DispositionV_So15NSURLCredentialCSgtSo019NSURLAuthenticationE0CYaF","roleHeading":"Instance Method","symbolKind":"method","title":"resolve(_:)","modules":[{"name":"AirshipNotificationServiceExtension"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resolve","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLAuthenticationChallenge","text":"URLAuthenticationChallenge","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLSession","text":"URLSession","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSURLSessionAuthChallengeDisposition","text":"AuthChallengeDisposition","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLCredential","text":"URLCredential","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/ChallengeResolver\/resolve(_:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["Mac Catalyst"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resolve","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"challenge","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"URLAuthenticationChallenge","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLAuthenticationChallenge"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> (","kind":"text"},{"text":"URLSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSession"},{"text":".","kind":"text"},{"text":"AuthChallengeDisposition","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSURLSessionAuthChallengeDisposition"},{"text":", ","kind":"text"},{"text":"URLCredential","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLCredential"},{"text":"?)","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipnotificationserviceextension\/challengeresolver\/resolve(_:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension","doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/ChallengeResolver"]]},"sections":[],"references":{"doc://com.urbanairship.AirshipNotificationServiceExtension/documentation/AirshipNotificationServiceExtension/ChallengeResolver/resolve(_:)":{"role":"symbol","url":"\/documentation\/airshipnotificationserviceextension\/challengeresolver\/resolve(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resolve"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"URLAuthenticationChallenge","preciseIdentifier":"c:objc(cs)NSURLAuthenticationChallenge"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> ("},{"kind":"typeIdentifier","text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"AuthChallengeDisposition","preciseIdentifier":"c:@E@NSURLSessionAuthChallengeDisposition"},{"kind":"text","text":", "},{"preciseIdentifier":"c:objc(cs)NSURLCredential","kind":"typeIdentifier","text":"URLCredential"},{"kind":"text","text":"?)"}],"kind":"symbol","title":"resolve(_:)","type":"topic","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/ChallengeResolver\/resolve(_:)"},"doc://com.urbanairship.AirshipNotificationServiceExtension/documentation/AirshipNotificationServiceExtension":{"abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension","title":"AirshipNotificationServiceExtension","type":"topic","url":"\/documentation\/airshipnotificationserviceextension","role":"collection","kind":"symbol"},"doc://com.urbanairship.AirshipNotificationServiceExtension/documentation/AirshipNotificationServiceExtension/ChallengeResolver":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChallengeResolver","kind":"identifier"}],"role":"symbol","title":"ChallengeResolver","url":"\/documentation\/airshipnotificationserviceextension\/challengeresolver","abstract":[{"type":"text","text":"Authentication challenge resolver class"}],"navigatorTitle":[{"text":"ChallengeResolver","kind":"identifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/ChallengeResolver","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"ChallengeResolver","op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipNotificationServiceExtension~1documentation~1AirshipNotificationServiceExtension~1ChallengeResolver\/title"},{"value":[{"text":"ChallengeResolver","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipNotificationServiceExtension~1documentation~1AirshipNotificationServiceExtension~1ChallengeResolver\/fragments"},{"value":[{"text":"ChallengeResolver","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipNotificationServiceExtension~1documentation~1AirshipNotificationServiceExtension~1ChallengeResolver\/navigatorTitle"}]}]}