{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/ChallengeResolver\/shared","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ChallengeResolver","kind":"typeIdentifier","preciseIdentifier":"c:@M@AirshipNotificationServiceExtension@objc(cs)ChallengeResolver","identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/ChallengeResolver"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipnotificationserviceextension\/challengeresolver\/shared"]}],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension","doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/ChallengeResolver"]]},"sections":[],"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Type Property","title":"shared","externalID":"s:35AirshipNotificationServiceExtension17ChallengeResolverC6sharedACvpZ","symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AirshipNotificationServiceExtension@objc(cs)ChallengeResolver","text":"ChallengeResolver","kind":"typeIdentifier"}],"modules":[{"name":"AirshipNotificationServiceExtension"}]},"references":{"doc://com.urbanairship.AirshipNotificationServiceExtension/documentation/AirshipNotificationServiceExtension/ChallengeResolver":{"navigatorTitle":[{"kind":"identifier","text":"ChallengeResolver"}],"url":"\/documentation\/airshipnotificationserviceextension\/challengeresolver","kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/ChallengeResolver","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChallengeResolver"}],"role":"symbol","abstract":[{"type":"text","text":"Authentication challenge resolver class"}],"title":"ChallengeResolver","type":"topic"},"doc://com.urbanairship.AirshipNotificationServiceExtension/documentation/AirshipNotificationServiceExtension/ChallengeResolver/shared":{"abstract":[],"role":"symbol","url":"\/documentation\/airshipnotificationserviceextension\/challengeresolver\/shared","kind":"symbol","title":"shared","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ChallengeResolver","preciseIdentifier":"c:@M@AirshipNotificationServiceExtension@objc(cs)ChallengeResolver","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/ChallengeResolver\/shared","type":"topic"},"doc://com.urbanairship.AirshipNotificationServiceExtension/documentation/AirshipNotificationServiceExtension":{"type":"topic","title":"AirshipNotificationServiceExtension","role":"collection","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension","url":"\/documentation\/airshipnotificationserviceextension","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"ChallengeResolver","path":"\/references\/doc:~1~1com.urbanairship.AirshipNotificationServiceExtension~1documentation~1AirshipNotificationServiceExtension~1ChallengeResolver\/title"},{"op":"replace","value":[{"text":"ChallengeResolver","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipNotificationServiceExtension~1documentation~1AirshipNotificationServiceExtension~1ChallengeResolver\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ChallengeResolver"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipNotificationServiceExtension~1documentation~1AirshipNotificationServiceExtension~1ChallengeResolver\/navigatorTitle"}]}]}