{"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"URLSession:task:didReceiveChallenge:completionHandler:","kind":"identifier"}],"extendedModule":"AirshipCore","title":"urlSession(_:task:didReceive:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"urlSession","kind":"identifier"},{"text":"(","kind":"text"},{"text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"task","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URLSessionTask","preciseIdentifier":"c:objc(cs)NSURLSessionTask","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didReceive","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URLAuthenticationChallenge","preciseIdentifier":"c:objc(cs)NSURLAuthenticationChallenge","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> (","kind":"text"},{"text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"AuthChallengeDisposition","preciseIdentifier":"c:@E@NSURLSessionAuthChallengeDisposition","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"URLCredential","preciseIdentifier":"c:objc(cs)NSURLCredential","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol","symbolKind":"method","modules":[{"name":"AirshipCore"}],"externalID":"c:@CM@AirshipCore@objc(cs)ChallengeResolver(im)URLSession:task:didReceiveChallenge:completionHandler:"},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"URLSessionTaskDelegate.urlSession(_:task:didReceive:)"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"urlSession","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"session","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLSession","text":"URLSession","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"task","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSURLSessionTask","kind":"typeIdentifier","text":"URLSessionTask"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":" "},{"kind":"internalParam","text":"challenge"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSURLAuthenticationChallenge","kind":"typeIdentifier","text":"URLAuthenticationChallenge"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> ("},{"preciseIdentifier":"c:objc(cs)NSURLSession","kind":"typeIdentifier","text":"URLSession"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@NSURLSessionAuthChallengeDisposition","kind":"typeIdentifier","text":"AuthChallengeDisposition"},{"kind":"text","text":", "},{"preciseIdentifier":"c:objc(cs)NSURLCredential","kind":"typeIdentifier","text":"URLCredential"},{"kind":"text","text":"?)"}],"platforms":["Mac Catalyst"]}]}],"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ChallengeResolver\/urlSession(_:task:didReceive:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/challengeresolver\/urlsession(_:task:didreceive:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airshipcore\/challengeresolver\/urlsession(_:task:didreceive:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ChallengeResolver"]]},"kind":"symbol","references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/ChallengeResolver":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChallengeResolver","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ChallengeResolver","abstract":[{"text":"Authentication challenge resolver class","type":"text"}],"title":"ChallengeResolver","kind":"symbol","navigatorTitle":[{"text":"ChallengeResolver","kind":"identifier"}],"url":"\/documentation\/airshipcore\/challengeresolver"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","url":"\/documentation\/airshipcore","title":"AirshipCore","kind":"symbol","role":"collection"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/ChallengeResolver/urlSession(_:task:didReceive:)":{"navigatorTitle":[{"text":"URLSession:task:didReceiveChallenge:completionHandler:","kind":"identifier"}],"role":"symbol","title":"urlSession(_:task:didReceive:)","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ChallengeResolver\/urlSession(_:task:didReceive:)","type":"topic","kind":"symbol","url":"\/documentation\/airshipcore\/challengeresolver\/urlsession(_:task:didreceive:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"urlSession","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLSession","text":"URLSession","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"task","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLSessionTask","text":"URLSessionTask","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didReceive","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLAuthenticationChallenge","text":"URLAuthenticationChallenge","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLSession","text":"URLSession","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSURLSessionAuthChallengeDisposition","text":"AuthChallengeDisposition","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLCredential","text":"URLCredential","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"URLSession:task:didReceiveChallenge:completionHandler:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"URLSession:task:didReceiveChallenge:completionHandler:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"URLSession:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSURLSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSession"},{"text":" *) ","kind":"text"},{"text":"session","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"task:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSURLSessionTask","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSessionTask"},{"text":" *) ","kind":"text"},{"text":"task","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didReceiveChallenge:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSURLAuthenticationChallenge","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLAuthenticationChallenge"},{"text":" *) ","kind":"text"},{"text":"challenge","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^)(","kind":"text"},{"text":"NSURLSessionAuthChallengeDisposition","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSURLSessionAuthChallengeDisposition"},{"text":" ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"NSURLCredential","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLCredential"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ChallengeResolver","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ChallengeResolver\/title"},{"value":[{"kind":"identifier","text":"ChallengeResolver"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ChallengeResolver\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ChallengeResolver"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ChallengeResolver\/navigatorTitle","op":"replace"},{"value":"URLSession:task:didReceiveChallenge:completionHandler:","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ChallengeResolver~1urlSession(_:task:didReceive:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"URLSession:task:didReceiveChallenge:completionHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ChallengeResolver~1urlSession(_:task:didReceive:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}