{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/challengeresolver\/urlsessiondelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airshipcore\/challengeresolver\/urlsessiondelegate-implementations"]}],"kind":"article","hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ChallengeResolver"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ChallengeResolver\/URLSessionDelegate-Implementations"},"topicSections":[{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ChallengeResolver\/urlSession(_:didReceive:)"],"title":"Instance Methods"}],"sections":[],"metadata":{"roleHeading":"API Collection","modules":[{"name":"AirshipCore"}],"role":"collectionGroup","title":"URLSessionDelegate Implementations"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/ChallengeResolver":{"url":"\/documentation\/airshipcore\/challengeresolver","kind":"symbol","abstract":[{"text":"Authentication challenge resolver class","type":"text"}],"navigatorTitle":[{"text":"ChallengeResolver","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChallengeResolver","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ChallengeResolver","title":"ChallengeResolver"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/ChallengeResolver/urlSession(_:didReceive:)":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ChallengeResolver\/urlSession(_:didReceive:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"urlSession","kind":"identifier"},{"text":"(","kind":"text"},{"text":"URLSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSession"},{"text":", ","kind":"text"},{"text":"didReceive","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URLAuthenticationChallenge","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLAuthenticationChallenge"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> (","kind":"text"},{"text":"URLSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSession"},{"text":".","kind":"text"},{"text":"AuthChallengeDisposition","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSURLSessionAuthChallengeDisposition"},{"text":", ","kind":"text"},{"text":"URLCredential","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLCredential"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"URLSession:didReceiveChallenge:completionHandler:","kind":"identifier"}],"url":"\/documentation\/airshipcore\/challengeresolver\/urlsession(_:didreceive:)","title":"urlSession(_:didReceive:)","type":"topic"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"url":"\/documentation\/airshipcore","kind":"symbol","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","abstract":[],"title":"AirshipCore","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ChallengeResolver\/urlSession(_:didReceive:)"],"generated":true,"anchor":"Instance-Methods"}],"path":"\/topicSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":"ChallengeResolver","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ChallengeResolver\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ChallengeResolver"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ChallengeResolver\/fragments"},{"op":"replace","value":[{"text":"ChallengeResolver","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ChallengeResolver\/navigatorTitle"},{"op":"replace","value":"URLSession:didReceiveChallenge:completionHandler:","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ChallengeResolver~1urlSession(_:didReceive:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"URLSession:didReceiveChallenge:completionHandler:"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ChallengeResolver~1urlSession(_:didReceive:)\/fragments"}]}]}