{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ChallengeResolver\/urlSession(_:didReceive:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/challengeresolver\/urlsession(_:didreceive:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airshipcore\/challengeresolver\/urlsession(_:didreceive:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ChallengeResolver"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"URLSessionDelegate.urlSession(_:didReceive:)"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["Mac Catalyst"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"urlSession","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"session","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didReceive","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"challenge","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"URLAuthenticationChallenge","preciseIdentifier":"c:objc(cs)NSURLAuthenticationChallenge","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> (","kind":"text"},{"text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"AuthChallengeDisposition","preciseIdentifier":"c:@E@NSURLSessionAuthChallengeDisposition","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"URLCredential","preciseIdentifier":"c:objc(cs)NSURLCredential","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"externalID":"c:@CM@AirshipCore@objc(cs)ChallengeResolver(im)URLSession:didReceiveChallenge:completionHandler:","title":"urlSession(_:didReceive:)","roleHeading":"Instance Method","role":"symbol","extendedModule":"AirshipCore","modules":[{"name":"AirshipCore"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"URLSession:didReceiveChallenge:completionHandler:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlSession"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSession","text":"URLSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLAuthenticationChallenge","text":"URLAuthenticationChallenge"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSession","text":"URLSession"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSURLSessionAuthChallengeDisposition","text":"AuthChallengeDisposition"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLCredential","text":"URLCredential"},{"kind":"text","text":"?)"}]},"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/ChallengeResolver/urlSession(_:didReceive:)":{"title":"urlSession(_:didReceive:)","url":"\/documentation\/airshipcore\/challengeresolver\/urlsession(_:didreceive:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlSession"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSURLSession","kind":"typeIdentifier","text":"URLSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSURLAuthenticationChallenge","kind":"typeIdentifier","text":"URLAuthenticationChallenge"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> ("},{"preciseIdentifier":"c:objc(cs)NSURLSession","kind":"typeIdentifier","text":"URLSession"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@NSURLSessionAuthChallengeDisposition","kind":"typeIdentifier","text":"AuthChallengeDisposition"},{"kind":"text","text":", "},{"preciseIdentifier":"c:objc(cs)NSURLCredential","kind":"typeIdentifier","text":"URLCredential"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"URLSession:didReceiveChallenge:completionHandler:"}],"role":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ChallengeResolver\/urlSession(_:didReceive:)","type":"topic","kind":"symbol","abstract":[]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"url":"\/documentation\/airshipcore","role":"collection","abstract":[],"title":"AirshipCore","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","type":"topic","kind":"symbol"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/ChallengeResolver":{"title":"ChallengeResolver","url":"\/documentation\/airshipcore\/challengeresolver","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChallengeResolver"}],"navigatorTitle":[{"kind":"identifier","text":"ChallengeResolver"}],"role":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ChallengeResolver","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Authentication challenge resolver class"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"URLSession:didReceiveChallenge:completionHandler:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"URLSession:didReceiveChallenge:completionHandler:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"URLSession:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSURLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"session"},{"kind":"text","text":" "},{"kind":"identifier","text":"didReceiveChallenge:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSURLAuthenticationChallenge","preciseIdentifier":"c:objc(cs)NSURLAuthenticationChallenge"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"challenge"},{"kind":"text","text":" "},{"kind":"identifier","text":"completionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" (^)("},{"kind":"typeIdentifier","text":"NSURLSessionAuthChallengeDisposition","preciseIdentifier":"c:@E@NSURLSessionAuthChallengeDisposition"},{"kind":"text","text":" "},{"kind":"internalParam","text":""},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"NSURLCredential","preciseIdentifier":"c:objc(cs)NSURLCredential"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completionHandler"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ChallengeResolver~1urlSession(_:didReceive:)\/title","op":"replace","value":"URLSession:didReceiveChallenge:completionHandler:"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ChallengeResolver~1urlSession(_:didReceive:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"URLSession:didReceiveChallenge:completionHandler:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ChallengeResolver\/title","op":"replace","value":"ChallengeResolver"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ChallengeResolver\/fragments","op":"replace","value":[{"text":"ChallengeResolver","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ChallengeResolver\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ChallengeResolver"}]}]}]}