{"variants":[{"paths":["\/documentation\/airshipcore\/jsonmatcher\/init(valuematcher:scope:ignorecase:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher"]]},"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"valueMatcher","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONValueMatcher","text":"JSONValueMatcher","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"scope","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"ignoreCase","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"s:11AirshipCore11JSONMatcherC12valueMatcher5scope10ignoreCaseAcA09JSONValueE0C_SaySSGSbtcfc","symbolKind":"init","roleHeading":"Initializer","role":"symbol","modules":[{"name":"AirshipCore"}],"title":"init(valueMatcher:scope:ignoreCase:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["Mac Catalyst"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"valueMatcher"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONValueMatcher","text":"JSONValueMatcher","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scope"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"ignoreCase"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"For internal use only. :nodoc:"}]}],"name":"Note"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/init(valueMatcher:scope:ignoreCase:)"},"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONMatcher/init(valueMatcher:scope:ignoreCase:)":{"url":"\/documentation\/airshipcore\/jsonmatcher\/init(valuematcher:scope:ignorecase:)","abstract":[],"title":"init(valueMatcher:scope:ignoreCase:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"valueMatcher","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONValueMatcher","text":"JSONValueMatcher","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"scope","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"ignoreCase","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/init(valueMatcher:scope:ignoreCase:)"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONValueMatcher":{"url":"\/documentation\/airshipcore\/jsonvaluematcher","abstract":[{"type":"text","text":"A "},{"code":"JSONValueMatcher","type":"codeVoice"},{"type":"text","text":" is used to match a JSON value against a set of constraints."}],"type":"topic","navigatorTitle":[{"text":"JSONValueMatcher","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JSONValueMatcher","kind":"identifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher","title":"JSONValueMatcher"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"url":"\/documentation\/airshipcore","kind":"symbol","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","title":"AirshipCore"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONMatcher":{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher","url":"\/documentation\/airshipcore\/jsonmatcher","title":"JSONMatcher","type":"topic","role":"symbol","navigatorTitle":[{"text":"JSONMatcher","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JSONMatcher","kind":"identifier"}],"abstract":[{"type":"text","text":"A matcher for evaluating a JSON payload against a set of criteria."}]}},"variantOverrides":[{"patch":[{"value":"JSONValueMatcher","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueMatcher\/title","op":"replace"},{"value":[{"text":"JSONValueMatcher","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueMatcher\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"JSONValueMatcher"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueMatcher\/navigatorTitle","op":"replace"},{"value":"JSONMatcher","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONMatcher\/title","op":"replace"},{"value":[{"text":"JSONMatcher","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONMatcher\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"JSONMatcher"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONMatcher\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}