{"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/init(valueMatcher:ignoreCase:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst"],"tokens":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"valueMatcher","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONValueMatcher","text":"JSONValueMatcher","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"ignoreCase","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"name":"Note","content":[{"inlineContent":[{"text":"For internal use only. :nodoc:","type":"text"}],"type":"paragraph"}],"type":"aside","style":"note"}]}],"variants":[{"paths":["\/documentation\/airshipcore\/jsonmatcher\/init(valuematcher:ignorecase:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher"]]},"metadata":{"role":"symbol","roleHeading":"Initializer","externalID":"s:11AirshipCore11JSONMatcherC12valueMatcher10ignoreCaseAcA09JSONValueE0C_Sbtcfc","modules":[{"name":"AirshipCore"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"valueMatcher"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONValueMatcher","kind":"typeIdentifier","text":"JSONValueMatcher"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ignoreCase"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"symbolKind":"init","title":"init(valueMatcher:ignoreCase:)"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"url":"\/documentation\/airshipcore","title":"AirshipCore","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","kind":"symbol","abstract":[],"type":"topic","role":"collection"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONMatcher/init(valueMatcher:ignoreCase:)":{"role":"symbol","kind":"symbol","url":"\/documentation\/airshipcore\/jsonmatcher\/init(valuematcher:ignorecase:)","type":"topic","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/init(valueMatcher:ignoreCase:)","title":"init(valueMatcher:ignoreCase:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"valueMatcher"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONValueMatcher","kind":"typeIdentifier","text":"JSONValueMatcher"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ignoreCase"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONValueMatcher":{"title":"JSONValueMatcher","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JSONValueMatcher","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/airshipcore\/jsonvaluematcher","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"JSONValueMatcher"},{"type":"text","text":" is used to match a JSON value against a set of constraints."}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher","role":"symbol","navigatorTitle":[{"text":"JSONValueMatcher","kind":"identifier"}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONMatcher":{"abstract":[{"type":"text","text":"A matcher for evaluating a JSON payload against a set of criteria."}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSONMatcher"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"JSONMatcher"}],"url":"\/documentation\/airshipcore\/jsonmatcher","role":"symbol","title":"JSONMatcher"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueMatcher\/title","value":"JSONValueMatcher"},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueMatcher\/fragments","value":[{"text":"JSONValueMatcher","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueMatcher\/navigatorTitle","value":[{"text":"JSONValueMatcher","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONMatcher\/title","op":"replace","value":"JSONMatcher"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONMatcher\/fragments","op":"replace","value":[{"text":"JSONMatcher","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONMatcher\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"JSONMatcher"}]}]}]}