{"variants":[{"paths":["\/documentation\/airshipcore\/jsonmatcher\/init(valuematcher:scope:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","abstract":[{"type":"text","text":"Creates a new "},{"type":"codeVoice","code":"JSONMatcher"},{"type":"text","text":" with a specified scope."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"valueMatcher","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"JSONValueMatcher","preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONValueMatcher","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"scope","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"roleHeading":"Initializer","title":"init(valueMatcher:scope:)","modules":[{"name":"AirshipCore"}],"symbolKind":"init","externalID":"s:11AirshipCore11JSONMatcherC12valueMatcher5scopeAcA09JSONValueE0C_SaySSGtcfc"},"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/init(valueMatcher:scope:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"valueMatcher","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"JSONValueMatcher","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher","preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONValueMatcher","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"scope","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"languages":["swift"],"platforms":["Mac Catalyst"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"JSONValueMatcher"},{"text":" to apply to the value.","type":"text"}]}],"name":"valueMatcher"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of keys representing the path to the value."}]}],"name":"scope"}],"kind":"parameters"},{"content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A new "},{"code":"JSONMatcher","type":"codeVoice"},{"type":"text","text":" instance."}]}],"kind":"content"}],"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONMatcher/init(valueMatcher:scope:)":{"title":"init(valueMatcher:scope:)","url":"\/documentation\/airshipcore\/jsonmatcher\/init(valuematcher:scope:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"valueMatcher"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONValueMatcher","text":"JSONValueMatcher"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scope"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"])"}],"abstract":[{"text":"Creates a new ","type":"text"},{"code":"JSONMatcher","type":"codeVoice"},{"text":" with a specified scope.","type":"text"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/init(valueMatcher:scope:)","type":"topic","kind":"symbol","role":"symbol"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONValueMatcher":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JSONValueMatcher","kind":"identifier"}],"navigatorTitle":[{"text":"JSONValueMatcher","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"JSONValueMatcher"},{"type":"text","text":" is used to match a JSON value against a set of constraints."}],"type":"topic","title":"JSONValueMatcher","url":"\/documentation\/airshipcore\/jsonvaluematcher","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher","role":"symbol"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONMatcher":{"abstract":[{"text":"A matcher for evaluating a JSON payload against a set of criteria.","type":"text"}],"navigatorTitle":[{"text":"JSONMatcher","kind":"identifier"}],"type":"topic","title":"JSONMatcher","url":"\/documentation\/airshipcore\/jsonmatcher","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JSONMatcher","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"abstract":[],"role":"collection","url":"\/documentation\/airshipcore","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","kind":"symbol","title":"AirshipCore"}},"variantOverrides":[{"patch":[{"value":"JSONValueMatcher","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueMatcher\/title","op":"replace"},{"value":[{"text":"JSONValueMatcher","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueMatcher\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"JSONValueMatcher"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueMatcher\/navigatorTitle","op":"replace"},{"value":"JSONMatcher","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONMatcher\/title","op":"replace"},{"value":[{"text":"JSONMatcher","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONMatcher\/fragments","op":"replace"},{"value":[{"text":"JSONMatcher","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONMatcher\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}