{"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use Codable conformance for serialization instead.","type":"text"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/jsonmatcher\/init(json:)"]}],"sections":[],"abstract":[{"text":"Creates a new ","type":"text"},{"type":"codeVoice","code":"JSONMatcher"},{"text":" from a JSON payload.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"json"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"}],"platforms":["Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The JSON payload to create the matcher from.","type":"text"}]}],"name":"json"}],"kind":"parameters"},{"content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":"A "},{"type":"codeVoice","code":"JSONMatcher"},{"type":"text","text":" instance."}],"type":"paragraph"}],"kind":"content"},{"content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"content":[{"inlineContent":[{"text":"An error if the JSON is invalid or cannot be decoded.","type":"text"}],"type":"paragraph"}],"name":"Throws","type":"aside","style":"note"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher"]]},"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/init(json:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"json","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"platforms":[{"message":"Use Codable conformance for serialization instead.","deprecated":true,"unavailable":false,"beta":false}],"modules":[{"name":"AirshipCore"}],"roleHeading":"Initializer","externalID":"s:11AirshipCore11JSONMatcherC4jsonACypSg_tKcfc","title":"init(json:)","symbolKind":"init"},"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONMatcher/init(json:)":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/init(json:)","deprecated":true,"title":"init(json:)","url":"\/documentation\/airshipcore\/jsonmatcher\/init(json:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"json","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"abstract":[{"type":"text","text":"Creates a new "},{"type":"codeVoice","code":"JSONMatcher"},{"type":"text","text":" from a JSON payload."}],"kind":"symbol"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONMatcher":{"url":"\/documentation\/airshipcore\/jsonmatcher","abstract":[{"text":"A matcher for evaluating a JSON payload against a set of criteria.","type":"text"}],"type":"topic","title":"JSONMatcher","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"JSONMatcher"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSONMatcher"}],"kind":"symbol"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"title":"AirshipCore","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/airshipcore"}},"variantOverrides":[{"patch":[{"value":"JSONMatcher","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONMatcher\/title","op":"replace"},{"value":[{"text":"JSONMatcher","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONMatcher\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"JSONMatcher"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONMatcher\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}