{"deprecationSummary":[{"inlineContent":[{"text":"Use Codable conformance for serialization instead.","type":"text"}],"type":"paragraph"}],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/payload()"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"payload","kind":"identifier"},{"text":"() -> [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"platforms":["Mac Catalyst"],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"A "},{"type":"codeVoice","code":"[String: Any]"},{"type":"text","text":" dictionary representing the matcher."}],"type":"paragraph"}]}],"kind":"symbol","metadata":{"role":"symbol","externalID":"s:11AirshipCore11JSONMatcherC7payloadSDySSypGyF","modules":[{"name":"AirshipCore"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"payload"},{"kind":"text","text":"() -> ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]"}],"title":"payload()","roleHeading":"Instance Method","symbolKind":"method","platforms":[{"deprecated":true,"beta":false,"message":"Use Codable conformance for serialization instead.","unavailable":false}]},"abstract":[{"type":"text","text":"Returns the matcher’s JSON payload representation."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/jsonmatcher\/payload()"]}],"sections":[],"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONMatcher/payload()":{"role":"symbol","abstract":[{"type":"text","text":"Returns the matcher’s JSON payload representation."}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/payload()","type":"topic","url":"\/documentation\/airshipcore\/jsonmatcher\/payload()","title":"payload()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"payload"},{"kind":"text","text":"() -> ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"deprecated":true},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"url":"\/documentation\/airshipcore","title":"AirshipCore","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","kind":"symbol","abstract":[],"type":"topic","role":"collection"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONMatcher":{"abstract":[{"type":"text","text":"A matcher for evaluating a JSON payload against a set of criteria."}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSONMatcher"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"JSONMatcher"}],"url":"\/documentation\/airshipcore\/jsonmatcher","role":"symbol","title":"JSONMatcher"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONMatcher\/title","value":"JSONMatcher","op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONMatcher\/fragments","value":[{"kind":"identifier","text":"JSONMatcher"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONMatcher\/navigatorTitle","value":[{"kind":"identifier","text":"JSONMatcher"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}