{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst"],"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actionsManifest","kind":"identifier"},{"text":": (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:11AirshipCore15ActionsManifestP","text":"ActionsManifest","kind":"typeIdentifier"},{"text":")?","kind":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/AutomationSDKModule\/actionsManifest"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipautomation\/automationsdkmodule\/actionsmanifest"]}],"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actionsManifest","kind":"identifier"},{"text":": (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:11AirshipCore15ActionsManifestP","text":"ActionsManifest","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"title":"actionsManifest","externalID":"s:17AirshipAutomation0B9SDKModuleC15actionsManifest0A4Core07ActionsE0_pSgvp","modules":[{"name":"AirshipAutomation"}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/AutomationSDKModule"]]},"abstract":[{"type":"text","text":"Inherited from "},{"code":"AirshipSDKModule.actionsManifest","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","references":{"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/AutomationSDKModule/actionsManifest":{"title":"actionsManifest","type":"topic","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actionsManifest","kind":"identifier"},{"text":": (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActionsManifest","kind":"typeIdentifier","preciseIdentifier":"s:11AirshipCore15ActionsManifestP"},{"text":")?","kind":"text"}],"identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/AutomationSDKModule\/actionsManifest","url":"\/documentation\/airshipautomation\/automationsdkmodule\/actionsmanifest"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation":{"kind":"symbol","url":"\/documentation\/airshipautomation","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation","title":"AirshipAutomation"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/AutomationSDKModule":{"type":"topic","title":"AutomationSDKModule","kind":"symbol","abstract":[{"text":"NOTE: For internal use only. :nodoc:","type":"text"}],"url":"\/documentation\/airshipautomation\/automationsdkmodule","identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/AutomationSDKModule","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomationSDKModule","kind":"identifier"}],"navigatorTitle":[{"text":"AutomationSDKModule","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.urbanairship.AirshipAutomation~1documentation~1AirshipAutomation~1AutomationSDKModule\/title","value":"UAAutomationSDKModule","op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipAutomation~1documentation~1AirshipAutomation~1AutomationSDKModule\/fragments","value":[{"text":"UAAutomationSDKModule","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipAutomation~1documentation~1AirshipAutomation~1AutomationSDKModule\/navigatorTitle","value":[{"text":"UAAutomationSDKModule","kind":"identifier"}],"op":"replace"}]}]}