{"metadata":{"roleHeading":"Type Property","modules":[{"name":"AirshipCore"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cell","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"externalID":"s:11AirshipCore14ConnectionTypeC4cellSSvpZ","title":"cell","symbolKind":"property","role":"symbol"},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/connectiontype\/cell"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ConnectionType\/cell"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cell","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"platforms":["Mac Catalyst"],"languages":["swift"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ConnectionType"]]},"abstract":[{"text":"Network is a cellular or mobile network.","type":"text"}],"sections":[],"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","url":"\/documentation\/airshipcore","abstract":[],"kind":"symbol","role":"collection","title":"AirshipCore"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/ConnectionType":{"title":"ConnectionType","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ConnectionType","kind":"identifier"}],"abstract":[{"type":"text","text":"Representations of various device connection types."}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ConnectionType","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConnectionType","kind":"identifier"}],"url":"\/documentation\/airshipcore\/connectiontype"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/ConnectionType/cell":{"title":"cell","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"cell"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/airshipcore\/connectiontype\/cell","abstract":[{"text":"Network is a cellular or mobile network.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ConnectionType\/cell"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ConnectionType\/title","value":"ConnectionType"},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ConnectionType\/fragments","value":[{"text":"ConnectionType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ConnectionType\/navigatorTitle","value":[{"kind":"identifier","text":"ConnectionType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}