{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["Mac Catalyst"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airshipcore\/connectiontype\/init"]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"AirshipCore"}],"role":"symbol","externalID":"c:@M@AirshipCore@objc(cs)ConnectionType(im)init","title":"init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ConnectionType"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ConnectionType\/init"},"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/ConnectionType/init":{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ConnectionType\/init","abstract":[],"kind":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol","url":"\/documentation\/airshipcore\/connectiontype\/init","type":"topic"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/ConnectionType":{"title":"ConnectionType","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConnectionType"}],"type":"topic","abstract":[{"type":"text","text":"Representations of various device connection types."}],"kind":"symbol","role":"symbol","url":"\/documentation\/airshipcore\/connectiontype","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ConnectionType","navigatorTitle":[{"kind":"identifier","text":"ConnectionType"}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"title":"AirshipCore","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/airshipcore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ConnectionType\/title","value":"ConnectionType","op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ConnectionType\/fragments","value":[{"text":"ConnectionType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ConnectionType\/navigatorTitle","value":[{"text":"ConnectionType","kind":"identifier"}],"op":"replace"}]}]}