{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ConnectionType\/none"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"languages":["swift"],"platforms":["Mac Catalyst"]}],"kind":"declarations"}],"metadata":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"symbolKind":"property","title":"none","roleHeading":"Type Property","externalID":"s:11AirshipCore14ConnectionTypeC4noneSSvpZ","modules":[{"name":"AirshipCore"}]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/connectiontype\/none"]}],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ConnectionType"]]},"abstract":[{"type":"text","text":"Network is unreachable."}],"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/ConnectionType/none":{"type":"topic","abstract":[{"text":"Network is unreachable.","type":"text"}],"kind":"symbol","url":"\/documentation\/airshipcore\/connectiontype\/none","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ConnectionType\/none","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"none"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/ConnectionType":{"type":"topic","abstract":[{"text":"Representations of various device connection types.","type":"text"}],"kind":"symbol","url":"\/documentation\/airshipcore\/connectiontype","role":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ConnectionType","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConnectionType"}],"navigatorTitle":[{"kind":"identifier","text":"ConnectionType"}],"title":"ConnectionType"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"url":"\/documentation\/airshipcore","title":"AirshipCore","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","kind":"symbol","abstract":[],"type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ConnectionType\/title","value":"ConnectionType","op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ConnectionType\/fragments","value":[{"kind":"identifier","text":"ConnectionType"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ConnectionType\/navigatorTitle","value":[{"text":"ConnectionType","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}