{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wifi","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ConnectionType\/wifi"},"metadata":{"role":"symbol","externalID":"s:11AirshipCore14ConnectionTypeC4wifiSSvpZ","title":"wifi","symbolKind":"property","modules":[{"name":"AirshipCore"}],"roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"wifi"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ConnectionType"]]},"abstract":[{"type":"text","text":"Network is a WiFi network."}],"variants":[{"paths":["\/documentation\/airshipcore\/connectiontype\/wifi"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"url":"\/documentation\/airshipcore","title":"AirshipCore","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","kind":"symbol","abstract":[],"type":"topic","role":"collection"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/ConnectionType":{"type":"topic","abstract":[{"text":"Representations of various device connection types.","type":"text"}],"kind":"symbol","url":"\/documentation\/airshipcore\/connectiontype","role":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ConnectionType","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConnectionType"}],"navigatorTitle":[{"kind":"identifier","text":"ConnectionType"}],"title":"ConnectionType"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/ConnectionType/wifi":{"title":"wifi","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"wifi","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/airshipcore\/connectiontype\/wifi","kind":"symbol","abstract":[{"text":"Network is a WiFi network.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ConnectionType\/wifi"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"ConnectionType","op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ConnectionType\/title"},{"value":[{"kind":"identifier","text":"ConnectionType"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ConnectionType\/fragments"},{"value":[{"text":"ConnectionType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ConnectionType\/navigatorTitle"}]}]}