{"kind":"symbol","hierarchy":{"paths":[[]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipfeatureflags"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airshipfeatureflags"]}],"metadata":{"roleHeading":"Framework","externalID":"AirshipFeatureFlags","role":"collection","symbolKind":"module","title":"AirshipFeatureFlags","modules":[{"name":"AirshipFeatureFlags"}]},"sections":[],"topicSections":[{"anchor":"Classes","generated":true,"title":"Classes","identifiers":["doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/AirshipFeatureFlagsSDKModule","doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/FeatureFlagManager","doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/FeatureFlagResultCache"]},{"anchor":"Structures","generated":true,"title":"Structures","identifiers":["doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/FeatureFlag"]},{"anchor":"Enumerations","generated":true,"title":"Enumerations","identifiers":["doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/FeatureFlagError","doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/FeatureFlagUpdateStatus"]},{"anchor":"Extended-Modules","title":"Extended Modules","identifiers":["doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/AirshipCore"],"generated":true}],"references":{"doc://com.urbanairship.richpush.AirshipFeatureFlags/documentation/AirshipFeatureFlags/FeatureFlagError":{"url":"\/documentation\/airshipfeatureflags\/featureflagerror","title":"FeatureFlagError","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Feature flag errors"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeatureFlagError"}],"navigatorTitle":[{"kind":"identifier","text":"FeatureFlagError"}],"identifier":"doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/FeatureFlagError"},"doc://com.urbanairship.richpush.AirshipFeatureFlags/documentation/AirshipFeatureFlags/FeatureFlag":{"abstract":[{"text":"Feature flag","type":"text"}],"title":"FeatureFlag","kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FeatureFlag","kind":"identifier"}],"identifier":"doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/FeatureFlag","type":"topic","navigatorTitle":[{"text":"FeatureFlag","kind":"identifier"}],"url":"\/documentation\/airshipfeatureflags\/featureflag"},"doc://com.urbanairship.richpush.AirshipFeatureFlags/documentation/AirshipFeatureFlags/FeatureFlagResultCache":{"navigatorTitle":[{"kind":"identifier","text":"FeatureFlagResultCache"}],"kind":"symbol","fragments":[{"text":"actor","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeatureFlagResultCache"}],"type":"topic","abstract":[{"text":"Feature Flag result cache","type":"text"}],"url":"\/documentation\/airshipfeatureflags\/featureflagresultcache","title":"FeatureFlagResultCache","role":"symbol","identifier":"doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/FeatureFlagResultCache"},"doc://com.urbanairship.richpush.AirshipFeatureFlags/documentation/AirshipFeatureFlags/FeatureFlagManager":{"role":"symbol","url":"\/documentation\/airshipfeatureflags\/featureflagmanager","title":"FeatureFlagManager","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeatureFlagManager"}],"navigatorTitle":[{"kind":"identifier","text":"FeatureFlagManager"}],"abstract":[{"type":"text","text":"Airship feature flag manager"}],"type":"topic","identifier":"doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/FeatureFlagManager"},"doc://com.urbanairship.richpush.AirshipFeatureFlags/documentation/AirshipFeatureFlags/AirshipFeatureFlagsVersionNumber":{"fragments":[{"text":"AirshipFeatureFlagsVersionNumber","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/AirshipFeatureFlagsVersionNumber","type":"topic","title":"AirshipFeatureFlagsVersionNumber","abstract":[{"text":"Project version number for AirshipFeatureFlags.","type":"text"}],"role":"symbol","url":"\/documentation\/airshipfeatureflags\/airshipfeatureflagsversionnumber"},"doc://com.urbanairship.richpush.AirshipFeatureFlags/documentation/AirshipFeatureFlags/AirshipCore":{"abstract":[],"role":"collection","url":"\/documentation\/airshipfeatureflags\/airshipcore","identifier":"doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/AirshipCore","kind":"symbol","title":"AirshipCore","type":"topic"},"doc://com.urbanairship.richpush.AirshipFeatureFlags/documentation/AirshipFeatureFlags":{"identifier":"doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags","type":"topic","abstract":[],"title":"AirshipFeatureFlags","role":"collection","kind":"symbol","url":"\/documentation\/airshipfeatureflags"},"doc://com.urbanairship.richpush.AirshipFeatureFlags/documentation/AirshipFeatureFlags/AirshipFeatureFlagsSDKModule":{"type":"topic","role":"symbol","title":"AirshipFeatureFlagsSDKModule","navigatorTitle":[{"text":"AirshipFeatureFlagsSDKModule","kind":"identifier"}],"url":"\/documentation\/airshipfeatureflags\/airshipfeatureflagssdkmodule","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirshipFeatureFlagsSDKModule","kind":"identifier"}],"abstract":[{"text":"AirshipFeatureFlags module loader.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/AirshipFeatureFlagsSDKModule"},"doc://com.urbanairship.richpush.AirshipFeatureFlags/documentation/AirshipFeatureFlags/AirshipFeatureFlagsVersionString":{"title":"AirshipFeatureFlagsVersionString","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Project version string for AirshipFeatureFlags."}],"type":"topic","url":"\/documentation\/airshipfeatureflags\/airshipfeatureflagsversionstring","identifier":"doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/AirshipFeatureFlagsVersionString","fragments":[{"kind":"identifier","text":"AirshipFeatureFlagsVersionString"}]},"doc://com.urbanairship.richpush.AirshipFeatureFlags/documentation/AirshipFeatureFlags/FeatureFlagUpdateStatus":{"abstract":[{"type":"text","text":"Feature flag status. Possible values are upToDate, stale and outOfDate."}],"title":"FeatureFlagUpdateStatus","url":"\/documentation\/airshipfeatureflags\/featureflagupdatestatus","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FeatureFlagUpdateStatus"}],"identifier":"doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/FeatureFlagUpdateStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FeatureFlagUpdateStatus"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"identifiers":["doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/AirshipFeatureFlagsSDKModule"],"title":"Classes","generated":true,"anchor":"Classes"},{"identifiers":["doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/AirshipFeatureFlagsVersionNumber","doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/AirshipFeatureFlagsVersionString"],"title":"Variables","generated":true,"anchor":"Variables"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":"UAFeatureFlagsSDKModule","op":"replace","path":"\/references\/doc:~1~1com.urbanairship.richpush.AirshipFeatureFlags~1documentation~1AirshipFeatureFlags~1AirshipFeatureFlagsSDKModule\/title"},{"value":[{"text":"UAFeatureFlagsSDKModule","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.richpush.AirshipFeatureFlags~1documentation~1AirshipFeatureFlags~1AirshipFeatureFlagsSDKModule\/fragments"},{"value":[{"kind":"identifier","text":"UAFeatureFlagsSDKModule"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.richpush.AirshipFeatureFlags~1documentation~1AirshipFeatureFlags~1AirshipFeatureFlagsSDKModule\/navigatorTitle"}]}]}