{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/airshipwknavigationdelegate\/closewindow(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airshipcore\/airshipwknavigationdelegate\/closewindow(_:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeWindow"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"animated"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipWKNavigationDelegate"]]},"metadata":{"symbolKind":"method","role":"symbol","modules":[{"name":"AirshipCore"}],"title":"closeWindow(_:)","navigatorTitle":[{"text":"closeWindow:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeWindow"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"externalID":"c:@M@AirshipCore@objc(pl)AirshipWKNavigationDelegate(im)closeWindow:","roleHeading":"Instance Method"},"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipWKNavigationDelegate\/closeWindow(_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/AirshipWKNavigationDelegate/closeWindow(_:)":{"role":"symbol","title":"closeWindow(_:)","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipWKNavigationDelegate\/closeWindow(_:)","navigatorTitle":[{"kind":"identifier","text":"closeWindow:"}],"kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"closeWindow"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"url":"\/documentation\/airshipcore\/airshipwknavigationdelegate\/closewindow(_:)","type":"topic"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/AirshipWKNavigationDelegate":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AirshipWKNavigationDelegate"}],"url":"\/documentation\/airshipcore\/airshipwknavigationdelegate","title":"AirshipWKNavigationDelegate","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipWKNavigationDelegate","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"AirshipWKNavigationDelegate"}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","role":"collection","title":"AirshipCore","url":"\/documentation\/airshipcore","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"closeWindow:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"closeWindow:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"closeWindow:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"animated","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"closeWindow:","op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1AirshipWKNavigationDelegate~1closeWindow(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"closeWindow:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1AirshipWKNavigationDelegate~1closeWindow(_:)\/fragments"},{"value":"AirshipWKNavigationDelegate","op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1AirshipWKNavigationDelegate\/title"},{"value":[{"text":"AirshipWKNavigationDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1AirshipWKNavigationDelegate\/fragments"},{"value":[{"text":"AirshipWKNavigationDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1AirshipWKNavigationDelegate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}