{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ChallengeResolver\/shared","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ChallengeResolver","kind":"typeIdentifier","preciseIdentifier":"c:@M@AirshipCore@objc(cs)ChallengeResolver","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ChallengeResolver"}],"platforms":["Mac Catalyst"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/airshipcore\/challengeresolver\/shared"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"modules":[{"name":"AirshipCore"}],"role":"symbol","externalID":"s:11AirshipCore17ChallengeResolverC6sharedACvpZ","symbolKind":"property","roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AirshipCore@objc(cs)ChallengeResolver","text":"ChallengeResolver","kind":"typeIdentifier"}],"title":"shared"},"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ChallengeResolver"]]},"kind":"symbol","sections":[],"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/ChallengeResolver/shared":{"url":"\/documentation\/airshipcore\/challengeresolver\/shared","role":"symbol","title":"shared","abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ChallengeResolver\/shared","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AirshipCore@objc(cs)ChallengeResolver","text":"ChallengeResolver","kind":"typeIdentifier"}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/ChallengeResolver":{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ChallengeResolver","url":"\/documentation\/airshipcore\/challengeresolver","abstract":[{"text":"Authentication challenge resolver class","type":"text"}],"title":"ChallengeResolver","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChallengeResolver","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"ChallengeResolver","kind":"identifier"}],"type":"topic"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"kind":"symbol","title":"AirshipCore","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","url":"\/documentation\/airshipcore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"ChallengeResolver","op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ChallengeResolver\/title"},{"value":[{"text":"ChallengeResolver","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ChallengeResolver\/fragments"},{"value":[{"kind":"identifier","text":"ChallengeResolver"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ChallengeResolver\/navigatorTitle"}]}]}