/* Copyright Airship and Contributors */

#import <Foundation/Foundation.h>
#import "UADeferredScheduleResult+Internal.h"
#import "UAScheduleTriggerContext+Internal.h"

NS_ASSUME_NONNULL_BEGIN

/**
 * Represents possible API client errors.
 */
typedef NS_ENUM(NSInteger, UADeferredScheduleAPIClientError) {
    /**
     * Indicates auth token unavailable.
     */
    UADeferredScheduleAPIClientErrorMissingAuthToken,

    /**
     * Indicates connection timeout.
     */
    UADeferredScheduleAPIClientErrorTimedOut,

    /**
     * Indicates an unsuccessful error.
     */
    UADeferredScheduleAPIClientErrorUnsuccessfulStatus
};

/**
 * The domain for NSErrors generated by the client.
 */
extern NSString * const UADeferredScheduleAPIClientErrorDomain;

/**
 * Deferred schedule API client.
 */
@interface UADeferredScheduleAPIClient : NSObject

/**
 * Resolves a deferred schedule.
 * @param URL The URL.
 * @param channelID The channel ID.
 * @param triggerContext The optional trigger context.
 * @param completionHandler The completion handler.
 */
- (void)resolveURL:(NSURL *)URL
         channelID:(NSString *)channelID
    triggerContext:(nullable UAScheduleTriggerContext *)triggerContext
 completionHandler:(void (^)(UADeferredScheduleResult * _Nullable, NSError * _Nullable))completionHandler;

@end

NS_ASSUME_NONNULL_END
