{"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueTransformer"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airshipcore\/jsonvaluetransformer\/init"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"externalID":"c:@M@AirshipCore@objc(cs)JSONValueTransformer(im)init","navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"AirshipCore"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst"],"languages":["occ"]}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueTransformer\/init"},"kind":"symbol","references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"url":"\/documentation\/airshipcore","kind":"symbol","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","abstract":[],"title":"AirshipCore","role":"collection"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONValueTransformer":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSONValueTransformer"}],"navigatorTitle":[{"kind":"identifier","text":"JSONValueTransformer"}],"kind":"symbol","url":"\/documentation\/airshipcore\/jsonvaluetransformer","type":"topic","abstract":[{"type":"text","text":"NOTE: For internal use only. :nodoc:"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueTransformer","title":"JSONValueTransformer","role":"symbol"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONValueTransformer/init":{"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/airshipcore\/jsonvaluetransformer\/init","type":"topic","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueTransformer\/init","title":"init","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueTransformer\/title","op":"replace","value":"JSONValueTransformer"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueTransformer\/fragments","op":"replace","value":[{"text":"JSONValueTransformer","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueTransformer\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"JSONValueTransformer"}]}]}]}