{"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/airshipcore\/jsonvaluetransformer\/transformedvalueclass()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airshipcore\/jsonvaluetransformer\/transformedvalueclass()"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueTransformer\/transformedValueClass()"},"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueTransformer"]]},"metadata":{"modules":[{"name":"AirshipCore"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transformedValueClass","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"AnyClass","kind":"typeIdentifier","preciseIdentifier":"s:s8AnyClassa"}],"externalID":"c:@M@AirshipCore@objc(cs)JSONValueTransformer(cm)transformedValueClass","roleHeading":"Type Method","role":"symbol","symbolKind":"method","title":"transformedValueClass()","navigatorTitle":[{"text":"transformedValueClass","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"platforms":["Mac Catalyst"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transformedValueClass"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s8AnyClassa","text":"AnyClass"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONValueTransformer/transformedValueClass()":{"title":"transformedValueClass()","url":"\/documentation\/airshipcore\/jsonvaluetransformer\/transformedvalueclass()","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueTransformer\/transformedValueClass()","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transformedValueClass"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"AnyClass","preciseIdentifier":"s:s8AnyClassa"}],"abstract":[],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"transformedValueClass"}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","role":"collection","title":"AirshipCore","url":"\/documentation\/airshipcore","abstract":[]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONValueTransformer":{"abstract":[{"type":"text","text":"NOTE: For internal use only. :nodoc:"}],"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueTransformer","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JSONValueTransformer","kind":"identifier"}],"role":"symbol","url":"\/documentation\/airshipcore\/jsonvaluetransformer","navigatorTitle":[{"text":"JSONValueTransformer","kind":"identifier"}],"title":"JSONValueTransformer"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"transformedValueClass"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"transformedValueClass","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"Class","preciseIdentifier":"c:@T@Class"},{"kind":"text","text":") "},{"kind":"identifier","text":"transformedValueClass"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["Mac Catalyst"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueTransformer~1transformedValueClass()\/title","op":"replace","value":"transformedValueClass"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueTransformer~1transformedValueClass()\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"transformedValueClass","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueTransformer\/title","op":"replace","value":"JSONValueTransformer"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueTransformer\/fragments","op":"replace","value":[{"kind":"identifier","text":"JSONValueTransformer"}]},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueTransformer\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"JSONValueTransformer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}