{"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"AirshipSDKModule.actionsManifest"},{"type":"text","text":"."}],"metadata":{"roleHeading":"Instance Property","externalID":"s:20AirshipMessageCenter0bC9SDKModuleC15actionsManifest0A4Core07ActionsF0_pSgvp","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actionsManifest","kind":"identifier"},{"text":": (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActionsManifest","kind":"typeIdentifier","preciseIdentifier":"s:11AirshipCore15ActionsManifestP"},{"text":")?","kind":"text"}],"role":"symbol","title":"actionsManifest","modules":[{"name":"AirshipMessageCenter"}],"symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterSDKModule"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterSDKModule\/actionsManifest","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["Mac Catalyst"],"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actionsManifest","kind":"identifier"},{"text":": (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActionsManifest","preciseIdentifier":"s:11AirshipCore15ActionsManifestP","kind":"typeIdentifier"},{"text":")?","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipmessagecenter\/messagecentersdkmodule\/actionsmanifest"]}],"references":{"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter":{"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter","abstract":[],"url":"\/documentation\/airshipmessagecenter","role":"collection","title":"AirshipMessageCenter","kind":"symbol","type":"topic"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterSDKModule/actionsManifest":{"abstract":[],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actionsManifest","kind":"identifier"},{"text":": (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActionsManifest","kind":"typeIdentifier","preciseIdentifier":"s:11AirshipCore15ActionsManifestP"},{"text":")?","kind":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterSDKModule\/actionsManifest","title":"actionsManifest","url":"\/documentation\/airshipmessagecenter\/messagecentersdkmodule\/actionsmanifest"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterSDKModule":{"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterSDKModule","abstract":[{"text":"AirshipMessageCenter module loader.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"MessageCenterSDKModule","kind":"identifier"}],"type":"topic","role":"symbol","title":"MessageCenterSDKModule","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageCenterSDKModule","kind":"identifier"}],"url":"\/documentation\/airshipmessagecenter\/messagecentersdkmodule"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"UAMessageCenterSDKModule","path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterSDKModule\/title","op":"replace"},{"value":[{"text":"UAMessageCenterSDKModule","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterSDKModule\/fragments","op":"replace"},{"value":[{"text":"UAMessageCenterSDKModule","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterSDKModule\/navigatorTitle","op":"replace"}]}]}