{"topicSections":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ChallengeResolver\/urlSession(_:task:didReceive:)"]}],"kind":"article","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/challengeresolver\/urlsessiontaskdelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airshipcore\/challengeresolver\/urlsessiontaskdelegate-implementations"]}],"sections":[],"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ChallengeResolver\/URLSessionTaskDelegate-Implementations","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"AirshipCore"}],"role":"collectionGroup","roleHeading":"API Collection","title":"URLSessionTaskDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ChallengeResolver"]]},"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/ChallengeResolver":{"kind":"symbol","role":"symbol","title":"ChallengeResolver","navigatorTitle":[{"text":"ChallengeResolver","kind":"identifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ChallengeResolver","url":"\/documentation\/airshipcore\/challengeresolver","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChallengeResolver","kind":"identifier"}],"abstract":[{"type":"text","text":"Authentication challenge resolver class"}],"type":"topic"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/airshipcore","role":"collection","title":"AirshipCore","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/ChallengeResolver/urlSession(_:task:didReceive:)":{"title":"urlSession(_:task:didReceive:)","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"URLSession:task:didReceiveChallenge:completionHandler:"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ChallengeResolver\/urlSession(_:task:didReceive:)","url":"\/documentation\/airshipcore\/challengeresolver\/urlsession(_:task:didreceive:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlSession"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"task"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSessionTask","preciseIdentifier":"c:objc(cs)NSURLSessionTask"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLAuthenticationChallenge","preciseIdentifier":"c:objc(cs)NSURLAuthenticationChallenge"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> ("},{"kind":"typeIdentifier","text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"AuthChallengeDisposition","preciseIdentifier":"c:@E@NSURLSessionAuthChallengeDisposition"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"URLCredential","preciseIdentifier":"c:objc(cs)NSURLCredential"},{"kind":"text","text":"?)"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ChallengeResolver\/urlSession(_:task:didReceive:)"]}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":"ChallengeResolver","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ChallengeResolver\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ChallengeResolver"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ChallengeResolver\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ChallengeResolver"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ChallengeResolver\/navigatorTitle","op":"replace"},{"value":"URLSession:task:didReceiveChallenge:completionHandler:","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ChallengeResolver~1urlSession(_:task:didReceive:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"URLSession:task:didReceiveChallenge:completionHandler:"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ChallengeResolver~1urlSession(_:task:didReceive:)\/fragments","op":"replace"}]}]}