{"abstract":[{"text":"Airship native bridge extension for the Message Center.","type":"text"}],"metadata":{"role":"symbol","externalID":"c:@M@AirshipMessageCenter@objc(cs)MessageCenterNativeBridgeExtension","navigatorTitle":[{"kind":"identifier","text":"MessageCenterNativeBridgeExtension"}],"modules":[{"name":"AirshipMessageCenter"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCenterNativeBridgeExtension"}],"roleHeading":"Class","symbolKind":"class","title":"MessageCenterNativeBridgeExtension"},"primaryContentSections":[{"declarations":[{"platforms":["Mac Catalyst"],"languages":["swift"],"tokens":[{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageCenterNativeBridgeExtension","kind":"identifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterNativeBridgeExtension\/init(message:user:)"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterNativeBridgeExtension\/actionsMetadata(for:webView:)","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterNativeBridgeExtension\/extendJavaScriptEnvironment(_:webView:)"]}],"variants":[{"paths":["\/documentation\/airshipmessagecenter\/messagecenternativebridgeextension"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airshipmessagecenter\/messagecenternativebridgeextension"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterNativeBridgeExtension","interfaceLanguage":"swift"},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.urbanairship.AirshipMessageCenter\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.urbanairship.AirshipMessageCenter\/11AirshipCore29NativeBridgeExtensionDelegateP","doc:\/\/com.urbanairship.AirshipMessageCenter\/objc(pl)NSObject","doc:\/\/com.urbanairship.AirshipMessageCenter\/s7CVarArgP","doc:\/\/com.urbanairship.AirshipMessageCenter\/s28CustomDebugStringConvertibleP","doc:\/\/com.urbanairship.AirshipMessageCenter\/s23CustomStringConvertibleP","doc:\/\/com.urbanairship.AirshipMessageCenter\/SQ","doc:\/\/com.urbanairship.AirshipMessageCenter\/SH","doc:\/\/com.urbanairship.AirshipMessageCenter\/s8SendableP"],"type":"conformsTo"}],"kind":"symbol","sections":[],"references":{"doc://com.urbanairship.AirshipMessageCenter/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/objc(cs)NSObject"},"doc://com.urbanairship.AirshipMessageCenter/objc(pl)NSObject":{"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.urbanairship.AirshipMessageCenter/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/s7CVarArgP"},"doc://com.urbanairship.AirshipMessageCenter/SH":{"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterNativeBridgeExtension":{"url":"\/documentation\/airshipmessagecenter\/messagecenternativebridgeextension","title":"MessageCenterNativeBridgeExtension","abstract":[{"type":"text","text":"Airship native bridge extension for the Message Center."}],"kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterNativeBridgeExtension","role":"symbol","navigatorTitle":[{"text":"MessageCenterNativeBridgeExtension","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageCenterNativeBridgeExtension","kind":"identifier"}],"type":"topic"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterNativeBridgeExtension/init(message:user:)":{"abstract":[],"role":"symbol","title":"init(message:user:)","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterNativeBridgeExtension\/init(message:user:)","kind":"symbol","url":"\/documentation\/airshipmessagecenter\/messagecenternativebridgeextension\/init(message:user:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:20AirshipMessageCenter0bcB0V","text":"MessageCenterMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"user"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:20AirshipMessageCenter0bC4UserV","text":"MessageCenterUser"},{"kind":"text","text":")"}]},"doc://com.urbanairship.AirshipMessageCenter/11AirshipCore29NativeBridgeExtensionDelegateP":{"type":"unresolvable","title":"AirshipCore.NativeBridgeExtensionDelegate","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/11AirshipCore29NativeBridgeExtensionDelegateP"},"doc://com.urbanairship.AirshipMessageCenter/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter":{"type":"topic","role":"collection","title":"AirshipMessageCenter","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter","url":"\/documentation\/airshipmessagecenter","kind":"symbol"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterNativeBridgeExtension/actionsMetadata(for:webView:)":{"abstract":[],"url":"\/documentation\/airshipmessagecenter\/messagecenternativebridgeextension\/actionsmetadata(for:webview:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actionsMetadata","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11AirshipCore17JavaScriptCommandV","text":"JavaScriptCommand","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"webView","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView","kind":"typeIdentifier"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterNativeBridgeExtension\/actionsMetadata(for:webView:)","title":"actionsMetadata(for:webView:)"},"doc://com.urbanairship.AirshipMessageCenter/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/SQ"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterNativeBridgeExtension/extendJavaScriptEnvironment(_:webView:)":{"abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterNativeBridgeExtension\/extendJavaScriptEnvironment(_:webView:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"extendJavaScriptEnvironment"},{"kind":"text","text":"("},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:11AirshipCore29JavaScriptEnvironmentProtocolP","text":"JavaScriptEnvironmentProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"webView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"}],"kind":"symbol","title":"extendJavaScriptEnvironment(_:webView:)","url":"\/documentation\/airshipmessagecenter\/messagecenternativebridgeextension\/extendjavascriptenvironment(_:webview:)","role":"symbol","type":"topic"},"doc://com.urbanairship.AirshipMessageCenter/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/s28CustomDebugStringConvertibleP"},"doc://com.urbanairship.AirshipMessageCenter/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/s8SendableP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"MessageCenterNativeBridgeExtension","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"MessageCenterNativeBridgeExtension","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"MessageCenterNativeBridgeExtension","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":null,"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.urbanairship.AirshipMessageCenter\/objc(cs)NSObject"]}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageCenterNativeBridgeExtension","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["Mac Catalyst"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MessageCenterNativeBridgeExtension","path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterNativeBridgeExtension\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MessageCenterNativeBridgeExtension"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterNativeBridgeExtension\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MessageCenterNativeBridgeExtension"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterNativeBridgeExtension\/navigatorTitle","op":"replace"}]}]}