{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterSDKModule"},"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter"]]},"metadata":{"externalID":"c:@M@AirshipMessageCenter@objc(cs)UAMessageCenterSDKModule","roleHeading":"Class","title":"MessageCenterSDKModule","symbolKind":"class","modules":[{"name":"AirshipMessageCenter"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageCenterSDKModule","kind":"identifier"}],"navigatorTitle":[{"text":"MessageCenterSDKModule","kind":"identifier"}]},"abstract":[{"text":"AirshipMessageCenter module loader.","type":"text"}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterSDKModule\/actionsManifest","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterSDKModule\/components"],"title":"Instance Properties","anchor":"Instance-Properties"},{"generated":true,"identifiers":["doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterSDKModule\/load(_:)"],"title":"Type Methods","anchor":"Type-Methods"}],"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/com.urbanairship.AirshipMessageCenter\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.urbanairship.AirshipMessageCenter\/11AirshipCore0A9SDKModuleP","doc:\/\/com.urbanairship.AirshipMessageCenter\/objc(pl)NSObject","doc:\/\/com.urbanairship.AirshipMessageCenter\/s7CVarArgP","doc:\/\/com.urbanairship.AirshipMessageCenter\/s28CustomDebugStringConvertibleP","doc:\/\/com.urbanairship.AirshipMessageCenter\/s23CustomStringConvertibleP","doc:\/\/com.urbanairship.AirshipMessageCenter\/SQ","doc:\/\/com.urbanairship.AirshipMessageCenter\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipmessagecenter\/messagecentersdkmodule"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airshipmessagecenter\/messagecentersdkmodule"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(UAMessageCenterSDKModule) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCenterSDKModule"}],"languages":["swift"],"platforms":["Mac Catalyst"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"overview","text":"Overview","level":2,"type":"heading"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"For internal use only. :nodoc:"}]}],"name":"Note","type":"aside"}]}],"sections":[],"references":{"doc://com.urbanairship.AirshipMessageCenter/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/SH","type":"unresolvable"},"doc://com.urbanairship.AirshipMessageCenter/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/objc(pl)NSObject","type":"unresolvable"},"doc://com.urbanairship.AirshipMessageCenter/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.urbanairship.AirshipMessageCenter/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/s7CVarArgP","type":"unresolvable"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterSDKModule/actionsManifest":{"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/airshipmessagecenter\/messagecentersdkmodule\/actionsmanifest","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterSDKModule\/actionsManifest","abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actionsManifest","kind":"identifier"},{"text":": (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:11AirshipCore15ActionsManifestP","text":"ActionsManifest","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"title":"actionsManifest"},"doc://com.urbanairship.AirshipMessageCenter/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.urbanairship.AirshipMessageCenter/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/SQ","type":"unresolvable"},"doc://com.urbanairship.AirshipMessageCenter/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/objc(cs)NSObject","type":"unresolvable"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterSDKModule/components":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"components"},{"kind":"text","text":": ["},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:11AirshipCore0A9ComponentP","text":"AirshipComponent"},{"kind":"text","text":"]"}],"type":"topic","url":"\/documentation\/airshipmessagecenter\/messagecentersdkmodule\/components","abstract":[],"title":"components","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterSDKModule\/components"},"doc://com.urbanairship.AirshipMessageCenter/11AirshipCore0A9SDKModuleP":{"title":"AirshipCore.AirshipSDKModule","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/11AirshipCore0A9SDKModuleP","type":"unresolvable"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter":{"type":"topic","kind":"symbol","url":"\/documentation\/airshipmessagecenter","role":"collection","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter","title":"AirshipMessageCenter"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterSDKModule/load(_:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"load","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:11AirshipCore24AirshiopModuleLoaderArgsV","text":"AirshiopModuleLoaderArgs","kind":"typeIdentifier"},{"text":") -> (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:11AirshipCore0A9SDKModuleP","text":"AirshipSDKModule","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterSDKModule\/load(_:)","title":"load(_:)","abstract":[],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/airshipmessagecenter\/messagecentersdkmodule\/load(_:)"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterSDKModule":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCenterSDKModule"}],"navigatorTitle":[{"kind":"identifier","text":"MessageCenterSDKModule"}],"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterSDKModule","kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/airshipmessagecenter\/messagecentersdkmodule","abstract":[{"text":"AirshipMessageCenter module loader.","type":"text"}],"title":"MessageCenterSDKModule"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"UAMessageCenterSDKModule"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"UAMessageCenterSDKModule"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"UAMessageCenterSDKModule","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":null},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.urbanairship.AirshipMessageCenter\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"UAMessageCenterSDKModule"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"],"platforms":["Mac Catalyst"]}]}},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterSDKModule\/title","op":"replace","value":"UAMessageCenterSDKModule"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterSDKModule\/fragments","op":"replace","value":[{"kind":"identifier","text":"UAMessageCenterSDKModule"}]},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterSDKModule\/navigatorTitle","op":"replace","value":[{"text":"UAMessageCenterSDKModule","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}