{"hierarchy":{"paths":[["doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags","doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/AirshipFeatureFlagsSDKModule"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/AirshipFeatureFlagsSDKModule\/actionsManifest"},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"AirshipSDKModule.actionsManifest"},{"text":".","type":"text"}],"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/airshipfeatureflags\/airshipfeatureflagssdkmodule\/actionsmanifest"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"actionsManifest"},{"kind":"text","text":": ("},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"preciseIdentifier":"s:11AirshipCore15ActionsManifestP","kind":"typeIdentifier","text":"ActionsManifest"},{"kind":"text","text":")?"}],"platforms":["Mac Catalyst"]}],"kind":"declarations"}],"metadata":{"title":"actionsManifest","externalID":"s:19AirshipFeatureFlags0abC9SDKModuleC15actionsManifest0A4Core07ActionsF0_pSgvp","symbolKind":"property","modules":[{"name":"AirshipFeatureFlags"}],"roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"actionsManifest"},{"kind":"text","text":": ("},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"preciseIdentifier":"s:11AirshipCore15ActionsManifestP","kind":"typeIdentifier","text":"ActionsManifest"},{"kind":"text","text":")?"}]},"references":{"doc://com.urbanairship.richpush.AirshipFeatureFlags/documentation/AirshipFeatureFlags/AirshipFeatureFlagsSDKModule/actionsManifest":{"role":"symbol","title":"actionsManifest","type":"topic","url":"\/documentation\/airshipfeatureflags\/airshipfeatureflagssdkmodule\/actionsmanifest","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actionsManifest","kind":"identifier"},{"text":": (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:11AirshipCore15ActionsManifestP","text":"ActionsManifest","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/AirshipFeatureFlagsSDKModule\/actionsManifest"},"doc://com.urbanairship.richpush.AirshipFeatureFlags/documentation/AirshipFeatureFlags":{"title":"AirshipFeatureFlags","identifier":"doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags","type":"topic","kind":"symbol","url":"\/documentation\/airshipfeatureflags","abstract":[],"role":"collection"},"doc://com.urbanairship.richpush.AirshipFeatureFlags/documentation/AirshipFeatureFlags/AirshipFeatureFlagsSDKModule":{"role":"symbol","navigatorTitle":[{"text":"AirshipFeatureFlagsSDKModule","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/airshipfeatureflags\/airshipfeatureflagssdkmodule","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirshipFeatureFlagsSDKModule","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/AirshipFeatureFlagsSDKModule","abstract":[{"text":"AirshipFeatureFlags module loader.","type":"text"}],"title":"AirshipFeatureFlagsSDKModule"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"UAFeatureFlagsSDKModule","op":"replace","path":"\/references\/doc:~1~1com.urbanairship.richpush.AirshipFeatureFlags~1documentation~1AirshipFeatureFlags~1AirshipFeatureFlagsSDKModule\/title"},{"value":[{"kind":"identifier","text":"UAFeatureFlagsSDKModule"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.richpush.AirshipFeatureFlags~1documentation~1AirshipFeatureFlags~1AirshipFeatureFlagsSDKModule\/fragments"},{"value":[{"text":"UAFeatureFlagsSDKModule","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.richpush.AirshipFeatureFlags~1documentation~1AirshipFeatureFlags~1AirshipFeatureFlagsSDKModule\/navigatorTitle"}]}]}