{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"components","kind":"identifier"},{"text":": [","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirshipComponent","kind":"typeIdentifier","preciseIdentifier":"s:11AirshipCore0A9ComponentP"},{"text":"]","kind":"text"}],"languages":["swift"],"platforms":["Mac Catalyst"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipfeatureflags\/airshipfeatureflagssdkmodule\/components"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags","doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/AirshipFeatureFlagsSDKModule"]]},"sections":[],"identifier":{"url":"doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/AirshipFeatureFlagsSDKModule\/components","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"AirshipFeatureFlags"}],"externalID":"s:19AirshipFeatureFlags0abC9SDKModuleC10componentsSay0A4Core0A9Component_pGvp","role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"components","kind":"identifier"},{"text":": [","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirshipComponent","preciseIdentifier":"s:11AirshipCore0A9ComponentP","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"symbolKind":"property","title":"components"},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"AirshipSDKModule.components"},{"text":".","type":"text"}],"references":{"doc://com.urbanairship.richpush.AirshipFeatureFlags/documentation/AirshipFeatureFlags/AirshipFeatureFlagsSDKModule/components":{"url":"\/documentation\/airshipfeatureflags\/airshipfeatureflagssdkmodule\/components","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"components"},{"kind":"text","text":": ["},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"AirshipComponent","preciseIdentifier":"s:11AirshipCore0A9ComponentP"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/AirshipFeatureFlagsSDKModule\/components","abstract":[],"title":"components","kind":"symbol"},"doc://com.urbanairship.richpush.AirshipFeatureFlags/documentation/AirshipFeatureFlags":{"title":"AirshipFeatureFlags","abstract":[],"role":"collection","identifier":"doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags","kind":"symbol","url":"\/documentation\/airshipfeatureflags","type":"topic"},"doc://com.urbanairship.richpush.AirshipFeatureFlags/documentation/AirshipFeatureFlags/AirshipFeatureFlagsSDKModule":{"kind":"symbol","identifier":"doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/AirshipFeatureFlagsSDKModule","abstract":[{"type":"text","text":"AirshipFeatureFlags module loader."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AirshipFeatureFlagsSDKModule"}],"navigatorTitle":[{"kind":"identifier","text":"AirshipFeatureFlagsSDKModule"}],"type":"topic","url":"\/documentation\/airshipfeatureflags\/airshipfeatureflagssdkmodule","title":"AirshipFeatureFlagsSDKModule"}},"variantOverrides":[{"patch":[{"op":"replace","value":"UAFeatureFlagsSDKModule","path":"\/references\/doc:~1~1com.urbanairship.richpush.AirshipFeatureFlags~1documentation~1AirshipFeatureFlags~1AirshipFeatureFlagsSDKModule\/title"},{"op":"replace","value":[{"text":"UAFeatureFlagsSDKModule","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.richpush.AirshipFeatureFlags~1documentation~1AirshipFeatureFlags~1AirshipFeatureFlagsSDKModule\/fragments"},{"op":"replace","value":[{"text":"UAFeatureFlagsSDKModule","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.richpush.AirshipFeatureFlags~1documentation~1AirshipFeatureFlags~1AirshipFeatureFlagsSDKModule\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}