{"kind":"symbol","identifier":{"url":"doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/AirshipFeatureFlagsSDKModule\/load(_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags","doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/AirshipFeatureFlagsSDKModule"]]},"abstract":[{"type":"text","text":"Inherited from "},{"code":"AirshipSDKModule.load(_:)","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"load"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"args"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11AirshipCore24AirshiopModuleLoaderArgsV","text":"AirshiopModuleLoaderArgs"},{"kind":"text","text":") -> ("},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:11AirshipCore0A9SDKModuleP","text":"AirshipSDKModule"},{"kind":"text","text":")?"}],"platforms":["Mac Catalyst"]}]}],"metadata":{"role":"symbol","title":"load(_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"load","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AirshiopModuleLoaderArgs","preciseIdentifier":"s:11AirshipCore24AirshiopModuleLoaderArgsV","kind":"typeIdentifier"},{"text":") -> (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirshipSDKModule","preciseIdentifier":"s:11AirshipCore0A9SDKModuleP","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"externalID":"s:19AirshipFeatureFlags0abC9SDKModuleC4loady0A4Core0aD0_pSgAE24AirshiopModuleLoaderArgsVFZ","symbolKind":"method","roleHeading":"Type Method","modules":[{"name":"AirshipFeatureFlags"}]},"variants":[{"paths":["\/documentation\/airshipfeatureflags\/airshipfeatureflagssdkmodule\/load(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.urbanairship.richpush.AirshipFeatureFlags/documentation/AirshipFeatureFlags":{"kind":"symbol","abstract":[],"url":"\/documentation\/airshipfeatureflags","type":"topic","identifier":"doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags","title":"AirshipFeatureFlags","role":"collection"},"doc://com.urbanairship.richpush.AirshipFeatureFlags/documentation/AirshipFeatureFlags/AirshipFeatureFlagsSDKModule/load(_:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"load"},{"kind":"text","text":"("},{"preciseIdentifier":"s:11AirshipCore24AirshiopModuleLoaderArgsV","kind":"typeIdentifier","text":"AirshiopModuleLoaderArgs"},{"kind":"text","text":") -> ("},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"preciseIdentifier":"s:11AirshipCore0A9SDKModuleP","kind":"typeIdentifier","text":"AirshipSDKModule"},{"kind":"text","text":")?"}],"abstract":[],"url":"\/documentation\/airshipfeatureflags\/airshipfeatureflagssdkmodule\/load(_:)","title":"load(_:)","kind":"symbol","identifier":"doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/AirshipFeatureFlagsSDKModule\/load(_:)","type":"topic"},"doc://com.urbanairship.richpush.AirshipFeatureFlags/documentation/AirshipFeatureFlags/AirshipFeatureFlagsSDKModule":{"identifier":"doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/AirshipFeatureFlagsSDKModule","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AirshipFeatureFlagsSDKModule"}],"abstract":[{"type":"text","text":"AirshipFeatureFlags module loader."}],"kind":"symbol","url":"\/documentation\/airshipfeatureflags\/airshipfeatureflagssdkmodule","title":"AirshipFeatureFlagsSDKModule","role":"symbol","navigatorTitle":[{"text":"AirshipFeatureFlagsSDKModule","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.urbanairship.richpush.AirshipFeatureFlags~1documentation~1AirshipFeatureFlags~1AirshipFeatureFlagsSDKModule\/title","op":"replace","value":"UAFeatureFlagsSDKModule"},{"path":"\/references\/doc:~1~1com.urbanairship.richpush.AirshipFeatureFlags~1documentation~1AirshipFeatureFlags~1AirshipFeatureFlagsSDKModule\/fragments","op":"replace","value":[{"text":"UAFeatureFlagsSDKModule","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.urbanairship.richpush.AirshipFeatureFlags~1documentation~1AirshipFeatureFlags~1AirshipFeatureFlagsSDKModule\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UAFeatureFlagsSDKModule"}]}]}]}