{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSArrayValueTransformer\/transformedValue(_:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/nsarrayvaluetransformer\/transformedvalue(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airshipcore\/nsarrayvaluetransformer\/transformedvalue(_:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSArrayValueTransformer"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transformedValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"value","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]}],"metadata":{"role":"symbol","modules":[{"name":"AirshipCore"}],"roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transformedValue"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"title":"transformedValue(_:)","navigatorTitle":[{"kind":"identifier","text":"transformedValue:"}],"externalID":"c:@M@AirshipCore@objc(cs)NSArrayValueTransformer(im)transformedValue:"},"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","url":"\/documentation\/airshipcore","abstract":[],"kind":"symbol","role":"collection","title":"AirshipCore"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSArrayValueTransformer":{"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSArrayValueTransformer","url":"\/documentation\/airshipcore\/nsarrayvaluetransformer","navigatorTitle":[{"kind":"identifier","text":"NSArrayValueTransformer"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSArrayValueTransformer"}],"role":"symbol","title":"NSArrayValueTransformer","abstract":[],"kind":"symbol"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSArrayValueTransformer/transformedValue(_:)":{"role":"symbol","abstract":[],"title":"transformedValue(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transformedValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSArrayValueTransformer\/transformedValue(_:)","navigatorTitle":[{"text":"transformedValue:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/airshipcore\/nsarrayvaluetransformer\/transformedvalue(_:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"transformedValue:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"transformedValue:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["Mac Catalyst"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"transformedValue:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"value"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSArrayValueTransformer\/title","op":"replace","value":"NSArrayValueTransformer"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSArrayValueTransformer\/fragments","value":[{"kind":"identifier","text":"NSArrayValueTransformer"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSArrayValueTransformer\/navigatorTitle","value":[{"kind":"identifier","text":"NSArrayValueTransformer"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSArrayValueTransformer~1transformedValue(_:)\/title","value":"transformedValue:","op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSArrayValueTransformer~1transformedValue(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"transformedValue:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}