{"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension","doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/UANotificationServiceExtension"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/UANotificationServiceExtension\/serviceExtensionTimeWillExpire()","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"serviceExtensionTimeWillExpire"},{"kind":"text","text":"()"}],"roleHeading":"Instance Method","role":"symbol","title":"serviceExtensionTimeWillExpire()","externalID":"c:@M@AirshipNotificationServiceExtension@objc(cs)UANotificationServiceExtension(im)serviceExtensionTimeWillExpire","navigatorTitle":[{"text":"serviceExtensionTimeWillExpire","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"AirshipNotificationServiceExtension"}]},"variants":[{"paths":["\/documentation\/airshipnotificationserviceextension\/uanotificationserviceextension\/serviceextensiontimewillexpire()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airshipnotificationserviceextension\/uanotificationserviceextension\/serviceextensiontimewillexpire()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"serviceExtensionTimeWillExpire","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.urbanairship.AirshipNotificationServiceExtension/documentation/AirshipNotificationServiceExtension/UANotificationServiceExtension/serviceExtensionTimeWillExpire()":{"navigatorTitle":[{"text":"serviceExtensionTimeWillExpire","kind":"identifier"}],"title":"serviceExtensionTimeWillExpire()","role":"symbol","kind":"symbol","url":"\/documentation\/airshipnotificationserviceextension\/uanotificationserviceextension\/serviceextensiontimewillexpire()","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/UANotificationServiceExtension\/serviceExtensionTimeWillExpire()","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"serviceExtensionTimeWillExpire","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://com.urbanairship.AirshipNotificationServiceExtension/documentation/AirshipNotificationServiceExtension":{"identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension","kind":"symbol","url":"\/documentation\/airshipnotificationserviceextension","abstract":[],"title":"AirshipNotificationServiceExtension","type":"topic","role":"collection"},"doc://com.urbanairship.AirshipNotificationServiceExtension/documentation/AirshipNotificationServiceExtension/UANotificationServiceExtension":{"title":"UANotificationServiceExtension","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UANotificationServiceExtension"}],"kind":"symbol","url":"\/documentation\/airshipnotificationserviceextension\/uanotificationserviceextension","role":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/UANotificationServiceExtension","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UANotificationServiceExtension"}],"abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"serviceExtensionTimeWillExpire"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"serviceExtensionTimeWillExpire"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["Mac Catalyst"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"serviceExtensionTimeWillExpire","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipNotificationServiceExtension~1documentation~1AirshipNotificationServiceExtension~1UANotificationServiceExtension~1serviceExtensionTimeWillExpire()\/title","value":"serviceExtensionTimeWillExpire"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"serviceExtensionTimeWillExpire"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipNotificationServiceExtension~1documentation~1AirshipNotificationServiceExtension~1UANotificationServiceExtension~1serviceExtensionTimeWillExpire()\/fragments"},{"value":"UANotificationServiceExtension","op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipNotificationServiceExtension~1documentation~1AirshipNotificationServiceExtension~1UANotificationServiceExtension\/title"},{"value":[{"kind":"identifier","text":"UANotificationServiceExtension"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipNotificationServiceExtension~1documentation~1AirshipNotificationServiceExtension~1UANotificationServiceExtension\/fragments"},{"value":[{"text":"UANotificationServiceExtension","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipNotificationServiceExtension~1documentation~1AirshipNotificationServiceExtension~1UANotificationServiceExtension\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}