{"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/objc(pl)NSURLSessionDelegate","doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/objc(pl)NSURLSessionTaskDelegate","doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/objc(pl)NSObject","doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/s7CVarArgP","doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/s8CopyableP","doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/s28CustomDebugStringConvertibleP","doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/s23CustomStringConvertibleP","doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/SQ","doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/SH","doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/s8SendableP","doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/s16SendableMetatypeP"],"type":"conformsTo"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChallengeResolver"}],"platforms":["Mac Catalyst"]}]},{"kind":"content","content":[{"text":"Overview","level":2,"anchor":"overview","type":"heading"},{"content":[{"inlineContent":[{"type":"text","text":"For internal use only. :nodoc:"}],"type":"paragraph"}],"name":"Note","style":"note","type":"aside"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipnotificationserviceextension\/challengeresolver"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airshipnotificationserviceextension\/challengeresolver"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/ChallengeResolver"},"metadata":{"modules":[{"name":"AirshipNotificationServiceExtension"}],"title":"ChallengeResolver","symbolKind":"class","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChallengeResolver"}],"externalID":"c:@M@AirshipNotificationServiceExtension@objc(cs)ChallengeResolver","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChallengeResolver"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension"]]},"abstract":[{"text":"Authentication challenge resolver class","type":"text"}],"topicSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/ChallengeResolver\/resolve(_:)"],"anchor":"Instance-Methods"},{"generated":true,"title":"Type Properties","identifiers":["doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/ChallengeResolver\/shared"],"anchor":"Type-Properties"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/ChallengeResolver\/URLSessionDelegate-Implementations","doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/ChallengeResolver\/URLSessionTaskDelegate-Implementations"],"anchor":"Default-Implementations"}],"references":{"doc://com.urbanairship.AirshipNotificationServiceExtension/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.urbanairship.AirshipNotificationServiceExtension/documentation/AirshipNotificationServiceExtension/ChallengeResolver/shared":{"url":"\/documentation\/airshipnotificationserviceextension\/challengeresolver\/shared","identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/ChallengeResolver\/shared","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChallengeResolver","preciseIdentifier":"c:@M@AirshipNotificationServiceExtension@objc(cs)ChallengeResolver"}],"kind":"symbol","abstract":[],"type":"topic","title":"shared"},"doc://com.urbanairship.AirshipNotificationServiceExtension/documentation/AirshipNotificationServiceExtension/ChallengeResolver/resolve(_:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"resolve"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"URLAuthenticationChallenge","preciseIdentifier":"c:objc(cs)NSURLAuthenticationChallenge"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> ("},{"kind":"typeIdentifier","text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"AuthChallengeDisposition","preciseIdentifier":"c:@E@NSURLSessionAuthChallengeDisposition"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"URLCredential","preciseIdentifier":"c:objc(cs)NSURLCredential"},{"kind":"text","text":"?)"}],"role":"symbol","url":"\/documentation\/airshipnotificationserviceextension\/challengeresolver\/resolve(_:)","abstract":[],"title":"resolve(_:)","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/ChallengeResolver\/resolve(_:)"},"doc://com.urbanairship.AirshipNotificationServiceExtension/objc(pl)NSObject":{"identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.urbanairship.AirshipNotificationServiceExtension/documentation/AirshipNotificationServiceExtension/ChallengeResolver/URLSessionDelegate-Implementations":{"kind":"article","role":"collectionGroup","url":"\/documentation\/airshipnotificationserviceextension\/challengeresolver\/urlsessiondelegate-implementations","abstract":[],"title":"URLSessionDelegate Implementations","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/ChallengeResolver\/URLSessionDelegate-Implementations"},"doc://com.urbanairship.AirshipNotificationServiceExtension/s8SendableP":{"identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.urbanairship.AirshipNotificationServiceExtension/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.urbanairship.AirshipNotificationServiceExtension/s8CopyableP":{"identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/s8CopyableP","title":"Swift.Copyable","type":"unresolvable"},"doc://com.urbanairship.AirshipNotificationServiceExtension/documentation/AirshipNotificationServiceExtension/ChallengeResolver":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChallengeResolver","kind":"identifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/ChallengeResolver","abstract":[{"type":"text","text":"Authentication challenge resolver class"}],"title":"ChallengeResolver","type":"topic","url":"\/documentation\/airshipnotificationserviceextension\/challengeresolver","navigatorTitle":[{"kind":"identifier","text":"ChallengeResolver"}],"kind":"symbol"},"doc://com.urbanairship.AirshipNotificationServiceExtension/SH":{"identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.urbanairship.AirshipNotificationServiceExtension/objc(pl)NSURLSessionTaskDelegate":{"identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/objc(pl)NSURLSessionTaskDelegate","title":"NSURLSessionTaskDelegate","type":"unresolvable"},"doc://com.urbanairship.AirshipNotificationServiceExtension/objc(pl)NSURLSessionDelegate":{"identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/objc(pl)NSURLSessionDelegate","title":"Foundation.URLSessionDelegate","type":"unresolvable"},"doc://com.urbanairship.AirshipNotificationServiceExtension/objc(cs)NSObject":{"identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.urbanairship.AirshipNotificationServiceExtension/SQ":{"identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.urbanairship.AirshipNotificationServiceExtension/documentation/AirshipNotificationServiceExtension":{"type":"topic","role":"collection","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension","url":"\/documentation\/airshipnotificationserviceextension","title":"AirshipNotificationServiceExtension","kind":"symbol"},"doc://com.urbanairship.AirshipNotificationServiceExtension/s16SendableMetatypeP":{"identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/s16SendableMetatypeP","title":"Swift.SendableMetatype","type":"unresolvable"},"doc://com.urbanairship.AirshipNotificationServiceExtension/s7CVarArgP":{"identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.urbanairship.AirshipNotificationServiceExtension/documentation/AirshipNotificationServiceExtension/ChallengeResolver/URLSessionTaskDelegate-Implementations":{"type":"topic","role":"collectionGroup","title":"URLSessionTaskDelegate Implementations","kind":"article","url":"\/documentation\/airshipnotificationserviceextension\/challengeresolver\/urlsessiontaskdelegate-implementations","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/ChallengeResolver\/URLSessionTaskDelegate-Implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"ChallengeResolver","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"ChallengeResolver"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"ChallengeResolver","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"anchor":"Default-Implementations","identifiers":["doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/ChallengeResolver\/URLSessionDelegate-Implementations","doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/ChallengeResolver\/URLSessionTaskDelegate-Implementations"],"generated":true,"title":"Default Implementations"}],"path":"\/topicSections","op":"replace"},{"value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/objc(pl)NSURLSessionTaskDelegate"],"kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChallengeResolver"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["Mac Catalyst"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ChallengeResolver","path":"\/references\/doc:~1~1com.urbanairship.AirshipNotificationServiceExtension~1documentation~1AirshipNotificationServiceExtension~1ChallengeResolver\/title","op":"replace"},{"value":[{"text":"ChallengeResolver","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipNotificationServiceExtension~1documentation~1AirshipNotificationServiceExtension~1ChallengeResolver\/fragments","op":"replace"},{"value":[{"text":"ChallengeResolver","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipNotificationServiceExtension~1documentation~1AirshipNotificationServiceExtension~1ChallengeResolver\/navigatorTitle","op":"replace"}]}]}