{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Evaluates the given ","type":"text"},{"type":"codeVoice","code":"AirshipJSON"},{"text":" value against the matcher.","type":"text"}],"metadata":{"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"evaluate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"json","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11AirshipCore0A4JSONO","text":"AirshipJSON","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"ignoreCase","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"modules":[{"name":"AirshipCore"}],"title":"evaluate(json:ignoreCase:)","externalID":"s:11AirshipCore16JSONValueMatcherC8evaluate4json10ignoreCaseSbAA0A4JSONO_SbtF"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["Mac Catalyst"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"evaluate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"json","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11AirshipCore0A4JSONO","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSON","text":"AirshipJSON","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"ignoreCase","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = false) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]}],"kind":"declarations"},{"parameters":[{"name":"json","content":[{"inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"AirshipJSON"},{"type":"text","text":" value to evaluate."}],"type":"paragraph"}]},{"name":"ignoreCase","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If "},{"type":"codeVoice","code":"true"},{"type":"text","text":", string comparisons will be case-insensitive."}]}]}],"kind":"parameters"},{"content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"inlineContent":[{"text":"","type":"text"},{"code":"true","type":"codeVoice"},{"text":" if the value matches, otherwise ","type":"text"},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}],"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher\/evaluate(json:ignoreCase:)"},"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/jsonvaluematcher\/evaluate(json:ignorecase:)"]}],"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","title":"AirshipCore","type":"topic","abstract":[],"role":"collection","kind":"symbol","url":"\/documentation\/airshipcore"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONValueMatcher":{"navigatorTitle":[{"text":"JSONValueMatcher","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JSONValueMatcher","kind":"identifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher","url":"\/documentation\/airshipcore\/jsonvaluematcher","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"JSONValueMatcher"},{"type":"text","text":" is used to match a JSON value against a set of constraints."}],"role":"symbol","title":"JSONValueMatcher","type":"topic"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONValueMatcher/evaluate(json:ignoreCase:)":{"type":"topic","url":"\/documentation\/airshipcore\/jsonvaluematcher\/evaluate(json:ignorecase:)","abstract":[{"type":"text","text":"Evaluates the given "},{"type":"codeVoice","code":"AirshipJSON"},{"type":"text","text":" value against the matcher."}],"role":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher\/evaluate(json:ignoreCase:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"evaluate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"json","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11AirshipCore0A4JSONO","text":"AirshipJSON","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"ignoreCase","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"evaluate(json:ignoreCase:)"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/AirshipJSON":{"url":"\/documentation\/airshipcore\/airshipjson","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSON","title":"AirshipJSON","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirshipJSON","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"AirshipJSON","kind":"identifier"}],"abstract":[{"text":"Airship JSON.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"JSONValueMatcher","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueMatcher\/title","op":"replace"},{"value":[{"text":"JSONValueMatcher","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueMatcher\/fragments","op":"replace"},{"value":[{"text":"JSONValueMatcher","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueMatcher\/navigatorTitle","op":"replace"}]}]}