{"kind":"symbol","identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher\/matcherWithArrayContainsPredicate(_:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"matcherWithArrayContainsPredicate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"predicate","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"JSONPredicate","kind":"typeIdentifier","preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONPredicate","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONPredicate"},{"text":") -> ","kind":"text"},{"text":"JSONValueMatcher","preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONValueMatcher","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"predicate","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The predicate to apply to elements in the array."}]}]}]},{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A "},{"code":"JSONValueMatcher","type":"codeVoice"},{"type":"text","text":" for the specified condition."}]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Creates a matcher that checks if an array contains an element that matches a ","type":"text"},{"code":"JSONPredicate","type":"codeVoice"},{"text":".","type":"text"}],"metadata":{"title":"matcherWithArrayContainsPredicate(_:)","symbolKind":"method","modules":[{"name":"AirshipCore"}],"externalID":"s:11AirshipCore16JSONValueMatcherC33matcherWithArrayContainsPredicateyACSgAA13JSONPredicateCFZ","roleHeading":"Type Method","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"matcherWithArrayContainsPredicate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"JSONPredicate","kind":"typeIdentifier","preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONPredicate"},{"text":") -> ","kind":"text"},{"text":"JSONValueMatcher","kind":"typeIdentifier","preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONValueMatcher"},{"text":"?","kind":"text"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/jsonvaluematcher\/matcherwitharraycontainspredicate(_:)"]}],"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"title":"AirshipCore","role":"collection","type":"topic","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","kind":"symbol","url":"\/documentation\/airshipcore"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONValueMatcher":{"navigatorTitle":[{"kind":"identifier","text":"JSONValueMatcher"}],"title":"JSONValueMatcher","kind":"symbol","type":"topic","url":"\/documentation\/airshipcore\/jsonvaluematcher","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"JSONValueMatcher"},{"type":"text","text":" is used to match a JSON value against a set of constraints."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSONValueMatcher"}],"role":"symbol"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONValueMatcher/matcherWithArrayContainsPredicate(_:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"matcherWithArrayContainsPredicate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"JSONPredicate","preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONPredicate"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"JSONValueMatcher","preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONValueMatcher"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher\/matcherWithArrayContainsPredicate(_:)","title":"matcherWithArrayContainsPredicate(_:)","abstract":[{"text":"Creates a matcher that checks if an array contains an element that matches a ","type":"text"},{"type":"codeVoice","code":"JSONPredicate"},{"text":".","type":"text"}],"url":"\/documentation\/airshipcore\/jsonvaluematcher\/matcherwitharraycontainspredicate(_:)","kind":"symbol","type":"topic"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONPredicate":{"kind":"symbol","url":"\/documentation\/airshipcore\/jsonpredicate","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONPredicate","title":"JSONPredicate","abstract":[{"type":"text","text":"Defines a predicate for evaluating a JSON payload."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JSONPredicate","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"JSONPredicate","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"JSONValueMatcher","op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueMatcher\/title"},{"value":[{"text":"JSONValueMatcher","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueMatcher\/fragments"},{"value":[{"text":"JSONValueMatcher","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueMatcher\/navigatorTitle"},{"value":"JSONPredicate","op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONPredicate\/title"},{"value":[{"kind":"identifier","text":"JSONPredicate"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONPredicate\/fragments"},{"value":[{"kind":"identifier","text":"JSONPredicate"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONPredicate\/navigatorTitle"}]}]}