{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["Mac Catalyst"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"load","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"args","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"AirshiopModuleLoaderArgs","preciseIdentifier":"s:11AirshipCore24AirshiopModuleLoaderArgsV","kind":"typeIdentifier"},{"text":") -> (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirshipSDKModule","preciseIdentifier":"s:11AirshipCore0A9SDKModuleP","kind":"typeIdentifier"},{"text":")?","kind":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterSDKModule\/load(_:)"},"abstract":[{"type":"text","text":"Inherited from "},{"code":"AirshipSDKModule.load(_:)","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterSDKModule"]]},"variants":[{"paths":["\/documentation\/airshipmessagecenter\/messagecentersdkmodule\/load(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"symbolKind":"method","title":"load(_:)","modules":[{"name":"AirshipMessageCenter"}],"role":"symbol","externalID":"s:20AirshipMessageCenter0bC9SDKModuleC4loady0A4Core0aD0_pSgAE24AirshiopModuleLoaderArgsVFZ","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"load"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:11AirshipCore24AirshiopModuleLoaderArgsV","text":"AirshiopModuleLoaderArgs"},{"kind":"text","text":") -> ("},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:11AirshipCore0A9SDKModuleP","text":"AirshipSDKModule"},{"kind":"text","text":")?"}]},"references":{"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterSDKModule":{"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterSDKModule","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageCenterSDKModule"}],"abstract":[{"type":"text","text":"AirshipMessageCenter module loader."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCenterSDKModule"}],"title":"MessageCenterSDKModule","url":"\/documentation\/airshipmessagecenter\/messagecentersdkmodule","type":"topic"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter":{"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter","abstract":[],"type":"topic","kind":"symbol","title":"AirshipMessageCenter","role":"collection","url":"\/documentation\/airshipmessagecenter"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterSDKModule/load(_:)":{"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterSDKModule\/load(_:)","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"load","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AirshiopModuleLoaderArgs","kind":"typeIdentifier","preciseIdentifier":"s:11AirshipCore24AirshiopModuleLoaderArgsV"},{"text":") -> (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirshipSDKModule","kind":"typeIdentifier","preciseIdentifier":"s:11AirshipCore0A9SDKModuleP"},{"text":")?","kind":"text"}],"title":"load(_:)","url":"\/documentation\/airshipmessagecenter\/messagecentersdkmodule\/load(_:)","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterSDKModule\/title","value":"UAMessageCenterSDKModule","op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterSDKModule\/fragments","value":[{"text":"UAMessageCenterSDKModule","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterSDKModule\/navigatorTitle","value":[{"text":"UAMessageCenterSDKModule","kind":"identifier"}],"op":"replace"}]}]}