/* Copyright Airship and Contributors */

#import <Foundation/Foundation.h>
#import "UAPreferenceDataStore+Internal.h"
#import "UARemoteDataPayload+Internal.h"
#import "UARequestSession.h"
#import "UALocaleManager.h"

NS_ASSUME_NONNULL_BEGIN

typedef void (^UARemoteDataAPIClientCompletionHandler)(NSArray<NSDictionary *> * _Nullable remoteData, NSString * _Nullable lastModified, NSError * _Nullable error);


/**
 * Represents possible remote data API client errors.
 */
typedef NS_ENUM(NSInteger, UARemoteDataAPIClientError) {
    /**
     * Indicates an unsuccessful client status.
     */
    UARemoteDataAPIClientErrorUnsuccessfulStatus,

    /**
     * Indicates an invalid server response.
     */
    UARemoteDataAPIClientErrorInvalidResponse
};

/**
 * The domain for NSErrors generated by the remote data client.
 */
extern NSString * const UARemoteDataAPIClientErrorDomain;

@interface UARemoteDataAPIClient : NSObject

///---------------------------------------------------------------------------------------
/// @name Internal Methods
///---------------------------------------------------------------------------------------

/**
 * Create the remote data API client.
 *
 * @param config The Airship config.
 * @return The remote data API client instance.
 */
+ (UARemoteDataAPIClient *)clientWithConfig:(UARuntimeConfig *)config;


/**
 * Create the remote data API client. Used for testing.
 *
 * @param config The Airship config.
 * @param session The UARequestSession session.
 * @return The remote data API client instance.
 */
+ (UARemoteDataAPIClient *)clientWithConfig:(UARuntimeConfig *)config
                                    session:(UARequestSession *)session;

/**
 * Refresh the remote data by calling the remote data cloud API.
 *
 * @param locale The current locale.
 * @param lastModified Optional last modified timestamp.
 * @param completionHandler The completion handler.
 * @return A UADisposable token which can be used to cancel completion handler execution.
 *
 * Note: one block and only one block will be called.
 */
- (UADisposable *)fetchRemoteDataWithLocale:(NSLocale *)locale
                               lastModified:(nullable NSString *)lastModified
                          completionHandler:(UARemoteDataAPIClientCompletionHandler)completionHandler;

@end

NS_ASSUME_NONNULL_END

