{"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore"]]},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.urbanairship.AirshipCore\/objc(pl)NSObject","doc:\/\/com.urbanairship.AirshipCore\/objc(pl)WKNavigationDelegate"],"type":"inheritsFrom","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"platforms":["Mac Catalyst"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AirshipWKNavigationDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)WKNavigationDelegate","text":"WKNavigationDelegate"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"topicSections":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipWKNavigationDelegate\/closeWindow(_:)"],"title":"Instance Methods","generated":true}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipWKNavigationDelegate"},"metadata":{"symbolKind":"protocol","navigatorTitle":[{"kind":"identifier","text":"AirshipWKNavigationDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AirshipWKNavigationDelegate"}],"roleHeading":"Protocol","modules":[{"name":"AirshipCore"}],"role":"symbol","title":"AirshipWKNavigationDelegate","externalID":"c:@M@AirshipCore@objc(pl)AirshipWKNavigationDelegate"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/airshipwknavigationdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airshipcore\/airshipwknavigationdelegate"]}],"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"url":"\/documentation\/airshipcore","title":"AirshipCore","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","kind":"symbol","abstract":[],"type":"topic","role":"collection"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/AirshipWKNavigationDelegate":{"type":"topic","abstract":[],"url":"\/documentation\/airshipcore\/airshipwknavigationdelegate","title":"AirshipWKNavigationDelegate","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipWKNavigationDelegate","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"AirshipWKNavigationDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirshipWKNavigationDelegate","kind":"identifier"}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/AirshipWKNavigationDelegate/closeWindow(_:)":{"navigatorTitle":[{"text":"closeWindow:","kind":"identifier"}],"title":"closeWindow(_:)","url":"\/documentation\/airshipcore\/airshipwknavigationdelegate\/closewindow(_:)","kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipWKNavigationDelegate\/closeWindow(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"closeWindow","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","role":"symbol"},"doc://com.urbanairship.AirshipCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipCore\/objc(pl)NSObject"},"doc://com.urbanairship.AirshipCore/objc(pl)WKNavigationDelegate":{"title":"WKNavigationDelegate","type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipCore\/objc(pl)WKNavigationDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"AirshipWKNavigationDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"AirshipWKNavigationDelegate","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"AirshipWKNavigationDelegate","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipWKNavigationDelegate\/closeWindow(_:)"],"anchor":"Instance-Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.urbanairship.AirshipCore\/objc(pl)WKNavigationDelegate"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirshipWKNavigationDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"text":"WKNavigationDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)WKNavigationDelegate"},{"text":">","kind":"text"}],"languages":["occ"],"platforms":["Mac Catalyst"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1AirshipWKNavigationDelegate\/title","value":"AirshipWKNavigationDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1AirshipWKNavigationDelegate\/fragments","value":[{"kind":"identifier","text":"AirshipWKNavigationDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1AirshipWKNavigationDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"AirshipWKNavigationDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1AirshipWKNavigationDelegate~1closeWindow(_:)\/title","value":"closeWindow:"},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1AirshipWKNavigationDelegate~1closeWindow(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"closeWindow:"}]}]}]}