{"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore"]]},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/connectiontype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airshipcore\/connectiontype"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["Mac Catalyst"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConnectionType","kind":"identifier"}]}],"kind":"declarations"}],"metadata":{"symbolKind":"class","modules":[{"name":"AirshipCore"}],"title":"ConnectionType","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConnectionType","kind":"identifier"}],"role":"symbol","externalID":"c:@M@AirshipCore@objc(cs)ConnectionType","navigatorTitle":[{"text":"ConnectionType","kind":"identifier"}],"roleHeading":"Class"},"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ConnectionType","interfaceLanguage":"swift"},"abstract":[{"text":"Representations of various device connection types.","type":"text"}],"topicSections":[{"title":"Type Properties","identifiers":["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ConnectionType\/cell","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ConnectionType\/none","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ConnectionType\/wifi"],"generated":true,"anchor":"Type-Properties"}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.urbanairship.AirshipCore\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/com.urbanairship.AirshipCore\/objc(pl)NSObject","doc:\/\/com.urbanairship.AirshipCore\/s7CVarArgP","doc:\/\/com.urbanairship.AirshipCore\/s28CustomDebugStringConvertibleP","doc:\/\/com.urbanairship.AirshipCore\/s23CustomStringConvertibleP","doc:\/\/com.urbanairship.AirshipCore\/SQ","doc:\/\/com.urbanairship.AirshipCore\/SH"],"kind":"relationships","type":"conformsTo"}],"references":{"doc://com.urbanairship.AirshipCore/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.urbanairship.AirshipCore\/SH"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/ConnectionType/wifi":{"abstract":[{"type":"text","text":"Network is a WiFi network."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"wifi"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ConnectionType\/wifi","kind":"symbol","url":"\/documentation\/airshipcore\/connectiontype\/wifi","role":"symbol","type":"topic","title":"wifi"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/ConnectionType/init":{"abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ConnectionType\/init","kind":"symbol","type":"topic","url":"\/documentation\/airshipcore\/connectiontype\/init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"title":"init","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://com.urbanairship.AirshipCore/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.urbanairship.AirshipCore\/s23CustomStringConvertibleP"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/ConnectionType":{"title":"ConnectionType","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ConnectionType","kind":"identifier"}],"abstract":[{"type":"text","text":"Representations of various device connection types."}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ConnectionType","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConnectionType","kind":"identifier"}],"url":"\/documentation\/airshipcore\/connectiontype"},"doc://com.urbanairship.AirshipCore/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.urbanairship.AirshipCore\/s7CVarArgP"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/ConnectionType/cell":{"title":"cell","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"cell"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/airshipcore\/connectiontype\/cell","abstract":[{"text":"Network is a cellular or mobile network.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ConnectionType\/cell"},"doc://com.urbanairship.AirshipCore/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.urbanairship.AirshipCore\/objc(cs)NSObject"},"doc://com.urbanairship.AirshipCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.urbanairship.AirshipCore\/s28CustomDebugStringConvertibleP"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/ConnectionType/none":{"abstract":[{"text":"Network is unreachable.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","title":"none","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ConnectionType\/none","kind":"symbol","url":"\/documentation\/airshipcore\/connectiontype\/none","type":"topic"},"doc://com.urbanairship.AirshipCore/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/objc(pl)NSObject"},"doc://com.urbanairship.AirshipCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.urbanairship.AirshipCore\/SQ"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","url":"\/documentation\/airshipcore","abstract":[],"kind":"symbol","role":"collection","title":"AirshipCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"ConnectionType"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ConnectionType"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"ConnectionType","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ConnectionType\/init"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/com.urbanairship.AirshipCore\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConnectionType","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["Mac Catalyst"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ConnectionType\/title","op":"replace","value":"ConnectionType"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ConnectionType\/fragments","op":"replace","value":[{"kind":"identifier","text":"ConnectionType"}]},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ConnectionType\/navigatorTitle","op":"replace","value":[{"text":"ConnectionType","kind":"identifier"}]}]}]}