{"relationshipsSections":[{"identifiers":["doc:\/\/com.urbanairship.AirshipCore\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/com.urbanairship.AirshipCore\/objc(pl)NSObject","doc:\/\/com.urbanairship.AirshipCore\/s7CVarArgP","doc:\/\/com.urbanairship.AirshipCore\/s28CustomDebugStringConvertibleP","doc:\/\/com.urbanairship.AirshipCore\/s23CustomStringConvertibleP","doc:\/\/com.urbanairship.AirshipCore\/Se","doc:\/\/com.urbanairship.AirshipCore\/SE","doc:\/\/com.urbanairship.AirshipCore\/SQ","doc:\/\/com.urbanairship.AirshipCore\/SH","doc:\/\/com.urbanairship.AirshipCore\/s8SendableP"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"topicSections":[{"identifiers":["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/init(from:)","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/init(json:)","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/init(valueMatcher:)","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/init(valueMatcher:ignoreCase:)","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/init(valueMatcher:scope:)","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/init(valueMatcher:scope:ignoreCase:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"identifiers":["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/hash"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/evaluate(_:)","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/evaluate(json:)","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/isEqual(_:)","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/isEqual(to:)","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/payload()"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSONMatcher"}],"platforms":["Mac Catalyst"]}],"kind":"declarations"},{"content":[{"text":"Overview","level":2,"type":"heading","anchor":"overview"},{"inlineContent":[{"type":"codeVoice","code":"JSONMatcher"},{"type":"text","text":" allows you to specify conditions for a JSON value, optionally at a specific key or nested path ("},{"type":"codeVoice","code":"scope"},{"type":"text","text":"),"},{"type":"text","text":" "},{"type":"text","text":"and then evaluate if a given JSON object meets those conditions."}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"text":"A matcher for evaluating a JSON payload against a set of criteria.","type":"text"}],"metadata":{"externalID":"c:@M@AirshipCore@objc(cs)JSONMatcher","symbolKind":"class","modules":[{"name":"AirshipCore"}],"title":"JSONMatcher","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JSONMatcher","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"JSONMatcher","kind":"identifier"}],"roleHeading":"Class"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/airshipcore\/jsonmatcher"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airshipcore\/jsonmatcher"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONMatcher":{"url":"\/documentation\/airshipcore\/jsonmatcher","abstract":[{"text":"A matcher for evaluating a JSON payload against a set of criteria.","type":"text"}],"type":"topic","title":"JSONMatcher","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"JSONMatcher"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSONMatcher"}],"kind":"symbol"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONMatcher/init(valueMatcher:)":{"type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"valueMatcher","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONValueMatcher","text":"JSONValueMatcher","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(valueMatcher:)","url":"\/documentation\/airshipcore\/jsonmatcher\/init(valuematcher:)","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/init(valueMatcher:)","abstract":[{"text":"Creates a new ","type":"text"},{"code":"JSONMatcher","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol"},"doc://com.urbanairship.AirshipCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipCore\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONMatcher/isEqual(to:)":{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/isEqual(to:)","role":"symbol","title":"isEqual(to:)","kind":"symbol","url":"\/documentation\/airshipcore\/jsonmatcher\/isequal(to:)","abstract":[],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONMatcher","text":"JSONMatcher","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://com.urbanairship.AirshipCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.urbanairship.AirshipCore/SH":{"type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipCore\/SH","title":"Swift.Hashable"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONMatcher/evaluate(json:)":{"type":"topic","role":"symbol","kind":"symbol","title":"evaluate(json:)","url":"\/documentation\/airshipcore\/jsonmatcher\/evaluate(json:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"evaluate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"json","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11AirshipCore0A4JSONO","text":"AirshipJSON","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/evaluate(json:)","abstract":[{"type":"text","text":"Evaluates the given "},{"type":"codeVoice","code":"AirshipJSON"},{"type":"text","text":" value against the matcher’s criteria."}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONMatcher/hash":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"hash"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/hash","abstract":[],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"hash","url":"\/documentation\/airshipcore\/jsonmatcher\/hash"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONMatcher/init(from:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": any "},{"preciseIdentifier":"s:s7DecoderP","kind":"typeIdentifier","text":"Decoder"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"kind":"symbol","url":"\/documentation\/airshipcore\/jsonmatcher\/init(from:)","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/init(from:)","title":"init(from:)","role":"symbol","type":"topic"},"doc://com.urbanairship.AirshipCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipCore\/SQ","title":"Swift.Equatable"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONMatcher/evaluate(_:)":{"role":"symbol","type":"topic","deprecated":true,"kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/evaluate(_:)","url":"\/documentation\/airshipcore\/jsonmatcher\/evaluate(_:)","title":"evaluate(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"evaluate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Evaluates the given value against the matcher’s criteria."}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONMatcher/init(json:)":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/init(json:)","deprecated":true,"title":"init(json:)","url":"\/documentation\/airshipcore\/jsonmatcher\/init(json:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"json","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"abstract":[{"type":"text","text":"Creates a new "},{"type":"codeVoice","code":"JSONMatcher"},{"type":"text","text":" from a JSON payload."}],"kind":"symbol"},"doc://com.urbanairship.AirshipCore/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipCore\/objc(cs)NSObject","title":"NSObject"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONMatcher/init(valueMatcher:scope:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"valueMatcher"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONValueMatcher","text":"JSONValueMatcher"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scope"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"])"}],"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/init(valueMatcher:scope:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Creates a new "},{"type":"codeVoice","code":"JSONMatcher"},{"type":"text","text":" with a specified scope."}],"title":"init(valueMatcher:scope:)","url":"\/documentation\/airshipcore\/jsonmatcher\/init(valuematcher:scope:)"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONMatcher/init(valueMatcher:ignoreCase:)":{"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/init(valueMatcher:ignoreCase:)","role":"symbol","abstract":[],"title":"init(valueMatcher:ignoreCase:)","kind":"symbol","url":"\/documentation\/airshipcore\/jsonmatcher\/init(valuematcher:ignorecase:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"valueMatcher","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"JSONValueMatcher","kind":"typeIdentifier","preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONValueMatcher"},{"text":", ","kind":"text"},{"text":"ignoreCase","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"title":"AirshipCore","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/airshipcore"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONMatcher/init(valueMatcher:scope:ignoreCase:)":{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/init(valueMatcher:scope:ignoreCase:)","title":"init(valueMatcher:scope:ignoreCase:)","kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/airshipcore\/jsonmatcher\/init(valuematcher:scope:ignorecase:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"valueMatcher","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"JSONValueMatcher","kind":"typeIdentifier","preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONValueMatcher"},{"text":", ","kind":"text"},{"text":"scope","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"text":"ignoreCase","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}]},"doc://com.urbanairship.AirshipCore/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipCore\/s8SendableP","title":"Swift.Sendable"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONMatcher/isEqual(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"url":"\/documentation\/airshipcore\/jsonmatcher\/isequal(_:)","type":"topic","abstract":[],"title":"isEqual(_:)","role":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/isEqual(_:)"},"doc://com.urbanairship.AirshipCore/SE":{"type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipCore\/SE","title":"Swift.Encodable"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONMatcher/payload()":{"title":"payload()","abstract":[{"text":"Returns the matcher’s JSON payload representation.","type":"text"}],"url":"\/documentation\/airshipcore\/jsonmatcher\/payload()","role":"symbol","type":"topic","deprecated":true,"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/payload()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"payload","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"kind":"symbol"},"doc://com.urbanairship.AirshipCore/Se":{"type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipCore\/Se","title":"Swift.Decodable"},"doc://com.urbanairship.AirshipCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.urbanairship.AirshipCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"JSONMatcher"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"JSONMatcher","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"JSONMatcher"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/hash"],"generated":true},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/isEqual(_:)"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.urbanairship.AirshipCore\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["Mac Catalyst"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSONMatcher"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONMatcher\/title","value":"JSONMatcher","op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONMatcher\/fragments","value":[{"kind":"identifier","text":"JSONMatcher"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONMatcher\/navigatorTitle","value":[{"text":"JSONMatcher","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONMatcher~1hash\/title","value":"hash","op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONMatcher~1hash\/fragments","value":[{"kind":"identifier","text":"hash"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONMatcher~1isEqual(_:)\/title","value":"isEqual:","op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONMatcher~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}