{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.urbanairship.AirshipCore\/objc(cs)NSValueTransformer"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.urbanairship.AirshipCore\/objc(pl)NSObject","doc:\/\/com.urbanairship.AirshipCore\/s7CVarArgP","doc:\/\/com.urbanairship.AirshipCore\/s28CustomDebugStringConvertibleP","doc:\/\/com.urbanairship.AirshipCore\/s23CustomStringConvertibleP","doc:\/\/com.urbanairship.AirshipCore\/SQ","doc:\/\/com.urbanairship.AirshipCore\/SH","doc:\/\/com.urbanairship.AirshipCore\/s8SendableP","doc:\/\/com.urbanairship.AirshipCore\/s16SendableMetatypeP"],"kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/nsarrayvaluetransformer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airshipcore\/nsarrayvaluetransformer"]}],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore"]]},"topicSections":[{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSArrayValueTransformer\/reverseTransformedValue(_:)","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSArrayValueTransformer\/transformedValue(_:)"]},{"anchor":"Type-Methods","generated":true,"title":"Type Methods","identifiers":["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSArrayValueTransformer\/allowsReverseTransformation()","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSArrayValueTransformer\/transformedValueClass()"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSArrayValueTransformer"}],"platforms":["Mac Catalyst"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"AirshipCore"}],"roleHeading":"Class","symbolKind":"class","title":"NSArrayValueTransformer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSArrayValueTransformer"}],"navigatorTitle":[{"kind":"identifier","text":"NSArrayValueTransformer"}],"externalID":"c:@M@AirshipCore@objc(cs)NSArrayValueTransformer","role":"symbol"},"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSArrayValueTransformer","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.urbanairship.AirshipCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSArrayValueTransformer":{"title":"NSArrayValueTransformer","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NSArrayValueTransformer"}],"url":"\/documentation\/airshipcore\/nsarrayvaluetransformer","role":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSArrayValueTransformer"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSArrayValueTransformer"},"doc://com.urbanairship.AirshipCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSArrayValueTransformer/init":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSArrayValueTransformer\/init","title":"init","url":"\/documentation\/airshipcore\/nsarrayvaluetransformer\/init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"role":"symbol","kind":"symbol"},"doc://com.urbanairship.AirshipCore/SH":{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.urbanairship.AirshipCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipCore\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.urbanairship.AirshipCore/s16SendableMetatypeP":{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/s16SendableMetatypeP","title":"Swift.SendableMetatype","type":"unresolvable"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSArrayValueTransformer/transformedValueClass()":{"kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/airshipcore\/nsarrayvaluetransformer\/transformedvalueclass()","navigatorTitle":[{"text":"transformedValueClass","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transformedValueClass","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:s8AnyClassa","text":"AnyClass","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSArrayValueTransformer\/transformedValueClass()","title":"transformedValueClass()","type":"topic"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"kind":"symbol","role":"collection","title":"AirshipCore","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","url":"\/documentation\/airshipcore","abstract":[]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSArrayValueTransformer/allowsReverseTransformation()":{"title":"allowsReverseTransformation()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"allowsReverseTransformation"}],"url":"\/documentation\/airshipcore\/nsarrayvaluetransformer\/allowsreversetransformation()","role":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowsReverseTransformation"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSArrayValueTransformer\/allowsReverseTransformation()"},"doc://com.urbanairship.AirshipCore/SQ":{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.urbanairship.AirshipCore/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipCore\/s8SendableP","title":"Swift.Sendable"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSArrayValueTransformer/reverseTransformedValue(_:)":{"title":"reverseTransformedValue(_:)","navigatorTitle":[{"text":"reverseTransformedValue:","kind":"identifier"}],"url":"\/documentation\/airshipcore\/nsarrayvaluetransformer\/reversetransformedvalue(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reverseTransformedValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?","kind":"text"}],"abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSArrayValueTransformer\/reverseTransformedValue(_:)"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSArrayValueTransformer/transformedValue(_:)":{"role":"symbol","url":"\/documentation\/airshipcore\/nsarrayvaluetransformer\/transformedvalue(_:)","type":"topic","kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSArrayValueTransformer\/transformedValue(_:)","title":"transformedValue(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transformedValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"transformedValue:","kind":"identifier"}],"abstract":[]},"doc://com.urbanairship.AirshipCore/objc(cs)NSValueTransformer":{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/objc(cs)NSValueTransformer","title":"NSValueTransformer","type":"unresolvable"},"doc://com.urbanairship.AirshipCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"NSArrayValueTransformer","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"NSArrayValueTransformer"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"NSArrayValueTransformer","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"generated":true,"identifiers":["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSArrayValueTransformer\/init","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSArrayValueTransformer\/reverseTransformedValue(_:)","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSArrayValueTransformer\/transformedValue(_:)"],"title":"Instance Methods","anchor":"Instance-Methods"},{"generated":true,"identifiers":["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSArrayValueTransformer\/allowsReverseTransformation()","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSArrayValueTransformer\/transformedValueClass()"],"title":"Type Methods","anchor":"Type-Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.urbanairship.AirshipCore\/objc(cs)NSValueTransformer"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSArrayValueTransformer","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSValueTransformer","preciseIdentifier":"c:objc(cs)NSValueTransformer","kind":"typeIdentifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"NSArrayValueTransformer","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSArrayValueTransformer\/title","op":"replace"},{"value":[{"text":"NSArrayValueTransformer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSArrayValueTransformer\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"NSArrayValueTransformer"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSArrayValueTransformer\/navigatorTitle","op":"replace"},{"value":"transformedValueClass","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSArrayValueTransformer~1transformedValueClass()\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"transformedValueClass"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSArrayValueTransformer~1transformedValueClass()\/fragments","op":"replace"},{"value":"allowsReverseTransformation","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSArrayValueTransformer~1allowsReverseTransformation()\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"allowsReverseTransformation"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSArrayValueTransformer~1allowsReverseTransformation()\/fragments","op":"replace"},{"value":"reverseTransformedValue:","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSArrayValueTransformer~1reverseTransformedValue(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"reverseTransformedValue:"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSArrayValueTransformer~1reverseTransformedValue(_:)\/fragments","op":"replace"},{"value":"transformedValue:","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSArrayValueTransformer~1transformedValue(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"transformedValue:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSArrayValueTransformer~1transformedValue(_:)\/fragments","op":"replace"}]}]}