{"abstract":[{"text":"NOTE: For internal use only. :nodoc:","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSDictionaryValueTransformer\/reverseTransformedValue(_:)","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSDictionaryValueTransformer\/transformedValue(_:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSDictionaryValueTransformer\/allowsReverseTransformation()","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSDictionaryValueTransformer\/transformedValueClass()"],"title":"Type Methods","generated":true,"anchor":"Type-Methods"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore"]]},"kind":"symbol","relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.urbanairship.AirshipCore\/objc(cs)NSValueTransformer"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/com.urbanairship.AirshipCore\/objc(pl)NSObject","doc:\/\/com.urbanairship.AirshipCore\/s7CVarArgP","doc:\/\/com.urbanairship.AirshipCore\/s28CustomDebugStringConvertibleP","doc:\/\/com.urbanairship.AirshipCore\/s23CustomStringConvertibleP","doc:\/\/com.urbanairship.AirshipCore\/SQ","doc:\/\/com.urbanairship.AirshipCore\/SH"],"title":"Conforms To","type":"conformsTo"}],"variants":[{"paths":["\/documentation\/airshipcore\/nsdictionaryvaluetransformer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airshipcore\/nsdictionaryvaluetransformer"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSDictionaryValueTransformer","kind":"identifier"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]}],"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSDictionaryValueTransformer","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"class","role":"symbol","title":"NSDictionaryValueTransformer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSDictionaryValueTransformer"}],"roleHeading":"Class","modules":[{"name":"AirshipCore"}],"externalID":"c:@M@AirshipCore@objc(cs)NSDictionaryValueTransformer","navigatorTitle":[{"kind":"identifier","text":"NSDictionaryValueTransformer"}]},"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSDictionaryValueTransformer/transformedValue(_:)":{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSDictionaryValueTransformer\/transformedValue(_:)","title":"transformedValue(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transformedValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?","kind":"text"}],"abstract":[],"role":"symbol","navigatorTitle":[{"text":"transformedValue:","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/airshipcore\/nsdictionaryvaluetransformer\/transformedvalue(_:)"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSDictionaryValueTransformer/init":{"kind":"symbol","url":"\/documentation\/airshipcore\/nsdictionaryvaluetransformer\/init","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSDictionaryValueTransformer\/init","type":"topic","title":"init","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"kind":"identifier","text":"init"}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSDictionaryValueTransformer/reverseTransformedValue(_:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reverseTransformedValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSDictionaryValueTransformer\/reverseTransformedValue(_:)","url":"\/documentation\/airshipcore\/nsdictionaryvaluetransformer\/reversetransformedvalue(_:)","abstract":[],"title":"reverseTransformedValue(_:)","navigatorTitle":[{"text":"reverseTransformedValue:","kind":"identifier"}],"type":"topic"},"doc://com.urbanairship.AirshipCore/objc(pl)NSObject":{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.urbanairship.AirshipCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.urbanairship.AirshipCore/s7CVarArgP":{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.urbanairship.AirshipCore/SH":{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.urbanairship.AirshipCore/objc(cs)NSValueTransformer":{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/objc(cs)NSValueTransformer","type":"unresolvable","title":"NSValueTransformer"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"url":"\/documentation\/airshipcore","kind":"symbol","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","title":"AirshipCore"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSDictionaryValueTransformer":{"abstract":[{"type":"text","text":"NOTE: For internal use only. :nodoc:"}],"url":"\/documentation\/airshipcore\/nsdictionaryvaluetransformer","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSDictionaryValueTransformer","navigatorTitle":[{"kind":"identifier","text":"NSDictionaryValueTransformer"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSDictionaryValueTransformer"}],"title":"NSDictionaryValueTransformer"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSDictionaryValueTransformer/allowsReverseTransformation()":{"abstract":[],"title":"allowsReverseTransformation()","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowsReverseTransformation","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/airshipcore\/nsdictionaryvaluetransformer\/allowsreversetransformation()","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSDictionaryValueTransformer\/allowsReverseTransformation()","type":"topic","kind":"symbol","navigatorTitle":[{"text":"allowsReverseTransformation","kind":"identifier"}]},"doc://com.urbanairship.AirshipCore/SQ":{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSDictionaryValueTransformer/transformedValueClass()":{"url":"\/documentation\/airshipcore\/nsdictionaryvaluetransformer\/transformedvalueclass()","navigatorTitle":[{"text":"transformedValueClass","kind":"identifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSDictionaryValueTransformer\/transformedValueClass()","abstract":[],"title":"transformedValueClass()","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transformedValueClass","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"AnyClass","preciseIdentifier":"s:s8AnyClassa","kind":"typeIdentifier"}],"role":"symbol"},"doc://com.urbanairship.AirshipCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"NSDictionaryValueTransformer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"NSDictionaryValueTransformer","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"NSDictionaryValueTransformer"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSDictionaryValueTransformer\/init","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSDictionaryValueTransformer\/reverseTransformedValue(_:)","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSDictionaryValueTransformer\/transformedValue(_:)"],"generated":true},{"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSDictionaryValueTransformer\/allowsReverseTransformation()","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSDictionaryValueTransformer\/transformedValueClass()"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.urbanairship.AirshipCore\/objc(cs)NSValueTransformer"],"type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSDictionaryValueTransformer","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSValueTransformer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSValueTransformer"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSDictionaryValueTransformer~1transformedValue(_:)\/title","value":"transformedValue:"},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSDictionaryValueTransformer~1transformedValue(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"transformedValue:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSDictionaryValueTransformer~1reverseTransformedValue(_:)\/title","value":"reverseTransformedValue:"},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSDictionaryValueTransformer~1reverseTransformedValue(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"reverseTransformedValue:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSDictionaryValueTransformer\/title","value":"NSDictionaryValueTransformer"},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSDictionaryValueTransformer\/fragments","value":[{"text":"NSDictionaryValueTransformer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSDictionaryValueTransformer\/navigatorTitle","value":[{"kind":"identifier","text":"NSDictionaryValueTransformer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSDictionaryValueTransformer~1allowsReverseTransformation()\/title","value":"allowsReverseTransformation"},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSDictionaryValueTransformer~1allowsReverseTransformation()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"allowsReverseTransformation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSDictionaryValueTransformer~1transformedValueClass()\/title","value":"transformedValueClass"},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSDictionaryValueTransformer~1transformedValueClass()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"transformedValueClass"}]}]}]}