{"topicSections":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSURLValueTransformer\/reverseTransformedValue(_:)","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSURLValueTransformer\/transformedValue(_:)"],"title":"Instance Methods","generated":true},{"identifiers":["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSURLValueTransformer\/allowsReverseTransformation()","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSURLValueTransformer\/transformedValueClass()"],"generated":true,"anchor":"Type-Methods","title":"Type Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/nsurlvaluetransformer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airshipcore\/nsurlvaluetransformer"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSURLValueTransformer"}],"languages":["swift"]}]}],"metadata":{"symbolKind":"class","roleHeading":"Class","role":"symbol","externalID":"c:@M@AirshipCore@objc(cs)NSURLValueTransformer","modules":[{"name":"AirshipCore"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSURLValueTransformer","kind":"identifier"}],"title":"NSURLValueTransformer","navigatorTitle":[{"kind":"identifier","text":"NSURLValueTransformer"}]},"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSURLValueTransformer","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore"]]},"kind":"symbol","sections":[],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.urbanairship.AirshipCore\/objc(cs)NSValueTransformer"],"type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/com.urbanairship.AirshipCore\/objc(pl)NSObject","doc:\/\/com.urbanairship.AirshipCore\/s7CVarArgP","doc:\/\/com.urbanairship.AirshipCore\/s28CustomDebugStringConvertibleP","doc:\/\/com.urbanairship.AirshipCore\/s23CustomStringConvertibleP","doc:\/\/com.urbanairship.AirshipCore\/SQ","doc:\/\/com.urbanairship.AirshipCore\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSURLValueTransformer/init":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSURLValueTransformer\/init","type":"topic","url":"\/documentation\/airshipcore\/nsurlvaluetransformer\/init","abstract":[],"title":"init","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"kind":"symbol","role":"symbol"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSURLValueTransformer/reverseTransformedValue(_:)":{"abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reverseTransformedValue"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"title":"reverseTransformedValue(_:)","type":"topic","url":"\/documentation\/airshipcore\/nsurlvaluetransformer\/reversetransformedvalue(_:)","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSURLValueTransformer\/reverseTransformedValue(_:)"},"doc://com.urbanairship.AirshipCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.urbanairship.AirshipCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.urbanairship.AirshipCore/s7CVarArgP":{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.urbanairship.AirshipCore/SQ":{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.urbanairship.AirshipCore/objc(cs)NSValueTransformer":{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/objc(cs)NSValueTransformer","title":"NSValueTransformer","type":"unresolvable"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","url":"\/documentation\/airshipcore","title":"AirshipCore","abstract":[],"role":"collection"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSURLValueTransformer/transformedValueClass()":{"abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transformedValueClass","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:s8AnyClassa","text":"AnyClass","kind":"typeIdentifier"}],"title":"transformedValueClass()","type":"topic","url":"\/documentation\/airshipcore\/nsurlvaluetransformer\/transformedvalueclass()","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSURLValueTransformer\/transformedValueClass()"},"doc://com.urbanairship.AirshipCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSURLValueTransformer/transformedValue(_:)":{"abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"transformedValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"title":"transformedValue(_:)","type":"topic","url":"\/documentation\/airshipcore\/nsurlvaluetransformer\/transformedvalue(_:)","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSURLValueTransformer\/transformedValue(_:)"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSURLValueTransformer":{"navigatorTitle":[{"text":"NSURLValueTransformer","kind":"identifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSURLValueTransformer","type":"topic","url":"\/documentation\/airshipcore\/nsurlvaluetransformer","abstract":[],"title":"NSURLValueTransformer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSURLValueTransformer"}],"kind":"symbol","role":"symbol"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSURLValueTransformer/allowsReverseTransformation()":{"abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"allowsReverseTransformation","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"allowsReverseTransformation()","type":"topic","url":"\/documentation\/airshipcore\/nsurlvaluetransformer\/allowsreversetransformation()","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSURLValueTransformer\/allowsReverseTransformation()"},"doc://com.urbanairship.AirshipCore/SH":{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/SH","type":"unresolvable","title":"Swift.Hashable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSURLValueTransformer\/init"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.urbanairship.AirshipCore\/objc(cs)NSValueTransformer"]}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NSURLValueTransformer"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSValueTransformer","kind":"typeIdentifier","text":"NSValueTransformer"}],"platforms":["iOS"]}],"kind":"declarations"}}],"traits":[{"interfaceLanguage":"occ"}]}]}