{"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/VersionMatcher","interfaceLanguage":"swift"},"deprecationSummary":[{"inlineContent":[{"text":"Marked to be removed in SDK 20","type":"text"}],"type":"paragraph"}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/airshipcore\/versionmatcher"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airshipcore\/versionmatcher"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Version matcher.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore"]]},"topicSections":[{"identifiers":["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/VersionMatcher\/init(versionConstraint:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/VersionMatcher\/evaluate(_:)"]},{"generated":true,"title":"Type Methods","identifiers":["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/VersionMatcher\/matcher(versionConstraint:)"],"anchor":"Type-Methods"}],"metadata":{"roleHeading":"Class","externalID":"c:@M@AirshipCore@objc(cs)VersionMatcher","title":"VersionMatcher","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VersionMatcher"}],"symbolKind":"class","modules":[{"name":"AirshipCore"}],"platforms":[],"navigatorTitle":[{"kind":"identifier","text":"VersionMatcher"}]},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.urbanairship.AirshipCore\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/com.urbanairship.AirshipCore\/objc(pl)NSObject","doc:\/\/com.urbanairship.AirshipCore\/s7CVarArgP","doc:\/\/com.urbanairship.AirshipCore\/s28CustomDebugStringConvertibleP","doc:\/\/com.urbanairship.AirshipCore\/s23CustomStringConvertibleP","doc:\/\/com.urbanairship.AirshipCore\/SQ","doc:\/\/com.urbanairship.AirshipCore\/SH"],"kind":"relationships","type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VersionMatcher"}],"platforms":["Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.urbanairship.AirshipCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/VersionMatcher/init(versionConstraint:)":{"kind":"symbol","deprecated":true,"url":"\/documentation\/airshipcore\/versionmatcher\/init(versionconstraint:)","title":"init(versionConstraint:)","role":"symbol","type":"topic","abstract":[{"type":"text","text":"NOTE: For internal use only. :nodoc:"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"versionConstraint","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/VersionMatcher\/init(versionConstraint:)"},"doc://com.urbanairship.AirshipCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipCore\/s23CustomStringConvertibleP"},"doc://com.urbanairship.AirshipCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipCore\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.urbanairship.AirshipCore/SH":{"type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipCore\/SH","title":"Swift.Hashable"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/VersionMatcher/matcher(versionConstraint:)":{"abstract":[{"text":"Create a matcher for the supplied version constraint","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"matcher","kind":"identifier"},{"text":"(","kind":"text"},{"text":"versionConstraint","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AirshipCore@objc(cs)VersionMatcher","text":"VersionMatcher"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/airshipcore\/versionmatcher\/matcher(versionconstraint:)","kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/VersionMatcher\/matcher(versionConstraint:)","title":"matcher(versionConstraint:)","deprecated":true},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","url":"\/documentation\/airshipcore","title":"AirshipCore","abstract":[],"role":"collection"},"doc://com.urbanairship.AirshipCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.urbanairship.AirshipCore/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipCore\/objc(cs)NSObject","title":"NSObject"},"doc://com.urbanairship.AirshipCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipCore\/SQ","title":"Swift.Equatable"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/VersionMatcher/evaluate(_:)":{"type":"topic","abstract":[{"text":"Evaluates the object with the matcher.","type":"text"}],"url":"\/documentation\/airshipcore\/versionmatcher\/evaluate(_:)","kind":"symbol","deprecated":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"evaluate"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/VersionMatcher\/evaluate(_:)","role":"symbol","title":"evaluate(_:)"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/VersionMatcher":{"kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"Version matcher.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"VersionMatcher","kind":"identifier"}],"title":"VersionMatcher","navigatorTitle":[{"text":"VersionMatcher","kind":"identifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/VersionMatcher","deprecated":true,"url":"\/documentation\/airshipcore\/versionmatcher"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":[],"path":"\/metadata\/platforms"},{"path":"\/topicSections","value":null,"op":"replace"},{"op":"replace","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.urbanairship.AirshipCore\/objc(cs)NSObject"],"title":"Inherits From"}],"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"VersionMatcher"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"}]}]}