{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterSDKModule"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterSDKModule\/actionsManifest"},"sections":[],"metadata":{"role":"symbol","symbolKind":"property","modules":[{"name":"AirshipPreferenceCenter"}],"roleHeading":"Instance Property","externalID":"s:23AirshipPreferenceCenter0bC9SDKModuleC15actionsManifest0A4Core07ActionsF0_pSgvp","title":"actionsManifest","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actionsManifest","kind":"identifier"},{"text":": (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:11AirshipCore15ActionsManifestP","text":"ActionsManifest","kind":"typeIdentifier"},{"text":")?","kind":"text"}]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"AirshipSDKModule.actionsManifest"},{"type":"text","text":"."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["Mac Catalyst"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"actionsManifest"},{"kind":"text","text":": ("},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:11AirshipCore15ActionsManifestP","text":"ActionsManifest"},{"kind":"text","text":")?"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshippreferencecenter\/preferencecentersdkmodule\/actionsmanifest"]}],"references":{"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterSDKModule/actionsManifest":{"abstract":[],"url":"\/documentation\/airshippreferencecenter\/preferencecentersdkmodule\/actionsmanifest","title":"actionsManifest","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actionsManifest","kind":"identifier"},{"text":": (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActionsManifest","kind":"typeIdentifier","preciseIdentifier":"s:11AirshipCore15ActionsManifestP"},{"text":")?","kind":"text"}],"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterSDKModule\/actionsManifest","type":"topic","kind":"symbol","role":"symbol"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter":{"url":"\/documentation\/airshippreferencecenter","abstract":[],"title":"AirshipPreferenceCenter","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter","type":"topic","kind":"symbol","role":"collection"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterSDKModule":{"type":"topic","title":"PreferenceCenterSDKModule","url":"\/documentation\/airshippreferencecenter\/preferencecentersdkmodule","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreferenceCenterSDKModule","kind":"identifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterSDKModule","abstract":[{"text":"AirshipPreferenceCenter module loader.","type":"text"}],"navigatorTitle":[{"text":"PreferenceCenterSDKModule","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.urbanairship.AirshipPreferenceCenter~1documentation~1AirshipPreferenceCenter~1PreferenceCenterSDKModule\/title","op":"replace","value":"UAPreferenceCenterSDKModule"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipPreferenceCenter~1documentation~1AirshipPreferenceCenter~1PreferenceCenterSDKModule\/fragments","op":"replace","value":[{"kind":"identifier","text":"UAPreferenceCenterSDKModule"}]},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipPreferenceCenter~1documentation~1AirshipPreferenceCenter~1PreferenceCenterSDKModule\/navigatorTitle","value":[{"text":"UAPreferenceCenterSDKModule","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}