{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"components"},{"kind":"text","text":": ["},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"AirshipComponent","preciseIdentifier":"s:11AirshipCore0A9ComponentP"},{"kind":"text","text":"]"}],"platforms":["Mac Catalyst"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterSDKModule\/components"},"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterSDKModule"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshippreferencecenter\/preferencecentersdkmodule\/components"]}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"AirshipSDKModule.components"},{"type":"text","text":"."}],"metadata":{"symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"components","kind":"identifier"},{"text":": [","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirshipComponent","preciseIdentifier":"s:11AirshipCore0A9ComponentP","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"modules":[{"name":"AirshipPreferenceCenter"}],"role":"symbol","roleHeading":"Instance Property","externalID":"s:23AirshipPreferenceCenter0bC9SDKModuleC10componentsSay0A4Core0A9Component_pGvp","title":"components"},"references":{"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterSDKModule/components":{"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterSDKModule\/components","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"components","kind":"identifier"},{"text":": [","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirshipComponent","kind":"typeIdentifier","preciseIdentifier":"s:11AirshipCore0A9ComponentP"},{"text":"]","kind":"text"}],"abstract":[],"title":"components","role":"symbol","url":"\/documentation\/airshippreferencecenter\/preferencecentersdkmodule\/components","kind":"symbol"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter":{"url":"\/documentation\/airshippreferencecenter","abstract":[],"title":"AirshipPreferenceCenter","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter","type":"topic","kind":"symbol","role":"collection"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterSDKModule":{"type":"topic","title":"PreferenceCenterSDKModule","url":"\/documentation\/airshippreferencecenter\/preferencecentersdkmodule","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreferenceCenterSDKModule","kind":"identifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterSDKModule","abstract":[{"text":"AirshipPreferenceCenter module loader.","type":"text"}],"navigatorTitle":[{"text":"PreferenceCenterSDKModule","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.urbanairship.AirshipPreferenceCenter~1documentation~1AirshipPreferenceCenter~1PreferenceCenterSDKModule\/title","op":"replace","value":"UAPreferenceCenterSDKModule"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipPreferenceCenter~1documentation~1AirshipPreferenceCenter~1PreferenceCenterSDKModule\/fragments","op":"replace","value":[{"kind":"identifier","text":"UAPreferenceCenterSDKModule"}]},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipPreferenceCenter~1documentation~1AirshipPreferenceCenter~1PreferenceCenterSDKModule\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UAPreferenceCenterSDKModule"}]}]}]}