{"abstract":[{"type":"text","text":"Audience selector initializer"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/DeviceAudienceSelector\/init(newUser:notificationOptIn:locationOptIn:languageIDs:tagSelector:versionPredicate:requiresAnalytics:permissionPredicate:testDevices:hashSelector:deviceTypes:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"newUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"notificationOptIn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"locationOptIn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"languageIDs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"tagSelector"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DeviceTagSelector","preciseIdentifier":"s:11AirshipCore17DeviceTagSelectorO"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"versionPredicate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JSONPredicate","preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONPredicate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"requiresAnalytics"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"permissionPredicate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JSONPredicate","preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONPredicate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"testDevices"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"hashSelector"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudienceHashSelector","preciseIdentifier":"s:11AirshipCore20AudienceHashSelectorV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"deviceTypes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?)"}],"title":"init(newUser:notificationOptIn:locationOptIn:languageIDs:tagSelector:versionPredicate:requiresAnalytics:permissionPredicate:testDevices:hashSelector:deviceTypes:)","roleHeading":"Initializer","symbolKind":"init","externalID":"s:11AirshipCore22DeviceAudienceSelectorV7newUser17notificationOptIn08locationiJ011languageIDs03tagE016versionPredicate17requiresAnalytics010permissionP011testDevices04hashE011deviceTypesACSbSg_A2OSaySSGSgAA0c3TagE0OSgAA13JSONPredicateCSgAowqA0d4HashE0VSgAQtcfc","modules":[{"name":"AirshipCore"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/deviceaudienceselector\/init(newuser:notificationoptin:locationoptin:languageids:tagselector:versionpredicate:requiresanalytics:permissionpredicate:testdevices:hashselector:devicetypes:)"]}],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/DeviceAudienceSelector"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"newUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"notificationOptIn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"locationOptIn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"languageIDs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"tagSelector"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/DeviceTagSelector","kind":"typeIdentifier","preciseIdentifier":"s:11AirshipCore17DeviceTagSelectorO","text":"DeviceTagSelector"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"versionPredicate"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONPredicate","kind":"typeIdentifier","preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONPredicate","text":"JSONPredicate"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"requiresAnalytics"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"permissionPredicate"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONPredicate","kind":"typeIdentifier","preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONPredicate","text":"JSONPredicate"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"testDevices"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]? = nil, "},{"kind":"externalParam","text":"hashSelector"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AudienceHashSelector","kind":"typeIdentifier","preciseIdentifier":"s:11AirshipCore20AudienceHashSelectorV","text":"AudienceHashSelector"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"deviceTypes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]? = nil)"}],"platforms":["Mac Catalyst"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Flag indicating if audience consists of new users"}]}],"name":"newUser"},{"content":[{"inlineContent":[{"text":"Flag indicating if audience consists of users opted into notifications","type":"text"}],"type":"paragraph"}],"name":"notificationOptIn"},{"content":[{"inlineContent":[{"text":"Flag indicating if audience consists of users that have opted into location","type":"text"}],"type":"paragraph"}],"name":"locationOptIn"},{"content":[{"inlineContent":[{"type":"text","text":"Array of language IDs representing a given audience"}],"type":"paragraph"}],"name":"languageIDs"},{"content":[{"inlineContent":[{"text":"Internal-only selector","type":"text"}],"type":"paragraph"}],"name":"tagSelector"},{"content":[{"inlineContent":[{"type":"text","text":"Version predicate representing a given audience"}],"type":"paragraph"}],"name":"versionPredicate"},{"content":[{"inlineContent":[{"type":"text","text":"Flag indicating if audience consists of users that require analytics tracking"}],"type":"paragraph"}],"name":"requiresAnalytics"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Flag indicating if audience consists of users that require certain permissions","type":"text"}]}],"name":"permissionPredicate"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Array of test device identifiers representing a given audience","type":"text"}]}],"name":"testDevices"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Internal-only selector","type":"text"}]}],"name":"hashSelector"},{"content":[{"inlineContent":[{"type":"text","text":"Array of device types representing a given audience"}],"type":"paragraph"}],"name":"deviceTypes"}]}],"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/DeviceTagSelector":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceTagSelector"}],"type":"topic","url":"\/documentation\/airshipcore\/devicetagselector","kind":"symbol","abstract":[{"text":"NOTE: For internal use only. :nodoc:","type":"text"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/DeviceTagSelector","navigatorTitle":[{"kind":"identifier","text":"DeviceTagSelector"}],"title":"DeviceTagSelector","role":"symbol"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"title":"AirshipCore","url":"\/documentation\/airshipcore","kind":"symbol","type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONPredicate":{"title":"JSONPredicate","type":"topic","role":"symbol","url":"\/documentation\/airshipcore\/jsonpredicate","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"JSONPredicate"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONPredicate","abstract":[{"text":"Defines a predicate for evaluating a JSON payload.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSONPredicate"}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/AudienceHashSelector":{"type":"topic","navigatorTitle":[{"text":"AudienceHashSelector","kind":"identifier"}],"role":"symbol","url":"\/documentation\/airshipcore\/audiencehashselector","kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AudienceHashSelector","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AudienceHashSelector","kind":"identifier"}],"title":"AudienceHashSelector","abstract":[{"text":"NOTE: For internal use only. :nodoc:","type":"text"}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/DeviceAudienceSelector/init(newUser:notificationOptIn:locationOptIn:languageIDs:tagSelector:versionPredicate:requiresAnalytics:permissionPredicate:testDevices:hashSelector:deviceTypes:)":{"type":"topic","kind":"symbol","abstract":[{"text":"Audience selector initializer","type":"text"}],"url":"\/documentation\/airshipcore\/deviceaudienceselector\/init(newuser:notificationoptin:locationoptin:languageids:tagselector:versionpredicate:requiresanalytics:permissionpredicate:testdevices:hashselector:devicetypes:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"newUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"notificationOptIn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"locationOptIn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"languageIDs"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"tagSelector"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DeviceTagSelector","preciseIdentifier":"s:11AirshipCore17DeviceTagSelectorO"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"versionPredicate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JSONPredicate","preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONPredicate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"requiresAnalytics"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"permissionPredicate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JSONPredicate","preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONPredicate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"testDevices"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"hashSelector"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudienceHashSelector","preciseIdentifier":"s:11AirshipCore20AudienceHashSelectorV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"deviceTypes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?)"}],"title":"init(newUser:notificationOptIn:locationOptIn:languageIDs:tagSelector:versionPredicate:requiresAnalytics:permissionPredicate:testDevices:hashSelector:deviceTypes:)","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/DeviceAudienceSelector\/init(newUser:notificationOptIn:locationOptIn:languageIDs:tagSelector:versionPredicate:requiresAnalytics:permissionPredicate:testDevices:hashSelector:deviceTypes:)"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/DeviceAudienceSelector":{"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/DeviceAudienceSelector","abstract":[{"text":"A collection of properties defining an automation audience","type":"text"}],"url":"\/documentation\/airshipcore\/deviceaudienceselector","navigatorTitle":[{"text":"DeviceAudienceSelector","kind":"identifier"}],"title":"DeviceAudienceSelector","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeviceAudienceSelector","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"JSONPredicate","op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONPredicate\/title"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONPredicate\/fragments","value":[{"kind":"identifier","text":"JSONPredicate"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONPredicate\/navigatorTitle","value":[{"text":"JSONPredicate","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}