{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher\/isEqual(_:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"other"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"platforms":["Mac Catalyst"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"isEqual(_:)","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"AirshipCore"}],"symbolKind":"method","externalID":"c:@M@AirshipCore@objc(cs)JSONValueMatcher(im)isEqual:","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}]},"variants":[{"paths":["\/documentation\/airshipcore\/jsonvaluematcher\/isequal(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airshipcore\/jsonvaluematcher\/isequal(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","url":"\/documentation\/airshipcore","abstract":[],"kind":"symbol","role":"collection","title":"AirshipCore"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONValueMatcher":{"abstract":[{"type":"text","text":"A "},{"code":"JSONValueMatcher","type":"codeVoice"},{"type":"text","text":" is used to match a JSON value against a set of constraints."}],"type":"topic","title":"JSONValueMatcher","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher","kind":"symbol","role":"symbol","url":"\/documentation\/airshipcore\/jsonvaluematcher","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JSONValueMatcher","kind":"identifier"}],"navigatorTitle":[{"text":"JSONValueMatcher","kind":"identifier"}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONValueMatcher/isEqual(_:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher\/isEqual(_:)","title":"isEqual(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/airshipcore\/jsonvaluematcher\/isequal(_:)","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"isEqual:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"other","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"JSONValueMatcher","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueMatcher\/title","op":"replace"},{"value":[{"kind":"identifier","text":"JSONValueMatcher"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueMatcher\/fragments","op":"replace"},{"value":[{"text":"JSONValueMatcher","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueMatcher\/navigatorTitle","op":"replace"},{"value":"isEqual:","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueMatcher~1isEqual(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueMatcher~1isEqual(_:)\/fragments","op":"replace"}]}]}