{"variants":[{"paths":["\/documentation\/airshipcore\/jsonvaluematcher\/matcherwherebooleanequals(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","metadata":{"externalID":"s:11AirshipCore16JSONValueMatcherC25matcherWhereBooleanEqualsyACSbFZ","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"matcherWhereBooleanEquals","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"text":"JSONValueMatcher","kind":"typeIdentifier","preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONValueMatcher"}],"modules":[{"name":"AirshipCore"}],"title":"matcherWhereBooleanEquals(_:)","symbolKind":"method","roleHeading":"Type Method","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Creates a matcher for an exact boolean value.","type":"text"}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["Mac Catalyst"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"matcherWhereBooleanEquals"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"boolean"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONValueMatcher","kind":"typeIdentifier","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher","text":"JSONValueMatcher"}]}],"kind":"declarations"},{"parameters":[{"name":"boolean","content":[{"inlineContent":[{"text":"The exact boolean to match.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"text":"Return Value","anchor":"return-value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"A "},{"code":"JSONValueMatcher","type":"codeVoice"},{"type":"text","text":" for the specified condition."}],"type":"paragraph"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher\/matcherWhereBooleanEquals(_:)"},"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONValueMatcher":{"role":"symbol","url":"\/documentation\/airshipcore\/jsonvaluematcher","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSONValueMatcher"}],"abstract":[{"text":"A ","type":"text"},{"code":"JSONValueMatcher","type":"codeVoice"},{"text":" is used to match a JSON value against a set of constraints.","type":"text"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher","title":"JSONValueMatcher","navigatorTitle":[{"kind":"identifier","text":"JSONValueMatcher"}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONValueMatcher/matcherWhereBooleanEquals(_:)":{"role":"symbol","url":"\/documentation\/airshipcore\/jsonvaluematcher\/matcherwherebooleanequals(_:)","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"matcherWhereBooleanEquals","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"text":"JSONValueMatcher","kind":"typeIdentifier","preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONValueMatcher"}],"abstract":[{"text":"Creates a matcher for an exact boolean value.","type":"text"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher\/matcherWhereBooleanEquals(_:)","title":"matcherWhereBooleanEquals(_:)"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"kind":"symbol","role":"collection","title":"AirshipCore","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","url":"\/documentation\/airshipcore","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"JSONValueMatcher","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueMatcher\/title","op":"replace"},{"value":[{"kind":"identifier","text":"JSONValueMatcher"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueMatcher\/fragments","op":"replace"},{"value":[{"text":"JSONValueMatcher","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueMatcher\/navigatorTitle","op":"replace"}]}]}