{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher\/matcherWhereNumberEquals(_:)","interfaceLanguage":"swift"},"abstract":[{"text":"Creates a matcher for an exact number value.","type":"text"}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["Mac Catalyst"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"matcherWhereNumberEquals","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"number","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSNumber","preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher","text":"JSONValueMatcher","preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONValueMatcher","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The exact number to match.","type":"text"}]}],"name":"number"}]},{"kind":"content","content":[{"text":"Return Value","type":"heading","level":2,"anchor":"return-value"},{"inlineContent":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"JSONValueMatcher"},{"text":" for the specified condition.","type":"text"}],"type":"paragraph"}]}],"metadata":{"externalID":"s:11AirshipCore16JSONValueMatcherC24matcherWhereNumberEqualsyACSo8NSNumberCFZ","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"matcherWhereNumberEquals","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSNumber","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber"},{"text":") -> ","kind":"text"},{"text":"JSONValueMatcher","kind":"typeIdentifier","preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONValueMatcher"}],"modules":[{"name":"AirshipCore"}],"roleHeading":"Type Method","role":"symbol","symbolKind":"method","title":"matcherWhereNumberEquals(_:)"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/jsonvaluematcher\/matcherwherenumberequals(_:)"]}],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher"]]},"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONValueMatcher":{"abstract":[{"type":"text","text":"A "},{"code":"JSONValueMatcher","type":"codeVoice"},{"type":"text","text":" is used to match a JSON value against a set of constraints."}],"type":"topic","title":"JSONValueMatcher","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher","kind":"symbol","role":"symbol","url":"\/documentation\/airshipcore\/jsonvaluematcher","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JSONValueMatcher","kind":"identifier"}],"navigatorTitle":[{"text":"JSONValueMatcher","kind":"identifier"}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONValueMatcher/matcherWhereNumberEquals(_:)":{"url":"\/documentation\/airshipcore\/jsonvaluematcher\/matcherwherenumberequals(_:)","kind":"symbol","title":"matcherWhereNumberEquals(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"matcherWhereNumberEquals"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONValueMatcher","text":"JSONValueMatcher"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher\/matcherWhereNumberEquals(_:)","abstract":[{"type":"text","text":"Creates a matcher for an exact number value."}],"role":"symbol","type":"topic"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","url":"\/documentation\/airshipcore","abstract":[],"kind":"symbol","role":"collection","title":"AirshipCore"}},"variantOverrides":[{"patch":[{"value":"JSONValueMatcher","op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueMatcher\/title"},{"value":[{"text":"JSONValueMatcher","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueMatcher\/fragments"},{"value":[{"text":"JSONValueMatcher","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueMatcher\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}