{"variants":[{"paths":["\/documentation\/airshipcore\/jsonpredicate\/encode(to:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONPredicate\/encode(to:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["Mac Catalyst"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encode","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"encoder","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Encoder","kind":"typeIdentifier","preciseIdentifier":"s:s7EncoderP"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"name":"Note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"For internal use only. :nodoc:"}]}],"style":"note"}]}],"kind":"symbol","metadata":{"externalID":"s:11AirshipCore13JSONPredicateC6encode2toys7Encoder_p_tKF","roleHeading":"Instance Method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s7EncoderP","text":"Encoder"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"title":"encode(to:)","modules":[{"name":"AirshipCore"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONPredicate"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Encodable.encode(to:)"},{"type":"text","text":"."}],"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONPredicate/encode(to:)":{"url":"\/documentation\/airshipcore\/jsonpredicate\/encode(to:)","role":"symbol","title":"encode(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"preciseIdentifier":"s:s7EncoderP","kind":"typeIdentifier","text":"Encoder"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONPredicate\/encode(to:)","type":"topic","abstract":[]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"kind":"symbol","url":"\/documentation\/airshipcore","type":"topic","abstract":[],"title":"AirshipCore","role":"collection","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONPredicate":{"title":"JSONPredicate","navigatorTitle":[{"kind":"identifier","text":"JSONPredicate"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONPredicate","abstract":[{"type":"text","text":"Defines a predicate for evaluating a JSON payload."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSONPredicate"}],"type":"topic","url":"\/documentation\/airshipcore\/jsonpredicate"}},"variantOverrides":[{"patch":[{"value":"JSONPredicate","op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONPredicate\/title"},{"value":[{"kind":"identifier","text":"JSONPredicate"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONPredicate\/fragments"},{"value":[{"text":"JSONPredicate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONPredicate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}