{"sections":[],"abstract":[{"type":"text","text":"Evaluates the given object against the predicate."}],"metadata":{"externalID":"s:11AirshipCore13JSONPredicateC8evaluateySbypSgF","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"evaluate"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"platforms":[{"unavailable":false,"deprecated":true,"beta":false,"message":"Use evaluate(json:) instead"}],"title":"evaluate(_:)","role":"symbol","modules":[{"name":"AirshipCore"}],"roleHeading":"Instance Method","symbolKind":"method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use evaluate(json:) instead"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONPredicate"]]},"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONPredicate\/evaluate(_:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/airshipcore\/jsonpredicate\/evaluate(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"evaluate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["Mac Catalyst"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"object","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The object to evaluate."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"code":"true","type":"codeVoice"},{"text":" if the predicate matches the object; otherwise, ","type":"text"},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}]}]}],"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONPredicate/evaluate(_:)":{"deprecated":true,"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONPredicate\/evaluate(_:)","url":"\/documentation\/airshipcore\/jsonpredicate\/evaluate(_:)","abstract":[{"type":"text","text":"Evaluates the given object against the predicate."}],"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"evaluate"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"evaluate(_:)"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONPredicate":{"type":"topic","abstract":[{"type":"text","text":"Defines a predicate for evaluating a JSON payload."}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONPredicate","title":"JSONPredicate","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JSONPredicate","kind":"identifier"}],"role":"symbol","url":"\/documentation\/airshipcore\/jsonpredicate","kind":"symbol","navigatorTitle":[{"text":"JSONPredicate","kind":"identifier"}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"url":"\/documentation\/airshipcore","kind":"symbol","abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","title":"AirshipCore"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONPredicate\/title","value":"JSONPredicate","op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONPredicate\/fragments","value":[{"text":"JSONPredicate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONPredicate\/navigatorTitle","value":[{"kind":"identifier","text":"JSONPredicate"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}