{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/jsonpredicate\/init(jsonmatcher:)"]}],"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONPredicate\/init(jsonMatcher:)","interfaceLanguage":"swift"},"abstract":[{"text":"Creates a predicate from a ","type":"text"},{"code":"JSONMatcher","type":"codeVoice"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONPredicate"]]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"jsonMatcher"},{"kind":"text","text":" "},{"kind":"internalParam","text":"matcher"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONMatcher","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher","kind":"typeIdentifier","text":"JSONMatcher"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The ","type":"text"},{"code":"JSONMatcher","type":"codeVoice"},{"text":" to base the predicate on.","type":"text"}],"type":"paragraph"}],"name":"matcher"}]}],"metadata":{"modules":[{"name":"AirshipCore"}],"externalID":"s:11AirshipCore13JSONPredicateC11jsonMatcherAcA11JSONMatcherC_tcfc","roleHeading":"Initializer","role":"symbol","title":"init(jsonMatcher:)","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"jsonMatcher"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JSONMatcher","preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONMatcher"},{"kind":"text","text":")"}]},"sections":[],"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"abstract":[],"role":"collection","url":"\/documentation\/airshipcore","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","kind":"symbol","title":"AirshipCore"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONPredicate/init(jsonMatcher:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"jsonMatcher"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONMatcher","kind":"typeIdentifier","text":"JSONMatcher"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONPredicate\/init(jsonMatcher:)","role":"symbol","kind":"symbol","url":"\/documentation\/airshipcore\/jsonpredicate\/init(jsonmatcher:)","title":"init(jsonMatcher:)","abstract":[{"text":"Creates a predicate from a ","type":"text"},{"type":"codeVoice","code":"JSONMatcher"},{"text":".","type":"text"}],"type":"topic"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONMatcher":{"abstract":[{"text":"A matcher for evaluating a JSON payload against a set of criteria.","type":"text"}],"navigatorTitle":[{"text":"JSONMatcher","kind":"identifier"}],"type":"topic","title":"JSONMatcher","url":"\/documentation\/airshipcore\/jsonmatcher","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JSONMatcher","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONPredicate":{"kind":"symbol","title":"JSONPredicate","navigatorTitle":[{"text":"JSONPredicate","kind":"identifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONPredicate","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JSONPredicate","kind":"identifier"}],"role":"symbol","url":"\/documentation\/airshipcore\/jsonpredicate","abstract":[{"type":"text","text":"Defines a predicate for evaluating a JSON payload."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONMatcher\/title","value":"JSONMatcher"},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONMatcher\/fragments","value":[{"kind":"identifier","text":"JSONMatcher"}]},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONMatcher\/navigatorTitle","value":[{"kind":"identifier","text":"JSONMatcher"}]},{"value":"JSONPredicate","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONPredicate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"JSONPredicate"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONPredicate\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"JSONPredicate"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONPredicate\/navigatorTitle","op":"replace"}]}]}