{"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONPredicate"]]},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/jsonpredicate\/init(json:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["Mac Catalyst"],"tokens":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"json"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"}]}]},{"kind":"parameters","parameters":[{"name":"json","content":[{"inlineContent":[{"type":"text","text":"The JSON payload representing the predicate."}],"type":"paragraph"}]}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An error if the JSON is invalid or cannot be decoded."}]}],"name":"Throws","style":"note","type":"aside"}]}],"metadata":{"title":"init(json:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"json"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"}],"modules":[{"name":"AirshipCore"}],"symbolKind":"init","roleHeading":"Initializer","externalID":"s:11AirshipCore13JSONPredicateC4jsonACypSg_tKcfc"},"abstract":[{"type":"text","text":"Creates a new predicate from a JSON payload."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONPredicate\/init(json:)"},"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONPredicate/init(json:)":{"role":"symbol","abstract":[{"type":"text","text":"Creates a new predicate from a JSON payload."}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"json"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"}],"kind":"symbol","title":"init(json:)","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONPredicate\/init(json:)","type":"topic","url":"\/documentation\/airshipcore\/jsonpredicate\/init(json:)"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONPredicate":{"type":"topic","url":"\/documentation\/airshipcore\/jsonpredicate","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONPredicate","abstract":[{"type":"text","text":"Defines a predicate for evaluating a JSON payload."}],"title":"JSONPredicate","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JSONPredicate","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"JSONPredicate","kind":"identifier"}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"title":"AirshipCore","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/airshipcore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONPredicate\/title","op":"replace","value":"JSONPredicate"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONPredicate\/fragments","op":"replace","value":[{"kind":"identifier","text":"JSONPredicate"}]},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONPredicate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"JSONPredicate"}]}]}]}