{"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","metadata":{"roleHeading":"Framework","role":"collection","title":"AirshipAutomation","modules":[{"name":"AirshipAutomation"}],"externalID":"AirshipAutomation","symbolKind":"module"},"identifier":{"url":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation","interfaceLanguage":"swift"},"hierarchy":{"paths":[[]]},"topicSections":[{"generated":true,"title":"Classes","identifiers":["doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/AutomationSDKModule","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/CancelSchedulesAction","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/InAppAutomation","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/InAppAutomationThemeManager","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/InAppMessageNativeBridgeExtension","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/LandingPageAction","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/ScheduleAction"],"anchor":"Classes"},{"generated":true,"title":"Protocols","identifiers":["doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/AirshipCachedAssetsProtocol","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/CustomDisplayAdapter","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/FrequencyCheckerProtocol","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/InAppActionRunner","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/InAppMessageDisplayDelegate","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/InAppMessageSceneDelegate","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/InAppMessageViewDelegate","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/InAppMessagingProtocol","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/LegacyInAppMessagingProtocol"],"anchor":"Protocols"},{"generated":true,"title":"Structures","identifiers":["doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/AutomationAudience","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/AutomationCompoundAudience","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/AutomationDelay","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/AutomationSchedule","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/CompoundAutomationTrigger","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/DeferredAutomationData","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/DisplayAdapterArgs","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/EventAutomationTrigger","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/ExecutionWindow","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/InAppMessage","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/InAppMessageButtonInfo","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/InAppMessageColor","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/InAppMessageMediaInfo","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/InAppMessageTextInfo","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/InAppMessageTheme","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/LegacyInAppMessage"],"anchor":"Structures"},{"generated":true,"title":"Type Aliases","identifiers":["doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/MessageConvertor","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/MessageExtender","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/ScheduleExtender"],"anchor":"Type-Aliases"},{"generated":true,"title":"Enumerations","identifiers":["doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/AutomationAppState","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/AutomationTrigger","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/CompoundAutomationTriggerType","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/CustomDisplayAdapterType","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/CustomDisplayResolution","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/EventAutomationTriggerType","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/InAppAutomationUpdateStatus","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/InAppMessageButtonLayoutType","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/InAppMessageDisplayContent"],"anchor":"Enumerations"},{"generated":true,"title":"Extended Modules","identifiers":["doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/AirshipCore"],"anchor":"Extended-Modules"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipautomation"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airshipautomation"]}],"references":{"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/InAppMessageDisplayContent":{"kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/InAppMessageDisplayContent","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InAppMessageDisplayContent","kind":"identifier"}],"title":"InAppMessageDisplayContent","url":"\/documentation\/airshipautomation\/inappmessagedisplaycontent","role":"symbol","navigatorTitle":[{"text":"InAppMessageDisplayContent","kind":"identifier"}],"abstract":[{"text":"In-App message display content","type":"text"}],"type":"topic"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/MessageExtender":{"url":"\/documentation\/airshipautomation\/messageextender","title":"MessageExtender","navigatorTitle":[{"text":"MessageExtender","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageExtender","kind":"identifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/MessageExtender","role":"symbol"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/DeferredAutomationData":{"url":"\/documentation\/airshipautomation\/deferredautomationdata","abstract":[{"text":"NOTE: For internal use only. :nodoc:","type":"text"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DeferredAutomationData","kind":"identifier"}],"navigatorTitle":[{"text":"DeferredAutomationData","kind":"identifier"}],"type":"topic","kind":"symbol","title":"DeferredAutomationData","identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/DeferredAutomationData"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/CustomDisplayAdapter":{"title":"CustomDisplayAdapter","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomDisplayAdapter"}],"kind":"symbol","abstract":[{"text":"Custom display adapter","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"CustomDisplayAdapter"}],"url":"\/documentation\/airshipautomation\/customdisplayadapter","identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/CustomDisplayAdapter","role":"symbol"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/CompoundAutomationTriggerType":{"identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/CompoundAutomationTriggerType","title":"CompoundAutomationTriggerType","type":"topic","kind":"symbol","navigatorTitle":[{"text":"CompoundAutomationTriggerType","kind":"identifier"}],"url":"\/documentation\/airshipautomation\/compoundautomationtriggertype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CompoundAutomationTriggerType","kind":"identifier"}],"abstract":[],"role":"symbol"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/InAppMessageColor":{"kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/InAppMessageColor","type":"topic","url":"\/documentation\/airshipautomation\/inappmessagecolor","abstract":[{"type":"text","text":"In-App message color"}],"title":"InAppMessageColor","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"InAppMessageColor"}],"navigatorTitle":[{"kind":"identifier","text":"InAppMessageColor"}],"role":"symbol"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/InAppMessage":{"navigatorTitle":[{"kind":"identifier","text":"InAppMessage"}],"abstract":[{"text":"In-App Message","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"InAppMessage"}],"url":"\/documentation\/airshipautomation\/inappmessage","kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/InAppMessage","title":"InAppMessage","role":"symbol","type":"topic"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/CancelSchedulesAction":{"title":"CancelSchedulesAction","navigatorTitle":[{"text":"CancelSchedulesAction","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Action to cancel automation schedules.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CancelSchedulesAction","kind":"identifier"}],"url":"\/documentation\/airshipautomation\/cancelschedulesaction","identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/CancelSchedulesAction","type":"topic","role":"symbol"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/AutomationTrigger":{"title":"AutomationTrigger","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomationTrigger","kind":"identifier"}],"navigatorTitle":[{"text":"AutomationTrigger","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/AutomationTrigger","url":"\/documentation\/airshipautomation\/automationtrigger"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/AirshipAutomationVersionNumber":{"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/AirshipAutomationVersionNumber","abstract":[{"text":"Project version number for AirshipAutomation.","type":"text"}],"fragments":[{"text":"AirshipAutomationVersionNumber","kind":"identifier"}],"title":"AirshipAutomationVersionNumber","role":"symbol","kind":"symbol","url":"\/documentation\/airshipautomation\/airshipautomationversionnumber"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/CompoundAutomationTrigger":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CompoundAutomationTrigger"}],"url":"\/documentation\/airshipautomation\/compoundautomationtrigger","role":"symbol","abstract":[{"type":"text","text":"NOTE: For internal use only. :nodoc:"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CompoundAutomationTrigger"}],"title":"CompoundAutomationTrigger","identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/CompoundAutomationTrigger"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/InAppMessageDisplayDelegate":{"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/InAppMessageDisplayDelegate","url":"\/documentation\/airshipautomation\/inappmessagedisplaydelegate","abstract":[{"text":"Message display delegate","type":"text"}],"title":"InAppMessageDisplayDelegate","navigatorTitle":[{"text":"InAppMessageDisplayDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InAppMessageDisplayDelegate","kind":"identifier"}]},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/InAppMessageTextInfo":{"identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/InAppMessageTextInfo","title":"InAppMessageTextInfo","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"InAppMessage text info"}],"navigatorTitle":[{"text":"InAppMessageTextInfo","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InAppMessageTextInfo","kind":"identifier"}],"url":"\/documentation\/airshipautomation\/inappmessagetextinfo","type":"topic"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/InAppMessageSceneDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"InAppMessageSceneDelegate"}],"title":"InAppMessageSceneDelegate","navigatorTitle":[{"kind":"identifier","text":"InAppMessageSceneDelegate"}],"kind":"symbol","abstract":[{"text":"Scene delegate","type":"text"}],"url":"\/documentation\/airshipautomation\/inappmessagescenedelegate","type":"topic","role":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/InAppMessageSceneDelegate"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/LegacyInAppMessagingProtocol":{"type":"topic","url":"\/documentation\/airshipautomation\/legacyinappmessagingprotocol","kind":"symbol","title":"LegacyInAppMessagingProtocol","identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/LegacyInAppMessagingProtocol","abstract":[{"type":"text","text":"Legacy in-app messaging protocol"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LegacyInAppMessagingProtocol","kind":"identifier"}],"navigatorTitle":[{"text":"LegacyInAppMessagingProtocol","kind":"identifier"}],"role":"symbol"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/CustomDisplayResolution":{"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/CustomDisplayResolution","abstract":[{"text":"Resolution data","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomDisplayResolution","kind":"identifier"}],"url":"\/documentation\/airshipautomation\/customdisplayresolution","title":"CustomDisplayResolution","navigatorTitle":[{"text":"CustomDisplayResolution","kind":"identifier"}]},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/InAppMessageButtonLayoutType":{"identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/InAppMessageButtonLayoutType","title":"InAppMessageButtonLayoutType","abstract":[{"text":"Button layout type","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"InAppMessageButtonLayoutType"}],"url":"\/documentation\/airshipautomation\/inappmessagebuttonlayouttype","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"InAppMessageButtonLayoutType"}]},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/LegacyInAppMessage":{"url":"\/documentation\/airshipautomation\/legacyinappmessage","abstract":[{"type":"text","text":"Model object representing in-app message data."}],"navigatorTitle":[{"text":"LegacyInAppMessage","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/LegacyInAppMessage","title":"LegacyInAppMessage","kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LegacyInAppMessage","kind":"identifier"}]},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/InAppAutomation":{"abstract":[{"text":"Provides a control interface for creating, canceling and executing in-app automations.","type":"text"}],"kind":"symbol","url":"\/documentation\/airshipautomation\/inappautomation","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InAppAutomation","kind":"identifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/InAppAutomation","navigatorTitle":[{"text":"InAppAutomation","kind":"identifier"}],"title":"InAppAutomation","role":"symbol"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/AutomationSchedule":{"url":"\/documentation\/airshipautomation\/automationschedule","title":"AutomationSchedule","abstract":[{"text":"Automation schedule","type":"text"}],"identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/AutomationSchedule","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomationSchedule","kind":"identifier"}],"navigatorTitle":[{"text":"AutomationSchedule","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/AutomationDelay":{"abstract":[{"text":"Automation delay","type":"text"}],"identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/AutomationDelay","type":"topic","navigatorTitle":[{"text":"AutomationDelay","kind":"identifier"}],"title":"AutomationDelay","url":"\/documentation\/airshipautomation\/automationdelay","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomationDelay","kind":"identifier"}],"kind":"symbol"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/AutomationSDKModule":{"navigatorTitle":[{"text":"AutomationSDKModule","kind":"identifier"}],"role":"symbol","title":"AutomationSDKModule","abstract":[{"text":"NOTE: For internal use only. :nodoc:","type":"text"}],"identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/AutomationSDKModule","url":"\/documentation\/airshipautomation\/automationsdkmodule","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomationSDKModule","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/InAppActionRunner":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"InAppActionRunner"}],"navigatorTitle":[{"kind":"identifier","text":"InAppActionRunner"}],"role":"symbol","title":"InAppActionRunner","abstract":[{"type":"text","text":"Action runner for in-app experiences. Must be used in order to properly attribute custom events to the message."}],"type":"topic","kind":"symbol","url":"\/documentation\/airshipautomation\/inappactionrunner","identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/InAppActionRunner"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/AutomationAppState":{"kind":"symbol","url":"\/documentation\/airshipautomation\/automationappstate","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomationAppState"}],"abstract":[{"type":"text","text":"Automation app state"}],"navigatorTitle":[{"kind":"identifier","text":"AutomationAppState"}],"title":"AutomationAppState","identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/AutomationAppState","type":"topic","role":"symbol"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/AutomationCompoundAudience":{"url":"\/documentation\/airshipautomation\/automationcompoundaudience","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutomationCompoundAudience","kind":"identifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/AutomationCompoundAudience","kind":"symbol","type":"topic","abstract":[{"text":"Automation compound audience","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"AutomationCompoundAudience","kind":"identifier"}],"title":"AutomationCompoundAudience"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation":{"type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/airshipautomation","title":"AirshipAutomation","identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation","role":"collection"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/InAppMessageMediaInfo":{"navigatorTitle":[{"text":"InAppMessageMediaInfo","kind":"identifier"}],"abstract":[{"type":"text","text":"Media info"}],"type":"topic","title":"InAppMessageMediaInfo","identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/InAppMessageMediaInfo","kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InAppMessageMediaInfo","kind":"identifier"}],"url":"\/documentation\/airshipautomation\/inappmessagemediainfo"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/InAppAutomationUpdateStatus":{"title":"InAppAutomationUpdateStatus","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/InAppAutomationUpdateStatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InAppAutomationUpdateStatus","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"InApp automation status. Possible values are upToDate, stale and outOfDate.","type":"text"}],"navigatorTitle":[{"text":"InAppAutomationUpdateStatus","kind":"identifier"}],"url":"\/documentation\/airshipautomation\/inappautomationupdatestatus"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/InAppAutomationThemeManager":{"role":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/InAppAutomationThemeManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"InAppAutomationThemeManager"}],"title":"InAppAutomationThemeManager","navigatorTitle":[{"kind":"identifier","text":"InAppAutomationThemeManager"}],"abstract":[{"type":"text","text":"Theme manager for in-app messages."}],"type":"topic","url":"\/documentation\/airshipautomation\/inappautomationthememanager","kind":"symbol"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/InAppMessageViewDelegate":{"navigatorTitle":[{"text":"InAppMessageViewDelegate","kind":"identifier"}],"url":"\/documentation\/airshipautomation\/inappmessageviewdelegate","title":"InAppMessageViewDelegate","identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/InAppMessageViewDelegate","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InAppMessageViewDelegate","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Delegate for receiving callback pertaining to in-app message lifecycle state"}]},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/InAppMessageNativeBridgeExtension":{"kind":"symbol","abstract":[{"type":"text","text":"Airship native bridge extension for an InAppMessage"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InAppMessageNativeBridgeExtension","kind":"identifier"}],"url":"\/documentation\/airshipautomation\/inappmessagenativebridgeextension","identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/InAppMessageNativeBridgeExtension","title":"InAppMessageNativeBridgeExtension","role":"symbol","navigatorTitle":[{"text":"InAppMessageNativeBridgeExtension","kind":"identifier"}],"type":"topic"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/MessageConvertor":{"title":"MessageConvertor","navigatorTitle":[{"kind":"identifier","text":"MessageConvertor"}],"role":"symbol","url":"\/documentation\/airshipautomation\/messageconvertor","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/MessageConvertor","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageConvertor"}],"kind":"symbol"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/FrequencyCheckerProtocol":{"navigatorTitle":[{"kind":"identifier","text":"FrequencyCheckerProtocol"}],"url":"\/documentation\/airshipautomation\/frequencycheckerprotocol","identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/FrequencyCheckerProtocol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FrequencyCheckerProtocol"}],"type":"topic","kind":"symbol","title":"FrequencyCheckerProtocol","abstract":[]},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/InAppMessagingProtocol":{"abstract":[{"type":"text","text":"In-app messaging"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InAppMessagingProtocol","kind":"identifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/InAppMessagingProtocol","type":"topic","url":"\/documentation\/airshipautomation\/inappmessagingprotocol","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"InAppMessagingProtocol","kind":"identifier"}],"title":"InAppMessagingProtocol"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/EventAutomationTriggerType":{"title":"EventAutomationTriggerType","kind":"symbol","role":"symbol","url":"\/documentation\/airshipautomation\/eventautomationtriggertype","abstract":[{"text":"Automation trigger types","type":"text"}],"identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/EventAutomationTriggerType","navigatorTitle":[{"text":"EventAutomationTriggerType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EventAutomationTriggerType","kind":"identifier"}],"type":"topic"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/ScheduleAction":{"navigatorTitle":[{"kind":"identifier","text":"ScheduleAction"}],"abstract":[{"type":"text","text":"Action to schedule other actions."}],"url":"\/documentation\/airshipautomation\/scheduleaction","kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/ScheduleAction","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScheduleAction"}],"role":"symbol","type":"topic","title":"ScheduleAction"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/ExecutionWindow":{"type":"topic","url":"\/documentation\/airshipautomation\/executionwindow","title":"ExecutionWindow","abstract":[],"navigatorTitle":[{"text":"ExecutionWindow","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/ExecutionWindow","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ExecutionWindow","kind":"identifier"}],"role":"symbol"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/DisplayAdapterArgs":{"title":"DisplayAdapterArgs","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DisplayAdapterArgs","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/DisplayAdapterArgs","url":"\/documentation\/airshipautomation\/displayadapterargs","navigatorTitle":[{"text":"DisplayAdapterArgs","kind":"identifier"}],"type":"topic","abstract":[{"text":"Display adapter args","type":"text"}]},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/AirshipCachedAssetsProtocol":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirshipCachedAssetsProtocol","kind":"identifier"}],"url":"\/documentation\/airshipautomation\/airshipcachedassetsprotocol","navigatorTitle":[{"text":"AirshipCachedAssetsProtocol","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Convenience struct representing an assets directory containing asset files"},{"type":"text","text":" "},{"type":"text","text":"with filenames derived from their remote URL using sha256."}],"identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/AirshipCachedAssetsProtocol","title":"AirshipCachedAssetsProtocol"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/ScheduleExtender":{"title":"ScheduleExtender","type":"topic","role":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/ScheduleExtender","url":"\/documentation\/airshipautomation\/scheduleextender","navigatorTitle":[{"kind":"identifier","text":"ScheduleExtender"}],"abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScheduleExtender"}]},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/InAppMessageTheme":{"navigatorTitle":[{"kind":"identifier","text":"InAppMessageTheme"}],"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/InAppMessageTheme","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"InAppMessageTheme"}],"url":"\/documentation\/airshipautomation\/inappmessagetheme","kind":"symbol","abstract":[{"type":"text","text":"In-app message themes"}],"role":"symbol","title":"InAppMessageTheme"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/AirshipCore":{"identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/AirshipCore","title":"AirshipCore","url":"\/documentation\/airshipautomation\/airshipcore","type":"topic","kind":"symbol","abstract":[],"role":"collection"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/LandingPageAction":{"identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/LandingPageAction","title":"LandingPageAction","role":"symbol","navigatorTitle":[{"text":"LandingPageAction","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LandingPageAction","kind":"identifier"}],"url":"\/documentation\/airshipautomation\/landingpageaction","kind":"symbol","abstract":[{"type":"text","text":"Landing page action"}]},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/EventAutomationTrigger":{"kind":"symbol","title":"EventAutomationTrigger","navigatorTitle":[{"kind":"identifier","text":"EventAutomationTrigger"}],"abstract":[{"type":"text","text":"Model for defining when an automation is triggered."}],"url":"\/documentation\/airshipautomation\/eventautomationtrigger","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/EventAutomationTrigger","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"EventAutomationTrigger"}]},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/AutomationAudience":{"url":"\/documentation\/airshipautomation\/automationaudience","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomationAudience"}],"navigatorTitle":[{"kind":"identifier","text":"AutomationAudience"}],"type":"topic","role":"symbol","title":"AutomationAudience","abstract":[{"text":"Automation device audience","type":"text"}],"identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/AutomationAudience"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/InAppMessageButtonInfo":{"abstract":[{"type":"text","text":"Button info"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"InAppMessageButtonInfo","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/airshipautomation\/inappmessagebuttoninfo","title":"InAppMessageButtonInfo","type":"topic","navigatorTitle":[{"text":"InAppMessageButtonInfo","kind":"identifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/InAppMessageButtonInfo"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/CustomDisplayAdapterType":{"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/CustomDisplayAdapterType","role":"symbol","title":"CustomDisplayAdapterType","abstract":[{"type":"text","text":"Custom display adapter types"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CustomDisplayAdapterType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomDisplayAdapterType"}],"url":"\/documentation\/airshipautomation\/customdisplayadaptertype"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/AirshipAutomationVersionString":{"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/AirshipAutomationVersionString","title":"AirshipAutomationVersionString","url":"\/documentation\/airshipautomation\/airshipautomationversionstring","fragments":[{"kind":"identifier","text":"AirshipAutomationVersionString"}],"abstract":[{"type":"text","text":"Project version string for AirshipAutomation."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"title":"Classes","anchor":"Classes","generated":true,"identifiers":["doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/AutomationSDKModule"]},{"title":"Variables","anchor":"Variables","generated":true,"identifiers":["doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/AirshipAutomationVersionNumber","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/AirshipAutomationVersionString"]}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":"UAAutomationSDKModule","path":"\/references\/doc:~1~1com.urbanairship.AirshipAutomation~1documentation~1AirshipAutomation~1AutomationSDKModule\/title","op":"replace"},{"value":[{"kind":"identifier","text":"UAAutomationSDKModule"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipAutomation~1documentation~1AirshipAutomation~1AutomationSDKModule\/fragments","op":"replace"},{"value":[{"text":"UAAutomationSDKModule","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipAutomation~1documentation~1AirshipAutomation~1AutomationSDKModule\/navigatorTitle","op":"replace"}]}]}