{"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter"]]},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreferenceCenterViewControllerFactory","kind":"identifier"}],"modules":[{"name":"AirshipPreferenceCenter"}],"externalID":"c:@M@AirshipPreferenceCenter@objc(cs)PreferenceCenterViewControllerFactory","navigatorTitle":[{"text":"PreferenceCenterViewControllerFactory","kind":"identifier"}],"roleHeading":"Class","role":"symbol","symbolKind":"class","title":"PreferenceCenterViewControllerFactory"},"abstract":[{"text":"View factories for Preference Center view controllers","type":"text"}],"topicSections":[{"generated":true,"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterViewControllerFactory\/makeViewController(preferenceCenterID:dismissAction:)","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterViewControllerFactory\/makeViewController(preferenceCenterID:preferenceCenterTheme:dismissAction:)","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterViewControllerFactory\/makeViewController(preferenceCenterID:preferenceCenterThemePlist:)","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterViewControllerFactory\/makeViewController(view:preferenceCenterTheme:dismissAction:)"]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.urbanairship.AirshipPreferenceCenter\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/com.urbanairship.AirshipPreferenceCenter\/objc(pl)NSObject","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/s7CVarArgP","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/s28CustomDebugStringConvertibleP","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/s23CustomStringConvertibleP","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/SQ","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreferenceCenterViewControllerFactory","kind":"identifier"}],"platforms":["Mac Catalyst"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterViewControllerFactory","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/airshippreferencecenter\/preferencecenterviewcontrollerfactory"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airshippreferencecenter\/preferencecenterviewcontrollerfactory"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterViewControllerFactory/makeViewController(view:preferenceCenterTheme:dismissAction:)":{"type":"topic","abstract":[{"text":"Makes a view controller for the given view  and theme.","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/airshippreferencecenter\/preferencecenterviewcontrollerfactory\/makeviewcontroller(view:preferencecentertheme:dismissaction:)","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterViewControllerFactory\/makeViewController(view:preferenceCenterTheme:dismissAction:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"view"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:23AirshipPreferenceCenter0bC4ViewV","text":"PreferenceCenterView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"preferenceCenterTheme"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:23AirshipPreferenceCenter0bC5ThemeV","text":"PreferenceCenterTheme"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"dismissAction"},{"kind":"text","text":": (@"},{"kind":"typeIdentifier","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" () -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"}],"title":"makeViewController(view:preferenceCenterTheme:dismissAction:)"},"doc://com.urbanairship.AirshipPreferenceCenter/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/objc(pl)NSObject"},"doc://com.urbanairship.AirshipPreferenceCenter/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterViewControllerFactory/init":{"type":"topic","abstract":[],"role":"symbol","kind":"symbol","url":"\/documentation\/airshippreferencecenter\/preferencecenterviewcontrollerfactory\/init","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterViewControllerFactory\/init","navigatorTitle":[{"kind":"identifier","text":"init"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"title":"init"},"doc://com.urbanairship.AirshipPreferenceCenter/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.urbanairship.AirshipPreferenceCenter/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/objc(cs)NSObject","type":"unresolvable"},"doc://com.urbanairship.AirshipPreferenceCenter/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterViewControllerFactory/makeViewController(preferenceCenterID:preferenceCenterThemePlist:)":{"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterViewControllerFactory\/makeViewController(preferenceCenterID:preferenceCenterThemePlist:)","abstract":[{"text":"Makes a view controller for the given Preference Center ID and theme.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"preferenceCenterID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"preferenceCenterThemePlist"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"}],"role":"symbol","title":"makeViewController(preferenceCenterID:preferenceCenterThemePlist:)","kind":"symbol","url":"\/documentation\/airshippreferencecenter\/preferencecenterviewcontrollerfactory\/makeviewcontroller(preferencecenterid:preferencecenterthemeplist:)","type":"topic"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterViewControllerFactory/makeViewController(preferenceCenterID:dismissAction:)":{"type":"topic","abstract":[{"text":"Makes a view controller for the given Preference Center ID.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterViewControllerFactory\/makeViewController(preferenceCenterID:dismissAction:)","url":"\/documentation\/airshippreferencecenter\/preferencecenterviewcontrollerfactory\/makeviewcontroller(preferencecenterid:dismissaction:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"makeViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"preferenceCenterID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dismissAction","kind":"externalParam"},{"text":": (() -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"}],"title":"makeViewController(preferenceCenterID:dismissAction:)"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterViewControllerFactory/makeViewController(preferenceCenterID:preferenceCenterTheme:dismissAction:)":{"type":"topic","abstract":[{"text":"Makes a view controller for the given Preference Center ID and theme.","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/airshippreferencecenter\/preferencecenterviewcontrollerfactory\/makeviewcontroller(preferencecenterid:preferencecentertheme:dismissaction:)","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterViewControllerFactory\/makeViewController(preferenceCenterID:preferenceCenterTheme:dismissAction:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"preferenceCenterID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"preferenceCenterTheme"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:23AirshipPreferenceCenter0bC5ThemeV","text":"PreferenceCenterTheme"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"dismissAction"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"}],"title":"makeViewController(preferenceCenterID:preferenceCenterTheme:dismissAction:)"},"doc://com.urbanairship.AirshipPreferenceCenter/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/SH","type":"unresolvable"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterViewControllerFactory":{"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterViewControllerFactory","abstract":[{"text":"View factories for Preference Center view controllers","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreferenceCenterViewControllerFactory"}],"role":"symbol","title":"PreferenceCenterViewControllerFactory","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PreferenceCenterViewControllerFactory"}],"type":"topic","url":"\/documentation\/airshippreferencecenter\/preferencecenterviewcontrollerfactory"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter":{"abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter","kind":"symbol","title":"AirshipPreferenceCenter","url":"\/documentation\/airshippreferencecenter"},"doc://com.urbanairship.AirshipPreferenceCenter/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"PreferenceCenterViewControllerFactory"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PreferenceCenterViewControllerFactory"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"PreferenceCenterViewControllerFactory","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterViewControllerFactory\/init"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.urbanairship.AirshipPreferenceCenter\/objc(cs)NSObject"],"title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["Mac Catalyst"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreferenceCenterViewControllerFactory","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"}},{"value":"PreferenceCenterViewControllerFactory","path":"\/references\/doc:~1~1com.urbanairship.AirshipPreferenceCenter~1documentation~1AirshipPreferenceCenter~1PreferenceCenterViewControllerFactory\/title","op":"replace"},{"value":[{"text":"PreferenceCenterViewControllerFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipPreferenceCenter~1documentation~1AirshipPreferenceCenter~1PreferenceCenterViewControllerFactory\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"PreferenceCenterViewControllerFactory"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipPreferenceCenter~1documentation~1AirshipPreferenceCenter~1PreferenceCenterViewControllerFactory\/navigatorTitle","op":"replace"}]}]}