{"metadata":{"roleHeading":"Type Method","externalID":"s:23AirshipPreferenceCenter0bC21ViewControllerFactoryC04makedE0010preferenceC2ID0hC5Theme13dismissActionSo06UIViewE0CSS_AA0bcJ0VSgyyYbcSgtFZ","role":"symbol","symbolKind":"method","modules":[{"name":"AirshipPreferenceCenter"}],"title":"makeViewController(preferenceCenterID:preferenceCenterTheme:dismissAction:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"makeViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"preferenceCenterID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"preferenceCenterTheme","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PreferenceCenterTheme","kind":"typeIdentifier","preciseIdentifier":"s:23AirshipPreferenceCenter0bC5ThemeV"},{"text":"?, ","kind":"text"},{"text":"dismissAction","kind":"externalParam"},{"text":": (() -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?) -> ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/airshippreferencecenter\/preferencecenterviewcontrollerfactory\/makeviewcontroller(preferencecenterid:preferencecentertheme:dismissaction:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterViewControllerFactory\/makeViewController(preferenceCenterID:preferenceCenterTheme:dismissAction:)"},"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterViewControllerFactory"]]},"abstract":[{"type":"text","text":"Makes a view controller for the given Preference Center ID and theme."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"makeViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"preferenceCenterID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"preferenceCenterTheme","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PreferenceCenterTheme","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterTheme","preciseIdentifier":"s:23AirshipPreferenceCenter0bC5ThemeV","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"dismissAction","kind":"externalParam"},{"text":": (() -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")? = nil) -> ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"}],"platforms":["Mac Catalyst"]}],"kind":"declarations"},{"parameters":[{"name":"preferenceCenterID","content":[{"type":"paragraph","inlineContent":[{"text":"The preferenceCenterID.","type":"text"}]}]},{"name":"preferenceCenterTheme","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The theme."}]}]},{"name":"dismissAction","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Optional action to dismiss the view controller."}]}]}],"kind":"parameters"},{"content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"A view controller.","type":"text"}]}],"kind":"content"}],"references":{"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterViewControllerFactory/makeViewController(preferenceCenterID:preferenceCenterTheme:dismissAction:)":{"abstract":[{"type":"text","text":"Makes a view controller for the given Preference Center ID and theme."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"preferenceCenterID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"preferenceCenterTheme"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:23AirshipPreferenceCenter0bC5ThemeV","text":"PreferenceCenterTheme"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"dismissAction"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"}],"role":"symbol","title":"makeViewController(preferenceCenterID:preferenceCenterTheme:dismissAction:)","url":"\/documentation\/airshippreferencecenter\/preferencecenterviewcontrollerfactory\/makeviewcontroller(preferencecenterid:preferencecentertheme:dismissaction:)","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterViewControllerFactory\/makeViewController(preferenceCenterID:preferenceCenterTheme:dismissAction:)"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterTheme":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PreferenceCenterTheme"}],"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreferenceCenterTheme"}],"type":"topic","url":"\/documentation\/airshippreferencecenter\/preferencecentertheme","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterTheme","abstract":[{"type":"text","text":"Preference Center theme"}],"title":"PreferenceCenterTheme"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterViewControllerFactory":{"navigatorTitle":[{"kind":"identifier","text":"PreferenceCenterViewControllerFactory"}],"kind":"symbol","title":"PreferenceCenterViewControllerFactory","type":"topic","abstract":[{"text":"View factories for Preference Center view controllers","type":"text"}],"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterViewControllerFactory","url":"\/documentation\/airshippreferencecenter\/preferencecenterviewcontrollerfactory","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreferenceCenterViewControllerFactory"}]},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter":{"abstract":[],"url":"\/documentation\/airshippreferencecenter","kind":"symbol","type":"topic","role":"collection","title":"AirshipPreferenceCenter","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.urbanairship.AirshipPreferenceCenter~1documentation~1AirshipPreferenceCenter~1PreferenceCenterViewControllerFactory\/title","op":"replace","value":"PreferenceCenterViewControllerFactory"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipPreferenceCenter~1documentation~1AirshipPreferenceCenter~1PreferenceCenterViewControllerFactory\/fragments","op":"replace","value":[{"text":"PreferenceCenterViewControllerFactory","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipPreferenceCenter~1documentation~1AirshipPreferenceCenter~1PreferenceCenterViewControllerFactory\/navigatorTitle","op":"replace","value":[{"text":"PreferenceCenterViewControllerFactory","kind":"identifier"}]}]}]}