{"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"components","kind":"identifier"},{"text":": [","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirshipComponent","preciseIdentifier":"s:11AirshipCore0A9ComponentP","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"platforms":["Mac Catalyst"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/AutomationSDKModule"]]},"identifier":{"url":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/AutomationSDKModule\/components","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipautomation\/automationsdkmodule\/components"]}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"AirshipSDKModule.components","type":"codeVoice"},{"text":".","type":"text"}],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"AirshipAutomation"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"components"},{"kind":"text","text":": ["},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"AirshipComponent","preciseIdentifier":"s:11AirshipCore0A9ComponentP"},{"kind":"text","text":"]"}],"role":"symbol","symbolKind":"property","externalID":"s:17AirshipAutomation0B9SDKModuleC10componentsSay0A4Core0A9Component_pGvp","title":"components"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/AutomationSDKModule/components":{"identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/AutomationSDKModule\/components","url":"\/documentation\/airshipautomation\/automationsdkmodule\/components","kind":"symbol","title":"components","abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"components"},{"kind":"text","text":": ["},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"AirshipComponent","preciseIdentifier":"s:11AirshipCore0A9ComponentP"},{"kind":"text","text":"]"}]},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation":{"url":"\/documentation\/airshipautomation","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation","title":"AirshipAutomation","kind":"symbol","abstract":[],"role":"collection"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/AutomationSDKModule":{"identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/AutomationSDKModule","url":"\/documentation\/airshipautomation\/automationsdkmodule","kind":"symbol","title":"AutomationSDKModule","abstract":[{"text":"NOTE: For internal use only. :nodoc:","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomationSDKModule"}],"navigatorTitle":[{"kind":"identifier","text":"AutomationSDKModule"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipAutomation~1documentation~1AirshipAutomation~1AutomationSDKModule\/title","value":"UAAutomationSDKModule"},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipAutomation~1documentation~1AirshipAutomation~1AutomationSDKModule\/fragments","value":[{"kind":"identifier","text":"UAAutomationSDKModule"}]},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipAutomation~1documentation~1AirshipAutomation~1AutomationSDKModule\/navigatorTitle","value":[{"text":"UAAutomationSDKModule","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}