{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/AutomationSDKModule\/load(_:)"},"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"AirshipSDKModule.load(_:)","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"load"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"args"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11AirshipCore24AirshiopModuleLoaderArgsV","kind":"typeIdentifier","text":"AirshiopModuleLoaderArgs"},{"kind":"text","text":") -> ("},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"preciseIdentifier":"s:11AirshipCore0A9SDKModuleP","kind":"typeIdentifier","text":"AirshipSDKModule"},{"kind":"text","text":")?"}],"platforms":["Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"AirshipAutomation"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"load","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AirshiopModuleLoaderArgs","preciseIdentifier":"s:11AirshipCore24AirshiopModuleLoaderArgsV","kind":"typeIdentifier"},{"text":") -> (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirshipSDKModule","preciseIdentifier":"s:11AirshipCore0A9SDKModuleP","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"role":"symbol","symbolKind":"method","roleHeading":"Type Method","title":"load(_:)","externalID":"s:17AirshipAutomation0B9SDKModuleC4loady0A4Core0aC0_pSgAE24AirshiopModuleLoaderArgsVFZ"},"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation","doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/AutomationSDKModule"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipautomation\/automationsdkmodule\/load(_:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/AutomationSDKModule/load(_:)":{"kind":"symbol","url":"\/documentation\/airshipautomation\/automationsdkmodule\/load(_:)","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"load","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AirshiopModuleLoaderArgs","kind":"typeIdentifier","preciseIdentifier":"s:11AirshipCore24AirshiopModuleLoaderArgsV"},{"text":") -> (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirshipSDKModule","kind":"typeIdentifier","preciseIdentifier":"s:11AirshipCore0A9SDKModuleP"},{"text":")?","kind":"text"}],"identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/AutomationSDKModule\/load(_:)","title":"load(_:)","type":"topic","role":"symbol"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation":{"abstract":[],"url":"\/documentation\/airshipautomation","title":"AirshipAutomation","identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation","role":"collection","type":"topic","kind":"symbol"},"doc://com.urbanairship.AirshipAutomation/documentation/AirshipAutomation/AutomationSDKModule":{"url":"\/documentation\/airshipautomation\/automationsdkmodule","identifier":"doc:\/\/com.urbanairship.AirshipAutomation\/documentation\/AirshipAutomation\/AutomationSDKModule","navigatorTitle":[{"kind":"identifier","text":"AutomationSDKModule"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutomationSDKModule"}],"role":"symbol","type":"topic","title":"AutomationSDKModule","kind":"symbol","abstract":[{"type":"text","text":"NOTE: For internal use only. :nodoc:"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.urbanairship.AirshipAutomation~1documentation~1AirshipAutomation~1AutomationSDKModule\/title","op":"replace","value":"UAAutomationSDKModule"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipAutomation~1documentation~1AirshipAutomation~1AutomationSDKModule\/fragments","op":"replace","value":[{"text":"UAAutomationSDKModule","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipAutomation~1documentation~1AirshipAutomation~1AutomationSDKModule\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UAAutomationSDKModule"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}