{"variants":[{"paths":["\/documentation\/airshipcore\/airshipjsonutils\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils"]]},"kind":"symbol","metadata":{"symbolKind":"method","modules":[{"name":"AirshipCore"}],"externalID":"c:@M@AirshipCore@objc(cs)AirshipJSONUtils(im)init","roleHeading":"Instance Method","title":"init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol"},"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils\/init","interfaceLanguage":"occ"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/AirshipJSONUtils/init":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils\/init","abstract":[],"url":"\/documentation\/airshipcore\/airshipjsonutils\/init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"title":"init","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/AirshipJSONUtils":{"role":"symbol","url":"\/documentation\/airshipcore\/airshipjsonutils","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AirshipJSONUtils"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils","title":"AirshipJSONUtils","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AirshipJSONUtils"}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"title":"AirshipCore","kind":"symbol","url":"\/documentation\/airshipcore","role":"collection","abstract":[],"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1AirshipJSONUtils\/title","value":"AirshipJSONUtils","op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1AirshipJSONUtils\/fragments","value":[{"text":"AirshipJSONUtils","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1AirshipJSONUtils\/navigatorTitle","value":[{"kind":"identifier","text":"AirshipJSONUtils"}],"op":"replace"}]}]}