{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils"]]},"variants":[{"paths":["\/documentation\/airshipcore\/airshipjsonutils\/json(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"metadata":{"roleHeading":"Type Method","modules":[{"name":"AirshipCore"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"json","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?","kind":"text"}],"title":"json(_:)","symbolKind":"method","role":"symbol","externalID":"s:11AirshipCore0A9JSONUtilsC4jsonyypSg10Foundation4DataVSgFZ"},"kind":"symbol","identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils\/json(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"json"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"languages":["swift"]}]}],"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/AirshipJSONUtils":{"title":"AirshipJSONUtils","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"AirshipJSONUtils","kind":"identifier"}],"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirshipJSONUtils","kind":"identifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils","type":"topic","url":"\/documentation\/airshipcore\/airshipjsonutils"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/AirshipJSONUtils/json(_:)":{"type":"topic","url":"\/documentation\/airshipcore\/airshipjsonutils\/json(_:)","role":"symbol","abstract":[],"kind":"symbol","title":"json(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"json"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils\/json(_:)"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"kind":"symbol","title":"AirshipCore","url":"\/documentation\/airshipcore","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore"}},"variantOverrides":[{"patch":[{"value":"AirshipJSONUtils","op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1AirshipJSONUtils\/title"},{"value":[{"text":"AirshipJSONUtils","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1AirshipJSONUtils\/fragments"},{"value":[{"kind":"identifier","text":"AirshipJSONUtils"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1AirshipJSONUtils\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}