{"sections":[],"variants":[{"paths":["\/documentation\/airshipcore\/airshipjsonutils\/object(_:options:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils\/object(_:options:)"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"object(_:options:)","role":"symbol","externalID":"s:11AirshipCore0A9JSONUtilsC6object_7optionsypSS_So20NSJSONReadingOptionsVtKFZ","symbolKind":"method","modules":[{"name":"AirshipCore"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"object","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSJSONSerialization","text":"JSONSerialization","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSJSONReadingOptions","text":"ReadingOptions","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Any","kind":"keyword"}],"roleHeading":"Type Method"},"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"object"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"string"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSJSONSerialization","text":"JSONSerialization"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSJSONReadingOptions","text":"ReadingOptions"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"keyword","text":"Any"}],"languages":["swift"]}]}],"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/AirshipJSONUtils":{"title":"AirshipJSONUtils","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils","abstract":[],"role":"symbol","navigatorTitle":[{"text":"AirshipJSONUtils","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirshipJSONUtils","kind":"identifier"}],"url":"\/documentation\/airshipcore\/airshipjsonutils","kind":"symbol"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/AirshipJSONUtils/object(_:options:)":{"abstract":[],"role":"symbol","type":"topic","title":"object(_:options:)","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"object"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSJSONSerialization","kind":"typeIdentifier","text":"JSONSerialization"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@NSJSONReadingOptions","kind":"typeIdentifier","text":"ReadingOptions"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"keyword","text":"Any"}],"url":"\/documentation\/airshipcore\/airshipjsonutils\/object(_:options:)","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils\/object(_:options:)"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"url":"\/documentation\/airshipcore","kind":"symbol","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","abstract":[],"title":"AirshipCore","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1AirshipJSONUtils\/title","value":"AirshipJSONUtils","op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1AirshipJSONUtils\/fragments","value":[{"kind":"identifier","text":"AirshipJSONUtils"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1AirshipJSONUtils\/navigatorTitle","value":[{"kind":"identifier","text":"AirshipJSONUtils"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}