{"abstract":[{"text":"Makes a message view controller with the given theme.","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"make"},{"kind":"text","text":"("},{"kind":"externalParam","text":"themePlist"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"predicate"},{"kind":"text","text":": ("},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"preciseIdentifier":"s:20AirshipMessageCenter0bC9PredicateP","kind":"typeIdentifier","text":"MessageCenterPredicate","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterPredicate"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterController","preciseIdentifier":"s:20AirshipMessageCenter0bC10ControllerC","text":"MessageCenterController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dismissAction"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")? = nil) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"}],"languages":["swift"],"platforms":["Mac Catalyst"]}],"kind":"declarations"},{"parameters":[{"name":"themePlist","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A path to a theme plist"}]}]},{"name":"predicate","content":[{"inlineContent":[{"text":"The message center predicate","type":"text"}],"type":"paragraph"}]},{"name":"controller","content":[{"inlineContent":[{"text":"The Message Center controller","type":"text"}],"type":"paragraph"}]},{"name":"dismissAction","content":[{"inlineContent":[{"type":"text","text":"Optional action to dismiss the view controller."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"inlineContent":[{"text":"A view controller.","type":"text"}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipmessagecenter\/messagecenterviewcontrollerfactory\/make(themeplist:predicate:controller:dismissaction:)"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterViewControllerFactory"]]},"metadata":{"modules":[{"name":"AirshipMessageCenter"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"make","kind":"identifier"},{"text":"(","kind":"text"},{"text":"themePlist","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"predicate","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageCenterPredicate","preciseIdentifier":"s:20AirshipMessageCenter0bC9PredicateP","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"controller","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessageCenterController","preciseIdentifier":"s:20AirshipMessageCenter0bC10ControllerC","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dismissAction","kind":"externalParam"},{"text":": (() -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?) ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"}],"title":"make(themePlist:predicate:controller:dismissAction:)","roleHeading":"Type Method","externalID":"s:20AirshipMessageCenter0bC21ViewControllerFactoryC4make10themePlist9predicate10controller13dismissActionSo06UIViewE0CSSSg_AA0bC9Predicate_pSgAA0bcE0CyyYbcSgtKFZ","role":"symbol","symbolKind":"method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterViewControllerFactory\/make(themePlist:predicate:controller:dismissAction:)"},"references":{"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterViewControllerFactory/make(themePlist:predicate:controller:dismissAction:)":{"url":"\/documentation\/airshipmessagecenter\/messagecenterviewcontrollerfactory\/make(themeplist:predicate:controller:dismissaction:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterViewControllerFactory\/make(themePlist:predicate:controller:dismissAction:)","title":"make(themePlist:predicate:controller:dismissAction:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"make"},{"kind":"text","text":"("},{"kind":"externalParam","text":"themePlist"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"predicate"},{"kind":"text","text":": ("},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"MessageCenterPredicate","preciseIdentifier":"s:20AirshipMessageCenter0bC9PredicateP"},{"kind":"text","text":")?, "},{"kind":"externalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageCenterController","preciseIdentifier":"s:20AirshipMessageCenter0bC10ControllerC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dismissAction"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"type":"topic","abstract":[{"type":"text","text":"Makes a message view controller with the given theme."}]},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter":{"kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter","title":"AirshipMessageCenter","url":"\/documentation\/airshipmessagecenter","abstract":[],"role":"collection","type":"topic"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterViewControllerFactory":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageCenterViewControllerFactory","kind":"identifier"}],"abstract":[{"type":"text","text":"View controller for Message Center view"}],"kind":"symbol","type":"topic","title":"MessageCenterViewControllerFactory","role":"symbol","navigatorTitle":[{"text":"MessageCenterViewControllerFactory","kind":"identifier"}],"url":"\/documentation\/airshipmessagecenter\/messagecenterviewcontrollerfactory","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterViewControllerFactory"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterPredicate":{"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageCenterPredicate"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCenterPredicate"}],"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterPredicate","url":"\/documentation\/airshipmessagecenter\/messagecenterpredicate","title":"MessageCenterPredicate"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterController":{"navigatorTitle":[{"text":"MessageCenterController","kind":"identifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterController","kind":"symbol","type":"topic","url":"\/documentation\/airshipmessagecenter\/messagecentercontroller","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageCenterController","kind":"identifier"}],"title":"MessageCenterController","abstract":[{"text":"Controller for the Message Center View.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterViewControllerFactory\/title","value":"MessageCenterViewControllerFactory","op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterViewControllerFactory\/fragments","value":[{"text":"MessageCenterViewControllerFactory","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterViewControllerFactory\/navigatorTitle","value":[{"text":"MessageCenterViewControllerFactory","kind":"identifier"}],"op":"replace"}]}]}