{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/jsonmatcher\/evaluate(json:)"]}],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"evaluate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"json","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AirshipJSON","kind":"typeIdentifier","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSON","preciseIdentifier":"s:11AirshipCore0A4JSONO"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"AirshipJSON"},{"text":" object to evaluate.","type":"text"}],"type":"paragraph"}],"name":"json"}],"kind":"parameters"},{"content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"code":"true","type":"codeVoice"},{"text":" if the value matches the criteria; otherwise, ","type":"text"},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}]}],"kind":"content"},{"content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"inlineContent":[{"type":"text","text":"This method traverses the JSON object using the "},{"type":"codeVoice","code":"scope"},{"type":"text","text":" and "},{"type":"codeVoice","code":"key"},{"type":"text","text":" to find the target value,"},{"type":"text","text":" "},{"type":"text","text":"then uses the "},{"type":"codeVoice","code":"valueMatcher"},{"type":"text","text":" to perform the evaluation."}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"AirshipCore"}],"role":"symbol","roleHeading":"Instance Method","title":"evaluate(json:)","externalID":"s:11AirshipCore11JSONMatcherC8evaluate4jsonSbAA0A4JSONO_tF","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"evaluate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"json","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11AirshipCore0A4JSONO","text":"AirshipJSON","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/evaluate(json:)","interfaceLanguage":"swift"},"abstract":[{"text":"Evaluates the given ","type":"text"},{"code":"AirshipJSON","type":"codeVoice"},{"text":" value against the matcher’s criteria.","type":"text"}],"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","url":"\/documentation\/airshipcore","title":"AirshipCore","kind":"symbol","role":"collection"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/AirshipJSON":{"title":"AirshipJSON","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"AirshipJSON","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirshipJSON","kind":"identifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSON","type":"topic","abstract":[{"type":"text","text":"Airship JSON."}],"url":"\/documentation\/airshipcore\/airshipjson"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONMatcher/evaluate(json:)":{"title":"evaluate(json:)","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/evaluate(json:)","role":"symbol","url":"\/documentation\/airshipcore\/jsonmatcher\/evaluate(json:)","abstract":[{"text":"Evaluates the given ","type":"text"},{"type":"codeVoice","code":"AirshipJSON"},{"text":" value against the matcher’s criteria.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"evaluate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"json","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AirshipJSON","preciseIdentifier":"s:11AirshipCore0A4JSONO","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONMatcher":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JSONMatcher","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"JSONMatcher","kind":"identifier"}],"abstract":[{"type":"text","text":"A matcher for evaluating a JSON payload against a set of criteria."}],"url":"\/documentation\/airshipcore\/jsonmatcher","title":"JSONMatcher","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONMatcher\/title","value":"JSONMatcher","op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONMatcher\/fragments","value":[{"text":"JSONMatcher","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONMatcher\/navigatorTitle","value":[{"text":"JSONMatcher","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}