{"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher"]]},"variants":[{"paths":["\/documentation\/airshipcore\/jsonmatcher\/init(valuematcher:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"abstract":[{"text":"Creates a new ","type":"text"},{"type":"codeVoice","code":"JSONMatcher"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["Mac Catalyst"],"tokens":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"valueMatcher"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher","preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONValueMatcher","kind":"typeIdentifier","text":"JSONValueMatcher"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"JSONValueMatcher"},{"type":"text","text":" to apply to the value."}]}],"name":"valueMatcher"}],"kind":"parameters"},{"content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"A new "},{"type":"codeVoice","code":"JSONMatcher"},{"type":"text","text":" instance."}]}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/init(valueMatcher:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"symbolKind":"init","role":"symbol","externalID":"s:11AirshipCore11JSONMatcherC12valueMatcherAcA09JSONValueE0C_tcfc","modules":[{"name":"AirshipCore"}],"title":"init(valueMatcher:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"valueMatcher","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"JSONValueMatcher","preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONValueMatcher","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Initializer"},"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONMatcher/init(valueMatcher:)":{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/init(valueMatcher:)","kind":"symbol","title":"init(valueMatcher:)","url":"\/documentation\/airshipcore\/jsonmatcher\/init(valuematcher:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"valueMatcher"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONValueMatcher","text":"JSONValueMatcher"},{"kind":"text","text":")"}],"type":"topic","abstract":[{"text":"Creates a new ","type":"text"},{"code":"JSONMatcher","type":"codeVoice"},{"text":".","type":"text"}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"url":"\/documentation\/airshipcore","role":"collection","abstract":[],"title":"AirshipCore","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","type":"topic","kind":"symbol"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONValueMatcher":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JSONValueMatcher","kind":"identifier"}],"title":"JSONValueMatcher","type":"topic","role":"symbol","navigatorTitle":[{"text":"JSONValueMatcher","kind":"identifier"}],"url":"\/documentation\/airshipcore\/jsonvaluematcher","abstract":[{"text":"A ","type":"text"},{"code":"JSONValueMatcher","type":"codeVoice"},{"text":" is used to match a JSON value against a set of constraints.","type":"text"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher","kind":"symbol"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONMatcher":{"title":"JSONMatcher","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSONMatcher"}],"url":"\/documentation\/airshipcore\/jsonmatcher","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"JSONMatcher"}],"kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher","abstract":[{"type":"text","text":"A matcher for evaluating a JSON payload against a set of criteria."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueMatcher\/title","value":"JSONValueMatcher"},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueMatcher\/fragments","value":[{"kind":"identifier","text":"JSONValueMatcher"}]},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueMatcher\/navigatorTitle","value":[{"kind":"identifier","text":"JSONValueMatcher"}]},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONMatcher\/title","value":"JSONMatcher"},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONMatcher\/fragments","value":[{"text":"JSONMatcher","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONMatcher\/navigatorTitle","value":[{"text":"JSONMatcher","kind":"identifier"}]}]}]}