{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":" "},{"kind":"internalParam","text":"matcher"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher","kind":"typeIdentifier","preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONMatcher","text":"JSONMatcher"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"platforms":["Mac Catalyst"]}]},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"aside","name":"Note","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"For internal use only. :nodoc:"}]}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/airshipcore\/jsonmatcher\/isequal(to:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"symbolKind":"method","title":"isEqual(to:)","roleHeading":"Instance Method","modules":[{"name":"AirshipCore"}],"externalID":"s:11AirshipCore11JSONMatcherC7isEqual2toSbAC_tF","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONMatcher","kind":"typeIdentifier","text":"JSONMatcher"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/isEqual(to:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONMatcher":{"abstract":[{"text":"A matcher for evaluating a JSON payload against a set of criteria.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JSONMatcher","kind":"identifier"}],"navigatorTitle":[{"text":"JSONMatcher","kind":"identifier"}],"title":"JSONMatcher","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher","type":"topic","url":"\/documentation\/airshipcore\/jsonmatcher","role":"symbol","kind":"symbol"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONMatcher/isEqual(to:)":{"type":"topic","url":"\/documentation\/airshipcore\/jsonmatcher\/isequal(to:)","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONMatcher\/isEqual(to:)","kind":"symbol","abstract":[],"title":"isEqual(to:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@AirshipCore@objc(cs)JSONMatcher","text":"JSONMatcher","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"url":"\/documentation\/airshipcore","kind":"symbol","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","abstract":[],"title":"AirshipCore","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONMatcher\/title","value":"JSONMatcher"},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONMatcher\/fragments","value":[{"kind":"identifier","text":"JSONMatcher"}]},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONMatcher\/navigatorTitle","value":[{"text":"JSONMatcher","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}