{"metadata":{"modules":[{"name":"AirshipCore"}],"role":"symbol","title":"allowsReverseTransformation()","symbolKind":"method","externalID":"c:@M@AirshipCore@objc(cs)NSURLValueTransformer(cm)allowsReverseTransformation","navigatorTitle":[{"kind":"identifier","text":"allowsReverseTransformation"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowsReverseTransformation"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"roleHeading":"Type Method"},"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSURLValueTransformer\/allowsReverseTransformation()","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst"],"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowsReverseTransformation","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSURLValueTransformer"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/nsurlvaluetransformer\/allowsreversetransformation()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airshipcore\/nsurlvaluetransformer\/allowsreversetransformation()"]}],"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"url":"\/documentation\/airshipcore","role":"collection","abstract":[],"title":"AirshipCore","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","type":"topic","kind":"symbol"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSURLValueTransformer":{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSURLValueTransformer","title":"NSURLValueTransformer","navigatorTitle":[{"text":"NSURLValueTransformer","kind":"identifier"}],"role":"symbol","url":"\/documentation\/airshipcore\/nsurlvaluetransformer","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSURLValueTransformer","kind":"identifier"}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSURLValueTransformer/allowsReverseTransformation()":{"role":"symbol","abstract":[],"title":"allowsReverseTransformation()","navigatorTitle":[{"text":"allowsReverseTransformation","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowsReverseTransformation","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","url":"\/documentation\/airshipcore\/nsurlvaluetransformer\/allowsreversetransformation()","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSURLValueTransformer\/allowsReverseTransformation()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"allowsReverseTransformation","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"allowsReverseTransformation","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["Mac Catalyst"],"tokens":[{"text":"+ (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"allowsReverseTransformation","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"NSURLValueTransformer","op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSURLValueTransformer\/title"},{"value":[{"text":"NSURLValueTransformer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSURLValueTransformer\/fragments"},{"value":[{"kind":"identifier","text":"NSURLValueTransformer"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSURLValueTransformer\/navigatorTitle"},{"value":"allowsReverseTransformation","op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSURLValueTransformer~1allowsReverseTransformation()\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"allowsReverseTransformation"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSURLValueTransformer~1allowsReverseTransformation()\/fragments"}]}]}