{"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSURLValueTransformer\/reverseTransformedValue(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reverseTransformedValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"value","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?","kind":"text"}],"platforms":["Mac Catalyst"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSURLValueTransformer"]]},"metadata":{"symbolKind":"method","role":"symbol","title":"reverseTransformedValue(_:)","modules":[{"name":"AirshipCore"}],"externalID":"c:@M@AirshipCore@objc(cs)NSURLValueTransformer(im)reverseTransformedValue:","navigatorTitle":[{"text":"reverseTransformedValue:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reverseTransformedValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?","kind":"text"}],"roleHeading":"Instance Method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/nsurlvaluetransformer\/reversetransformedvalue(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airshipcore\/nsurlvaluetransformer\/reversetransformedvalue(_:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"title":"AirshipCore","url":"\/documentation\/airshipcore","kind":"symbol","type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSURLValueTransformer/reverseTransformedValue(_:)":{"role":"symbol","url":"\/documentation\/airshipcore\/nsurlvaluetransformer\/reversetransformedvalue(_:)","type":"topic","title":"reverseTransformedValue(_:)","kind":"symbol","navigatorTitle":[{"text":"reverseTransformedValue:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"reverseTransformedValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSURLValueTransformer\/reverseTransformedValue(_:)","abstract":[]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSURLValueTransformer":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSURLValueTransformer","kind":"identifier"}],"url":"\/documentation\/airshipcore\/nsurlvaluetransformer","type":"topic","title":"NSURLValueTransformer","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSURLValueTransformer","role":"symbol","navigatorTitle":[{"text":"NSURLValueTransformer","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"reverseTransformedValue:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"reverseTransformedValue:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["Mac Catalyst"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"reverseTransformedValue:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"value"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"reverseTransformedValue:","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSURLValueTransformer~1reverseTransformedValue(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"reverseTransformedValue:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSURLValueTransformer~1reverseTransformedValue(_:)\/fragments"},{"op":"replace","value":"NSURLValueTransformer","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSURLValueTransformer\/title"},{"op":"replace","value":[{"text":"NSURLValueTransformer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSURLValueTransformer\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"NSURLValueTransformer"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSURLValueTransformer\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}