{"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSURLValueTransformer"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/nsurlvaluetransformer\/transformedvalue(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airshipcore\/nsurlvaluetransformer\/transformedvalue(_:)"]}],"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSURLValueTransformer\/transformedValue(_:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"method","externalID":"c:@M@AirshipCore@objc(cs)NSURLValueTransformer(im)transformedValue:","roleHeading":"Instance Method","modules":[{"name":"AirshipCore"}],"navigatorTitle":[{"text":"transformedValue:","kind":"identifier"}],"title":"transformedValue(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transformedValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?","kind":"text"}]},"primaryContentSections":[{"declarations":[{"platforms":["Mac Catalyst"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transformedValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"value","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"title":"AirshipCore","kind":"symbol","url":"\/documentation\/airshipcore","role":"collection","abstract":[],"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSURLValueTransformer/transformedValue(_:)":{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSURLValueTransformer\/transformedValue(_:)","kind":"symbol","url":"\/documentation\/airshipcore\/nsurlvaluetransformer\/transformedvalue(_:)","title":"transformedValue(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transformedValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"transformedValue:","kind":"identifier"}],"role":"symbol","abstract":[],"type":"topic"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSURLValueTransformer":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"NSURLValueTransformer"}],"role":"symbol","url":"\/documentation\/airshipcore\/nsurlvaluetransformer","title":"NSURLValueTransformer","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSURLValueTransformer","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSURLValueTransformer"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"transformedValue:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"transformedValue:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"transformedValue:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"value","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSURLValueTransformer~1transformedValue(_:)\/title","value":"transformedValue:"},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSURLValueTransformer~1transformedValue(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"transformedValue:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSURLValueTransformer\/title","value":"NSURLValueTransformer"},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSURLValueTransformer\/fragments","value":[{"text":"NSURLValueTransformer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSURLValueTransformer\/navigatorTitle","value":[{"kind":"identifier","text":"NSURLValueTransformer"}]}]}]}