/* Copyright 2017 Urban Airship and Contributors */

#import <Foundation/Foundation.h>
#import "UAScheduleTrigger.h"
#import "UAScheduleDelay.h"

NS_ASSUME_NONNULL_BEGIN


/**
 * Represents the possible error conditions when deserializing schedule info from JSON.
 */
typedef NS_ENUM(NSInteger, UAScheduleInfoErrorCode) {
    /**
     * Indicates an error with the schedule info JSON definition.
     */
    UAScheduleInfoErrorCodeInvalidJSON,
};

/**
 * The domain for NSErrors generated by `actionScheduleInfoWithJSON:error:`.
 */
extern NSString * const UAScheduleInfoErrorDomain;

/**
 * Max priority that a schedule can be given. This is a negative integer.
 */
extern NSInteger const UAScheduleInfoMaxPriority;

/**
 * Min priority that a schedule can be given. This is a positive integer.
 */
extern NSInteger const UAScheduleInfoMinPriority;


/**
 * JSON key for the actions's priority.
 */
extern NSString *const UAScheduleInfoPriorityKey;

/**
 * JSON key for the schedule's limit.
 */
extern NSString *const UAScheduleInfoLimitKey;

/**
 * JSON key for the schedule's group.
 */
extern NSString *const UAScheduleInfoGroupKey;

/**
 * JSON key for the schedule's end.
 */
extern NSString *const UAScheduleInfoEndKey;

/**
 * JSON key for the schedule's start.
 */
extern NSString *const UAScheduleInfoStartKey;

/**
 * JSON key for the schedule's triggers.
 */
extern NSString *const UAScheduleInfoTriggersKey;

/**
 * JSON key for the schedule's delay.
 */
extern NSString *const UAScheduleInfoDelayKey;

/**
 * Max number of triggers a schedule can support.
 */
extern NSUInteger const UAScheduleInfoMaxTriggers;

/**
 * Builder class for a UAScheduleInfo.
 */
@interface UAScheduleInfoBuilder : NSObject

///---------------------------------------------------------------------------------------
/// @name Schedule Info Builder Properties
///---------------------------------------------------------------------------------------

/**
 * The schedule's priority. Priority is optional and defaults to 0. Schedules are
 * executed by priority in ascending order.
 */
@property(nonatomic, assign) NSInteger priority;

/**
 * Number of times the actions will be triggered until the schedule is
 * canceled.
 */
@property(nonatomic, assign) NSUInteger limit;

/**
 * Array of triggers. Triggers define conditions on when to run
 * the actions.
 */
@property(nonatomic, strong, nullable) NSArray<UAScheduleTrigger *> *triggers;

/**
 * The schedule's start time.
 */
@property(nonatomic, strong, nullable) NSDate *start;

/**
 * The schedule's end time. After the end time the schedule will be canceled.
 */
@property(nonatomic, strong, nullable) NSDate *end;

/**
 * The schedule's delay.
 */
@property(nonatomic, strong, nullable) UAScheduleDelay *delay;

/**
 * The schedule's group.
 */
@property(nonatomic, copy, nullable) NSString *group;

@end

/**
 * Defines the scheduled action.
 */
@interface UAScheduleInfo : NSObject

///---------------------------------------------------------------------------------------
/// @name Schedule Info Properties
///---------------------------------------------------------------------------------------

/**
* The schedule's priority. Priority is optional and defaults to 0. Schedules are
* executed by priority in ascending order.
*/
@property(nonatomic, readonly) NSInteger priority;

/**
 * Array of triggers. Triggers define conditions on when to run
 * the actions.
 */
@property(nonatomic, readonly) NSArray<UAScheduleTrigger *> *triggers;

/**
 * Number of times the actions will be triggered until the schedule is
 * canceled.
 */
@property(nonatomic, readonly) NSUInteger limit;

/**
 * The schedule's start time.
 */
@property(nonatomic, readonly) NSDate *start;

/**
 * The schedule's end time. After the end time the schedule will be canceled.
 */
@property(nonatomic, readonly) NSDate *end;

/**
 * The schedule's delay.
 */
@property(nonatomic, readonly) UAScheduleDelay *delay;

/**
 * The schedule's group.
 */
@property(nonatomic, copy, nullable) NSString *group;

/**
 * Checks if the schedule info is valid. A valid schedule
 * contains between 1 to 10 triggers, if a delay is defined it must be valid,
 * and the end time must be after the start time. Invalid schedules will not be scheduled.
 */
@property(nonatomic, readonly) BOOL isValid;

///---------------------------------------------------------------------------------------
/// @name Schedule Info Management
///---------------------------------------------------------------------------------------

/**
 * Checks if the schedule info is equal to another schedule info
 *
 * @param scheduleInfo The other schedule info to compare against.
 * @return `YES` if the schedule infos are equal, otherwise `NO`.
 */
- (BOOL)isEqualToScheduleInfo:(nullable UAScheduleInfo *)scheduleInfo;

@end

NS_ASSUME_NONNULL_END


