{"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[[]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipmessagecenter"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airshipmessagecenter"]}],"topicSections":[{"anchor":"Classes","generated":true,"identifiers":["doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterAction","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterController","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterMessageListViewModel","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterMessageViewModel","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterNativeBridgeExtension","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterSDKModule","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterViewControllerFactory"],"title":"Classes"},{"anchor":"Protocols","generated":true,"identifiers":["doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenter","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterDisplayDelegate","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterInbox","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterListItemViewStyle","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterPredicate","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageViewStyle"],"title":"Protocols"},{"anchor":"Structures","generated":true,"identifiers":["doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/DefaultListItemViewStyle","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/DefaultMessageViewStyle","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/ListItemViewStyleConfiguration","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterContent","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterListView","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterListViewWithNavigation","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterMessage","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterMessageView","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterMessageViewWithNavigation","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterTheme","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterUser","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterView","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageViewStyleConfiguration"],"title":"Structures"},{"anchor":"Enumerations","generated":true,"identifiers":["doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterState","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/SeparatorStyle"],"title":"Enumerations"},{"anchor":"Extended-Modules","generated":true,"identifiers":["doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/AirshipCore","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/SwiftUICore"],"title":"Extended Modules"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter"},"sections":[],"kind":"symbol","metadata":{"symbolKind":"module","modules":[{"name":"AirshipMessageCenter"}],"roleHeading":"Framework","title":"AirshipMessageCenter","role":"collection","externalID":"AirshipMessageCenter"},"references":{"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterUser":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageCenterUser"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCenterUser"}],"title":"MessageCenterUser","abstract":[{"text":"Model object for holding user data.","type":"text"}],"url":"\/documentation\/airshipmessagecenter\/messagecenteruser","kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterUser"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterListItemViewStyle":{"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterListItemViewStyle","role":"symbol","url":"\/documentation\/airshipmessagecenter\/messagecenterlistitemviewstyle","abstract":[{"text":"A protocol that defines the style for a Message Center list item view.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageCenterListItemViewStyle","kind":"identifier"}],"kind":"symbol","title":"MessageCenterListItemViewStyle","type":"topic","navigatorTitle":[{"text":"MessageCenterListItemViewStyle","kind":"identifier"}]},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterMessageListViewModel":{"navigatorTitle":[{"text":"MessageCenterMessageListViewModel","kind":"identifier"}],"title":"MessageCenterMessageListViewModel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageCenterMessageListViewModel","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"A view model for the message center list.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterMessageListViewModel","role":"symbol","url":"\/documentation\/airshipmessagecenter\/messagecentermessagelistviewmodel"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterView":{"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterView","kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageCenterView","kind":"identifier"}],"navigatorTitle":[{"text":"MessageCenterView","kind":"identifier"}],"abstract":[{"type":"text","text":"The main view for the Airship Message Center. This view provides a navigation stack."},{"type":"text","text":" "},{"type":"text","text":"If you wish to provide your own navigation, see "},{"code":"MessageCenterContent","type":"codeVoice"},{"type":"text","text":"."}],"title":"MessageCenterView","url":"\/documentation\/airshipmessagecenter\/messagecenterview"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterController":{"title":"MessageCenterController","url":"\/documentation\/airshipmessagecenter\/messagecentercontroller","abstract":[{"text":"Controller for the Message Center.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageCenterController","kind":"identifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterController","kind":"symbol","navigatorTitle":[{"text":"MessageCenterController","kind":"identifier"}],"type":"topic"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageViewStyleConfiguration":{"kind":"symbol","type":"topic","title":"MessageViewStyleConfiguration","url":"\/documentation\/airshipmessagecenter\/messageviewstyleconfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageViewStyleConfiguration"}],"abstract":[{"text":"The configuration for a Message Center message view.","type":"text"}],"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageViewStyleConfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageViewStyleConfiguration"}]},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterSDKModule":{"url":"\/documentation\/airshipmessagecenter\/messagecentersdkmodule","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterSDKModule","kind":"symbol","role":"symbol","title":"MessageCenterSDKModule","navigatorTitle":[{"text":"MessageCenterSDKModule","kind":"identifier"}],"abstract":[{"type":"text","text":"AirshipMessageCenter module loader."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageCenterSDKModule","kind":"identifier"}],"type":"topic"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterDisplayDelegate":{"type":"topic","abstract":[{"text":"Delegate protocol for receiving callbacks related to message center.","type":"text"}],"role":"symbol","title":"MessageCenterDisplayDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageCenterDisplayDelegate","kind":"identifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterDisplayDelegate","url":"\/documentation\/airshipmessagecenter\/messagecenterdisplaydelegate","navigatorTitle":[{"text":"MessageCenterDisplayDelegate","kind":"identifier"}],"kind":"symbol"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/AirshipCore":{"url":"\/documentation\/airshipmessagecenter\/airshipcore","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/AirshipCore","abstract":[],"kind":"symbol","role":"collection","title":"AirshipCore","type":"topic"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterListViewWithNavigation":{"type":"topic","abstract":[{"type":"text","text":"A view that displays a list of messages as well as modifies the toolbars and navigation title."}],"role":"symbol","navigatorTitle":[{"text":"MessageCenterListViewWithNavigation","kind":"identifier"}],"url":"\/documentation\/airshipmessagecenter\/messagecenterlistviewwithnavigation","kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterListViewWithNavigation","title":"MessageCenterListViewWithNavigation","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageCenterListViewWithNavigation","kind":"identifier"}]},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/AirshipMessageCenterVersionNumber":{"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/AirshipMessageCenterVersionNumber","abstract":[{"text":"Project version number for AirshipAutomation.","type":"text"}],"fragments":[{"text":"AirshipMessageCenterVersionNumber","kind":"identifier"}],"kind":"symbol","title":"AirshipMessageCenterVersionNumber","type":"topic","url":"\/documentation\/airshipmessagecenter\/airshipmessagecenterversionnumber","role":"symbol"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterViewControllerFactory":{"url":"\/documentation\/airshipmessagecenter\/messagecenterviewcontrollerfactory","role":"symbol","abstract":[{"text":"View controller for Message Center view","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageCenterViewControllerFactory","kind":"identifier"}],"navigatorTitle":[{"text":"MessageCenterViewControllerFactory","kind":"identifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterViewControllerFactory","kind":"symbol","title":"MessageCenterViewControllerFactory"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/SwiftUICore":{"title":"SwiftUICore","kind":"symbol","url":"\/documentation\/airshipmessagecenter\/swiftuicore","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/SwiftUICore","role":"collection","type":"topic"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterContent":{"abstract":[{"type":"text","text":"The Message Center content view."},{"type":"text","text":" "},{"type":"text","text":"This view can be used to construct a custom Message Center. For a more turnkey solution, see "},{"type":"codeVoice","code":"MessageCenterView"},{"type":"text","text":"."}],"type":"topic","role":"symbol","title":"MessageCenterContent","url":"\/documentation\/airshipmessagecenter\/messagecentercontent","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCenterContent"}],"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterContent","navigatorTitle":[{"kind":"identifier","text":"MessageCenterContent"}]},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/DefaultMessageViewStyle":{"url":"\/documentation\/airshipmessagecenter\/defaultmessageviewstyle","kind":"symbol","abstract":[{"type":"text","text":"The default style for a Message Center message view."}],"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/DefaultMessageViewStyle","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DefaultMessageViewStyle","kind":"identifier"}],"title":"DefaultMessageViewStyle","type":"topic","navigatorTitle":[{"text":"DefaultMessageViewStyle","kind":"identifier"}]},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterNativeBridgeExtension":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageCenterNativeBridgeExtension","kind":"identifier"}],"url":"\/documentation\/airshipmessagecenter\/messagecenternativebridgeextension","type":"topic","navigatorTitle":[{"text":"MessageCenterNativeBridgeExtension","kind":"identifier"}],"kind":"symbol","title":"MessageCenterNativeBridgeExtension","abstract":[{"type":"text","text":"Airship native bridge extension for the Message Center."}],"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterNativeBridgeExtension"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageViewStyle":{"url":"\/documentation\/airshipmessagecenter\/messageviewstyle","navigatorTitle":[{"text":"MessageViewStyle","kind":"identifier"}],"abstract":[{"type":"text","text":"A protocol that defines the style for a Message Center message view."}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageViewStyle","title":"MessageViewStyle","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageViewStyle","kind":"identifier"}]},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterMessageView":{"title":"MessageCenterMessageView","role":"symbol","abstract":[{"type":"text","text":"The Message Center message view."}],"navigatorTitle":[{"text":"MessageCenterMessageView","kind":"identifier"}],"url":"\/documentation\/airshipmessagecenter\/messagecentermessageview","type":"topic","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageCenterMessageView","kind":"identifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterMessageView"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/ListItemViewStyleConfiguration":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ListItemViewStyleConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"The configuration for a Message Center list item view."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/ListItemViewStyleConfiguration","role":"symbol","title":"ListItemViewStyleConfiguration","navigatorTitle":[{"text":"ListItemViewStyleConfiguration","kind":"identifier"}],"url":"\/documentation\/airshipmessagecenter\/listitemviewstyleconfiguration"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterMessage":{"url":"\/documentation\/airshipmessagecenter\/messagecentermessage","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterMessage","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageCenterMessage"}],"kind":"symbol","abstract":[{"text":"Message center message.","type":"text"}],"title":"MessageCenterMessage","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCenterMessage"}]},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterAction":{"title":"MessageCenterAction","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Message center action that launches the message center."}],"type":"topic","url":"\/documentation\/airshipmessagecenter\/messagecenteraction","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCenterAction"}],"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterAction","navigatorTitle":[{"kind":"identifier","text":"MessageCenterAction"}]},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/DefaultListItemViewStyle":{"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultListItemViewStyle"}],"navigatorTitle":[{"kind":"identifier","text":"DefaultListItemViewStyle"}],"abstract":[{"text":"The default style for a Message Center list item view.","type":"text"}],"url":"\/documentation\/airshipmessagecenter\/defaultlistitemviewstyle","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/DefaultListItemViewStyle","type":"topic","kind":"symbol","title":"DefaultListItemViewStyle"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter":{"abstract":[],"role":"collection","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter","kind":"symbol","title":"AirshipMessageCenter","url":"\/documentation\/airshipmessagecenter"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterPredicate":{"url":"\/documentation\/airshipmessagecenter\/messagecenterpredicate","title":"MessageCenterPredicate","kind":"symbol","abstract":[{"type":"text","text":"Predicate for filtering messages in the Message Center."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageCenterPredicate","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterPredicate","navigatorTitle":[{"text":"MessageCenterPredicate","kind":"identifier"}]},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterListView":{"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterListView","title":"MessageCenterListView","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageCenterListView","kind":"identifier"}],"navigatorTitle":[{"text":"MessageCenterListView","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A view that displays a list of messages."}],"url":"\/documentation\/airshipmessagecenter\/messagecenterlistview","role":"symbol"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterMessageViewModel":{"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterMessageViewModel","navigatorTitle":[{"kind":"identifier","text":"MessageCenterMessageViewModel"}],"url":"\/documentation\/airshipmessagecenter\/messagecentermessageviewmodel","title":"MessageCenterMessageViewModel","type":"topic","abstract":[{"type":"text","text":"A view model for a message."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCenterMessageViewModel"}]},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterMessageViewWithNavigation":{"abstract":[{"type":"text","text":"A view that displays a message as well as modifies the toolbars and navigation title."}],"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterMessageViewWithNavigation","url":"\/documentation\/airshipmessagecenter\/messagecentermessageviewwithnavigation","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCenterMessageViewWithNavigation"}],"navigatorTitle":[{"kind":"identifier","text":"MessageCenterMessageViewWithNavigation"}],"type":"topic","title":"MessageCenterMessageViewWithNavigation","role":"symbol"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/AirshipMessageCenterVersionString":{"kind":"symbol","abstract":[{"type":"text","text":"Project version string for AirshipAutomation."}],"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/AirshipMessageCenterVersionString","type":"topic","url":"\/documentation\/airshipmessagecenter\/airshipmessagecenterversionstring","role":"symbol","fragments":[{"kind":"identifier","text":"AirshipMessageCenterVersionString"}],"title":"AirshipMessageCenterVersionString"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterState":{"type":"topic","title":"MessageCenterState","kind":"symbol","abstract":[{"text":"The message center controller’s possible states.","type":"text"}],"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterState","url":"\/documentation\/airshipmessagecenter\/messagecenterstate","role":"symbol","navigatorTitle":[{"text":"MessageCenterState","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageCenterState","kind":"identifier"}]},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterInbox":{"abstract":[{"text":"Airship Message Center inbox protocol.","type":"text"}],"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterInbox","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCenterInbox"}],"title":"MessageCenterInbox","url":"\/documentation\/airshipmessagecenter\/messagecenterinbox","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageCenterInbox"}],"type":"topic"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterTheme":{"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterTheme","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageCenterTheme","kind":"identifier"}],"title":"MessageCenterTheme","role":"symbol","abstract":[{"text":"Model object representing a custom theme to be applied to the default message center.","type":"text"}],"url":"\/documentation\/airshipmessagecenter\/messagecentertheme","type":"topic","kind":"symbol","navigatorTitle":[{"text":"MessageCenterTheme","kind":"identifier"}]},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenter":{"title":"MessageCenter","type":"topic","abstract":[{"type":"text","text":"Airship Message Center Protocol."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCenter"}],"navigatorTitle":[{"kind":"identifier","text":"MessageCenter"}],"role":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenter","url":"\/documentation\/airshipmessagecenter\/messagecenter","kind":"symbol"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/SeparatorStyle":{"role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SeparatorStyle","kind":"identifier"}],"title":"SeparatorStyle","url":"\/documentation\/airshipmessagecenter\/separatorstyle","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/SeparatorStyle","abstract":[],"navigatorTitle":[{"text":"SeparatorStyle","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"anchor":"Classes","title":"Classes","identifiers":["doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterNativeBridgeExtension","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterSDKModule","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterViewControllerFactory"]},{"generated":true,"anchor":"Variables","title":"Variables","identifiers":["doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/AirshipMessageCenterVersionNumber","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/AirshipMessageCenterVersionString"]}]},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterSDKModule\/title","op":"replace","value":"UAMessageCenterSDKModule"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterSDKModule\/fragments","op":"replace","value":[{"kind":"identifier","text":"UAMessageCenterSDKModule"}]},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterSDKModule\/navigatorTitle","op":"replace","value":[{"text":"UAMessageCenterSDKModule","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterViewControllerFactory\/title","op":"replace","value":"MessageCenterViewControllerFactory"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterViewControllerFactory\/fragments","op":"replace","value":[{"text":"MessageCenterViewControllerFactory","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterViewControllerFactory\/navigatorTitle","op":"replace","value":[{"text":"MessageCenterViewControllerFactory","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterNativeBridgeExtension\/title","op":"replace","value":"MessageCenterNativeBridgeExtension"},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterNativeBridgeExtension\/fragments","value":[{"text":"MessageCenterNativeBridgeExtension","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterNativeBridgeExtension\/navigatorTitle","value":[{"text":"MessageCenterNativeBridgeExtension","kind":"identifier"}]}]}]}