{"abstract":[{"text":"NOTE: For internal use only. :nodoc:","type":"text"}],"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/VersionMatcher\/init(versionConstraint:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"versionConstraint","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"platforms":["Mac Catalyst"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/versionmatcher\/init(versionconstraint:)"]}],"sections":[],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Marked to be removed in SDK 20"}],"type":"paragraph"}],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/VersionMatcher"]]},"metadata":{"externalID":"s:11AirshipCore14VersionMatcherC17versionConstraintACSgSS_tcfc","platforms":[{"message":"Marked to be removed in SDK 20","beta":false,"deprecated":true,"unavailable":false}],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"versionConstraint","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"init","role":"symbol","title":"init(versionConstraint:)","roleHeading":"Initializer","modules":[{"name":"AirshipCore"}]},"kind":"symbol","references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/VersionMatcher":{"navigatorTitle":[{"kind":"identifier","text":"VersionMatcher"}],"title":"VersionMatcher","url":"\/documentation\/airshipcore\/versionmatcher","type":"topic","kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/VersionMatcher","deprecated":true,"abstract":[{"type":"text","text":"Version matcher."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VersionMatcher"}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"kind":"symbol","role":"collection","title":"AirshipCore","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","url":"\/documentation\/airshipcore","abstract":[]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/VersionMatcher/init(versionConstraint:)":{"deprecated":true,"kind":"symbol","role":"symbol","title":"init(versionConstraint:)","type":"topic","url":"\/documentation\/airshipcore\/versionmatcher\/init(versionconstraint:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"versionConstraint","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/VersionMatcher\/init(versionConstraint:)","abstract":[{"type":"text","text":"NOTE: For internal use only. :nodoc:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"VersionMatcher","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1VersionMatcher\/title"},{"op":"replace","value":[{"text":"VersionMatcher","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1VersionMatcher\/fragments"},{"op":"replace","value":[{"text":"VersionMatcher","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1VersionMatcher\/navigatorTitle"}]}]}