{"metadata":{"modules":[{"name":"AirshipCore"}],"role":"symbol","roleHeading":"Type Method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"matcher","kind":"identifier"},{"text":"(","kind":"text"},{"text":"versionConstraint","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"VersionMatcher","preciseIdentifier":"c:@M@AirshipCore@objc(cs)VersionMatcher","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"method","externalID":"s:11AirshipCore14VersionMatcherC7matcher17versionConstraintACSgSS_tFZ","title":"matcher(versionConstraint:)","platforms":[{"beta":false,"message":"Marked to be removed in SDK 20","deprecated":true,"unavailable":false}]},"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/VersionMatcher\/matcher(versionConstraint:)","interfaceLanguage":"swift"},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Marked to be removed in SDK 20","type":"text"}]}],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/VersionMatcher"]]},"abstract":[{"type":"text","text":"Create a matcher for the supplied version constraint"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"matcher","kind":"identifier"},{"text":"(","kind":"text"},{"text":"versionConstraint","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"VersionMatcher","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/VersionMatcher","kind":"typeIdentifier","preciseIdentifier":"c:@M@AirshipCore@objc(cs)VersionMatcher"},{"text":"?","kind":"text"}],"platforms":["Mac Catalyst"],"languages":["swift"]}]},{"parameters":[{"name":"versionConstraint","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Constraint that matches one of our supported patterns"}]}]}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Matcher or nil if versionConstraint does not match any of the expected patterns"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/versionmatcher\/matcher(versionconstraint:)"]}],"sections":[],"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/VersionMatcher/matcher(versionConstraint:)":{"title":"matcher(versionConstraint:)","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/VersionMatcher\/matcher(versionConstraint:)","url":"\/documentation\/airshipcore\/versionmatcher\/matcher(versionconstraint:)","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"matcher","kind":"identifier"},{"text":"(","kind":"text"},{"text":"versionConstraint","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@AirshipCore@objc(cs)VersionMatcher","text":"VersionMatcher","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"Create a matcher for the supplied version constraint","type":"text"}],"role":"symbol","deprecated":true},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/VersionMatcher":{"navigatorTitle":[{"kind":"identifier","text":"VersionMatcher"}],"title":"VersionMatcher","url":"\/documentation\/airshipcore\/versionmatcher","type":"topic","kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/VersionMatcher","deprecated":true,"abstract":[{"type":"text","text":"Version matcher."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"VersionMatcher"}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"kind":"symbol","role":"collection","title":"AirshipCore","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","url":"\/documentation\/airshipcore","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1VersionMatcher\/title","value":"VersionMatcher","op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1VersionMatcher\/fragments","value":[{"text":"VersionMatcher","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1VersionMatcher\/navigatorTitle","value":[{"text":"VersionMatcher","kind":"identifier"}],"op":"replace"}]}]}