{"sections":[],"variants":[{"paths":["\/documentation\/airshippreferencecenter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airshippreferencecenter"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[[]]},"metadata":{"role":"collection","modules":[{"name":"AirshipPreferenceCenter"}],"roleHeading":"Framework","title":"AirshipPreferenceCenter","externalID":"AirshipPreferenceCenter","symbolKind":"module"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/AirshipPreferenceCenterResources","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterSDKModule","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterState","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterViewControllerFactory"],"generated":true,"anchor":"Classes"},{"title":"Protocols","identifiers":["doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/ChannelSubscriptionViewStyle","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/CommonSectionViewStyle","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/ContactManagementSectionStyle","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/ContactSubscriptionGroupStyle","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/ContactSubscriptionViewStyle","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/LabeledSectionBreakStyle","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenter","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterAlertStyle","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterConfigItem","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterConfigSection","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterContentStyle","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterOpenDelegate","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceConfigCondition"],"generated":true,"anchor":"Protocols"},{"title":"Structures","identifiers":["doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/ChannelSubscriptionView","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/ChannelSubscriptionViewStyleConfiguration","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/ChannelTextField","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/CommonSectionView","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/CommonSectionViewStyleConfiguration","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/ContactManagementSectionStyleConfiguration","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/ContactSubscriptionGroupStyleConfiguration","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/ContactSubscriptionGroupView","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/ContactSubscriptionView","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/ContactSubscriptionViewStyleConfiguration","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/DefaultChannelSubscriptionViewStyle","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/DefaultCommonSectionViewStyle","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/DefaultContactManagementSectionStyle","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/DefaultContactSubscriptionGroupStyle","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/DefaultContactSubscriptionViewStyle","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/DefaultLabeledSectionBreakStyle","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/DefaultPreferenceCenterAlertStyle","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/DefaultPreferenceCenterViewStyle","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/ErrorLabel","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/LabeledSectionBreakStyleConfiguration","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/LabeledSectionBreakView","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterAlertStyleConfiguration","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterAlertView","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterConfig","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterContactManagementView","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterContent","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterContentStyleConfiguration","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterTheme","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterView"],"generated":true,"anchor":"Structures"},{"title":"Enumerations","identifiers":["doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/AddChannelState","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterConfigConditionType","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterConfigItemType","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterConfigSectionType","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterContentPhase"],"generated":true,"anchor":"Enumerations"},{"title":"Extended Modules","identifiers":["doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/AirshipCore","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/SwiftUICore"],"generated":true,"anchor":"Extended-Modules"}],"references":{"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/DefaultCommonSectionViewStyle":{"type":"topic","abstract":[{"type":"text","text":"The default common section view style"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DefaultCommonSectionViewStyle","kind":"identifier"}],"url":"\/documentation\/airshippreferencecenter\/defaultcommonsectionviewstyle","kind":"symbol","navigatorTitle":[{"text":"DefaultCommonSectionViewStyle","kind":"identifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/DefaultCommonSectionViewStyle","title":"DefaultCommonSectionViewStyle","role":"symbol"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/CommonSectionView":{"abstract":[{"type":"text","text":"Common section item view"}],"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/CommonSectionView","kind":"symbol","title":"CommonSectionView","role":"symbol","url":"\/documentation\/airshippreferencecenter\/commonsectionview","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonSectionView"}],"navigatorTitle":[{"kind":"identifier","text":"CommonSectionView"}],"type":"topic"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/ChannelSubscriptionViewStyle":{"kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/ChannelSubscriptionViewStyle","url":"\/documentation\/airshippreferencecenter\/channelsubscriptionviewstyle","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChannelSubscriptionViewStyle"}],"title":"ChannelSubscriptionViewStyle","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChannelSubscriptionViewStyle"}]},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/LabeledSectionBreakView":{"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/LabeledSectionBreakView","title":"LabeledSectionBreakView","type":"topic","url":"\/documentation\/airshippreferencecenter\/labeledsectionbreakview","navigatorTitle":[{"kind":"identifier","text":"LabeledSectionBreakView"}],"kind":"symbol","abstract":[{"text":"Labeled section break view","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LabeledSectionBreakView"}],"role":"symbol"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/DefaultContactSubscriptionGroupStyle":{"abstract":[{"text":"The default subscription group item style","type":"text"}],"url":"\/documentation\/airshippreferencecenter\/defaultcontactsubscriptiongroupstyle","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DefaultContactSubscriptionGroupStyle"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultContactSubscriptionGroupStyle"}],"title":"DefaultContactSubscriptionGroupStyle","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/DefaultContactSubscriptionGroupStyle","role":"symbol"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterContentStyleConfiguration":{"kind":"symbol","role":"symbol","url":"\/documentation\/airshippreferencecenter\/preferencecentercontentstyleconfiguration","navigatorTitle":[{"text":"PreferenceCenterContentStyleConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Preference Center view style configuration"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreferenceCenterContentStyleConfiguration","kind":"identifier"}],"title":"PreferenceCenterContentStyleConfiguration","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterContentStyleConfiguration"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/AirshipCore":{"type":"topic","url":"\/documentation\/airshippreferencecenter\/airshipcore","title":"AirshipCore","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/AirshipCore","role":"collection","kind":"symbol"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/LabeledSectionBreakStyleConfiguration":{"kind":"symbol","role":"symbol","title":"LabeledSectionBreakStyleConfiguration","abstract":[{"text":"The labeled section break style configuration","type":"text"}],"type":"topic","url":"\/documentation\/airshippreferencecenter\/labeledsectionbreakstyleconfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LabeledSectionBreakStyleConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"LabeledSectionBreakStyleConfiguration"}],"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/LabeledSectionBreakStyleConfiguration"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/DefaultChannelSubscriptionViewStyle":{"abstract":[{"type":"text","text":"The default channel subscription view style"}],"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/DefaultChannelSubscriptionViewStyle","role":"symbol","url":"\/documentation\/airshippreferencecenter\/defaultchannelsubscriptionviewstyle","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DefaultChannelSubscriptionViewStyle","kind":"identifier"}],"navigatorTitle":[{"text":"DefaultChannelSubscriptionViewStyle","kind":"identifier"}],"kind":"symbol","type":"topic","title":"DefaultChannelSubscriptionViewStyle"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/SwiftUICore":{"kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/SwiftUICore","url":"\/documentation\/airshippreferencecenter\/swiftuicore","role":"collection","title":"SwiftUICore","type":"topic","abstract":[]},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterContentPhase":{"role":"symbol","kind":"symbol","url":"\/documentation\/airshippreferencecenter\/preferencecentercontentphase","navigatorTitle":[{"text":"PreferenceCenterContentPhase","kind":"identifier"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreferenceCenterContentPhase","kind":"identifier"}],"title":"PreferenceCenterContentPhase","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterContentPhase","abstract":[{"text":"Preference center content phase","type":"text"}]},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/DefaultPreferenceCenterViewStyle":{"navigatorTitle":[{"kind":"identifier","text":"DefaultPreferenceCenterViewStyle"}],"type":"topic","kind":"symbol","url":"\/documentation\/airshippreferencecenter\/defaultpreferencecenterviewstyle","abstract":[{"text":"The default Preference Center view style","type":"text"}],"role":"symbol","title":"DefaultPreferenceCenterViewStyle","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultPreferenceCenterViewStyle"}],"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/DefaultPreferenceCenterViewStyle"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterConfigConditionType":{"type":"topic","abstract":[{"text":"Condition types","type":"text"}],"url":"\/documentation\/airshippreferencecenter\/preferencecenterconfigconditiontype","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreferenceCenterConfigConditionType"}],"navigatorTitle":[{"kind":"identifier","text":"PreferenceCenterConfigConditionType"}],"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterConfigConditionType","role":"symbol","kind":"symbol","title":"PreferenceCenterConfigConditionType"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/DefaultContactSubscriptionViewStyle":{"type":"topic","title":"DefaultContactSubscriptionViewStyle","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DefaultContactSubscriptionViewStyle","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DefaultContactSubscriptionViewStyle","kind":"identifier"}],"url":"\/documentation\/airshippreferencecenter\/defaultcontactsubscriptionviewstyle","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/DefaultContactSubscriptionViewStyle","abstract":[{"type":"text","text":"Default contact subscription view style"}]},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/ErrorLabel":{"type":"topic","navigatorTitle":[{"text":"ErrorLabel","kind":"identifier"}],"abstract":[{"type":"text","text":"Error text view that appears under the add channel fields when an error occurs"}],"title":"ErrorLabel","url":"\/documentation\/airshippreferencecenter\/errorlabel","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ErrorLabel","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/ErrorLabel"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/ContactSubscriptionGroupStyle":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ContactSubscriptionGroupStyle"}],"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/ContactSubscriptionGroupStyle","kind":"symbol","url":"\/documentation\/airshippreferencecenter\/contactsubscriptiongroupstyle","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactSubscriptionGroupStyle"}],"title":"ContactSubscriptionGroupStyle","type":"topic"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/ContactSubscriptionViewStyle":{"navigatorTitle":[{"kind":"identifier","text":"ContactSubscriptionViewStyle"}],"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/ContactSubscriptionViewStyle","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactSubscriptionViewStyle"}],"type":"topic","url":"\/documentation\/airshippreferencecenter\/contactsubscriptionviewstyle","title":"ContactSubscriptionViewStyle","kind":"symbol","abstract":[{"type":"text","text":"Contact subcription view style"}]},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceConfigCondition":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreferenceConfigCondition","kind":"identifier"}],"url":"\/documentation\/airshippreferencecenter\/preferenceconfigcondition","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceConfigCondition","navigatorTitle":[{"text":"PreferenceConfigCondition","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Condition"}],"title":"PreferenceConfigCondition","type":"topic"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterConfigSection":{"abstract":[{"type":"text","text":"Preference config section."}],"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterConfigSection","title":"PreferenceCenterConfigSection","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreferenceCenterConfigSection"}],"navigatorTitle":[{"kind":"identifier","text":"PreferenceCenterConfigSection"}],"type":"topic","role":"symbol","url":"\/documentation\/airshippreferencecenter\/preferencecenterconfigsection","kind":"symbol"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/ContactSubscriptionView":{"title":"ContactSubscriptionView","navigatorTitle":[{"text":"ContactSubscriptionView","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/airshippreferencecenter\/contactsubscriptionview","abstract":[{"text":"The contact subscription item view","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/ContactSubscriptionView","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactSubscriptionView"}]},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/ContactSubscriptionGroupView":{"url":"\/documentation\/airshippreferencecenter\/contactsubscriptiongroupview","title":"ContactSubscriptionGroupView","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Contact subscription group item view"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactSubscriptionGroupView","kind":"identifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/ContactSubscriptionGroupView","navigatorTitle":[{"text":"ContactSubscriptionGroupView","kind":"identifier"}],"type":"topic"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/ChannelSubscriptionViewStyleConfiguration":{"url":"\/documentation\/airshippreferencecenter\/channelsubscriptionviewstyleconfiguration","role":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/ChannelSubscriptionViewStyleConfiguration","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChannelSubscriptionViewStyleConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"ChannelSubscriptionViewStyleConfiguration"}],"title":"ChannelSubscriptionViewStyleConfiguration","abstract":[{"type":"text","text":"Channel subscription item view style configuration"}],"kind":"symbol","type":"topic"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterView":{"url":"\/documentation\/airshippreferencecenter\/preferencecenterview","title":"PreferenceCenterView","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The main view for the Airship Preference Center. This view provides a navigation stack."},{"type":"text","text":" "},{"type":"text","text":"If you wish to provide your own navigation, see "},{"type":"codeVoice","code":"PreferenceCenterContent"},{"type":"text","text":"."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreferenceCenterView","kind":"identifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterView","navigatorTitle":[{"text":"PreferenceCenterView","kind":"identifier"}],"type":"topic"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/CommonSectionViewStyle":{"abstract":[{"text":"Common section view style","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommonSectionViewStyle","kind":"identifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/CommonSectionViewStyle","role":"symbol","navigatorTitle":[{"text":"CommonSectionViewStyle","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/airshippreferencecenter\/commonsectionviewstyle","title":"CommonSectionViewStyle"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterAlertStyleConfiguration":{"abstract":[{"text":"Preference Center alert style configuration","type":"text"}],"kind":"symbol","title":"PreferenceCenterAlertStyleConfiguration","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterAlertStyleConfiguration","url":"\/documentation\/airshippreferencecenter\/preferencecenteralertstyleconfiguration","role":"symbol","navigatorTitle":[{"text":"PreferenceCenterAlertStyleConfiguration","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreferenceCenterAlertStyleConfiguration","kind":"identifier"}]},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterContent":{"title":"PreferenceCenterContent","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterContent","abstract":[{"type":"text","text":"The core view for the Airship Preference Center."},{"type":"text","text":" "},{"type":"text","text":"This view is responsible for loading and displaying the preference center content. For a navigation controller, see "},{"type":"codeVoice","code":"PreferenceCenterView"},{"type":"text","text":"."}],"url":"\/documentation\/airshippreferencecenter\/preferencecentercontent","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreferenceCenterContent","kind":"identifier"}],"navigatorTitle":[{"text":"PreferenceCenterContent","kind":"identifier"}]},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/AirshipPreferenceCenterVersionString":{"kind":"symbol","url":"\/documentation\/airshippreferencecenter\/airshippreferencecenterversionstring","abstract":[{"type":"text","text":"Project version string for AirshipPreferenceCenter."}],"type":"topic","title":"AirshipPreferenceCenterVersionString","fragments":[{"text":"AirshipPreferenceCenterVersionString","kind":"identifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/AirshipPreferenceCenterVersionString","role":"symbol"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/DefaultPreferenceCenterAlertStyle":{"title":"DefaultPreferenceCenterAlertStyle","abstract":[{"text":"The default Preference Center alert style","type":"text"}],"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/DefaultPreferenceCenterAlertStyle","url":"\/documentation\/airshippreferencecenter\/defaultpreferencecenteralertstyle","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DefaultPreferenceCenterAlertStyle","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"DefaultPreferenceCenterAlertStyle","kind":"identifier"}],"kind":"symbol"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/ContactManagementSectionStyle":{"navigatorTitle":[{"text":"ContactManagementSectionStyle","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/ContactManagementSectionStyle","title":"ContactManagementSectionStyle","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactManagementSectionStyle","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Contact management section style","type":"text"}],"url":"\/documentation\/airshippreferencecenter\/contactmanagementsectionstyle","role":"symbol"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterState":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreferenceCenterState"}],"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterState","abstract":[{"text":"Preference Center State","type":"text"}],"title":"PreferenceCenterState","url":"\/documentation\/airshippreferencecenter\/preferencecenterstate","navigatorTitle":[{"kind":"identifier","text":"PreferenceCenterState"}],"type":"topic"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/AirshipPreferenceCenterVersionNumber":{"title":"AirshipPreferenceCenterVersionNumber","type":"topic","kind":"symbol","fragments":[{"text":"AirshipPreferenceCenterVersionNumber","kind":"identifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/AirshipPreferenceCenterVersionNumber","abstract":[{"type":"text","text":"Project version number for AirshipPreferenceCenter."}],"url":"\/documentation\/airshippreferencecenter\/airshippreferencecenterversionnumber","role":"symbol"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterAlertView":{"title":"PreferenceCenterAlertView","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterAlertView","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PreferenceCenterAlertView"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreferenceCenterAlertView"}],"kind":"symbol","url":"\/documentation\/airshippreferencecenter\/preferencecenteralertview","abstract":[{"text":"The Preference Center alert item view","type":"text"}]},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterContentStyle":{"title":"PreferenceCenterContentStyle","url":"\/documentation\/airshippreferencecenter\/preferencecentercontentstyle","abstract":[{"text":"Preference Center view style","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreferenceCenterContentStyle"}],"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterContentStyle","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PreferenceCenterContentStyle"}]},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterAlertStyle":{"title":"PreferenceCenterAlertStyle","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterAlertStyle","navigatorTitle":[{"kind":"identifier","text":"PreferenceCenterAlertStyle"}],"url":"\/documentation\/airshippreferencecenter\/preferencecenteralertstyle","abstract":[{"text":"Preference Center alert style","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreferenceCenterAlertStyle"}]},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterContactManagementView":{"abstract":[],"navigatorTitle":[{"text":"PreferenceCenterContactManagementView","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterContactManagementView","title":"PreferenceCenterContactManagementView","url":"\/documentation\/airshippreferencecenter\/preferencecentercontactmanagementview","kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreferenceCenterContactManagementView","kind":"identifier"}]},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/DefaultLabeledSectionBreakStyle":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultLabeledSectionBreakStyle"}],"navigatorTitle":[{"kind":"identifier","text":"DefaultLabeledSectionBreakStyle"}],"type":"topic","title":"DefaultLabeledSectionBreakStyle","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/DefaultLabeledSectionBreakStyle","url":"\/documentation\/airshippreferencecenter\/defaultlabeledsectionbreakstyle","abstract":[{"type":"text","text":"Default labeled section break style"}]},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/ContactSubscriptionViewStyleConfiguration":{"title":"ContactSubscriptionViewStyleConfiguration","type":"topic","url":"\/documentation\/airshippreferencecenter\/contactsubscriptionviewstyleconfiguration","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/ContactSubscriptionViewStyleConfiguration","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactSubscriptionViewStyleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"ContactSubscriptionViewStyleConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Contact subscription item view style configuration"}],"role":"symbol"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/ContactManagementSectionStyleConfiguration":{"abstract":[{"type":"text","text":"The labeled section break style configuration"}],"navigatorTitle":[{"kind":"identifier","text":"ContactManagementSectionStyleConfiguration"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactManagementSectionStyleConfiguration"}],"title":"ContactManagementSectionStyleConfiguration","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/ContactManagementSectionStyleConfiguration","type":"topic","url":"\/documentation\/airshippreferencecenter\/contactmanagementsectionstyleconfiguration"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/DefaultContactManagementSectionStyle":{"navigatorTitle":[{"text":"DefaultContactManagementSectionStyle","kind":"identifier"}],"title":"DefaultContactManagementSectionStyle","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/DefaultContactManagementSectionStyle","abstract":[{"type":"text","text":"Default contact management section style. Also styles alert views."}],"url":"\/documentation\/airshippreferencecenter\/defaultcontactmanagementsectionstyle","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DefaultContactManagementSectionStyle","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterConfig":{"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreferenceCenterConfig"}],"navigatorTitle":[{"kind":"identifier","text":"PreferenceCenterConfig"}],"role":"symbol","url":"\/documentation\/airshippreferencecenter\/preferencecenterconfig","title":"PreferenceCenterConfig","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterConfig","type":"topic","abstract":[{"type":"text","text":"Preference center config."}]},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/AddChannelState":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AddChannelState"}],"kind":"symbol","title":"AddChannelState","navigatorTitle":[{"kind":"identifier","text":"AddChannelState"}],"type":"topic","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/AddChannelState","url":"\/documentation\/airshippreferencecenter\/addchannelstate","role":"symbol"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/ContactSubscriptionGroupStyleConfiguration":{"type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactSubscriptionGroupStyleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"ContactSubscriptionGroupStyleConfiguration","kind":"identifier"}],"kind":"symbol","title":"ContactSubscriptionGroupStyleConfiguration","abstract":[{"type":"text","text":"The contact subscription group item style config"}],"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/ContactSubscriptionGroupStyleConfiguration","url":"\/documentation\/airshippreferencecenter\/contactsubscriptiongroupstyleconfiguration"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterOpenDelegate":{"navigatorTitle":[{"text":"PreferenceCenterOpenDelegate","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterOpenDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreferenceCenterOpenDelegate","kind":"identifier"}],"url":"\/documentation\/airshippreferencecenter\/preferencecenteropendelegate","title":"PreferenceCenterOpenDelegate","abstract":[{"text":"Open delegate.","type":"text"}]},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/LabeledSectionBreakStyle":{"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"LabeledSectionBreakStyle"}],"abstract":[{"text":"Labeled section break style","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"LabeledSectionBreakStyle"}],"title":"LabeledSectionBreakStyle","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/LabeledSectionBreakStyle","url":"\/documentation\/airshippreferencecenter\/labeledsectionbreakstyle","role":"symbol"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterConfigSectionType":{"abstract":[{"text":"Preference config section type.","type":"text"}],"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterConfigSectionType","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PreferenceCenterConfigSectionType"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreferenceCenterConfigSectionType"}],"url":"\/documentation\/airshippreferencecenter\/preferencecenterconfigsectiontype","title":"PreferenceCenterConfigSectionType"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterTheme":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreferenceCenterTheme"}],"url":"\/documentation\/airshippreferencecenter\/preferencecentertheme","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Preference Center theme"}],"role":"symbol","title":"PreferenceCenterTheme","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterTheme","navigatorTitle":[{"kind":"identifier","text":"PreferenceCenterTheme"}]},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenter":{"type":"topic","navigatorTitle":[{"text":"PreferenceCenter","kind":"identifier"}],"title":"PreferenceCenter","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenter","abstract":[{"type":"text","text":"An interface for interacting with Airship’s Preference Center."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreferenceCenter","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/airshippreferencecenter\/preferencecenter","role":"symbol"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/ChannelTextField":{"type":"topic","navigatorTitle":[{"text":"ChannelTextField","kind":"identifier"}],"abstract":[],"title":"ChannelTextField","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChannelTextField","kind":"identifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/ChannelTextField","url":"\/documentation\/airshippreferencecenter\/channeltextfield","kind":"symbol","role":"symbol"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterConfigItem":{"navigatorTitle":[{"text":"PreferenceCenterConfigItem","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterConfigItem","url":"\/documentation\/airshippreferencecenter\/preferencecenterconfigitem","abstract":[{"text":"Preference section item info.","type":"text"}],"kind":"symbol","title":"PreferenceCenterConfigItem","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreferenceCenterConfigItem","kind":"identifier"}]},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter":{"url":"\/documentation\/airshippreferencecenter","kind":"symbol","role":"collection","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter","title":"AirshipPreferenceCenter","type":"topic"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterConfigItemType":{"role":"symbol","title":"PreferenceCenterConfigItemType","url":"\/documentation\/airshippreferencecenter\/preferencecenterconfigitemtype","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreferenceCenterConfigItemType"}],"kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterConfigItemType","navigatorTitle":[{"kind":"identifier","text":"PreferenceCenterConfigItemType"}],"abstract":[{"type":"text","text":"Item types."}]},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterViewControllerFactory":{"title":"PreferenceCenterViewControllerFactory","navigatorTitle":[{"text":"PreferenceCenterViewControllerFactory","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreferenceCenterViewControllerFactory","kind":"identifier"}],"abstract":[{"type":"text","text":"View factories for Preference Center view controllers"}],"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterViewControllerFactory","url":"\/documentation\/airshippreferencecenter\/preferencecenterviewcontrollerfactory"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/ChannelSubscriptionView":{"url":"\/documentation\/airshippreferencecenter\/channelsubscriptionview","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/ChannelSubscriptionView","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChannelSubscriptionView","kind":"identifier"}],"role":"symbol","title":"ChannelSubscriptionView","abstract":[{"text":"The channel subscription item view","type":"text"}],"type":"topic","navigatorTitle":[{"text":"ChannelSubscriptionView","kind":"identifier"}],"kind":"symbol"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/AirshipPreferenceCenterResources":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AirshipPreferenceCenterResources"}],"url":"\/documentation\/airshippreferencecenter\/airshippreferencecenterresources","title":"AirshipPreferenceCenterResources","role":"symbol","abstract":[{"type":"text","text":"Resources for AirshipPreferenceCenter."}],"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/AirshipPreferenceCenterResources","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AirshipPreferenceCenterResources"}]},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/CommonSectionViewStyleConfiguration":{"title":"CommonSectionViewStyleConfiguration","kind":"symbol","url":"\/documentation\/airshippreferencecenter\/commonsectionviewstyleconfiguration","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/CommonSectionViewStyleConfiguration","type":"topic","abstract":[{"text":"Common section style configuration","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"CommonSectionViewStyleConfiguration","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommonSectionViewStyleConfiguration","kind":"identifier"}]},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterSDKModule":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"PreferenceCenterSDKModule","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"AirshipPreferenceCenter module loader."}],"url":"\/documentation\/airshippreferencecenter\/preferencecentersdkmodule","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PreferenceCenterSDKModule","kind":"identifier"}],"title":"PreferenceCenterSDKModule","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterSDKModule"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"generated":true,"identifiers":["doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterSDKModule","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterViewControllerFactory"],"anchor":"Classes","title":"Classes"},{"generated":true,"identifiers":["doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/AirshipPreferenceCenterVersionNumber","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/AirshipPreferenceCenterVersionString"],"anchor":"Variables","title":"Variables"}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":"PreferenceCenterViewControllerFactory","path":"\/references\/doc:~1~1com.urbanairship.AirshipPreferenceCenter~1documentation~1AirshipPreferenceCenter~1PreferenceCenterViewControllerFactory\/title","op":"replace"},{"value":[{"text":"PreferenceCenterViewControllerFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipPreferenceCenter~1documentation~1AirshipPreferenceCenter~1PreferenceCenterViewControllerFactory\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"PreferenceCenterViewControllerFactory"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipPreferenceCenter~1documentation~1AirshipPreferenceCenter~1PreferenceCenterViewControllerFactory\/navigatorTitle","op":"replace"},{"value":"UAPreferenceCenterSDKModule","path":"\/references\/doc:~1~1com.urbanairship.AirshipPreferenceCenter~1documentation~1AirshipPreferenceCenter~1PreferenceCenterSDKModule\/title","op":"replace"},{"value":[{"text":"UAPreferenceCenterSDKModule","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipPreferenceCenter~1documentation~1AirshipPreferenceCenter~1PreferenceCenterSDKModule\/fragments","op":"replace"},{"value":[{"text":"UAPreferenceCenterSDKModule","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipPreferenceCenter~1documentation~1AirshipPreferenceCenter~1PreferenceCenterSDKModule\/navigatorTitle","op":"replace"}]}]}