{"kind":"symbol","variants":[{"paths":["\/documentation\/airshippreferencecenter\/preferencecenterviewcontrollerfactory\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterViewControllerFactory"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"title":"init","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"init"}],"roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@AirshipPreferenceCenter@objc(cs)PreferenceCenterViewControllerFactory(im)init","modules":[{"name":"AirshipPreferenceCenter"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},"identifier":{"url":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterViewControllerFactory\/init","interfaceLanguage":"occ"},"references":{"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterViewControllerFactory":{"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterViewControllerFactory","kind":"symbol","role":"symbol","url":"\/documentation\/airshippreferencecenter\/preferencecenterviewcontrollerfactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreferenceCenterViewControllerFactory"}],"abstract":[{"text":"View factories for Preference Center view controllers","type":"text"}],"title":"PreferenceCenterViewControllerFactory","navigatorTitle":[{"kind":"identifier","text":"PreferenceCenterViewControllerFactory"}]},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter":{"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter","title":"AirshipPreferenceCenter","role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/airshippreferencecenter","abstract":[]},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterViewControllerFactory/init":{"kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterViewControllerFactory\/init","title":"init","abstract":[],"role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/airshippreferencecenter\/preferencecenterviewcontrollerfactory\/init","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.urbanairship.AirshipPreferenceCenter~1documentation~1AirshipPreferenceCenter~1PreferenceCenterViewControllerFactory\/title","op":"replace","value":"PreferenceCenterViewControllerFactory"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipPreferenceCenter~1documentation~1AirshipPreferenceCenter~1PreferenceCenterViewControllerFactory\/fragments","op":"replace","value":[{"text":"PreferenceCenterViewControllerFactory","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipPreferenceCenter~1documentation~1AirshipPreferenceCenter~1PreferenceCenterViewControllerFactory\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"PreferenceCenterViewControllerFactory"}]}]}]}