{"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterViewControllerFactory"]]},"abstract":[{"text":"Makes a view controller for the given view  and theme.","type":"text"}],"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterViewControllerFactory\/makeViewController(view:preferenceCenterTheme:dismissAction:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"makeViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"view","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PreferenceCenterView","kind":"typeIdentifier","preciseIdentifier":"s:23AirshipPreferenceCenter0bC4ViewV","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterView"},{"text":", ","kind":"text"},{"text":"preferenceCenterTheme","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PreferenceCenterTheme","kind":"typeIdentifier","preciseIdentifier":"s:23AirshipPreferenceCenter0bC5ThemeV","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterTheme"},{"text":"?, ","kind":"text"},{"text":"dismissAction","kind":"externalParam"},{"text":": (@","kind":"text"},{"text":"MainActor","kind":"typeIdentifier","preciseIdentifier":"s:ScM"},{"text":" () -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")? = nil) -> ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The theme.","type":"text"}]}],"name":"preferenceCenterTheme"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Optional action to dismiss the view controller.","type":"text"}]}],"name":"dismissAction"}],"kind":"parameters"},{"content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"A view controller."}]}],"kind":"content"}],"metadata":{"roleHeading":"Type Method","modules":[{"name":"AirshipPreferenceCenter"}],"title":"makeViewController(view:preferenceCenterTheme:dismissAction:)","externalID":"s:23AirshipPreferenceCenter0bC21ViewControllerFactoryC04makedE04view010preferenceC5Theme13dismissActionSo06UIViewE0CAA0bcD0V_AA0bcJ0VSgyyYbScMYccSgtFZ","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"makeViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"view","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PreferenceCenterView","preciseIdentifier":"s:23AirshipPreferenceCenter0bC4ViewV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"preferenceCenterTheme","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PreferenceCenterTheme","preciseIdentifier":"s:23AirshipPreferenceCenter0bC5ThemeV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"dismissAction","kind":"externalParam"},{"text":": (@","kind":"text"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"typeIdentifier"},{"text":" () -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"}],"role":"symbol","symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshippreferencecenter\/preferencecenterviewcontrollerfactory\/makeviewcontroller(view:preferencecentertheme:dismissaction:)"]}],"references":{"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter":{"kind":"symbol","title":"AirshipPreferenceCenter","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter","url":"\/documentation\/airshippreferencecenter","abstract":[],"type":"topic","role":"collection"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterViewControllerFactory/makeViewController(view:preferenceCenterTheme:dismissAction:)":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterViewControllerFactory\/makeViewController(view:preferenceCenterTheme:dismissAction:)","title":"makeViewController(view:preferenceCenterTheme:dismissAction:)","url":"\/documentation\/airshippreferencecenter\/preferencecenterviewcontrollerfactory\/makeviewcontroller(view:preferencecentertheme:dismissaction:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"makeViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"view","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:23AirshipPreferenceCenter0bC4ViewV","text":"PreferenceCenterView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"preferenceCenterTheme","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PreferenceCenterTheme","preciseIdentifier":"s:23AirshipPreferenceCenter0bC5ThemeV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"dismissAction"},{"kind":"text","text":": (@"},{"kind":"typeIdentifier","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?) -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"abstract":[{"type":"text","text":"Makes a view controller for the given view  and theme."}],"type":"topic"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterView":{"abstract":[{"type":"text","text":"The main view for the Airship Preference Center. This view provides a navigation stack."},{"type":"text","text":" "},{"type":"text","text":"If you wish to provide your own navigation, see "},{"type":"codeVoice","code":"PreferenceCenterContent"},{"type":"text","text":"."}],"title":"PreferenceCenterView","kind":"symbol","url":"\/documentation\/airshippreferencecenter\/preferencecenterview","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreferenceCenterView"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PreferenceCenterView"}],"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterView"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterViewControllerFactory":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreferenceCenterViewControllerFactory"}],"abstract":[{"text":"View factories for Preference Center view controllers","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PreferenceCenterViewControllerFactory"}],"url":"\/documentation\/airshippreferencecenter\/preferencecenterviewcontrollerfactory","type":"topic","title":"PreferenceCenterViewControllerFactory","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterViewControllerFactory"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterTheme":{"role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreferenceCenterTheme"}],"title":"PreferenceCenterTheme","abstract":[{"text":"Preference Center theme","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PreferenceCenterTheme"}],"kind":"symbol","url":"\/documentation\/airshippreferencecenter\/preferencecentertheme","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterTheme"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"PreferenceCenterViewControllerFactory","path":"\/references\/doc:~1~1com.urbanairship.AirshipPreferenceCenter~1documentation~1AirshipPreferenceCenter~1PreferenceCenterViewControllerFactory\/title"},{"op":"replace","value":[{"text":"PreferenceCenterViewControllerFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipPreferenceCenter~1documentation~1AirshipPreferenceCenter~1PreferenceCenterViewControllerFactory\/fragments"},{"op":"replace","value":[{"text":"PreferenceCenterViewControllerFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipPreferenceCenter~1documentation~1AirshipPreferenceCenter~1PreferenceCenterViewControllerFactory\/navigatorTitle"}]}]}