{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterViewControllerFactory"]]},"identifier":{"url":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterViewControllerFactory\/makeViewController(preferenceCenterID:preferenceCenterThemePlist:)","interfaceLanguage":"swift"},"abstract":[{"text":"Makes a view controller for the given Preference Center ID and theme.","type":"text"}],"variants":[{"paths":["\/documentation\/airshippreferencecenter\/preferencecenterviewcontrollerfactory\/makeviewcontroller(preferencecenterid:preferencecenterthemeplist:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","metadata":{"modules":[{"name":"AirshipPreferenceCenter"}],"title":"makeViewController(preferenceCenterID:preferenceCenterThemePlist:)","role":"symbol","roleHeading":"Type Method","symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"makeViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"preferenceCenterID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"preferenceCenterThemePlist","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}],"externalID":"s:23AirshipPreferenceCenter0bC21ViewControllerFactoryC04makedE0010preferenceC2ID0hC10ThemePlistSo06UIViewE0CSS_SStKFZ"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"preferenceCenterID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"preferenceCenterThemePlist"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"preferenceCenterID","content":[{"inlineContent":[{"type":"text","text":"The preferenceCenterID."}],"type":"paragraph"}]},{"name":"preferenceCenterThemePlist","content":[{"inlineContent":[{"text":"The theme plist.","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"A view controller.","type":"text"}],"type":"paragraph"}]}],"references":{"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterViewControllerFactory/makeViewController(preferenceCenterID:preferenceCenterThemePlist:)":{"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterViewControllerFactory\/makeViewController(preferenceCenterID:preferenceCenterThemePlist:)","abstract":[{"text":"Makes a view controller for the given Preference Center ID and theme.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"preferenceCenterID"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"preferenceCenterThemePlist"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"}],"role":"symbol","title":"makeViewController(preferenceCenterID:preferenceCenterThemePlist:)","kind":"symbol","url":"\/documentation\/airshippreferencecenter\/preferencecenterviewcontrollerfactory\/makeviewcontroller(preferencecenterid:preferencecenterthemeplist:)","type":"topic"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter":{"abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter","kind":"symbol","title":"AirshipPreferenceCenter","url":"\/documentation\/airshippreferencecenter"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterViewControllerFactory":{"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterViewControllerFactory","abstract":[{"text":"View factories for Preference Center view controllers","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreferenceCenterViewControllerFactory"}],"role":"symbol","title":"PreferenceCenterViewControllerFactory","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PreferenceCenterViewControllerFactory"}],"type":"topic","url":"\/documentation\/airshippreferencecenter\/preferencecenterviewcontrollerfactory"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipPreferenceCenter~1documentation~1AirshipPreferenceCenter~1PreferenceCenterViewControllerFactory\/title","value":"PreferenceCenterViewControllerFactory"},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipPreferenceCenter~1documentation~1AirshipPreferenceCenter~1PreferenceCenterViewControllerFactory\/fragments","value":[{"kind":"identifier","text":"PreferenceCenterViewControllerFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipPreferenceCenter~1documentation~1AirshipPreferenceCenter~1PreferenceCenterViewControllerFactory\/navigatorTitle","value":[{"kind":"identifier","text":"PreferenceCenterViewControllerFactory"}]}]}]}