{"abstract":[{"text":"Makes a view controller for the given Preference Center ID.","type":"text"}],"metadata":{"title":"makeViewController(preferenceCenterID:dismissAction:)","role":"symbol","modules":[{"name":"AirshipPreferenceCenter"}],"symbolKind":"method","externalID":"s:23AirshipPreferenceCenter0bC21ViewControllerFactoryC04makedE0010preferenceC2ID13dismissActionSo06UIViewE0CSS_yyYbcSgtFZ","roleHeading":"Type Method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"makeViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"preferenceCenterID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"dismissAction","kind":"externalParam"},{"text":": (() -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?) -> ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}]},"variants":[{"paths":["\/documentation\/airshippreferencecenter\/preferencecenterviewcontrollerfactory\/makeviewcontroller(preferencecenterid:dismissaction:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"makeViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"preferenceCenterID","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dismissAction","kind":"externalParam"},{"text":": (() -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")? = nil) -> ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"}],"platforms":["Mac Catalyst"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The preferenceCenterID.","type":"text"}]}],"name":"preferenceCenterID"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Optional action to dismiss the view controller.","type":"text"}]}],"name":"dismissAction"}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"inlineContent":[{"type":"text","text":"A view controller."}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterViewControllerFactory"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterViewControllerFactory\/makeViewController(preferenceCenterID:dismissAction:)","interfaceLanguage":"swift"},"references":{"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterViewControllerFactory/makeViewController(preferenceCenterID:dismissAction:)":{"role":"symbol","url":"\/documentation\/airshippreferencecenter\/preferencecenterviewcontrollerfactory\/makeviewcontroller(preferencecenterid:dismissaction:)","kind":"symbol","abstract":[{"text":"Makes a view controller for the given Preference Center ID.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"preferenceCenterID"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dismissAction"},{"kind":"text","text":": (() -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?) -> "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"}],"type":"topic","title":"makeViewController(preferenceCenterID:dismissAction:)","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterViewControllerFactory\/makeViewController(preferenceCenterID:dismissAction:)"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter":{"abstract":[],"url":"\/documentation\/airshippreferencecenter","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter","type":"topic","title":"AirshipPreferenceCenter","kind":"symbol","role":"collection"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterViewControllerFactory":{"role":"symbol","url":"\/documentation\/airshippreferencecenter\/preferencecenterviewcontrollerfactory","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PreferenceCenterViewControllerFactory"}],"abstract":[{"text":"View factories for Preference Center view controllers","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreferenceCenterViewControllerFactory"}],"type":"topic","title":"PreferenceCenterViewControllerFactory","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterViewControllerFactory"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"PreferenceCenterViewControllerFactory","path":"\/references\/doc:~1~1com.urbanairship.AirshipPreferenceCenter~1documentation~1AirshipPreferenceCenter~1PreferenceCenterViewControllerFactory\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipPreferenceCenter~1documentation~1AirshipPreferenceCenter~1PreferenceCenterViewControllerFactory\/fragments","value":[{"kind":"identifier","text":"PreferenceCenterViewControllerFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipPreferenceCenter~1documentation~1AirshipPreferenceCenter~1PreferenceCenterViewControllerFactory\/navigatorTitle","value":[{"text":"PreferenceCenterViewControllerFactory","kind":"identifier"}]}]}]}