{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterViewControllerFactory"]]},"identifier":{"url":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterViewControllerFactory\/init","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst"],"languages":["occ"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airshipmessagecenter\/messagecenterviewcontrollerfactory\/init"]}],"metadata":{"symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"title":"init","externalID":"c:@M@AirshipMessageCenter@objc(cs)MessageCenterViewControllerFactory(im)init","navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol","roleHeading":"Instance Method","modules":[{"name":"AirshipMessageCenter"}]},"sections":[],"kind":"symbol","references":{"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterViewControllerFactory/init":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"type":"topic","url":"\/documentation\/airshipmessagecenter\/messagecenterviewcontrollerfactory\/init","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterViewControllerFactory\/init","abstract":[],"title":"init"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter":{"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter","type":"topic","title":"AirshipMessageCenter","kind":"symbol","role":"collection","abstract":[],"url":"\/documentation\/airshipmessagecenter"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterViewControllerFactory":{"navigatorTitle":[{"kind":"identifier","text":"MessageCenterViewControllerFactory"}],"type":"topic","abstract":[{"text":"View controller for Message Center view","type":"text"}],"title":"MessageCenterViewControllerFactory","url":"\/documentation\/airshipmessagecenter\/messagecenterviewcontrollerfactory","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCenterViewControllerFactory"}],"kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterViewControllerFactory"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterViewControllerFactory\/title","value":"MessageCenterViewControllerFactory"},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterViewControllerFactory\/fragments","value":[{"kind":"identifier","text":"MessageCenterViewControllerFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterViewControllerFactory\/navigatorTitle","value":[{"text":"MessageCenterViewControllerFactory","kind":"identifier"}]}]}]}