{"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterViewControllerFactory"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["Mac Catalyst"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"make","kind":"identifier"},{"text":"(","kind":"text"},{"text":"themePlist","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"controller","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:20AirshipMessageCenter0bC10ControllerC","text":"MessageCenterController","kind":"typeIdentifier","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterController"},{"text":", ","kind":"text"},{"text":"dismissAction","kind":"externalParam"},{"text":": (() -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")? = nil) ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"}]}]},{"kind":"parameters","parameters":[{"name":"themePlist","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A path to a theme plist"}]}]},{"name":"controller","content":[{"inlineContent":[{"text":"The Message Center controller","type":"text"}],"type":"paragraph"}]},{"name":"dismissAction","content":[{"inlineContent":[{"text":"Optional action to dismiss the view controller.","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"type":"text","text":"A view controller."}],"type":"paragraph"}]}],"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/airshipmessagecenter\/messagecenterviewcontrollerfactory\/make(themeplist:controller:dismissaction:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterViewControllerFactory\/make(themePlist:controller:dismissAction:)"},"abstract":[{"text":"Makes a message view controller with the given theme.","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"AirshipMessageCenter"}],"symbolKind":"method","role":"symbol","externalID":"s:20AirshipMessageCenter0bC21ViewControllerFactoryC4make10themePlist10controller13dismissActionSo06UIViewE0CSSSg_AA0bcE0CyyYbcSgtKFZ","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"make"},{"kind":"text","text":"("},{"kind":"externalParam","text":"themePlist"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageCenterController","preciseIdentifier":"s:20AirshipMessageCenter0bC10ControllerC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dismissAction"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"roleHeading":"Type Method","title":"make(themePlist:controller:dismissAction:)"},"references":{"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter":{"kind":"symbol","title":"AirshipMessageCenter","url":"\/documentation\/airshipmessagecenter","abstract":[],"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter","role":"collection"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterViewControllerFactory/make(themePlist:controller:dismissAction:)":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"make","kind":"identifier"},{"text":"(","kind":"text"},{"text":"themePlist","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"controller","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:20AirshipMessageCenter0bC10ControllerC","text":"MessageCenterController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dismissAction"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"}],"url":"\/documentation\/airshipmessagecenter\/messagecenterviewcontrollerfactory\/make(themeplist:controller:dismissaction:)","role":"symbol","type":"topic","title":"make(themePlist:controller:dismissAction:)","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterViewControllerFactory\/make(themePlist:controller:dismissAction:)","abstract":[{"text":"Makes a message view controller with the given theme.","type":"text"}]},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCenterController"}],"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterController","abstract":[{"text":"Controller for the Message Center.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MessageCenterController"}],"title":"MessageCenterController","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/airshipmessagecenter\/messagecentercontroller"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterViewControllerFactory":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterViewControllerFactory","url":"\/documentation\/airshipmessagecenter\/messagecenterviewcontrollerfactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCenterViewControllerFactory"}],"title":"MessageCenterViewControllerFactory","navigatorTitle":[{"kind":"identifier","text":"MessageCenterViewControllerFactory"}],"kind":"symbol","abstract":[{"type":"text","text":"View controller for Message Center view"}]}},"variantOverrides":[{"patch":[{"value":"MessageCenterViewControllerFactory","path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterViewControllerFactory\/title","op":"replace"},{"value":[{"text":"MessageCenterViewControllerFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterViewControllerFactory\/fragments","op":"replace"},{"value":[{"text":"MessageCenterViewControllerFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterViewControllerFactory\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}