{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterViewControllerFactory\/make(theme:predicate:controller:dismissAction:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"make","kind":"identifier"},{"text":"(","kind":"text"},{"text":"theme","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessageCenterTheme","preciseIdentifier":"s:20AirshipMessageCenter0bC5ThemeV","kind":"typeIdentifier","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterTheme"},{"text":"? = nil, ","kind":"text"},{"text":"predicate","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageCenterPredicate","preciseIdentifier":"s:20AirshipMessageCenter0bC9PredicateP","kind":"typeIdentifier","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterPredicate"},{"text":")? = nil, ","kind":"text"},{"text":"controller","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessageCenterController","preciseIdentifier":"s:20AirshipMessageCenter0bC10ControllerC","kind":"typeIdentifier","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterController"},{"text":", ","kind":"text"},{"text":"dismissAction","kind":"externalParam"},{"text":": (@","kind":"text"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"typeIdentifier"},{"text":" () -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")? = nil) -> ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"The message center theme.","type":"text"}],"type":"paragraph"}],"name":"theme"},{"content":[{"inlineContent":[{"text":"The message center predicate.","type":"text"}],"type":"paragraph"}],"name":"predicate"},{"content":[{"inlineContent":[{"type":"text","text":"The Message Center controller"}],"type":"paragraph"}],"name":"controller"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Optional action to dismiss the view controller.","type":"text"}]}],"name":"dismissAction"}],"kind":"parameters"},{"content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"A view controller.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"symbolKind":"method","title":"make(theme:predicate:controller:dismissAction:)","externalID":"s:20AirshipMessageCenter0bC21ViewControllerFactoryC4make5theme9predicate10controller13dismissActionSo06UIViewE0CAA0bC5ThemeVSg_AA0bC9Predicate_pSgAA0bcE0CyyYbScMYccSgtFZ","modules":[{"name":"AirshipMessageCenter"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"make"},{"kind":"text","text":"("},{"kind":"externalParam","text":"theme"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageCenterTheme","preciseIdentifier":"s:20AirshipMessageCenter0bC5ThemeV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"predicate"},{"kind":"text","text":": ("},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageCenterPredicate","kind":"typeIdentifier","preciseIdentifier":"s:20AirshipMessageCenter0bC9PredicateP"},{"text":")?, ","kind":"text"},{"text":"controller","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessageCenterController","kind":"typeIdentifier","preciseIdentifier":"s:20AirshipMessageCenter0bC10ControllerC"},{"text":", ","kind":"text"},{"text":"dismissAction","kind":"externalParam"},{"text":": (@","kind":"text"},{"text":"MainActor","kind":"typeIdentifier","preciseIdentifier":"s:ScM"},{"text":" () -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?) -> ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}],"role":"symbol","roleHeading":"Type Method"},"kind":"symbol","abstract":[{"text":"Makes a message view controller with the given theme.","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipmessagecenter\/messagecenterviewcontrollerfactory\/make(theme:predicate:controller:dismissaction:)"]}],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterViewControllerFactory"]]},"references":{"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterViewControllerFactory/make(theme:predicate:controller:dismissAction:)":{"title":"make(theme:predicate:controller:dismissAction:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"make"},{"kind":"text","text":"("},{"kind":"externalParam","text":"theme"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:20AirshipMessageCenter0bC5ThemeV","text":"MessageCenterTheme"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"predicate"},{"text":": (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageCenterPredicate","preciseIdentifier":"s:20AirshipMessageCenter0bC9PredicateP","kind":"typeIdentifier"},{"text":")?, ","kind":"text"},{"text":"controller","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessageCenterController","preciseIdentifier":"s:20AirshipMessageCenter0bC10ControllerC","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dismissAction","kind":"externalParam"},{"text":": (@","kind":"text"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"typeIdentifier"},{"text":" () -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?) -> ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Makes a message view controller with the given theme."}],"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterViewControllerFactory\/make(theme:predicate:controller:dismissAction:)","kind":"symbol","url":"\/documentation\/airshipmessagecenter\/messagecenterviewcontrollerfactory\/make(theme:predicate:controller:dismissaction:)"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter":{"kind":"symbol","role":"collection","title":"AirshipMessageCenter","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter","abstract":[],"url":"\/documentation\/airshipmessagecenter"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterViewControllerFactory":{"role":"symbol","abstract":[{"type":"text","text":"View controller for Message Center view"}],"navigatorTitle":[{"text":"MessageCenterViewControllerFactory","kind":"identifier"}],"type":"topic","title":"MessageCenterViewControllerFactory","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageCenterViewControllerFactory","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterViewControllerFactory","url":"\/documentation\/airshipmessagecenter\/messagecenterviewcontrollerfactory"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterTheme":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCenterTheme"}],"navigatorTitle":[{"kind":"identifier","text":"MessageCenterTheme"}],"type":"topic","url":"\/documentation\/airshipmessagecenter\/messagecentertheme","abstract":[{"type":"text","text":"Model object representing a custom theme to be applied to the default message center."}],"title":"MessageCenterTheme","role":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterTheme","kind":"symbol"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterController":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"MessageCenterController","kind":"identifier"}],"url":"\/documentation\/airshipmessagecenter\/messagecentercontroller","title":"MessageCenterController","kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterController","abstract":[{"type":"text","text":"Controller for the Message Center."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageCenterController","kind":"identifier"}]},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterPredicate":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageCenterPredicate","kind":"identifier"}],"url":"\/documentation\/airshipmessagecenter\/messagecenterpredicate","abstract":[{"type":"text","text":"Predicate for filtering messages in the Message Center."}],"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterPredicate","title":"MessageCenterPredicate","navigatorTitle":[{"text":"MessageCenterPredicate","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"MessageCenterViewControllerFactory","path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterViewControllerFactory\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MessageCenterViewControllerFactory"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterViewControllerFactory\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MessageCenterViewControllerFactory"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterViewControllerFactory\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}