{"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.urbanairship.AirshipPreferenceCenter\/objc(cs)NSObject"]},{"type":"conformsTo","identifiers":["doc:\/\/com.urbanairship.AirshipPreferenceCenter\/11AirshipCore0A9SDKModuleP","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/objc(pl)NSObject","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/s7CVarArgP","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/s28CustomDebugStringConvertibleP","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/s23CustomStringConvertibleP","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/SQ","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/SH"],"kind":"relationships","title":"Conforms To"}],"sections":[],"identifier":{"url":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterSDKModule","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","externalID":"c:@M@AirshipPreferenceCenter@objc(cs)UAPreferenceCenterSDKModule","modules":[{"name":"AirshipPreferenceCenter"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PreferenceCenterSDKModule"}],"navigatorTitle":[{"kind":"identifier","text":"PreferenceCenterSDKModule"}],"title":"PreferenceCenterSDKModule","symbolKind":"class","roleHeading":"Class"},"abstract":[{"text":"AirshipPreferenceCenter module loader.","type":"text"}],"topicSections":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterSDKModule\/actionsManifest","doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterSDKModule\/components"],"anchor":"Instance-Properties"},{"title":"Type Methods","identifiers":["doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterSDKModule\/load(_:)"],"anchor":"Type-Methods","generated":true}],"variants":[{"paths":["\/documentation\/airshippreferencecenter\/preferencecentersdkmodule"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airshippreferencecenter\/preferencecentersdkmodule"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(UAPreferenceCenterSDKModule) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PreferenceCenterSDKModule"}],"platforms":["Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"overview","type":"heading","text":"Overview","level":2},{"content":[{"inlineContent":[{"text":"For internal use only. :nodoc:","type":"text"}],"type":"paragraph"}],"name":"Note","type":"aside","style":"note"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter"]]},"references":{"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter":{"role":"collection","abstract":[],"title":"AirshipPreferenceCenter","type":"topic","kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter","url":"\/documentation\/airshippreferencecenter"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterSDKModule/components":{"abstract":[],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"components","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"text":"AirshipComponent","kind":"typeIdentifier","preciseIdentifier":"s:11AirshipCore0A9ComponentP"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterSDKModule\/components","url":"\/documentation\/airshippreferencecenter\/preferencecentersdkmodule\/components","kind":"symbol","role":"symbol","title":"components"},"doc://com.urbanairship.AirshipPreferenceCenter/11AirshipCore0A9SDKModuleP":{"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/11AirshipCore0A9SDKModuleP","type":"unresolvable","title":"AirshipCore.AirshipSDKModule"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterSDKModule":{"kind":"symbol","type":"topic","url":"\/documentation\/airshippreferencecenter\/preferencecentersdkmodule","title":"PreferenceCenterSDKModule","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterSDKModule","abstract":[{"text":"AirshipPreferenceCenter module loader.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PreferenceCenterSDKModule"}],"navigatorTitle":[{"text":"PreferenceCenterSDKModule","kind":"identifier"}]},"doc://com.urbanairship.AirshipPreferenceCenter/SQ":{"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterSDKModule/load(_:)":{"role":"symbol","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterSDKModule\/load(_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"load","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AirshiopModuleLoaderArgs","preciseIdentifier":"s:11AirshipCore24AirshiopModuleLoaderArgsV","kind":"typeIdentifier"},{"text":") -> (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:11AirshipCore0A9SDKModuleP","text":"AirshipSDKModule","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"kind":"symbol","url":"\/documentation\/airshippreferencecenter\/preferencecentersdkmodule\/load(_:)","title":"load(_:)","type":"topic"},"doc://com.urbanairship.AirshipPreferenceCenter/documentation/AirshipPreferenceCenter/PreferenceCenterSDKModule/actionsManifest":{"abstract":[],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actionsManifest","kind":"identifier"},{"text":": (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:11AirshipCore15ActionsManifestP","text":"ActionsManifest","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/documentation\/AirshipPreferenceCenter\/PreferenceCenterSDKModule\/actionsManifest","url":"\/documentation\/airshippreferencecenter\/preferencecentersdkmodule\/actionsmanifest","kind":"symbol","role":"symbol","title":"actionsManifest"},"doc://com.urbanairship.AirshipPreferenceCenter/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.urbanairship.AirshipPreferenceCenter/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/objc(cs)NSObject","title":"NSObject"},"doc://com.urbanairship.AirshipPreferenceCenter/SH":{"type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/SH","title":"Swift.Hashable"},"doc://com.urbanairship.AirshipPreferenceCenter/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.urbanairship.AirshipPreferenceCenter/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.urbanairship.AirshipPreferenceCenter/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipPreferenceCenter\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.urbanairship.AirshipPreferenceCenter\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UAPreferenceCenterSDKModule","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"}]}]}