{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterNativeBridgeExtension\/actionsMetadata(for:webView:)"},"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterNativeBridgeExtension"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"externalID":"s:20AirshipMessageCenter0bC21NativeBridgeExtensionC15actionsMetadata3for7webViewSDyS2SG0A4Core17JavaScriptCommandV_So05WKWebK0CtF","title":"actionsMetadata(for:webView:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actionsMetadata","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"JavaScriptCommand","preciseIdentifier":"s:11AirshipCore17JavaScriptCommandV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"webView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"AirshipMessageCenter"}]},"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"NativeBridgeExtensionDelegate.actionsMetadata(for:webView:)"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["Mac Catalyst"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actionsMetadata","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"command","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"JavaScriptCommand","preciseIdentifier":"s:11AirshipCore17JavaScriptCommandV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"webView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipmessagecenter\/messagecenternativebridgeextension\/actionsmetadata(for:webview:)"]}],"references":{"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter":{"title":"AirshipMessageCenter","url":"\/documentation\/airshipmessagecenter","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter","role":"collection"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterNativeBridgeExtension/actionsMetadata(for:webView:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actionsMetadata","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11AirshipCore17JavaScriptCommandV","text":"JavaScriptCommand","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"webView","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterNativeBridgeExtension\/actionsMetadata(for:webView:)","abstract":[],"role":"symbol","title":"actionsMetadata(for:webView:)","kind":"symbol","url":"\/documentation\/airshipmessagecenter\/messagecenternativebridgeextension\/actionsmetadata(for:webview:)"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterNativeBridgeExtension":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageCenterNativeBridgeExtension","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterNativeBridgeExtension","abstract":[{"text":"Airship native bridge extension for the Message Center.","type":"text"}],"role":"symbol","title":"MessageCenterNativeBridgeExtension","kind":"symbol","url":"\/documentation\/airshipmessagecenter\/messagecenternativebridgeextension","navigatorTitle":[{"text":"MessageCenterNativeBridgeExtension","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterNativeBridgeExtension\/title","value":"MessageCenterNativeBridgeExtension"},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterNativeBridgeExtension\/fragments","value":[{"kind":"identifier","text":"MessageCenterNativeBridgeExtension"}]},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterNativeBridgeExtension\/navigatorTitle","value":[{"kind":"identifier","text":"MessageCenterNativeBridgeExtension"}]}]}]}