{"metadata":{"externalID":"s:20AirshipMessageCenter0bC21NativeBridgeExtensionC27extendJavaScriptEnvironment_7webViewy0A4Core0hiJ8Protocol_p_So05WKWebL0CtYaF","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"extendJavaScriptEnvironment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:11AirshipCore29JavaScriptEnvironmentProtocolP","text":"JavaScriptEnvironmentProtocol","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"webView","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"}],"modules":[{"name":"AirshipMessageCenter"}],"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","title":"extendJavaScriptEnvironment(_:webView:)"},"abstract":[{"type":"text","text":"Inherited from "},{"code":"NativeBridgeExtensionDelegate.extendJavaScriptEnvironment(_:webView:)","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"extendJavaScriptEnvironment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"js","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:11AirshipCore29JavaScriptEnvironmentProtocolP","text":"JavaScriptEnvironmentProtocol","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"webView","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"}],"platforms":["Mac Catalyst"]}]}],"variants":[{"paths":["\/documentation\/airshipmessagecenter\/messagecenternativebridgeextension\/extendjavascriptenvironment(_:webview:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterNativeBridgeExtension\/extendJavaScriptEnvironment(_:webView:)"},"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterNativeBridgeExtension"]]},"references":{"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter":{"title":"AirshipMessageCenter","type":"topic","url":"\/documentation\/airshipmessagecenter","role":"collection","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterNativeBridgeExtension":{"navigatorTitle":[{"text":"MessageCenterNativeBridgeExtension","kind":"identifier"}],"url":"\/documentation\/airshipmessagecenter\/messagecenternativebridgeextension","abstract":[{"type":"text","text":"Airship native bridge extension for the Message Center."}],"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterNativeBridgeExtension","title":"MessageCenterNativeBridgeExtension","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageCenterNativeBridgeExtension","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterNativeBridgeExtension/extendJavaScriptEnvironment(_:webView:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"extendJavaScriptEnvironment","kind":"identifier"},{"text":"(","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JavaScriptEnvironmentProtocol","preciseIdentifier":"s:11AirshipCore29JavaScriptEnvironmentProtocolP","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"webView","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"}],"title":"extendJavaScriptEnvironment(_:webView:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterNativeBridgeExtension\/extendJavaScriptEnvironment(_:webView:)","url":"\/documentation\/airshipmessagecenter\/messagecenternativebridgeextension\/extendjavascriptenvironment(_:webview:)","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterNativeBridgeExtension\/title","op":"replace","value":"MessageCenterNativeBridgeExtension"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterNativeBridgeExtension\/fragments","op":"replace","value":[{"kind":"identifier","text":"MessageCenterNativeBridgeExtension"}]},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterNativeBridgeExtension\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MessageCenterNativeBridgeExtension"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}