{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessageCenterMessage","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterMessage","kind":"typeIdentifier","preciseIdentifier":"s:20AirshipMessageCenter0bcB0V"},{"text":", ","kind":"text"},{"text":"user","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessageCenterUser","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterUser","kind":"typeIdentifier","preciseIdentifier":"s:20AirshipMessageCenter0bC4UserV"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]}],"metadata":{"modules":[{"name":"AirshipMessageCenter"}],"externalID":"s:20AirshipMessageCenter0bC21NativeBridgeExtensionC7message4userAcA0bcB0V_AA0bC4UserVtcfc","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessageCenterMessage","preciseIdentifier":"s:20AirshipMessageCenter0bcB0V","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"user","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessageCenterUser","preciseIdentifier":"s:20AirshipMessageCenter0bC4UserV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(message:user:)","role":"symbol","roleHeading":"Initializer","symbolKind":"init"},"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter","doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterNativeBridgeExtension"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterNativeBridgeExtension\/init(message:user:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipmessagecenter\/messagecenternativebridgeextension\/init(message:user:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","references":{"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterUser":{"title":"MessageCenterUser","kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Model object for holding user data."}],"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterUser","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageCenterUser","kind":"identifier"}],"url":"\/documentation\/airshipmessagecenter\/messagecenteruser","navigatorTitle":[{"text":"MessageCenterUser","kind":"identifier"}]},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter":{"kind":"symbol","role":"collection","title":"AirshipMessageCenter","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter","abstract":[],"url":"\/documentation\/airshipmessagecenter"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterMessage":{"navigatorTitle":[{"text":"MessageCenterMessage","kind":"identifier"}],"url":"\/documentation\/airshipmessagecenter\/messagecentermessage","title":"MessageCenterMessage","abstract":[{"text":"Message center message.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageCenterMessage","kind":"identifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterMessage","type":"topic"},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterNativeBridgeExtension":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageCenterNativeBridgeExtension"}],"kind":"symbol","title":"MessageCenterNativeBridgeExtension","url":"\/documentation\/airshipmessagecenter\/messagecenternativebridgeextension","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterNativeBridgeExtension","role":"symbol","abstract":[{"type":"text","text":"Airship native bridge extension for the Message Center."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCenterNativeBridgeExtension"}]},"doc://com.urbanairship.AirshipMessageCenter/documentation/AirshipMessageCenter/MessageCenterNativeBridgeExtension/init(message:user:)":{"type":"topic","kind":"symbol","title":"init(message:user:)","url":"\/documentation\/airshipmessagecenter\/messagecenternativebridgeextension\/init(message:user:)","identifier":"doc:\/\/com.urbanairship.AirshipMessageCenter\/documentation\/AirshipMessageCenter\/MessageCenterNativeBridgeExtension\/init(message:user:)","role":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:20AirshipMessageCenter0bcB0V","text":"MessageCenterMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"user"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:20AirshipMessageCenter0bC4UserV","text":"MessageCenterUser"},{"kind":"text","text":")"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterNativeBridgeExtension\/title","op":"replace","value":"MessageCenterNativeBridgeExtension"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterNativeBridgeExtension\/fragments","op":"replace","value":[{"kind":"identifier","text":"MessageCenterNativeBridgeExtension"}]},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipMessageCenter~1documentation~1AirshipMessageCenter~1MessageCenterNativeBridgeExtension\/navigatorTitle","op":"replace","value":[{"text":"MessageCenterNativeBridgeExtension","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}