{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/jsonpredicate\/evaluate(json:)"]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"evaluate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"json"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11AirshipCore0A4JSONO","kind":"typeIdentifier","text":"AirshipJSON"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"AirshipCore"}],"role":"symbol","title":"evaluate(json:)","externalID":"s:11AirshipCore13JSONPredicateC8evaluate4jsonSbAA0A4JSONO_tF"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Evaluates the given "},{"code":"AirshipJSON","type":"codeVoice"},{"type":"text","text":" value against the predicate."}],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONPredicate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"evaluate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"json"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSON","kind":"typeIdentifier","preciseIdentifier":"s:11AirshipCore0A4JSONO","text":"AirshipJSON"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"platforms":["Mac Catalyst"],"languages":["swift"]}]},{"parameters":[{"name":"json","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"AirshipJSON"},{"type":"text","text":" object to evaluate."}]}]}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"true"},{"type":"text","text":" if the value matches the predicate; otherwise, "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}]}]}],"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONPredicate\/evaluate(json:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONPredicate":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JSONPredicate","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/airshipcore\/jsonpredicate","title":"JSONPredicate","role":"symbol","navigatorTitle":[{"text":"JSONPredicate","kind":"identifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONPredicate","abstract":[{"type":"text","text":"Defines a predicate for evaluating a JSON payload."}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/AirshipJSON":{"type":"topic","title":"AirshipJSON","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AirshipJSON"}],"navigatorTitle":[{"kind":"identifier","text":"AirshipJSON"}],"url":"\/documentation\/airshipcore\/airshipjson","abstract":[{"type":"text","text":"Airship JSON."}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSON","kind":"symbol","role":"symbol"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONPredicate/evaluate(json:)":{"title":"evaluate(json:)","kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONPredicate\/evaluate(json:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"evaluate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"json","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AirshipJSON","kind":"typeIdentifier","preciseIdentifier":"s:11AirshipCore0A4JSONO"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","abstract":[{"type":"text","text":"Evaluates the given "},{"type":"codeVoice","code":"AirshipJSON"},{"type":"text","text":" value against the predicate."}],"role":"symbol","url":"\/documentation\/airshipcore\/jsonpredicate\/evaluate(json:)"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"kind":"symbol","title":"AirshipCore","url":"\/documentation\/airshipcore","abstract":[],"type":"topic","role":"collection","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONPredicate\/title","op":"replace","value":"JSONPredicate"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONPredicate\/fragments","op":"replace","value":[{"kind":"identifier","text":"JSONPredicate"}]},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONPredicate\/navigatorTitle","op":"replace","value":[{"text":"JSONPredicate","kind":"identifier"}]}]}]}