{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"airshipConfig","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AirshipExtensionConfig","kind":"typeIdentifier","preciseIdentifier":"s:35AirshipNotificationServiceExtension0aD6ConfigV","identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/AirshipExtensionConfig"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/airshipnotificationserviceextension\/uanotificationserviceextension\/airshipconfig"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"airshipConfig","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AirshipExtensionConfig","preciseIdentifier":"s:35AirshipNotificationServiceExtension0aD6ConfigV","kind":"typeIdentifier"}],"title":"airshipConfig","role":"symbol","modules":[{"name":"AirshipNotificationServiceExtension"}],"externalID":"s:35AirshipNotificationServiceExtension014UANotificationcD0C13airshipConfigAA0adG0Vvp","roleHeading":"Instance Property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/UANotificationServiceExtension\/airshipConfig"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension","doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/UANotificationServiceExtension"]]},"references":{"doc://com.urbanairship.AirshipNotificationServiceExtension/documentation/AirshipNotificationServiceExtension/AirshipExtensionConfig":{"role":"symbol","abstract":[{"type":"text","text":"Airship extension config. Can be supplied with the property "},{"type":"codeVoice","code":"airshipExtensionConfig"},{"type":"text","text":" in "},{"type":"codeVoice","code":"UANotificationServiceExtension"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"AirshipExtensionConfig"}],"title":"AirshipExtensionConfig","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AirshipExtensionConfig"}],"identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/AirshipExtensionConfig","kind":"symbol","url":"\/documentation\/airshipnotificationserviceextension\/airshipextensionconfig"},"doc://com.urbanairship.AirshipNotificationServiceExtension/documentation/AirshipNotificationServiceExtension/UANotificationServiceExtension":{"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UANotificationServiceExtension"}],"navigatorTitle":[{"kind":"identifier","text":"UANotificationServiceExtension"}],"role":"symbol","kind":"symbol","url":"\/documentation\/airshipnotificationserviceextension\/uanotificationserviceextension","identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/UANotificationServiceExtension","title":"UANotificationServiceExtension","type":"topic"},"doc://com.urbanairship.AirshipNotificationServiceExtension/documentation/AirshipNotificationServiceExtension/UANotificationServiceExtension/airshipConfig":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"airshipConfig"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AirshipExtensionConfig","preciseIdentifier":"s:35AirshipNotificationServiceExtension0aD6ConfigV"}],"url":"\/documentation\/airshipnotificationserviceextension\/uanotificationserviceextension\/airshipconfig","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/UANotificationServiceExtension\/airshipConfig","title":"airshipConfig","type":"topic","kind":"symbol","role":"symbol"},"doc://com.urbanairship.AirshipNotificationServiceExtension/documentation/AirshipNotificationServiceExtension":{"url":"\/documentation\/airshipnotificationserviceextension","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension","type":"topic","role":"collection","kind":"symbol","title":"AirshipNotificationServiceExtension"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"UANotificationServiceExtension","op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipNotificationServiceExtension~1documentation~1AirshipNotificationServiceExtension~1UANotificationServiceExtension\/title"},{"value":[{"text":"UANotificationServiceExtension","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipNotificationServiceExtension~1documentation~1AirshipNotificationServiceExtension~1UANotificationServiceExtension\/fragments"},{"value":[{"kind":"identifier","text":"UANotificationServiceExtension"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipNotificationServiceExtension~1documentation~1AirshipNotificationServiceExtension~1UANotificationServiceExtension\/navigatorTitle"}]}]}