{"metadata":{"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@AirshipNotificationServiceExtension@objc(cs)UANotificationServiceExtension(im)init","navigatorTitle":[{"text":"init","kind":"identifier"}],"modules":[{"name":"AirshipNotificationServiceExtension"}],"role":"symbol","title":"init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airshipnotificationserviceextension\/uanotificationserviceextension\/init"]}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/UANotificationServiceExtension\/init","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension","doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/UANotificationServiceExtension"]]},"references":{"doc://com.urbanairship.AirshipNotificationServiceExtension/documentation/AirshipNotificationServiceExtension":{"type":"topic","role":"collection","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension","url":"\/documentation\/airshipnotificationserviceextension","title":"AirshipNotificationServiceExtension","kind":"symbol"},"doc://com.urbanairship.AirshipNotificationServiceExtension/documentation/AirshipNotificationServiceExtension/UANotificationServiceExtension/init":{"url":"\/documentation\/airshipnotificationserviceextension\/uanotificationserviceextension\/init","identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/UANotificationServiceExtension\/init","kind":"symbol","type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},"doc://com.urbanairship.AirshipNotificationServiceExtension/documentation/AirshipNotificationServiceExtension/UANotificationServiceExtension":{"kind":"symbol","role":"symbol","url":"\/documentation\/airshipnotificationserviceextension\/uanotificationserviceextension","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UANotificationServiceExtension","kind":"identifier"}],"navigatorTitle":[{"text":"UANotificationServiceExtension","kind":"identifier"}],"type":"topic","title":"UANotificationServiceExtension","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/UANotificationServiceExtension"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.urbanairship.AirshipNotificationServiceExtension~1documentation~1AirshipNotificationServiceExtension~1UANotificationServiceExtension\/title","value":"UANotificationServiceExtension","op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipNotificationServiceExtension~1documentation~1AirshipNotificationServiceExtension~1UANotificationServiceExtension\/fragments","value":[{"text":"UANotificationServiceExtension","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipNotificationServiceExtension~1documentation~1AirshipNotificationServiceExtension~1UANotificationServiceExtension\/navigatorTitle","value":[{"kind":"identifier","text":"UANotificationServiceExtension"}],"op":"replace"}]}]}