{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipfeatureflags\/airshipfeatureflagssdkmodule"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airshipfeatureflags\/airshipfeatureflagssdkmodule"]}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"title":"AirshipFeatureFlagsSDKModule","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AirshipFeatureFlagsSDKModule"}],"externalID":"c:@M@AirshipFeatureFlags@objc(cs)UAFeatureFlagsSDKModule","symbolKind":"class","modules":[{"name":"AirshipFeatureFlags"}],"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"AirshipFeatureFlagsSDKModule"}],"role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/AirshipFeatureFlagsSDKModule"},"relationshipsSections":[{"identifiers":["doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/11AirshipCore0A9SDKModuleP","doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/objc(pl)NSObject","doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/s7CVarArgP","doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/s28CustomDebugStringConvertibleP","doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/s23CustomStringConvertibleP","doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/SQ","doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(UAFeatureFlagsSDKModule) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirshipFeatureFlagsSDKModule","kind":"identifier"}],"languages":["swift"]}]},{"content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"name":"Note","style":"note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"For internal use only. :nodoc:"}]}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags"]]},"topicSections":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/AirshipFeatureFlagsSDKModule\/actionsManifest","doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/AirshipFeatureFlagsSDKModule\/components"],"title":"Instance Properties"},{"generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/AirshipFeatureFlagsSDKModule\/load(_:)"],"title":"Type Methods"}],"abstract":[{"type":"text","text":"AirshipFeatureFlags module loader."}],"references":{"doc://com.urbanairship.richpush.AirshipFeatureFlags/documentation/AirshipFeatureFlags/AirshipFeatureFlagsSDKModule":{"role":"symbol","navigatorTitle":[{"text":"AirshipFeatureFlagsSDKModule","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/airshipfeatureflags\/airshipfeatureflagssdkmodule","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirshipFeatureFlagsSDKModule","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/AirshipFeatureFlagsSDKModule","abstract":[{"text":"AirshipFeatureFlags module loader.","type":"text"}],"title":"AirshipFeatureFlagsSDKModule"},"doc://com.urbanairship.richpush.AirshipFeatureFlags/documentation/AirshipFeatureFlags/AirshipFeatureFlagsSDKModule/load(_:)":{"identifier":"doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/AirshipFeatureFlagsSDKModule\/load(_:)","role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/airshipfeatureflags\/airshipfeatureflagssdkmodule\/load(_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"load","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:11AirshipCore24AirshiopModuleLoaderArgsV","text":"AirshiopModuleLoaderArgs","kind":"typeIdentifier"},{"text":") -> (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:11AirshipCore0A9SDKModuleP","text":"AirshipSDKModule","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"title":"load(_:)","abstract":[]},"doc://com.urbanairship.richpush.AirshipFeatureFlags/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/SQ","type":"unresolvable"},"doc://com.urbanairship.richpush.AirshipFeatureFlags/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/s7CVarArgP"},"doc://com.urbanairship.richpush.AirshipFeatureFlags/documentation/AirshipFeatureFlags/AirshipFeatureFlagsSDKModule/actionsManifest":{"role":"symbol","title":"actionsManifest","type":"topic","url":"\/documentation\/airshipfeatureflags\/airshipfeatureflagssdkmodule\/actionsmanifest","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actionsManifest","kind":"identifier"},{"text":": (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:11AirshipCore15ActionsManifestP","text":"ActionsManifest","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/AirshipFeatureFlagsSDKModule\/actionsManifest"},"doc://com.urbanairship.richpush.AirshipFeatureFlags/documentation/AirshipFeatureFlags/AirshipFeatureFlagsSDKModule/components":{"type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"components","kind":"identifier"},{"text":": [","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:11AirshipCore0A9ComponentP","text":"AirshipComponent","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"title":"components","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags\/AirshipFeatureFlagsSDKModule\/components","url":"\/documentation\/airshipfeatureflags\/airshipfeatureflagssdkmodule\/components"},"doc://com.urbanairship.richpush.AirshipFeatureFlags/documentation/AirshipFeatureFlags":{"title":"AirshipFeatureFlags","identifier":"doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/documentation\/AirshipFeatureFlags","type":"topic","kind":"symbol","url":"\/documentation\/airshipfeatureflags","abstract":[],"role":"collection"},"doc://com.urbanairship.richpush.AirshipFeatureFlags/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.urbanairship.richpush.AirshipFeatureFlags/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/SH"},"doc://com.urbanairship.richpush.AirshipFeatureFlags/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/objc(cs)NSObject","type":"unresolvable"},"doc://com.urbanairship.richpush.AirshipFeatureFlags/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/objc(pl)NSObject"},"doc://com.urbanairship.richpush.AirshipFeatureFlags/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.urbanairship.richpush.AirshipFeatureFlags/11AirshipCore0A9SDKModuleP":{"type":"unresolvable","title":"AirshipCore.AirshipSDKModule","identifier":"doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/11AirshipCore0A9SDKModuleP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"UAFeatureFlagsSDKModule","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"UAFeatureFlagsSDKModule","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"UAFeatureFlagsSDKModule"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":null,"op":"replace","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/com.urbanairship.richpush.AirshipFeatureFlags\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UAFeatureFlagsSDKModule","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"UAFeatureFlagsSDKModule","op":"replace","path":"\/references\/doc:~1~1com.urbanairship.richpush.AirshipFeatureFlags~1documentation~1AirshipFeatureFlags~1AirshipFeatureFlagsSDKModule\/title"},{"value":[{"kind":"identifier","text":"UAFeatureFlagsSDKModule"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.richpush.AirshipFeatureFlags~1documentation~1AirshipFeatureFlags~1AirshipFeatureFlagsSDKModule\/fragments"},{"value":[{"text":"UAFeatureFlagsSDKModule","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.richpush.AirshipFeatureFlags~1documentation~1AirshipFeatureFlags~1AirshipFeatureFlagsSDKModule\/navigatorTitle"}]}]}