{"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore"]]},"metadata":{"title":"AirshipJSONUtils","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AirshipJSONUtils"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AirshipJSONUtils"}],"modules":[{"name":"AirshipCore"}],"externalID":"c:@M@AirshipCore@objc(cs)AirshipJSONUtils","symbolKind":"class","roleHeading":"Class"},"kind":"symbol","relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.urbanairship.AirshipCore\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.urbanairship.AirshipCore\/objc(pl)NSObject","doc:\/\/com.urbanairship.AirshipCore\/s7CVarArgP","doc:\/\/com.urbanairship.AirshipCore\/s28CustomDebugStringConvertibleP","doc:\/\/com.urbanairship.AirshipCore\/s23CustomStringConvertibleP","doc:\/\/com.urbanairship.AirshipCore\/SQ","doc:\/\/com.urbanairship.AirshipCore\/SH"],"type":"conformsTo"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["Mac Catalyst"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AirshipJSONUtils"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","anchor":"overview","level":2,"text":"Overview"},{"type":"aside","style":"note","content":[{"inlineContent":[{"type":"text","text":"Internal use only :nodoc:"}],"type":"paragraph"}],"name":"Note"}]}],"variants":[{"paths":["\/documentation\/airshipcore\/airshipjsonutils"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airshipcore\/airshipjsonutils"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"topicSections":[{"generated":true,"title":"Type Methods","identifiers":["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils\/data(_:options:)","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils\/decode(data:)","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils\/encode(object:)","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils\/json(_:)","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils\/object(_:)","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils\/object(_:options:)","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils\/string(_:)","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils\/string(_:options:)","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils\/toData(_:)"],"anchor":"Type-Methods"}],"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/AirshipJSONUtils":{"role":"symbol","url":"\/documentation\/airshipcore\/airshipjsonutils","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AirshipJSONUtils"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils","title":"AirshipJSONUtils","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AirshipJSONUtils"}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/AirshipJSONUtils/data(_:options:)":{"url":"\/documentation\/airshipcore\/airshipjsonutils\/data(_:options:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"data"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSJSONSerialization","text":"JSONSerialization"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSJSONWritingOptions","text":"WritingOptions"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils\/data(_:options:)","role":"symbol","title":"data(_:options:)","kind":"symbol","abstract":[],"type":"topic"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/AirshipJSONUtils/string(_:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"string"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils\/string(_:)","url":"\/documentation\/airshipcore\/airshipjsonutils\/string(_:)","role":"symbol","title":"string(_:)","type":"topic"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"title":"AirshipCore","kind":"symbol","url":"\/documentation\/airshipcore","role":"collection","abstract":[],"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore"},"doc://com.urbanairship.AirshipCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/objc(pl)NSObject","type":"unresolvable"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/AirshipJSONUtils/decode(data:)":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"decode"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"T"},{"kind":"text","text":">("},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:11AirshipCore0A9JSONUtilsC6decode4datax10Foundation4DataVSg_tKSeRzlFZ1TL_xmfp","text":"T"}],"kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils\/decode(data:)","type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/airshipcore\/airshipjsonutils\/decode(data:)","title":"decode(data:)"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/AirshipJSONUtils/json(_:)":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"json"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils\/json(_:)","type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/airshipcore\/airshipjsonutils\/json(_:)","title":"json(_:)"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/AirshipJSONUtils/object(_:)":{"abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils\/object(_:)","url":"\/documentation\/airshipcore\/airshipjsonutils\/object(_:)","title":"object(_:)","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"object"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}]},"doc://com.urbanairship.AirshipCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.urbanairship.AirshipCore\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.urbanairship.AirshipCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.urbanairship.AirshipCore\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.urbanairship.AirshipCore/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.urbanairship.AirshipCore\/objc(cs)NSObject","type":"unresolvable"},"doc://com.urbanairship.AirshipCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.urbanairship.AirshipCore\/SQ","type":"unresolvable"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/AirshipJSONUtils/init":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils\/init","abstract":[],"url":"\/documentation\/airshipcore\/airshipjsonutils\/init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"title":"init","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/AirshipJSONUtils/object(_:options:)":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils\/object(_:options:)","abstract":[],"url":"\/documentation\/airshipcore\/airshipjsonutils\/object(_:options:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"object","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"JSONSerialization","preciseIdentifier":"c:objc(cs)NSJSONSerialization"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ReadingOptions","preciseIdentifier":"c:@E@NSJSONReadingOptions"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"keyword","text":"Any"}],"title":"object(_:options:)","type":"topic"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/AirshipJSONUtils/toData(_:)":{"type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/airshipcore\/airshipjsonutils\/todata(_:)","kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils\/toData(_:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"toData(_:)"},"doc://com.urbanairship.AirshipCore/s7CVarArgP":{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/AirshipJSONUtils/string(_:options:)":{"title":"string(_:options:)","kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils\/string(_:options:)","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"string","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSJSONSerialization","text":"JSONSerialization","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"WritingOptions","preciseIdentifier":"c:@E@NSJSONWritingOptions","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"url":"\/documentation\/airshipcore\/airshipjsonutils\/string(_:options:)"},"doc://com.urbanairship.AirshipCore/SH":{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/AirshipJSONUtils/encode(object:)":{"abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encode"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"T"},{"kind":"text","text":">("},{"kind":"externalParam","text":"object"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11AirshipCore0A9JSONUtilsC6encode6object10Foundation4DataVxSg_tKSERzlFZ1TL_xmfp","kind":"typeIdentifier","text":"T"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"}],"kind":"symbol","type":"topic","url":"\/documentation\/airshipcore\/airshipjsonutils\/encode(object:)","title":"encode(object:)","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils\/encode(object:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AirshipJSONUtils"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"AirshipJSONUtils","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AirshipJSONUtils"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils\/init"],"anchor":"Instance-Methods","title":"Instance Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.urbanairship.AirshipCore\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AirshipJSONUtils"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["Mac Catalyst"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1AirshipJSONUtils\/title","value":"AirshipJSONUtils"},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1AirshipJSONUtils\/fragments","value":[{"kind":"identifier","text":"AirshipJSONUtils"}]},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1AirshipJSONUtils\/navigatorTitle","value":[{"kind":"identifier","text":"AirshipJSONUtils"}]}]}]}