{"kind":"symbol","topicSections":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ChallengeResolver\/resolve(_:)"],"anchor":"Instance-Methods"},{"title":"Type Properties","generated":true,"identifiers":["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ChallengeResolver\/shared"],"anchor":"Type-Properties"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ChallengeResolver\/URLSessionDelegate-Implementations","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ChallengeResolver\/URLSessionTaskDelegate-Implementations"],"anchor":"Default-Implementations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ChallengeResolver"},"metadata":{"externalID":"c:@M@AirshipCore@objc(cs)ChallengeResolver","navigatorTitle":[{"kind":"identifier","text":"ChallengeResolver"}],"title":"ChallengeResolver","modules":[{"name":"AirshipCore"}],"symbolKind":"class","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChallengeResolver","kind":"identifier"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChallengeResolver"}],"platforms":["Mac Catalyst"]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"overview","type":"heading","text":"Overview"},{"type":"aside","style":"note","name":"Note","content":[{"inlineContent":[{"type":"text","text":"For internal use only. :nodoc:"}],"type":"paragraph"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/challengeresolver"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airshipcore\/challengeresolver"]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.urbanairship.AirshipCore\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.urbanairship.AirshipCore\/objc(pl)NSURLSessionDelegate","doc:\/\/com.urbanairship.AirshipCore\/objc(pl)NSURLSessionTaskDelegate","doc:\/\/com.urbanairship.AirshipCore\/objc(pl)NSObject","doc:\/\/com.urbanairship.AirshipCore\/s7CVarArgP","doc:\/\/com.urbanairship.AirshipCore\/s8CopyableP","doc:\/\/com.urbanairship.AirshipCore\/s28CustomDebugStringConvertibleP","doc:\/\/com.urbanairship.AirshipCore\/s23CustomStringConvertibleP","doc:\/\/com.urbanairship.AirshipCore\/SQ","doc:\/\/com.urbanairship.AirshipCore\/SH","doc:\/\/com.urbanairship.AirshipCore\/s8SendableP","doc:\/\/com.urbanairship.AirshipCore\/s16SendableMetatypeP"],"type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore"]]},"abstract":[{"text":"Authentication challenge resolver class","type":"text"}],"references":{"doc://com.urbanairship.AirshipCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.urbanairship.AirshipCore\/SQ","type":"unresolvable"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/ChallengeResolver":{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ChallengeResolver","title":"ChallengeResolver","kind":"symbol","url":"\/documentation\/airshipcore\/challengeresolver","navigatorTitle":[{"text":"ChallengeResolver","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChallengeResolver","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Authentication challenge resolver class"}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/ChallengeResolver/URLSessionTaskDelegate-Implementations":{"url":"\/documentation\/airshipcore\/challengeresolver\/urlsessiontaskdelegate-implementations","type":"topic","role":"collectionGroup","kind":"article","title":"URLSessionTaskDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ChallengeResolver\/URLSessionTaskDelegate-Implementations"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"type":"topic","abstract":[],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","title":"AirshipCore","url":"\/documentation\/airshipcore"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/ChallengeResolver/URLSessionDelegate-Implementations":{"url":"\/documentation\/airshipcore\/challengeresolver\/urlsessiondelegate-implementations","type":"topic","role":"collectionGroup","kind":"article","title":"URLSessionDelegate Implementations","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ChallengeResolver\/URLSessionDelegate-Implementations"},"doc://com.urbanairship.AirshipCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.urbanairship.AirshipCore\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.urbanairship.AirshipCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipCore\/s28CustomDebugStringConvertibleP"},"doc://com.urbanairship.AirshipCore/s8CopyableP":{"title":"Swift.Copyable","identifier":"doc:\/\/com.urbanairship.AirshipCore\/s8CopyableP","type":"unresolvable"},"doc://com.urbanairship.AirshipCore/objc(pl)NSURLSessionTaskDelegate":{"title":"NSURLSessionTaskDelegate","type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipCore\/objc(pl)NSURLSessionTaskDelegate"},"doc://com.urbanairship.AirshipCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/objc(pl)NSObject","type":"unresolvable"},"doc://com.urbanairship.AirshipCore/s16SendableMetatypeP":{"title":"Swift.SendableMetatype","type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipCore\/s16SendableMetatypeP"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/ChallengeResolver/shared":{"url":"\/documentation\/airshipcore\/challengeresolver\/shared","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ChallengeResolver","kind":"typeIdentifier","preciseIdentifier":"c:@M@AirshipCore@objc(cs)ChallengeResolver"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ChallengeResolver\/shared","title":"shared","abstract":[],"role":"symbol","kind":"symbol","type":"topic"},"doc://com.urbanairship.AirshipCore/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.urbanairship.AirshipCore\/s7CVarArgP","type":"unresolvable"},"doc://com.urbanairship.AirshipCore/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipCore\/s8SendableP"},"doc://com.urbanairship.AirshipCore/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.urbanairship.AirshipCore\/SH","type":"unresolvable"},"doc://com.urbanairship.AirshipCore/objc(pl)NSURLSessionDelegate":{"title":"Foundation.URLSessionDelegate","type":"unresolvable","identifier":"doc:\/\/com.urbanairship.AirshipCore\/objc(pl)NSURLSessionDelegate"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/ChallengeResolver/resolve(_:)":{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ChallengeResolver\/resolve(_:)","url":"\/documentation\/airshipcore\/challengeresolver\/resolve(_:)","title":"resolve(_:)","role":"symbol","type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resolve","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLAuthenticationChallenge","text":"URLAuthenticationChallenge","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"async","kind":"keyword"},{"text":" -> (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLSession","text":"URLSession","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSURLSessionAuthChallengeDisposition","text":"AuthChallengeDisposition","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"URLCredential","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLCredential"},{"text":"?)","kind":"text"}]},"doc://com.urbanairship.AirshipCore/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.urbanairship.AirshipCore\/objc(cs)NSObject","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"ChallengeResolver"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ChallengeResolver"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ChallengeResolver"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ChallengeResolver\/URLSessionDelegate-Implementations","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/ChallengeResolver\/URLSessionTaskDelegate-Implementations"],"anchor":"Default-Implementations"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.urbanairship.AirshipCore\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.urbanairship.AirshipCore\/objc(pl)NSURLSessionTaskDelegate"],"kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChallengeResolver","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["Mac Catalyst"]}]}},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ChallengeResolver\/title","op":"replace","value":"ChallengeResolver"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ChallengeResolver\/fragments","op":"replace","value":[{"text":"ChallengeResolver","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1ChallengeResolver\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ChallengeResolver"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}