{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils\/string(_:options:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"string","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"obj","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSJSONSerialization","text":"JSONSerialization"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSJSONWritingOptions","text":"WritingOptions"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"platforms":["Mac Catalyst"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/airshipjsonutils\/string(_:options:)"]}],"metadata":{"role":"symbol","externalID":"s:11AirshipCore0A9JSONUtilsC6string_7optionsSSyp_So20NSJSONWritingOptionsVtKFZ","symbolKind":"method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"string"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSJSONSerialization","text":"JSONSerialization"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSJSONWritingOptions","text":"WritingOptions"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"roleHeading":"Type Method","modules":[{"name":"AirshipCore"}],"title":"string(_:options:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils"]]},"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"url":"\/documentation\/airshipcore","title":"AirshipCore","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","kind":"symbol","abstract":[],"type":"topic","role":"collection"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/AirshipJSONUtils":{"abstract":[],"title":"AirshipJSONUtils","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils","kind":"symbol","url":"\/documentation\/airshipcore\/airshipjsonutils","navigatorTitle":[{"kind":"identifier","text":"AirshipJSONUtils"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AirshipJSONUtils"}],"role":"symbol"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/AirshipJSONUtils/string(_:options:)":{"title":"string(_:options:)","type":"topic","url":"\/documentation\/airshipcore\/airshipjsonutils\/string(_:options:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"string","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"JSONSerialization","preciseIdentifier":"c:objc(cs)NSJSONSerialization","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"WritingOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSJSONWritingOptions"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils\/string(_:options:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1AirshipJSONUtils\/title","value":"AirshipJSONUtils","op":"replace"},{"value":[{"kind":"identifier","text":"AirshipJSONUtils"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1AirshipJSONUtils\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"AirshipJSONUtils"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1AirshipJSONUtils\/navigatorTitle","op":"replace"}]}]}