{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["Mac Catalyst"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"obj","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}]}]}],"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils\/toData(_:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Type Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toData"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":"?"}],"externalID":"s:11AirshipCore0A9JSONUtilsC6toDatay10Foundation0E0VSgypSgFZ","title":"toData(_:)","role":"symbol","modules":[{"name":"AirshipCore"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/airshipjsonutils\/todata(_:)"]}],"sections":[],"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/AirshipJSONUtils":{"title":"AirshipJSONUtils","type":"topic","role":"symbol","url":"\/documentation\/airshipcore\/airshipjsonutils","kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AirshipJSONUtils"}],"navigatorTitle":[{"kind":"identifier","text":"AirshipJSONUtils"}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/AirshipJSONUtils/toData(_:)":{"title":"toData(_:)","kind":"symbol","url":"\/documentation\/airshipcore\/airshipjsonutils\/todata(_:)","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSONUtils\/toData(_:)","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"toData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"title":"AirshipCore","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/airshipcore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"AirshipJSONUtils","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1AirshipJSONUtils\/title"},{"op":"replace","value":[{"text":"AirshipJSONUtils","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1AirshipJSONUtils\/fragments"},{"op":"replace","value":[{"text":"AirshipJSONUtils","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1AirshipJSONUtils\/navigatorTitle"}]}]}