{"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSArrayValueTransformer"]]},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/airshipcore\/nsarrayvaluetransformer\/transformedvalueclass()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airshipcore\/nsarrayvaluetransformer\/transformedvalueclass()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transformedValueClass"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s8AnyClassa","text":"AnyClass"}],"platforms":["Mac Catalyst"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSArrayValueTransformer\/transformedValueClass()","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@AirshipCore@objc(cs)NSArrayValueTransformer(cm)transformedValueClass","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transformedValueClass","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"AnyClass","preciseIdentifier":"s:s8AnyClassa","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"transformedValueClass","kind":"identifier"}],"symbolKind":"method","role":"symbol","modules":[{"name":"AirshipCore"}],"roleHeading":"Type Method","title":"transformedValueClass()"},"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"type":"topic","title":"AirshipCore","role":"collection","url":"\/documentation\/airshipcore","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","kind":"symbol"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSArrayValueTransformer/transformedValueClass()":{"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSArrayValueTransformer\/transformedValueClass()","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transformedValueClass","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"AnyClass","kind":"typeIdentifier","preciseIdentifier":"s:s8AnyClassa"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"transformedValueClass","kind":"identifier"}],"abstract":[],"title":"transformedValueClass()","url":"\/documentation\/airshipcore\/nsarrayvaluetransformer\/transformedvalueclass()"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSArrayValueTransformer":{"url":"\/documentation\/airshipcore\/nsarrayvaluetransformer","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSArrayValueTransformer","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"NSArrayValueTransformer","kind":"identifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSArrayValueTransformer","title":"NSArrayValueTransformer","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"transformedValueClass","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"transformedValueClass","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"text":"Class","kind":"typeIdentifier","preciseIdentifier":"c:@T@Class"},{"text":") ","kind":"text"},{"text":"transformedValueClass","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSArrayValueTransformer~1transformedValueClass()\/title","value":"transformedValueClass","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSArrayValueTransformer~1transformedValueClass()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"transformedValueClass"}]},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSArrayValueTransformer\/title","value":"NSArrayValueTransformer"},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSArrayValueTransformer\/fragments","value":[{"text":"NSArrayValueTransformer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSArrayValueTransformer\/navigatorTitle","value":[{"kind":"identifier","text":"NSArrayValueTransformer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}