{"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"NativeBridge initializer."}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"actionRunner","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NativeBridgeActionRunner","kind":"typeIdentifier","preciseIdentifier":"s:11AirshipCore24NativeBridgeActionRunnerP","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridgeActionRunner"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["Mac Catalyst"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An action runner to run actions triggered from the web view"}]}],"name":"actionRunner"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/nativebridge\/init(actionrunner:)"]}],"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge\/init(actionRunner:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"symbolKind":"init","roleHeading":"Initializer","title":"init(actionRunner:)","modules":[{"name":"AirshipCore"}],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"actionRunner"},{"kind":"text","text":": "},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:11AirshipCore24NativeBridgeActionRunnerP","text":"NativeBridgeActionRunner"},{"kind":"text","text":")"}],"externalID":"s:11AirshipCore12NativeBridgeC12actionRunnerAcA0cd6ActionF0_p_tcfc"},"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NativeBridge":{"title":"NativeBridge","type":"topic","abstract":[{"type":"text","text":"The native bridge will automatically load the Airship JavaScript environment into whitlelisted sites. The native"},{"type":"text","text":" "},{"type":"text","text":"bridge must be assigned as the navigation delegate on a "},{"type":"codeVoice","code":"WKWebView"},{"type":"text","text":" in order to function."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NativeBridge"}],"url":"\/documentation\/airshipcore\/nativebridge","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge","navigatorTitle":[{"kind":"identifier","text":"NativeBridge"}],"kind":"symbol"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NativeBridge/init(actionRunner:)":{"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"actionRunner","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NativeBridgeActionRunner","preciseIdentifier":"s:11AirshipCore24NativeBridgeActionRunnerP","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/airshipcore\/nativebridge\/init(actionrunner:)","role":"symbol","title":"init(actionRunner:)","abstract":[{"text":"NativeBridge initializer.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge\/init(actionRunner:)"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NativeBridgeActionRunner":{"type":"topic","role":"symbol","abstract":[{"text":"Action runner used in the ","type":"text"},{"code":"NativeBridge","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NativeBridgeActionRunner","kind":"identifier"}],"navigatorTitle":[{"text":"NativeBridgeActionRunner","kind":"identifier"}],"url":"\/documentation\/airshipcore\/nativebridgeactionrunner","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridgeActionRunner","title":"NativeBridgeActionRunner"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"url":"\/documentation\/airshipcore","kind":"symbol","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","abstract":[],"title":"AirshipCore","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge\/title","value":"NativeBridge"},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge\/fragments","value":[{"kind":"identifier","text":"NativeBridge"}]},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge\/navigatorTitle","value":[{"kind":"identifier","text":"NativeBridge"}]}]}]}