{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"javaScriptCommandDelegate"},{"kind":"text","text":": ("},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JavaScriptCommandDelegate","text":"JavaScriptCommandDelegate","preciseIdentifier":"s:11AirshipCore25JavaScriptCommandDelegateP"},{"kind":"text","text":")?"}],"platforms":["Mac Catalyst"],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/airshipcore\/nativebridge\/javascriptcommanddelegate"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge"]]},"kind":"symbol","abstract":[{"type":"text","text":"Optional delegate to support custom JavaScript commands."}],"metadata":{"externalID":"s:11AirshipCore12NativeBridgeC25javaScriptCommandDelegateAA04JavafgH0_pSgvp","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"AirshipCore"}],"role":"symbol","title":"javaScriptCommandDelegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"javaScriptCommandDelegate","kind":"identifier"},{"text":": (","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:11AirshipCore25JavaScriptCommandDelegateP","text":"JavaScriptCommandDelegate","kind":"typeIdentifier"},{"text":")?","kind":"text"}]},"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge\/javaScriptCommandDelegate","interfaceLanguage":"swift"},"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NativeBridge/javaScriptCommandDelegate":{"type":"topic","abstract":[{"text":"Optional delegate to support custom JavaScript commands.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge\/javaScriptCommandDelegate","title":"javaScriptCommandDelegate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"javaScriptCommandDelegate"},{"kind":"text","text":": ("},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:11AirshipCore25JavaScriptCommandDelegateP","text":"JavaScriptCommandDelegate"},{"kind":"text","text":")?"}],"url":"\/documentation\/airshipcore\/nativebridge\/javascriptcommanddelegate"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NativeBridge":{"kind":"symbol","abstract":[{"type":"text","text":"The native bridge will automatically load the Airship JavaScript environment into whitlelisted sites. The native"},{"type":"text","text":" "},{"type":"text","text":"bridge must be assigned as the navigation delegate on a "},{"type":"codeVoice","code":"WKWebView"},{"type":"text","text":" in order to function."}],"title":"NativeBridge","role":"symbol","url":"\/documentation\/airshipcore\/nativebridge","navigatorTitle":[{"kind":"identifier","text":"NativeBridge"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NativeBridge"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JavaScriptCommandDelegate":{"kind":"symbol","url":"\/documentation\/airshipcore\/javascriptcommanddelegate","title":"JavaScriptCommandDelegate","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JavaScriptCommandDelegate","navigatorTitle":[{"kind":"identifier","text":"JavaScriptCommandDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"JavaScriptCommandDelegate"}],"abstract":[{"text":"A standard protocol for handling commands from the NativeBridge..","type":"text"}],"role":"symbol","type":"topic"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"title":"AirshipCore","url":"\/documentation\/airshipcore","kind":"symbol","type":"topic","abstract":[],"role":"collection","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge\/title","value":"NativeBridge"},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge\/fragments","value":[{"kind":"identifier","text":"NativeBridge"}]},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge\/navigatorTitle","value":[{"text":"NativeBridge","kind":"identifier"}]}]}]}