{"abstract":[{"text":"Called when an error occurs during navigation. :nodoc:","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/nativebridge\/webview(_:didfail:witherror:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airshipcore\/nativebridge\/webview(_:didfail:witherror:)"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"webView","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFail","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"navigation","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKNavigation","text":"WKNavigation","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"withError","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["Mac Catalyst"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge\/webView(_:didFail:withError:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFail","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"WKNavigation","preciseIdentifier":"c:objc(cs)WKNavigation","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"text":"withError","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"webView:didFailNavigation:withError:","kind":"identifier"}],"role":"symbol","title":"webView(_:didFail:withError:)","externalID":"c:@M@AirshipCore@objc(cs)NativeBridge(im)webView:didFailNavigation:withError:","roleHeading":"Instance Method","modules":[{"name":"AirshipCore"}]},"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NativeBridge":{"abstract":[{"text":"The native bridge will automatically load the Airship JavaScript environment into whitlelisted sites. The native","type":"text"},{"text":" ","type":"text"},{"text":"bridge must be assigned as the navigation delegate on a ","type":"text"},{"type":"codeVoice","code":"WKWebView"},{"type":"text","text":" in order to function."}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge","url":"\/documentation\/airshipcore\/nativebridge","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NativeBridge"}],"title":"NativeBridge","navigatorTitle":[{"kind":"identifier","text":"NativeBridge"}],"kind":"symbol"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NativeBridge/webView(_:didFail:withError:)":{"url":"\/documentation\/airshipcore\/nativebridge\/webview(_:didfail:witherror:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKNavigation","preciseIdentifier":"c:objc(cs)WKNavigation"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"withError"},{"kind":"text","text":": "},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"webView:didFailNavigation:withError:"}],"abstract":[{"text":"Called when an error occurs during navigation. :nodoc:","type":"text"}],"type":"topic","title":"webView(_:didFail:withError:)","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge\/webView(_:didFail:withError:)"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"type":"topic","abstract":[],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","url":"\/documentation\/airshipcore","title":"AirshipCore","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"webView:didFailNavigation:withError:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:didFailNavigation:withError:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"webView:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)WKWebView","kind":"typeIdentifier","text":"WKWebView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"webView"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFailNavigation:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)WKNavigation","kind":"typeIdentifier","text":"WKNavigation"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"navigation"},{"kind":"text","text":" "},{"kind":"identifier","text":"withError:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge\/title","value":"NativeBridge","op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge\/fragments","value":[{"text":"NativeBridge","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge\/navigatorTitle","value":[{"text":"NativeBridge","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge~1webView(_:didFail:withError:)\/title","value":"webView:didFailNavigation:withError:","op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge~1webView(_:didFail:withError:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:didFailNavigation:withError:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}