{"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge\/webView(_:didFailProvisionalNavigation:withError:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Called when an error occurs while the web view is loading content. :nodoc:","type":"text"}],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"AirshipCore"}],"symbolKind":"method","role":"symbol","title":"webView(_:didFailProvisionalNavigation:withError:)","navigatorTitle":[{"kind":"identifier","text":"webView:didFailProvisionalNavigation:withError:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFailProvisionalNavigation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKNavigation","preciseIdentifier":"c:objc(cs)WKNavigation"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"withError"},{"kind":"text","text":": "},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"externalID":"c:@M@AirshipCore@objc(cs)NativeBridge(im)webView:didFailProvisionalNavigation:withError:"},"variants":[{"paths":["\/documentation\/airshipcore\/nativebridge\/webview(_:didfailprovisionalnavigation:witherror:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airshipcore\/nativebridge\/webview(_:didfailprovisionalnavigation:witherror:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"webView"},{"kind":"text","text":": "},{"text":"WKWebView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView"},{"text":", ","kind":"text"},{"text":"didFailProvisionalNavigation","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"navigation","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"WKNavigation","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKNavigation"},{"text":"!, ","kind":"text"},{"text":"withError","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge"]]},"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"title":"AirshipCore","kind":"symbol","url":"\/documentation\/airshipcore","role":"collection","abstract":[],"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NativeBridge":{"role":"symbol","abstract":[{"type":"text","text":"The native bridge will automatically load the Airship JavaScript environment into whitlelisted sites. The native"},{"type":"text","text":" "},{"type":"text","text":"bridge must be assigned as the navigation delegate on a "},{"type":"codeVoice","code":"WKWebView"},{"type":"text","text":" in order to function."}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge","navigatorTitle":[{"text":"NativeBridge","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NativeBridge","kind":"identifier"}],"title":"NativeBridge","url":"\/documentation\/airshipcore\/nativebridge","kind":"symbol","type":"topic"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NativeBridge/webView(_:didFailProvisionalNavigation:withError:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"WKWebView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView"},{"text":", ","kind":"text"},{"text":"didFailProvisionalNavigation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"WKNavigation","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKNavigation"},{"text":"!, ","kind":"text"},{"text":"withError","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge\/webView(_:didFailProvisionalNavigation:withError:)","navigatorTitle":[{"text":"webView:didFailProvisionalNavigation:withError:","kind":"identifier"}],"url":"\/documentation\/airshipcore\/nativebridge\/webview(_:didfailprovisionalnavigation:witherror:)","title":"webView(_:didFailProvisionalNavigation:withError:)","kind":"symbol","abstract":[{"type":"text","text":"Called when an error occurs while the web view is loading content. :nodoc:"}],"role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"webView:didFailProvisionalNavigation:withError:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:didFailProvisionalNavigation:withError:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"webView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"webView"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFailProvisionalNavigation:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKNavigation","text":"WKNavigation"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"navigation"},{"kind":"text","text":" "},{"kind":"identifier","text":"withError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["Mac Catalyst"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge\/title","value":"NativeBridge"},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge\/fragments","value":[{"text":"NativeBridge","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge\/navigatorTitle","value":[{"text":"NativeBridge","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge~1webView(_:didFailProvisionalNavigation:withError:)\/title","value":"webView:didFailProvisionalNavigation:withError:"},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge~1webView(_:didFailProvisionalNavigation:withError:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"webView:didFailProvisionalNavigation:withError:","kind":"identifier"}]}]}]}