{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webViewWebContentProcessDidTerminate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"webView"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)WKWebView","kind":"typeIdentifier","text":"WKWebView"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]}],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge\/webViewWebContentProcessDidTerminate(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"roleHeading":"Instance Method","modules":[{"name":"AirshipCore"}],"title":"webViewWebContentProcessDidTerminate(_:)","navigatorTitle":[{"kind":"identifier","text":"webViewWebContentProcessDidTerminate:"}],"externalID":"c:@M@AirshipCore@objc(cs)NativeBridge(im)webViewWebContentProcessDidTerminate:","symbolKind":"method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webViewWebContentProcessDidTerminate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":")"}]},"sections":[],"abstract":[{"type":"text","text":"Called when the web view’s web content process is terminated. :nodoc:"}],"variants":[{"paths":["\/documentation\/airshipcore\/nativebridge\/webviewwebcontentprocessdidterminate(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airshipcore\/nativebridge\/webviewwebcontentprocessdidterminate(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","title":"AirshipCore","role":"collection","abstract":[],"url":"\/documentation\/airshipcore","kind":"symbol"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NativeBridge/webViewWebContentProcessDidTerminate(_:)":{"type":"topic","title":"webViewWebContentProcessDidTerminate(_:)","abstract":[{"text":"Called when the web view’s web content process is terminated. :nodoc:","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"webViewWebContentProcessDidTerminate:"}],"role":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge\/webViewWebContentProcessDidTerminate(_:)","kind":"symbol","url":"\/documentation\/airshipcore\/nativebridge\/webviewwebcontentprocessdidterminate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webViewWebContentProcessDidTerminate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":")"}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NativeBridge":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NativeBridge","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"NativeBridge","kind":"identifier"}],"abstract":[{"text":"The native bridge will automatically load the Airship JavaScript environment into whitlelisted sites. The native","type":"text"},{"text":" ","type":"text"},{"text":"bridge must be assigned as the navigation delegate on a ","type":"text"},{"type":"codeVoice","code":"WKWebView"},{"text":" in order to function.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge","title":"NativeBridge","url":"\/documentation\/airshipcore\/nativebridge","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"webViewWebContentProcessDidTerminate:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"webViewWebContentProcessDidTerminate:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"webViewWebContentProcessDidTerminate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"webView"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge~1webViewWebContentProcessDidTerminate(_:)\/title","value":"webViewWebContentProcessDidTerminate:","op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge~1webViewWebContentProcessDidTerminate(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"webViewWebContentProcessDidTerminate:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge\/title","value":"NativeBridge","op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge\/fragments","value":[{"text":"NativeBridge","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge\/navigatorTitle","value":[{"kind":"identifier","text":"NativeBridge"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}