{"kind":"symbol","identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge\/webView(_:didReceiveServerRedirectForProvisionalNavigation:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"webView","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"WKWebView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView"},{"text":", ","kind":"text"},{"text":"didReceiveServerRedirectForProvisionalNavigation","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"navigation","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"WKNavigation","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKNavigation"},{"text":"!)","kind":"text"}],"languages":["swift"],"platforms":["Mac Catalyst"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge"]]},"metadata":{"role":"symbol","modules":[{"name":"AirshipCore"}],"externalID":"c:@M@AirshipCore@objc(cs)NativeBridge(im)webView:didReceiveServerRedirectForProvisionalNavigation:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webView","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didReceiveServerRedirectForProvisionalNavigation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKNavigation","text":"WKNavigation","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"webView:didReceiveServerRedirectForProvisionalNavigation:","kind":"identifier"}],"title":"webView(_:didReceiveServerRedirectForProvisionalNavigation:)","symbolKind":"method"},"abstract":[{"type":"text","text":"Called when a web view receives a server redirect. :nodoc:"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/nativebridge\/webview(_:didreceiveserverredirectforprovisionalnavigation:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airshipcore\/nativebridge\/webview(_:didreceiveserverredirectforprovisionalnavigation:)"]}],"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NativeBridge":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NativeBridge","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"NativeBridge","kind":"identifier"}],"abstract":[{"text":"The native bridge will automatically load the Airship JavaScript environment into whitlelisted sites. The native","type":"text"},{"text":" ","type":"text"},{"text":"bridge must be assigned as the navigation delegate on a ","type":"text"},{"type":"codeVoice","code":"WKWebView"},{"text":" in order to function.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge","title":"NativeBridge","url":"\/documentation\/airshipcore\/nativebridge","role":"symbol"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NativeBridge/webView(_:didReceiveServerRedirectForProvisionalNavigation:)":{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge\/webView(_:didReceiveServerRedirectForProvisionalNavigation:)","url":"\/documentation\/airshipcore\/nativebridge\/webview(_:didreceiveserverredirectforprovisionalnavigation:)","abstract":[{"type":"text","text":"Called when a web view receives a server redirect. :nodoc:"}],"navigatorTitle":[{"text":"webView:didReceiveServerRedirectForProvisionalNavigation:","kind":"identifier"}],"kind":"symbol","title":"webView(_:didReceiveServerRedirectForProvisionalNavigation:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webView","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didReceiveServerRedirectForProvisionalNavigation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKNavigation","text":"WKNavigation","kind":"typeIdentifier"},{"text":"!)","kind":"text"}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","title":"AirshipCore","role":"collection","abstract":[],"url":"\/documentation\/airshipcore","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"webView:didReceiveServerRedirectForProvisionalNavigation:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:didReceiveServerRedirectForProvisionalNavigation:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["Mac Catalyst"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"webView:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"webView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didReceiveServerRedirectForProvisionalNavigation:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"WKNavigation","preciseIdentifier":"c:objc(cs)WKNavigation","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"navigation","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"NativeBridge","op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge\/title"},{"value":[{"text":"NativeBridge","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge\/fragments"},{"value":[{"kind":"identifier","text":"NativeBridge"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge\/navigatorTitle"},{"value":"webView:didReceiveServerRedirectForProvisionalNavigation:","op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge~1webView(_:didReceiveServerRedirectForProvisionalNavigation:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:didReceiveServerRedirectForProvisionalNavigation:"}],"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge~1webView(_:didReceiveServerRedirectForProvisionalNavigation:)\/fragments"}]}]}