{"metadata":{"role":"symbol","externalID":"c:@M@AirshipCore@objc(cs)NativeBridge(im)webView:didStartProvisionalNavigation:","navigatorTitle":[{"text":"webView:didStartProvisionalNavigation:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"WKWebView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView"},{"text":", ","kind":"text"},{"text":"didStartProvisionalNavigation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"WKNavigation","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKNavigation"},{"text":"!)","kind":"text"}],"symbolKind":"method","modules":[{"name":"AirshipCore"}],"title":"webView(_:didStartProvisionalNavigation:)","roleHeading":"Instance Method"},"abstract":[{"type":"text","text":"Called when web content begins to load in a web view. :nodoc:"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"webView"},{"kind":"text","text":": "},{"text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didStartProvisionalNavigation","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"navigation","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"WKNavigation","preciseIdentifier":"c:objc(cs)WKNavigation","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"platforms":["Mac Catalyst"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge"]]},"sections":[],"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge\/webView(_:didStartProvisionalNavigation:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/nativebridge\/webview(_:didstartprovisionalnavigation:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airshipcore\/nativebridge\/webview(_:didstartprovisionalnavigation:)"]}],"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NativeBridge":{"abstract":[{"type":"text","text":"The native bridge will automatically load the Airship JavaScript environment into whitlelisted sites. The native"},{"type":"text","text":" "},{"type":"text","text":"bridge must be assigned as the navigation delegate on a "},{"type":"codeVoice","code":"WKWebView"},{"type":"text","text":" in order to function."}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge","title":"NativeBridge","url":"\/documentation\/airshipcore\/nativebridge","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NativeBridge"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NativeBridge"}],"kind":"symbol"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"url":"\/documentation\/airshipcore","role":"collection","abstract":[],"title":"AirshipCore","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","type":"topic","kind":"symbol"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NativeBridge/webView(_:didStartProvisionalNavigation:)":{"title":"webView(_:didStartProvisionalNavigation:)","url":"\/documentation\/airshipcore\/nativebridge\/webview(_:didstartprovisionalnavigation:)","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge\/webView(_:didStartProvisionalNavigation:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)WKWebView","kind":"typeIdentifier","text":"WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didStartProvisionalNavigation"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)WKNavigation","kind":"typeIdentifier","text":"WKNavigation"},{"kind":"text","text":"!)"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"webView:didStartProvisionalNavigation:"}],"role":"symbol","abstract":[{"type":"text","text":"Called when web content begins to load in a web view. :nodoc:"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"webView:didStartProvisionalNavigation:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:didStartProvisionalNavigation:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["Mac Catalyst"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"webView:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"WKWebView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView"},{"text":" *) ","kind":"text"},{"text":"webView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didStartProvisionalNavigation:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"WKNavigation","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKNavigation"},{"text":" *) ","kind":"text"},{"text":"navigation","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"NativeBridge","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge\/title"},{"op":"replace","value":[{"text":"NativeBridge","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge\/fragments"},{"op":"replace","value":[{"text":"NativeBridge","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge\/navigatorTitle"},{"op":"replace","value":"webView:didStartProvisionalNavigation:","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge~1webView(_:didStartProvisionalNavigation:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:didStartProvisionalNavigation:"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge~1webView(_:didStartProvisionalNavigation:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}