{"abstract":[{"type":"text","text":"Called when the web view needs to respond to an authentication challenge. :nodoc:"}],"primaryContentSections":[{"declarations":[{"platforms":["Mac Catalyst"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"webView"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"webView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WKWebView","preciseIdentifier":"c:objc(cs)WKWebView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":" "},{"kind":"internalParam","text":"challenge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLAuthenticationChallenge","preciseIdentifier":"c:objc(cs)NSURLAuthenticationChallenge"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completionHandler"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" @"},{"kind":"typeIdentifier","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"AuthChallengeDisposition","preciseIdentifier":"c:@E@NSURLSessionAuthChallengeDisposition"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"URLCredential","preciseIdentifier":"c:objc(cs)NSURLCredential"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/nativebridge\/webview(_:didreceive:completionhandler:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airshipcore\/nativebridge\/webview(_:didreceive:completionhandler:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge\/webView(_:didReceive:completionHandler:)"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"webView(_:didReceive:completionHandler:)","role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webView","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)WKWebView","text":"WKWebView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didReceive","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLAuthenticationChallenge","text":"URLAuthenticationChallenge","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": @","kind":"text"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"typeIdentifier"},{"text":" (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLSession","text":"URLSession","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSURLSessionAuthChallengeDisposition","text":"AuthChallengeDisposition","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLCredential","text":"URLCredential","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","externalID":"c:@M@AirshipCore@objc(cs)NativeBridge(im)webView:didReceiveAuthenticationChallenge:completionHandler:","navigatorTitle":[{"text":"webView:didReceiveAuthenticationChallenge:completionHandler:","kind":"identifier"}],"modules":[{"name":"AirshipCore"}]},"kind":"symbol","references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"type":"topic","abstract":[],"kind":"symbol","role":"collection","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","title":"AirshipCore","url":"\/documentation\/airshipcore"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NativeBridge":{"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge","url":"\/documentation\/airshipcore\/nativebridge","abstract":[{"type":"text","text":"The native bridge will automatically load the Airship JavaScript environment into whitlelisted sites. The native"},{"type":"text","text":" "},{"type":"text","text":"bridge must be assigned as the navigation delegate on a "},{"type":"codeVoice","code":"WKWebView"},{"type":"text","text":" in order to function."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NativeBridge"}],"kind":"symbol","title":"NativeBridge","navigatorTitle":[{"kind":"identifier","text":"NativeBridge"}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NativeBridge/webView(_:didReceive:completionHandler:)":{"title":"webView(_:didReceive:completionHandler:)","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NativeBridge\/webView(_:didReceive:completionHandler:)","role":"symbol","navigatorTitle":[{"text":"webView:didReceiveAuthenticationChallenge:completionHandler:","kind":"identifier"}],"abstract":[{"type":"text","text":"Called when the web view needs to respond to an authentication challenge. :nodoc:"}],"url":"\/documentation\/airshipcore\/nativebridge\/webview(_:didreceive:completionhandler:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"WKWebView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView"},{"text":", ","kind":"text"},{"text":"didReceive","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URLAuthenticationChallenge","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLAuthenticationChallenge"},{"text":", ","kind":"text"},{"text":"completionHandler","kind":"externalParam"},{"text":": @","kind":"text"},{"text":"MainActor","kind":"typeIdentifier","preciseIdentifier":"s:ScM"},{"text":" (","kind":"text"},{"text":"URLSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSession"},{"text":".","kind":"text"},{"text":"AuthChallengeDisposition","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSURLSessionAuthChallengeDisposition"},{"text":", ","kind":"text"},{"text":"URLCredential","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLCredential"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"webView:didReceiveAuthenticationChallenge:completionHandler:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"webView:didReceiveAuthenticationChallenge:completionHandler:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["Mac Catalyst"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"webView:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"WKWebView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)WKWebView"},{"text":" *) ","kind":"text"},{"text":"webView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didReceiveAuthenticationChallenge:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSURLAuthenticationChallenge","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLAuthenticationChallenge"},{"text":" *) ","kind":"text"},{"text":"challenge","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^)(","kind":"text"},{"text":"NSURLSessionAuthChallengeDisposition","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSURLSessionAuthChallengeDisposition"},{"text":" ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"NSURLCredential","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLCredential"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge\/title","value":"NativeBridge","op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge\/fragments","value":[{"text":"NativeBridge","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge\/navigatorTitle","value":[{"kind":"identifier","text":"NativeBridge"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge~1webView(_:didReceive:completionHandler:)\/title","value":"webView:didReceiveAuthenticationChallenge:completionHandler:","op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NativeBridge~1webView(_:didReceive:completionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"webView:didReceiveAuthenticationChallenge:completionHandler:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}