{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension","doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/ChallengeResolver"]]},"sections":[],"metadata":{"extendedModule":"AirshipNotificationServiceExtension","symbolKind":"method","title":"urlSession(_:didReceive:)","externalID":"c:@CM@AirshipNotificationServiceExtension@objc(cs)ChallengeResolver(im)URLSession:didReceiveChallenge:completionHandler:","modules":[{"name":"AirshipNotificationServiceExtension"}],"role":"symbol","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlSession"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSession","text":"URLSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLAuthenticationChallenge","text":"URLAuthenticationChallenge"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSession","text":"URLSession"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSURLSessionAuthChallengeDisposition","text":"AuthChallengeDisposition"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLCredential","text":"URLCredential"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"URLSession:didReceiveChallenge:completionHandler:"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"URLSessionDelegate.urlSession(_:didReceive:)"},{"type":"text","text":"."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/ChallengeResolver\/urlSession(_:didReceive:)"},"variants":[{"paths":["\/documentation\/airshipnotificationserviceextension\/challengeresolver\/urlsession(_:didreceive:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airshipnotificationserviceextension\/challengeresolver\/urlsession(_:didreceive:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"urlSession","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"session","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"URLSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSession"},{"text":", ","kind":"text"},{"text":"didReceive","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"challenge"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSURLAuthenticationChallenge","kind":"typeIdentifier","text":"URLAuthenticationChallenge"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"kind":"text","text":" -> ("},{"preciseIdentifier":"c:objc(cs)NSURLSession","kind":"typeIdentifier","text":"URLSession"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@NSURLSessionAuthChallengeDisposition","kind":"typeIdentifier","text":"AuthChallengeDisposition"},{"text":", ","kind":"text"},{"text":"URLCredential","preciseIdentifier":"c:objc(cs)NSURLCredential","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"platforms":["Mac Catalyst"]}]}],"references":{"doc://com.urbanairship.AirshipNotificationServiceExtension/documentation/AirshipNotificationServiceExtension/ChallengeResolver":{"navigatorTitle":[{"text":"ChallengeResolver","kind":"identifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/ChallengeResolver","url":"\/documentation\/airshipnotificationserviceextension\/challengeresolver","title":"ChallengeResolver","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChallengeResolver","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Authentication challenge resolver class","type":"text"}],"role":"symbol"},"doc://com.urbanairship.AirshipNotificationServiceExtension/documentation/AirshipNotificationServiceExtension/ChallengeResolver/urlSession(_:didReceive:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlSession"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSession","text":"URLSession"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didReceive"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLAuthenticationChallenge","text":"URLAuthenticationChallenge"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"},{"text":" -> (","kind":"text"},{"text":"URLSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSession"},{"text":".","kind":"text"},{"text":"AuthChallengeDisposition","kind":"typeIdentifier","preciseIdentifier":"c:@E@NSURLSessionAuthChallengeDisposition"},{"text":", ","kind":"text"},{"text":"URLCredential","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLCredential"},{"text":"?)","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/ChallengeResolver\/urlSession(_:didReceive:)","title":"urlSession(_:didReceive:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"URLSession:didReceiveChallenge:completionHandler:"}],"type":"topic","kind":"symbol","url":"\/documentation\/airshipnotificationserviceextension\/challengeresolver\/urlsession(_:didreceive:)"},"doc://com.urbanairship.AirshipNotificationServiceExtension/documentation/AirshipNotificationServiceExtension":{"abstract":[],"url":"\/documentation\/airshipnotificationserviceextension","title":"AirshipNotificationServiceExtension","role":"collection","identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"URLSession:didReceiveChallenge:completionHandler:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"URLSession:didReceiveChallenge:completionHandler:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"URLSession:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSURLSession","preciseIdentifier":"c:objc(cs)NSURLSession","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"session","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didReceiveChallenge:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSURLAuthenticationChallenge","preciseIdentifier":"c:objc(cs)NSURLAuthenticationChallenge","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"challenge","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" (^)(","kind":"text"},{"text":"NSURLSessionAuthChallengeDisposition","preciseIdentifier":"c:@E@NSURLSessionAuthChallengeDisposition","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"NSURLCredential","preciseIdentifier":"c:objc(cs)NSURLCredential","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completionHandler","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipNotificationServiceExtension~1documentation~1AirshipNotificationServiceExtension~1ChallengeResolver\/title","value":"ChallengeResolver"},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipNotificationServiceExtension~1documentation~1AirshipNotificationServiceExtension~1ChallengeResolver\/fragments","value":[{"kind":"identifier","text":"ChallengeResolver"}]},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipNotificationServiceExtension~1documentation~1AirshipNotificationServiceExtension~1ChallengeResolver\/navigatorTitle","value":[{"text":"ChallengeResolver","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipNotificationServiceExtension~1documentation~1AirshipNotificationServiceExtension~1ChallengeResolver~1urlSession(_:didReceive:)\/title","value":"URLSession:didReceiveChallenge:completionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipNotificationServiceExtension~1documentation~1AirshipNotificationServiceExtension~1ChallengeResolver~1urlSession(_:didReceive:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"URLSession:didReceiveChallenge:completionHandler:","kind":"identifier"}]}]}]}