{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSDictionaryValueTransformer"]]},"primaryContentSections":[{"declarations":[{"platforms":["Mac Catalyst"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowsReverseTransformation","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSDictionaryValueTransformer\/allowsReverseTransformation()","interfaceLanguage":"swift"},"sections":[],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowsReverseTransformation"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"modules":[{"name":"AirshipCore"}],"symbolKind":"method","title":"allowsReverseTransformation()","roleHeading":"Type Method","externalID":"c:@M@AirshipCore@objc(cs)NSDictionaryValueTransformer(cm)allowsReverseTransformation","navigatorTitle":[{"kind":"identifier","text":"allowsReverseTransformation"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/nsdictionaryvaluetransformer\/allowsreversetransformation()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airshipcore\/nsdictionaryvaluetransformer\/allowsreversetransformation()"]}],"kind":"symbol","references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSDictionaryValueTransformer/allowsReverseTransformation()":{"title":"allowsReverseTransformation()","url":"\/documentation\/airshipcore\/nsdictionaryvaluetransformer\/allowsreversetransformation()","abstract":[],"type":"topic","navigatorTitle":[{"text":"allowsReverseTransformation","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allowsReverseTransformation","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSDictionaryValueTransformer\/allowsReverseTransformation()"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","title":"AirshipCore","role":"collection","abstract":[],"url":"\/documentation\/airshipcore","kind":"symbol"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSDictionaryValueTransformer":{"url":"\/documentation\/airshipcore\/nsdictionaryvaluetransformer","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSDictionaryValueTransformer","kind":"identifier"}],"navigatorTitle":[{"text":"NSDictionaryValueTransformer","kind":"identifier"}],"kind":"symbol","title":"NSDictionaryValueTransformer","abstract":[{"text":"NOTE: For internal use only. :nodoc:","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSDictionaryValueTransformer"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"allowsReverseTransformation","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"allowsReverseTransformation","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"allowsReverseTransformation","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"allowsReverseTransformation","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSDictionaryValueTransformer~1allowsReverseTransformation()\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"allowsReverseTransformation"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSDictionaryValueTransformer~1allowsReverseTransformation()\/fragments","op":"replace"},{"value":"NSDictionaryValueTransformer","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSDictionaryValueTransformer\/title","op":"replace"},{"value":[{"kind":"identifier","text":"NSDictionaryValueTransformer"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSDictionaryValueTransformer\/fragments","op":"replace"},{"value":[{"text":"NSDictionaryValueTransformer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSDictionaryValueTransformer\/navigatorTitle","op":"replace"}]}]}