{"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["Mac Catalyst"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSDictionaryValueTransformer"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airshipcore\/nsdictionaryvaluetransformer\/init"]}],"kind":"symbol","metadata":{"role":"symbol","modules":[{"name":"AirshipCore"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"externalID":"c:@M@AirshipCore@objc(cs)NSDictionaryValueTransformer(im)init","symbolKind":"method","title":"init","roleHeading":"Instance Method"},"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSDictionaryValueTransformer\/init","interfaceLanguage":"occ"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSDictionaryValueTransformer":{"url":"\/documentation\/airshipcore\/nsdictionaryvaluetransformer","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSDictionaryValueTransformer","kind":"identifier"}],"navigatorTitle":[{"text":"NSDictionaryValueTransformer","kind":"identifier"}],"kind":"symbol","title":"NSDictionaryValueTransformer","abstract":[{"text":"NOTE: For internal use only. :nodoc:","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSDictionaryValueTransformer"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","title":"AirshipCore","role":"collection","abstract":[],"url":"\/documentation\/airshipcore","kind":"symbol"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSDictionaryValueTransformer/init":{"title":"init","navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSDictionaryValueTransformer\/init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"kind":"symbol","abstract":[],"url":"\/documentation\/airshipcore\/nsdictionaryvaluetransformer\/init","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"NSDictionaryValueTransformer","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSDictionaryValueTransformer\/title"},{"op":"replace","value":[{"kind":"identifier","text":"NSDictionaryValueTransformer"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSDictionaryValueTransformer\/fragments"},{"op":"replace","value":[{"text":"NSDictionaryValueTransformer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSDictionaryValueTransformer\/navigatorTitle"}]}]}