{"kind":"symbol","variants":[{"paths":["\/documentation\/airshipcore\/nsdictionaryvaluetransformer\/reversetransformedvalue(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airshipcore\/nsdictionaryvaluetransformer\/reversetransformedvalue(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"reverseTransformedValue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"value"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"platforms":["Mac Catalyst"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSDictionaryValueTransformer"]]},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"reverseTransformedValue"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"title":"reverseTransformedValue(_:)","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"reverseTransformedValue:"}],"externalID":"c:@M@AirshipCore@objc(cs)NSDictionaryValueTransformer(im)reverseTransformedValue:","role":"symbol","symbolKind":"method","modules":[{"name":"AirshipCore"}]},"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSDictionaryValueTransformer\/reverseTransformedValue(_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"title":"AirshipCore","kind":"symbol","url":"\/documentation\/airshipcore","role":"collection","abstract":[],"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSDictionaryValueTransformer/reverseTransformedValue(_:)":{"kind":"symbol","title":"reverseTransformedValue(_:)","navigatorTitle":[{"kind":"identifier","text":"reverseTransformedValue:"}],"url":"\/documentation\/airshipcore\/nsdictionaryvaluetransformer\/reversetransformedvalue(_:)","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSDictionaryValueTransformer\/reverseTransformedValue(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"reverseTransformedValue"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"abstract":[],"type":"topic","role":"symbol"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSDictionaryValueTransformer":{"url":"\/documentation\/airshipcore\/nsdictionaryvaluetransformer","title":"NSDictionaryValueTransformer","abstract":[{"type":"text","text":"NOTE: For internal use only. :nodoc:"}],"navigatorTitle":[{"text":"NSDictionaryValueTransformer","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSDictionaryValueTransformer","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSDictionaryValueTransformer"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"reverseTransformedValue:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"reverseTransformedValue:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"reverseTransformedValue:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"value"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"reverseTransformedValue:","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSDictionaryValueTransformer~1reverseTransformedValue(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSDictionaryValueTransformer~1reverseTransformedValue(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"reverseTransformedValue:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSDictionaryValueTransformer\/title","value":"NSDictionaryValueTransformer","op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSDictionaryValueTransformer\/fragments","value":[{"text":"NSDictionaryValueTransformer","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSDictionaryValueTransformer\/navigatorTitle","value":[{"kind":"identifier","text":"NSDictionaryValueTransformer"}],"op":"replace"}]}]}