{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSDictionaryValueTransformer\/transformedValue(_:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipcore\/nsdictionaryvaluetransformer\/transformedvalue(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airshipcore\/nsdictionaryvaluetransformer\/transformedvalue(_:)"]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transformedValue"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"value"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?","kind":"text"}],"platforms":["Mac Catalyst"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSDictionaryValueTransformer"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"transformedValue:"}],"role":"symbol","modules":[{"name":"AirshipCore"}],"symbolKind":"method","externalID":"c:@M@AirshipCore@objc(cs)NSDictionaryValueTransformer(im)transformedValue:","title":"transformedValue(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transformedValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?","kind":"text"}],"roleHeading":"Instance Method"},"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSDictionaryValueTransformer/transformedValue(_:)":{"abstract":[],"title":"transformedValue(_:)","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSDictionaryValueTransformer\/transformedValue(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transformedValue"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/airshipcore\/nsdictionaryvaluetransformer\/transformedvalue(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"transformedValue:"}],"kind":"symbol"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSDictionaryValueTransformer":{"url":"\/documentation\/airshipcore\/nsdictionaryvaluetransformer","title":"NSDictionaryValueTransformer","abstract":[{"type":"text","text":"NOTE: For internal use only. :nodoc:"}],"navigatorTitle":[{"text":"NSDictionaryValueTransformer","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSDictionaryValueTransformer","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NSDictionaryValueTransformer"}],"kind":"symbol"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"title":"AirshipCore","kind":"symbol","url":"\/documentation\/airshipcore","role":"collection","abstract":[],"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"transformedValue:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"transformedValue:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"transformedValue:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"value"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"transformedValue:","op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSDictionaryValueTransformer~1transformedValue(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSDictionaryValueTransformer~1transformedValue(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"transformedValue:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSDictionaryValueTransformer\/title","value":"NSDictionaryValueTransformer"},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSDictionaryValueTransformer\/fragments","value":[{"text":"NSDictionaryValueTransformer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSDictionaryValueTransformer\/navigatorTitle","value":[{"text":"NSDictionaryValueTransformer","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}