{"variants":[{"paths":["\/documentation\/airshipcore\/nsdictionaryvaluetransformer\/transformedvalueclass()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/airshipcore\/nsdictionaryvaluetransformer\/transformedvalueclass()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSDictionaryValueTransformer\/transformedValueClass()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSDictionaryValueTransformer"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transformedValueClass","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"AnyClass","kind":"typeIdentifier","preciseIdentifier":"s:s8AnyClassa"}],"languages":["swift"],"platforms":["Mac Catalyst"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"method","title":"transformedValueClass()","externalID":"c:@M@AirshipCore@objc(cs)NSDictionaryValueTransformer(cm)transformedValueClass","roleHeading":"Type Method","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transformedValueClass","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"AnyClass","kind":"typeIdentifier","preciseIdentifier":"s:s8AnyClassa"}],"modules":[{"name":"AirshipCore"}],"navigatorTitle":[{"text":"transformedValueClass","kind":"identifier"}]},"kind":"symbol","references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSDictionaryValueTransformer":{"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSDictionaryValueTransformer","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSDictionaryValueTransformer","kind":"identifier"}],"url":"\/documentation\/airshipcore\/nsdictionaryvaluetransformer","abstract":[{"text":"NOTE: For internal use only. :nodoc:","type":"text"}],"role":"symbol","title":"NSDictionaryValueTransformer","kind":"symbol","navigatorTitle":[{"text":"NSDictionaryValueTransformer","kind":"identifier"}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"kind":"symbol","url":"\/documentation\/airshipcore","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","title":"AirshipCore","abstract":[],"role":"collection"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/NSDictionaryValueTransformer/transformedValueClass()":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"transformedValueClass"}],"title":"transformedValueClass()","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transformedValueClass"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:s8AnyClassa","kind":"typeIdentifier","text":"AnyClass"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/NSDictionaryValueTransformer\/transformedValueClass()","url":"\/documentation\/airshipcore\/nsdictionaryvaluetransformer\/transformedvalueclass()"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"transformedValueClass","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"transformedValueClass","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"Class","preciseIdentifier":"c:@T@Class"},{"kind":"text","text":") "},{"kind":"identifier","text":"transformedValueClass"},{"kind":"text","text":";"}],"platforms":["Mac Catalyst"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"NSDictionaryValueTransformer","op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSDictionaryValueTransformer\/title"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSDictionaryValueTransformer\/fragments","op":"replace","value":[{"kind":"identifier","text":"NSDictionaryValueTransformer"}]},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSDictionaryValueTransformer\/navigatorTitle","op":"replace","value":[{"text":"NSDictionaryValueTransformer","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSDictionaryValueTransformer~1transformedValueClass()\/title","op":"replace","value":"transformedValueClass"},{"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1NSDictionaryValueTransformer~1transformedValueClass()\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"transformedValueClass","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}