{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"evaluate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"json"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSON","preciseIdentifier":"s:11AirshipCore0A4JSONO","kind":"typeIdentifier","text":"AirshipJSON"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ignoreCase"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"platforms":["Mac Catalyst"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"json","content":[{"inlineContent":[{"type":"text","text":"The "},{"type":"codeVoice","code":"AirshipJSON"},{"type":"text","text":" value to evaluate."}],"type":"paragraph"}]},{"name":"ignoreCase","content":[{"inlineContent":[{"type":"text","text":"If "},{"type":"codeVoice","code":"true"},{"type":"text","text":", string comparisons will be case-insensitive."}],"type":"paragraph"}]}]},{"kind":"content","content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"true"},{"type":"text","text":" if the JSON value matches the predicate’s conditions, otherwise "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/airshipcore\/jsonvaluematcher\/predicate\/evaluate(json:ignorecase:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"modules":[{"name":"AirshipCore"}],"role":"symbol","title":"evaluate(json:ignoreCase:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"evaluate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"json","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11AirshipCore0A4JSONO","text":"AirshipJSON","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"ignoreCase","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"externalID":"s:11AirshipCore16JSONValueMatcherC9PredicateP8evaluate4json10ignoreCaseSbAA0A4JSONO_SbtF","roleHeading":"Instance Method","required":true,"symbolKind":"method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher\/Predicate\/evaluate(json:ignoreCase:)"},"abstract":[{"text":"Evaluates the predicate against a given JSON value.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher","doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher\/Predicate"]]},"references":{"doc://com.urbanairship.AirshipCore/documentation/AirshipCore":{"url":"\/documentation\/airshipcore","kind":"symbol","type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore","abstract":[],"title":"AirshipCore","role":"collection"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONValueMatcher/Predicate":{"type":"topic","role":"symbol","title":"JSONValueMatcher.Predicate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"Predicate"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher\/Predicate","abstract":[{"type":"text","text":"A protocol for defining the specific logic of a JSON value matcher."},{"type":"text","text":" "},{"type":"text","text":"Each predicate implementation checks a JSON value against a specific condition."}],"kind":"symbol","url":"\/documentation\/airshipcore\/jsonvaluematcher\/predicate","navigatorTitle":[{"kind":"identifier","text":"Predicate"}]},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/AirshipJSON":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirshipJSON","kind":"identifier"}],"navigatorTitle":[{"text":"AirshipJSON","kind":"identifier"}],"title":"AirshipJSON","abstract":[{"text":"Airship JSON.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/AirshipJSON","url":"\/documentation\/airshipcore\/airshipjson","kind":"symbol"},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONValueMatcher/Predicate/evaluate(json:ignoreCase:)":{"role":"symbol","type":"topic","url":"\/documentation\/airshipcore\/jsonvaluematcher\/predicate\/evaluate(json:ignorecase:)","title":"evaluate(json:ignoreCase:)","abstract":[{"text":"Evaluates the predicate against a given JSON value.","type":"text"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher\/Predicate\/evaluate(json:ignoreCase:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"evaluate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"json"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AirshipJSON","preciseIdentifier":"s:11AirshipCore0A4JSONO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ignoreCase"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","required":true},"doc://com.urbanairship.AirshipCore/documentation/AirshipCore/JSONValueMatcher":{"navigatorTitle":[{"kind":"identifier","text":"JSONValueMatcher"}],"identifier":"doc:\/\/com.urbanairship.AirshipCore\/documentation\/AirshipCore\/JSONValueMatcher","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"JSONValueMatcher"}],"abstract":[{"text":"A ","type":"text"},{"code":"JSONValueMatcher","type":"codeVoice"},{"text":" is used to match a JSON value against a set of constraints.","type":"text"}],"role":"symbol","type":"topic","title":"JSONValueMatcher","url":"\/documentation\/airshipcore\/jsonvaluematcher"}},"variantOverrides":[{"patch":[{"op":"replace","value":"JSONValueMatcher","path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueMatcher\/title"},{"op":"replace","value":[{"text":"JSONValueMatcher","kind":"identifier"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueMatcher\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"JSONValueMatcher"}],"path":"\/references\/doc:~1~1com.urbanairship.AirshipCore~1documentation~1AirshipCore~1JSONValueMatcher\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}