{"hierarchy":{"paths":[[]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/airshipnotificationserviceextension"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/airshipnotificationserviceextension"]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"title":"Classes","anchor":"Classes","generated":true,"identifiers":["doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/ChallengeResolver","doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/DefaultAirshipExtensionLogHandler","doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/UANotificationServiceExtension"]},{"title":"Protocols","anchor":"Protocols","generated":true,"identifiers":["doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/AirshipExtensionLogHandler"]},{"title":"Structures","anchor":"Structures","generated":true,"identifiers":["doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/AirshipExtensionConfig"]},{"title":"Type Aliases","anchor":"Type-Aliases","generated":true,"identifiers":["doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/ChallengeResolveClosure"]},{"title":"Enumerations","anchor":"Enumerations","generated":true,"identifiers":["doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/AirshipExtensionLogLevel"]},{"title":"Extended Modules","anchor":"Extended-Modules","generated":true,"identifiers":["doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/UserNotifications"]}],"metadata":{"title":"AirshipNotificationServiceExtension","role":"collection","roleHeading":"Framework","externalID":"AirshipNotificationServiceExtension","symbolKind":"module","modules":[{"name":"AirshipNotificationServiceExtension"}]},"identifier":{"url":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension","interfaceLanguage":"swift"},"references":{"doc://com.urbanairship.AirshipNotificationServiceExtension/documentation/AirshipNotificationServiceExtension/UANotificationServiceExtension":{"title":"UANotificationServiceExtension","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UANotificationServiceExtension"}],"kind":"symbol","url":"\/documentation\/airshipnotificationserviceextension\/uanotificationserviceextension","role":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/UANotificationServiceExtension","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UANotificationServiceExtension"}],"abstract":[]},"doc://com.urbanairship.AirshipNotificationServiceExtension/documentation/AirshipNotificationServiceExtension/AirshipExtensionConfig":{"role":"symbol","kind":"symbol","url":"\/documentation\/airshipnotificationserviceextension\/airshipextensionconfig","title":"AirshipExtensionConfig","abstract":[{"text":"Airship extension config. Can be supplied with the property ","type":"text"},{"code":"airshipExtensionConfig","type":"codeVoice"},{"text":" in ","type":"text"},{"code":"UANotificationServiceExtension","type":"codeVoice"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AirshipExtensionConfig"}],"type":"topic","identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/AirshipExtensionConfig","navigatorTitle":[{"kind":"identifier","text":"AirshipExtensionConfig"}]},"doc://com.urbanairship.AirshipNotificationServiceExtension/documentation/AirshipNotificationServiceExtension/UserNotifications":{"role":"collection","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/airshipnotificationserviceextension\/usernotifications","title":"UserNotifications","identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/UserNotifications"},"doc://com.urbanairship.AirshipNotificationServiceExtension/documentation/AirshipNotificationServiceExtension/ChallengeResolver":{"identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/ChallengeResolver","kind":"symbol","url":"\/documentation\/airshipnotificationserviceextension\/challengeresolver","abstract":[{"type":"text","text":"Authentication challenge resolver class"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChallengeResolver","kind":"identifier"}],"title":"ChallengeResolver","type":"topic","role":"symbol","navigatorTitle":[{"text":"ChallengeResolver","kind":"identifier"}]},"doc://com.urbanairship.AirshipNotificationServiceExtension/documentation/AirshipNotificationServiceExtension/AirshipExtensionLogHandler":{"type":"topic","abstract":[{"type":"text","text":"Protocol used by AirshipExtension to log all messages.."}],"role":"symbol","title":"AirshipExtensionLogHandler","kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/AirshipExtensionLogHandler","navigatorTitle":[{"kind":"identifier","text":"AirshipExtensionLogHandler"}],"url":"\/documentation\/airshipnotificationserviceextension\/airshipextensionloghandler","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"AirshipExtensionLogHandler"}]},"doc://com.urbanairship.AirshipNotificationServiceExtension/documentation/AirshipNotificationServiceExtension":{"identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension","kind":"symbol","url":"\/documentation\/airshipnotificationserviceextension","abstract":[],"title":"AirshipNotificationServiceExtension","type":"topic","role":"collection"},"doc://com.urbanairship.AirshipNotificationServiceExtension/documentation/AirshipNotificationServiceExtension/AirshipNotificationServiceExtensionVersionNumber":{"identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/AirshipNotificationServiceExtensionVersionNumber","abstract":[{"type":"text","text":"Project version number for AirshipNotificationServiceExtension."}],"kind":"symbol","title":"AirshipNotificationServiceExtensionVersionNumber","role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"AirshipNotificationServiceExtensionVersionNumber"}],"url":"\/documentation\/airshipnotificationserviceextension\/airshipnotificationserviceextensionversionnumber"},"doc://com.urbanairship.AirshipNotificationServiceExtension/documentation/AirshipNotificationServiceExtension/ChallengeResolveClosure":{"navigatorTitle":[{"kind":"identifier","text":"ChallengeResolveClosure"}],"kind":"symbol","identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/ChallengeResolveClosure","title":"ChallengeResolveClosure","abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/airshipnotificationserviceextension\/challengeresolveclosure","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChallengeResolveClosure"}]},"doc://com.urbanairship.AirshipNotificationServiceExtension/documentation/AirshipNotificationServiceExtension/AirshipExtensionLogLevel":{"role":"symbol","navigatorTitle":[{"text":"AirshipExtensionLogLevel","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AirshipExtensionLogLevel","kind":"identifier"}],"identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/AirshipExtensionLogLevel","url":"\/documentation\/airshipnotificationserviceextension\/airshipextensionloglevel","abstract":[{"text":"Represents the possible log levels.","type":"text"}],"title":"AirshipExtensionLogLevel","type":"topic","kind":"symbol"},"doc://com.urbanairship.AirshipNotificationServiceExtension/documentation/AirshipNotificationServiceExtension/AirshipNotificationServiceExtensionVersionString":{"identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/AirshipNotificationServiceExtensionVersionString","kind":"symbol","abstract":[{"type":"text","text":"Project version string for AirshipNotificationServiceExtension."}],"url":"\/documentation\/airshipnotificationserviceextension\/airshipnotificationserviceextensionversionstring","role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"AirshipNotificationServiceExtensionVersionString"}],"title":"AirshipNotificationServiceExtensionVersionString"},"doc://com.urbanairship.AirshipNotificationServiceExtension/documentation/AirshipNotificationServiceExtension/DefaultAirshipExtensionLogHandler":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultAirshipExtensionLogHandler"}],"identifier":"doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/DefaultAirshipExtensionLogHandler","abstract":[],"url":"\/documentation\/airshipnotificationserviceextension\/defaultairshipextensionloghandler","kind":"symbol","title":"DefaultAirshipExtensionLogHandler","role":"symbol","navigatorTitle":[{"text":"DefaultAirshipExtensionLogHandler","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Classes","identifiers":["doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/ChallengeResolver","doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/UANotificationServiceExtension"],"title":"Classes"},{"generated":true,"anchor":"Variables","identifiers":["doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/AirshipNotificationServiceExtensionVersionNumber","doc:\/\/com.urbanairship.AirshipNotificationServiceExtension\/documentation\/AirshipNotificationServiceExtension\/AirshipNotificationServiceExtensionVersionString"],"title":"Variables"}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipNotificationServiceExtension~1documentation~1AirshipNotificationServiceExtension~1UANotificationServiceExtension\/title","value":"UANotificationServiceExtension"},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipNotificationServiceExtension~1documentation~1AirshipNotificationServiceExtension~1UANotificationServiceExtension\/fragments","value":[{"text":"UANotificationServiceExtension","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipNotificationServiceExtension~1documentation~1AirshipNotificationServiceExtension~1UANotificationServiceExtension\/navigatorTitle","value":[{"kind":"identifier","text":"UANotificationServiceExtension"}]},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipNotificationServiceExtension~1documentation~1AirshipNotificationServiceExtension~1ChallengeResolver\/title","value":"ChallengeResolver"},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipNotificationServiceExtension~1documentation~1AirshipNotificationServiceExtension~1ChallengeResolver\/fragments","value":[{"kind":"identifier","text":"ChallengeResolver"}]},{"op":"replace","path":"\/references\/doc:~1~1com.urbanairship.AirshipNotificationServiceExtension~1documentation~1AirshipNotificationServiceExtension~1ChallengeResolver\/navigatorTitle","value":[{"text":"ChallengeResolver","kind":"identifier"}]}]}]}